### ISSUE TITLE
Impossible to get the scrubbar to a different position on animated maps.

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10055]

**Comment by xavijam** [comment]
Which scrubbar?, sorry but I don't know what you mean.

**Comment by saleiva** [comment]
the bar that shows the position on time.

**Comment by xavijam** [comment]
Do you remember the link where it was happening?

**Comment by saleiva** [comment]
This is a dupe of another issue I talked to @piensaenpixel las week

**Comment by inigomedina** [comment]
I'm closing this issue because it has been inactive for a long time. This probably means that it is not reproducible or it has been fixed in a newer version. If it's an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue.

Thank you!
