### ISSUE TITLE
Password-protection graphics look different in Windows/IE

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#10058]
@xavijam 

S/B 10131162

## Context
Looks like fonts & graphics aren't loading in 
Internet Explorer 8.1 / Windows 7

## Process
1. From inside a Builder map click the Privacy setting button
2. In the next screen click Privacy setting button again & choose Password
3. Enter a password, then click Publish & copy Get the url link
4. Paste link in browser tab

Happening for client in Editor map too.

## Expected result

![screen_shot_2016-10-05_at_2 40 57_pm](https://cloud.githubusercontent.com/assets/1779444/19133943/fb055fd6-8b28-11e6-85ee-a588680f0be1.png)

## Current result

![image](https://cloud.githubusercontent.com/assets/1779444/19133959/102453ea-8b29-11e6-85a9-fe2eb439a0b8.png)

(tested in VirtualBox Windows 7 environment)

**Comment by xavijam** [comment]
We don't provide support for IE versions below to 11.

**Comment by ztephm** [comment]
@xavijam also happening in Chrome 53.0.2785.143 m in Windows 8.1

(looks fine for that Chrome version in OSX)

**Comment by xavijam** [comment]
Ouch, that's another history, could you take a look @mariacheca?

**Comment by MariaCheca** [comment]
sure!

**Comment by MariaCheca** [comment]
Hey @ztephm! I tested that in a Windows 7 VM using the same Chrome version as you said and everything seems fine:

![screen shot 2016-10-07 at 11 05 57](https://cloud.githubusercontent.com/assets/2141690/19184640/6d0ac714-8c7e-11e6-899a-f416f1b1b484.png)
![screen shot 2016-10-07 at 11 06 17](https://cloud.githubusercontent.com/assets/2141690/19184639/6d0a7e80-8c7e-11e6-8a88-72946ab7f4a3.png)

Could you tell us if that still happens in Chrome or another browser? A possible cause could be that the browser has cached an older version of the assets, so when the page is loading it can't find them because there's a new one. Please try removing the browser cache just in case :)

**Comment by ztephm** [comment]
Weird @MariaCheca ! This is what it looks like for me in Chrome 53.0.2785.143 m in VirtualBox Windows 8.1 environment - no caching:

![win81_chrome](https://cloud.githubusercontent.com/assets/1779444/19201169/8dcb7ef0-8c9a-11e6-8a2a-7426e2ad638b.png)

The .ova I used had [Windows 8.1/IE11 bundled together](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/). I just used IE browser to download latest Chrome, not sure if the way environment is set up has something to do with it?

**Comment by ztephm** [comment]
Thanks @MariaCheca and @xavijam !

**Comment by MariaCheca** [comment]
@ztephm yw! thank you for reporting it :)
