### ISSUE TITLE
Metrics API missing fields [Read ticket for deployment instructions, coordinate with jmartin]

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#10069]
- [x] Organizations. For each user, show builder/viewer
- ~[ ] Organizations. Add owner to user list~
- [x] Organizations. Total number of builders and viewers
- [x] Organizations. Total number of maps and datasets

cc @jmartinter

**Comment by jmartinter** [comment]
1) For organizations, it would be great to return builder list and viewer list as different keys of the retrieved json. 

2) Requests that retrieve daily metrics return them as a dict / hash with key = date. Because the fact that Python dicts don't keep the sorting, preprocessing and sorting the data before presenting is required. It would be great that the API returns an array of {date: <date>, value: <value of metric>}

@javitonino what do you think?

**Comment by javitonino** [comment]
To deploy this, coordinate with @jmartinter:
 - We must deploy cartodb and cartodb-central (linked PRs). Both can be deployed at the same time.
 - Marlango must be deployed by @jmartinter at the same time as Central to minimize downtime.
