### ISSUE TITLE
executing sql queries fail if there is no the_geom

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#10083]
@javisantana commented on [Fri Oct 07 2016](https://github.com/CartoDB/leapfrog/issues/7)

1) open a visualization and go to a layer
2) execute "select 1"

you look at network panel and you see sql api response error like this 

```
{"error":["column \"the_geom\" does not exist"]}
```

Form my POV when there is not the_geom or the_geom_webmercator the map tab should be hidden and show data one

For reference, the old editor in that case updates the map (shows nothing) and the legends and not changed

As side effect of this is:

```
SELECT 'SRID=3857;POINT(0 0)' as the_geom_webmercator
```

raises the same error (and in that case the map could be rendered)
#SMOKE_MG38

**Comment by saleiva** [comment]
Priorizing since lots of documentation refers to example without the_geom

**Comment by xavijam** [comment]
When you have all the stuff ready (in camshaft?) @dgaubert, let me know and we will open a new PR with the last changes 💋 .

**Comment by xavijam** [comment]
Thanks to @dgaubert we already have the proper error in the UI.

![screen_shot_2016-11-02_at_11 45 53](https://cloud.githubusercontent.com/assets/132146/19926559/872adbf8-a0f5-11e6-8568-65ea6aad91bf.png)
![screen_shot_2016-11-02_at_11 46 04](https://cloud.githubusercontent.com/assets/132146/19926558/8721acea-a0f5-11e6-88e3-54e6d73a82c4.png)

What I propose now is:

- Parse message error and create a better one (as we did with some analyses errors).
- Instead of showing an error notification, show a warning one (yellowish).
- Show the error in the layers view (it is likely we have a mini bug there and we are not showing there the mini red dot with the error message).
- Try, and check if it is possible to disable the map part when this kind of query is applied (I feel it is not an easy task right now). IMHO, we should do it in another ticket, but as you wish.

@saleiva @javisantana 
And cc @alonsogarciapablo because you was involved on Monday.

@javierarce could take care of it.

**Comment by xavijam** [comment]
Approved then!

**Comment by alonsogarciapablo** [comment]
Related https://github.com/CartoDB/Windshaft-cartodb/issues/571 and https://github.com/CartoDB/Windshaft-cartodb/issues/544.

Not sure when, but I'd be great if windshaft-cartodb included some error codes so that we don't need to:

> Parse message error and create a better one (as we did with some analyses errors).

And also, so that we can provide translations for these error messages.
