### ISSUE TITLE
Carto::DataImport Load

### ISSUE THREAD

**Issue by Baguewi** [CartoDB/cartodb#10166]
Hello if someone can help me.
I had installed CartoDB locally on my Ubuntu 14.04 and the installation was perfect. I can create dataset by CartoDB's GUI and able to visulaize data perfectly without any problem. But when i drag and drop a csv or geojson file externally from my system, it is throwing an error as below

Rails: 
![capture du 2016-10-13 13 58 36](https://cloud.githubusercontent.com/assets/10731720/19348488/73d1b0b0-914e-11e6-92dd-c079c7c2d7fe.png)

And my CartoDb's UI is showing

1 An unknown error has happened

Persisting error? Please send us the following code:
01f18226-a811-4992-84b5-8c2143ca4088

if I run the tests in my repertoire cartodb the results of tests gives me the following results
![capture du 2016-10-13 14 24 09](https://cloud.githubusercontent.com/assets/10731720/19349169/047bb8e2-9152-11e6-9395-f33e91e9395e.png)

**Comment by javitonino** [comment]
Hey, I'm probably late with this. We usually don't answer installation/configuration  questions though GitHub. As this does not appear to be an issue with CARTO itself, it's better if you contact us through [our mailing list](https://groups.google.com/forum/#!forum/cartodb). If you cannot find the problem with this tips, please contact us there.

If all data imports fail, the issue is likely related to `ogr2ogr` (part of gdal) installation. You can take a look at out [installation guide](http://cartodb.readthedocs.io/en/latest/install.html#gis-dependencies) to see if it helps.

You can also search for the import log to see if that offers any clue. Open a rails console by running `bundle exec rails console` and the run `puts Carto::Log.find(DataImport['f1dc7af7-58df-4459-8940-7f9b054a8ae2'].logger).entries` which should show the import log.
