### ISSUE TITLE
exporting a .carto with sql in a layer does modify the sql properly in multiuser accounts

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#10257]
As an organization user:

- create a map with a layer with a sql query
- export it as .carto (attached)
- import it in a different user (user2)

SQL should be `select .... from user2.table`

#SMOKE_MM03

[table_29_8 map (on 2016-10-19 at 14.10.48).carto.zip](https://github.com/CartoDB/cartodb/files/539282/table_29_8.map.on.2016-10-19.at.14.10.48.carto.zip)

**Comment by javisantana** [comment]
cc @CartoDB/backend

**Comment by javitonino** [comment]
That map has no username in the query, so it doesn't get rewritten. If the original map had `user1.table` it would have been correctly rewritten to `user2.table`.

We do it this way in order to keep the original query as untouched as possible, and also to avoid unnecessarily qualifying the query. It is not needed to qualify own queries in the map queries, as maps are always loaded in the owner context.

**Comment by javitonino** [comment]
Just tested with another map (with qualified table names in the query) and it works. :tada:
