### ISSUE TITLE
Export .carto is not downloading involved datasets in analysis where it is required a second node

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#10274]
Like in JOINs operations.

**Comment by xavijam** [comment]
cc @CartoDB/builder-backend

**Comment by javitonino** [comment]
If you create a table with a long table name in an organization account, so "username.table_name" is longer than 64 characters (max length for postgres identifiers), the return value is truncated.

```
select CDB_QueryTables('select * from javitonino.very_long_table_name_very_near_of_64_characters_gets_truncated');                     
                          cdb_querytables                                                                                                                                                     
-------------------------------------------------------------------                                                                                                                           
 {javitonino.very_long_table_name_very_near_of_64_characters_gets}
```

CDB_QueryTablesText works
```
select CDB_QueryTablesText('select * from javitonino.very_long_table_name_very_near_of_64_characters_gets_truncated');                 
                             cdb_querytablestext                                                                                                                                              
-----------------------------------------------------------------------------                                                                                                                 
 {javitonino.very_long_table_name_very_near_of_64_characters_gets_truncated}                                                                                                                  
(1 row)
```

The problem seems to be that CDB_QueryTables returns a [name](https://www.postgresql.org/docs/9.5/static/datatype-character.html#DATATYPE-CHARACTER-SPECIAL-TABLE) type, which is capped at 64 chars, while the text version returns text.

See: https://github.com/CartoDB/cartodb-postgresql/blob/091aea088e1d37290dbac9d602256d0ececd50bb/scripts-available/CDB_QueryTables.sql#L73

We can fix this in the builder, by using the other version of the function, or we can modify the extension (the name returning version is supposed to be legacy). Anyone with a bit more context about the legacy version care to share some thought? @rafatower? (you were the last one to touch that)

**Comment by rafatower** [comment]
I'd go for `CDB_QueryTablesText` which was indeed there to overcome the (ab)used `name` type with its limitations. The legacy one was kept there for backwards compatibility (you know, a "public" function that you have to maintain for a while).

When we no longer have usages of `CDB_QueryTables` we could consider raising a deprecation warning or even an error and finally remove it...

**Comment by javitonino** [comment]
:+1: Will replace all ocurrences in the builder code to use the new function. Thanks!
