### ISSUE TITLE
Exporting a map as .carto exports the working copy, not the published one

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#10303]
Sorry for the little detail, will add more info on demand.

If you publish a map and make some changes later in the Builder and then export the .carto from builder, you will have the modified version of the map instead of the published one. Is this expected? Should I get the published one from the public map view? What if its a LINK map?

**Comment by javitonino** [comment]
Right now we always export the working copy from everywhere, although it might make more sense to export the published version from public views. We could also export both versions (current + published) for the owner, and only the published version otherwise.

Anyway, this is a product decision, cc @xavijam @saleiva

**Comment by AbelVM** [comment]
Real case: beautiful finished demo, radically changed the demo on the fly during the meeting, tried to go back to the original state... no way, let's download the .carto and reupload... FUCK! 

So, yes, please add the option to download the published version of the map :cry:

**Comment by javitonino** [comment]
This was parked as a product decision. Maybe @alonsogarciapablo wants to take a look.
