### ISSUE TITLE
GitHub auth not working on sign up page

### ISSUE THREAD

**Issue by santisaez** [CartoDB/cartodb#10313]
Steps:

1) Go to https://carto.com/signup
2) Click on GitHub button
3) Log into GitHub (tested with an account with two-factor auth enabled)
4) You will be redirected to https://carto.com/github?code=xxx&state=yyy

The sign-up form does not appear.
# SMOKE_OB03

**Comment by javitonino** [comment]
Hey, I talked with Santi and it actually works. He was being redirected to the signup flow because he didnn't have an account linked with that GH email. The screen he gets is:

![screen shot 2016-10-24 at 14 56 25](https://cloud.githubusercontent.com/assets/7569673/19678163/e7f6d19e-9a9c-11e6-9f29-3b689f469537.png)

Asking him to choose another username, as the one in GitHub is already taken. We tested signup and then login and it worked. The only thing here, is that it may be unclear that the screen is asking you to choose another username in order to sign up. @CartoDB/design do you think we need to do some change here? Otherwise, let's close this.

**Comment by arianaescobar** [comment]
We could add a red tooltip (like the one we use in the Builder) instead of that ! to indicate the error explicitly. 

@carlostallon any idea?

**Comment by carlostallon** [comment]
Now we are showing a tooltip when hover the red circle
![image](https://cloud.githubusercontent.com/assets/1712650/19678532/6c789fc8-9a9e-11e6-8e19-00aa81606b88.png)

but, to make it clear what do you think to show the error this way:
![image](https://cloud.githubusercontent.com/assets/1712650/19678897/f6dbcb9e-9a9f-11e6-87aa-1a207fa3c99a.png)

**Comment by arianaescobar** [comment]
yup, that was my suggestion :)

**Comment by javitonino** [comment]
cc @MariaCheca
