### ISSUE TITLE
add WMS URL basemap is not displaying list of layers to add

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb#10325]
## Steps

When you add a custom WMS basemap to the Builder, CARTO is not displaying the list of layers of the URL to add on the map.

URL WMS: http://www.ign.es/wmts/pnoa-ma
### Editor:
- Add WMS URL
  ![screen shot 2016-10-25 at 09 59 08](https://cloud.githubusercontent.com/assets/11177693/19677497/e2966636-9a99-11e6-97a6-3dd053553501.png)
- Select `Get Layers` option and a list of available layers appear:

![screen shot 2016-10-25 at 09 59 14](https://cloud.githubusercontent.com/assets/11177693/19677504/e933b958-9a99-11e6-8b70-7bd31b8065dc.png)
### Builder
- Add WMS URL
  ![screen shot 2016-10-25 at 10 03 10](https://cloud.githubusercontent.com/assets/11177693/19677607/5720468e-9a9a-11e6-82a4-5b8cad89ebe5.png)
-  Select `Get Layers` option and a message appears as 1 layer available, but you can't select it:

![screen shot 2016-10-25 at 10 03 39](https://cloud.githubusercontent.com/assets/11177693/19677628/7d31805e-9a9a-11e6-8301-df272712d6ff.png)
# SMOKE_MG40

**Comment by jsanz** [comment]
This is also happening with WMTS capabilities documents: http://www.ign.es/wmts/ign-base?REQUEST=GetCapabilities&SERVICE=WMTS

At the editor it works

![image](https://cloud.githubusercontent.com/assets/188264/20097393/7a5a2146-a5ae-11e6-9fc6-dde7a4c28bdb.png)

**Comment by AbelVM** [comment]
Confirmed with both **WMTS** URLs

* http://www.ign.es/wmts/pnoa-ma
* http://www.ign.es/wmts/pnoa-ma?request=GetCapabilities

You get no available layers. Maybe because of 3857 projection declared as `GoogleMapsCompatible` instead of `EPSG:3857`

Using **WMS** endpoint for the same resource, both URLs:

* http://www.ign.es/wms-inspire/pnoa-ma
* http://www.ign.es/wms-inspire/pnoa-ma?request=GetCapabilities

Same issue. In this case, the projection is strictly declared. 

Fetching WMS 1.1.1 version of the endpoint (default version is 1.3.0):

* http://www.ign.es/wms-inspire/pnoa-ma?request=GetCapabilities&service=WMS&version=1.1.1

Same result.

Looks like the problem is on our side.

**Comment by jarmoasu** [comment]
FYI: List of layers is displaying correctly with FireFox (49.0.2). So this is browser related issue.

![image](https://cloud.githubusercontent.com/assets/16135355/20339079/1ca69a4e-abe3-11e6-9ed2-ac450364f421.png)

**Comment by jsanz** [comment]
Great catch Jarmo, thanks!

--
Jorge Sanz
CARTO - Predict through location

**Comment by saleiva** [comment]
@matallo can you confirm this plz?

**Comment by xavijam** [comment]
@matallo, could you take care of this before continuing with geometry edition tasks? 💋

**Comment by matallo** [comment]
on it, thanks for the thorough report 👍
