### ISSUE TITLE
SQL is applied after creating a new dataset from query

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#10326]
### STR

* Apply an SQL query to a dataset. 

```sql
select 
    s.cartodb_id,
    s.area_id,
    s.the_geom_webmercator,
    s.the_geom,
    s.total_pop,
    count(d.*) as counts_total
from
    secciones s
join 
    detalle d
on 
    s.area_id = d.ucensal_ps and 
    s.the_geom && ST_MakeEnvelope(2.092896,39.061849,3.643341,40.146339)  
group by s.cartodb_id
```

* The new dataset is created with the SQL applied:

```sql
select * from new_dataset
```

### Expected result

```sql
select * from "username".new_dataset
```

### Workaround

* Add a space after `new_dataset`.
* Apply SQL query.
* Clear.

cc @CartoDB/support 

#SMOKE_DT17

**Comment by ramiroaznar** [comment]
Hey @javitonino, I think I am probably missing a step. After applying the query, *rename the dataset*.

**Comment by javitonino** [comment]
I cannot replicate :cry: 
If I don't rename the dataset, it works as expected.
If I rename the dataset, the query is reset (bug!).

**Comment by javitonino** [comment]
The rename issue has been fixed. It still resets the query, but the resetted query is now correct. I think this fixes this issue, although I'm not 100% sure since I haven't been able to replicate exactly. But the incorrect query looks like the ones generated by the incorrect rename code.

Anyway, I'm closing this for now, feel free to reopen if you see the issue again.

Also, it seems that dataset renaming should reset the query (there is a test for that). That seems a bit overkill, we may want to rewrite the query with the new name. But I would count that as an enhancement for later.
