### ISSUE TITLE
Add ability to hide widgets

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartodb#10360]
Widgets take up a lot of space on mobile. Having the ability to hide/show them would improve the user's interactions with the map.

**Comment by saleiva** [comment]
You mean on embeds?

**Comment by ohasselblad** [comment]
Yep, on embeds

**Comment by saleiva** [comment]
This should be part of the sharing options screen

**Comment by ohasselblad** [comment]
A good example of this is @makella's new blog post on CartoColors. The data map piece is forced to be minimized because of the widgets and the legend:

<img width="755" alt="screen shot 2016-12-08 at 10 21 39" src="https://cloud.githubusercontent.com/assets/1041056/21015479/20c60674-bd30-11e6-8fdf-c66365518af7.png">

**Comment by makella** [comment]
+1!

**Comment by ivanmalagon** [comment]
Widget style tweaks being done in https://github.com/CartoDB/cartodb/issues/13487 to save space.

Not able to hide but better experience.
