### ISSUE TITLE
Finish embed view

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#10402]

**Comment by urbanphes** [comment]
### Context

Related to https://github.com/CartoDB/design/issues/302
(This feature has been worked on CartoDB/design)

**Comment by saleiva** [comment]
This is getting traction.

**Comment by xavijam** [comment]
We have a problem with the legends in mobile view right now, it is not possible to show them without touching Deep-insights. This is due to the fact that we added a new menu bar (which contains the title, description, social links etc) and collides with the changes proposed from Design (check https://github.com/CartoDB/cartodb/issues/10400). Also, legends don't live in Deep-insights, we have all the logic, data and HTML in CartoDB.js.

My proposal here is, taking into account Deep-insights will not be merged soon into CartoDB.js:
- Move the "blue menu bar" stuff (with the title, description, ...) from Deep-insights to CartoDB.js, and control there what to show depending the device.
- Move social stuff to CartoDB.js too, and not render if device is mobile (requested by @urbanphes). 
- It could require changes in the viz.json for CartoDB.js (nothing hard, and we can afford it, because vizjson is not public yet).
- Prepare the application to render the legends in a "hidden" menu when the device is small (mobiles).

It makes sense because Deep-insights should not manage anything apart from widgets (from my point of view), and we would avoid any hack and future problems.

Adding several people who know the problem described:
cc @noguerol @jorgesancha @alonsogarciapablo @saleiva @javisantana @piensaenpixel @nobuti

**Comment by xavijam** [comment]
We should review changes, first with @CartoDB/design and then together. 💋 
(for the future taker)

**Comment by saleiva** [comment]
Should we do a short meeting for this?

**Comment by xavijam** [comment]
Yep, it would be great, let's wait until we have someone picking it :)

**Comment by xavijam** [comment]
Blocked until we have a meeting about the new changes.

**Comment by jorgesancha** [comment]
For someone that has not been part of the discussions or that is not close to previous work on related issues, it is close to impossible to understand what this ticket is about without going into a lengthy investigation through varios links to issues, invisions, etc.

This is a friendly reminder to, please:

1. Assume that the reader of the issue doesn't know what you are talking about. Remember, this is open source.
2. Try to state what problem we are trying to solve in the title of the issue (if not possible, consider a) breaking down the issue into multiple issues or b) providing a good description as per point 3)
3. Write a good description of the problem we are trying to solve or the outcome we are trying to achieve.

Many thanks

**Comment by xavijam** [comment]
Closing in favor of https://github.com/CartoDB/cartodb/issues/11623. 💋
