### ISSUE TITLE
infowindow fields are not cleared after changing the schema

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#10429]
1) create a map and apply a simple sql query like "select 1 as test"
2) create a popup with test colum
3) reset SQL

Map fails to render because it requests `test` in the attributes

**Comment by inigomedina** [comment]
I'm closing this issue because it has been inactive for a long time. This probably means that it is not reproducible or it has been fixed in a newer version. If it's an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue.

Thank you!
