### ISSUE TITLE
Legend customization small fixes

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10438]
![screen shot 2016-10-28 at 15 11 33](https://cloud.githubusercontent.com/assets/132149/19807566/f0a1672e-9d20-11e6-80ee-f37ac5136bb8.png)
- [x] When not having a by size style we should disable the link to 'size' instead of showing just none.
- [ ] Change 'COLOR' and 'SIZE' to  'POINTS COLOR' - 'POINTS SIZE'. Note that it could be points/polygons/lines

**Comment by ztephm** [comment]
S/B 10521471 - different "size" question: can we expose code that clients can modify to increase legend width? 

Looks like containing div is not available in custom legend HTML to add inline width (min-width or max-width) style to, right? 

Or is there another way we want clients to do this anyway if they're using custom HTML view, instead of inline style hack?
