### ISSUE TITLE
Error when trying to style a layer with a "Centroid from geometries" analysis

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#10528]
**Steps to reproduce:**

1. Create a new map.
2. Add a layer with polygons.
3. Add a "Centroid from geometries" analysis.
4. Wait for the analysis to finish.
5. Go to the Styles tab.
6. Click the Squares Aggregation.

**Expected results:**
- I should be able to style the points that I'm seeing in the screen.

**Actual results:**
- Map shows the following error:

  ```
  barrios: style0:2:2 Invalid code: polygon-fill: ramp([agg_value], (#245668, #04817E, #39AB7E, #8BD16D, #EDEF5D), quantiles);.
  ```

**Comment by alonsogarciapablo** [comment]
cc: @dgaubert any idea?

**Comment by alonsogarciapablo** [comment]
I checked the table and it doesn't seem to have an `agg_value`:

![screen shot 2016-11-03 at 13 56 43](https://cloud.githubusercontent.com/assets/390398/19966742/732c8ef2-a1cd-11e6-8ad0-bb28a28a1d1d.png)

**Comment by alonsogarciapablo** [comment]
![screen shot 2016-11-03 at 13 58 15](https://cloud.githubusercontent.com/assets/390398/19966787/a3d1c02c-a1cd-11e6-80ca-122302381ff5.png)

**Comment by javitonino** [comment]
Oh, this happened to me in the past with custom SQL but hadn't managed to reproduce. After seeing the centroid analysis causing the issue I found out why.

If you add a `LIMIT X` to your queries, where X is less than the number of buckets, you get this issue. If X >= buckets, it works. The centroid fails because it returns just one point and the default number of buckets is 5.

**Comment by saleiva** [comment]
Is this still happening?

**Comment by javitonino** [comment]
I cannot replicate anymore.
