### ISSUE TITLE
Error connecting to ArcGIS Online service

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#10556]
### Context

A partner is trying to connect to ArcGIS Online Service ("feature services") without success.

### STR

* Click on "NEW DATASET".
* Click on "ArcGIS Server" connector.
* Introduce this url: http://services1.arcgis.com/tZw461SiDpcf6V4o/arcgis/rest/services/KuntienAanestysprosentit/FeatureServer/0
* Connect.

### Result

* The datasource connection fails.
* Importing error: `ExternalServiceError: http://services1.arcgis.com/tZw461SiDpcf6V4o/arcgis/rest/services/KuntienAanestysprosentit/FeatureServer/0/query : {"error":{"code":400,"message":"Cannot perform query. Invalid query parameters`.

### Expected result

* A successful importation.

cc @CartoDB/dataservices

**Comment by jgoizueta** [comment]
The problem is [here](https://github.com/CartoDB/cartodb/blob/4b10090ca50f9cf3749fbeab4da090949edcf0c5/services/datasources/lib/datasources/url/arcgis.rb#L412)

This dataset has columns with names like `Äänioikeut` encoded as `%C3%84%C3%A4nioikeut`. The URI.encode in that line seems superfluous; if we remove it this dataset imports correctly.

I guess `http_client.post` takes care of the encoding, so we should remove the encoding of the fields.
