### ISSUE TITLE
feature request: if dataset is too large, offer to simplify polygons or sub sample points

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartodb#10762]
Uploading a too-large dataset into Carto prevents people from making maps! One way to get around this is to reduce the file size of the imported dataset. A few ways to do this:

1. if geoms are polygons, add option to simplify
2. if table is really long, offer to subsample
3. if there are lots of columns, allow the user the option to only grab a selected few

Offering all of the above would be great. Reminds me of this great ticket on advanced import options: https://github.com/CartoDB/cartodb/issues/4282

cc @saleiva @talos

**Comment by talos** [comment]
👍 This would be a major improvement to our UX.

**Comment by saleiva** [comment]
Agreed. @rafatower @ethervoid how hard would it be show a warning message and if confirming, import all rows that fit within the user limit? 
cc @javisantana

**Comment by javisantana** [comment]
ok, let me go through this:

- How do we know the dataset is big? using the file size? how do we know the geometries are big and not the payload in the columns? We can estimate but that requires to change the way importer works right now (which I'm totally willing to do)

- Case 1: how do we simplify polygons? based on zoom level? using just Douglas-Peucker? do we have data about how many datasets we can't import because of the size of the polygons? In this case we'd need to change the importer architecture because we'd need to process geometry before inserting in the database

- Case 2: what subsampling method we offer? we do know that geo sampling is not as easy as picking a X% of the rows and in those cases the tables are point based (for which we have overview solution)

- Case3: sounds good, we'd need to change the api to allow to import only some columns. Also a new part of the api to know the columns stored in the file

My vision here is different, why don't we work on being able to create maps with those datasets and work on a way to add analysis that allow us to modify the dataset? All of the things you proposed can be done as an analysis ("simplify", "subsample" and "pick columns"). In other words: "your dataset is too big, we added a subsampling analysis in order to render it properly"

Other idea is to allow to add analysis workflow to the import api so we can send not only the file but the steps we want that file to pass through (so instead of providing a set of custom solutions we do provide something closed to an ETL?)

**Comment by talos** [comment]
I think trying to reuse analysis steps to do the processing as opposed to building more other code to do it is a great idea.  OTOH it still has to be done pre-import, since the dataset has to live in the user account, correct?

Depending on the file format being brought in, I see a few quick rules of thumb we can use to figure out what's "heavy":

* Shapefiles: looking at `.shp` vs `.dbf` filesize should give us a quick indication of whether there's a lot of columnar data, or whether the shapes themselves are complex.
* CSV: `wc` could provide a quick indication of whether the file has a lot of rows, or is just very wide.  It's probably relatively safe to assume most client imports of a CSV are going to either be point or address based, so considering whether to simplify geometries is less important.

👍 also on getting more information about how many datasets aren't being imported because of filesize vs row length.
KML and GeoJSON would be trickier to do pre-transformation analysis of, unfortunately.
