### ISSUE TITLE
Histograms (or barcharts then) (time and number) should allow to aggregate by operation and not only by count

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10809]
### Context
Sometimes you want to show histograms/barcharts that shows data aggregated by something that is not COUNT. Well those are barcharts.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Imagine you have data with timestamps and commuters on transportation
2. You want to see commuters per day and create a timeseries widget or a histogram.
3. When adding a widget, you can only see count of features which doesn't tell the same story.

### Expected result
By adding the aggregation operation input we can add this capacity.

This would mean we cannot call the widget histogram anymore :_(

cc/ @javisantana @rochoa @Jorgedelara

**Comment by rochoa** [comment]
Is that example a count aggregation? What changes is the aggregation range, isn't it?

**Comment by Jorgedelara** [comment]
@jsanz could you help @rochoa explaining this issue? It is the EMT problem representing commuters count in the timeseries

**Comment by rochoa** [comment]
After talking with @saleiva, we have agreed that the Time Series widget should allow aggregations, but that doesn't mean we need the histograms to implement that feature, because what we need is a category widget to do the aggregation.

This would work with date[time] columns, but also with any other aggregated category. As an example, consider _sum of clients by customer value_, in that case, the frontend will display a _bar chart_ instead of a histogram.

cc @xavijam

**Comment by rochoa** [comment]
BTW, this use case is already supported by torque.

**Comment by AbelVM** [comment]
I do  not agree with not supporting aggregations in histograms :disappointed: 

**Real life case:** You have an arbitrary number monitoring stations gathering pollution values hourly. You sure want a 24 bins' histogram with the hourly average pollution value of all your stations. Category widget here makes no sense.

**Comment by saleiva** [comment]
Then that would be a barchart. We are not saying not to aggregations
anyway, but we should separate both issues.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
