### ISSUE TITLE
Square/Hexbin aggregation

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#10815]
### Context
For squares/hexbins aggregation, Builder takes a bin size based on the zoom level at the moment of the map creation. After that, the bin size remains static regardless of the zoom level. 

The current query to create those maps is: 

```
SELECT 
  CDB_HexagonGrid ( 
    ST_Expand(
      !bbox!, 
      CDB_XYZ_Resolution(ZOOM_LEVEL) * 12), 
    CDB_XYZ_Resolution(ZOOM_LEVEL) * 12) 
  AS cell
```

while in the Editor it was: 

```
SELECT 
  CDB_HexagonGrid(
    ST_Expand(
      !bbox!, 
      greatest(!pixel_width!,!pixel_height!) * 24), 
    greatest(!pixel_width!,!pixel_height!) * 24) 
  AS cell
```

### Steps to Reproduce

1. Create a map with a point's dataset
2. Select squares or hexbins aggregation and set a size
3. Zoom in/out

### Current Result
The map is instantiated with a fixed bin size based on the initial zoom level, so the grid doesn't change at different zoom levels

 
### Expected result
Bins should resize on each zoom level according with the pixel size value used as a parameter. 

### Additional info

If we decide to have a fixed bin size, we should use a different unit than pixels for setting it, like meters.

**Comment by ztephm** [comment]
@CartoDB/support please let S/B 11122671 know if we add this enhancement.

**Comment by saleiva** [comment]
Right now ~21% of our users are clicking on this option. Prioritizing to next.

**Comment by saleiva** [comment]
cc/ @rochoa

**Comment by jsanz** [comment]
@saleiva is this issue being actioned? anything you need from our side?

**Comment by saleiva** [comment]
Nope, and I'm afraid we will not have time soon (unless is critical)

**Comment by saleiva** [comment]
cc/ @jorgesancha

**Comment by jsanz** [comment]
No, it's not critical just wanted to know the status, thanks!

**Comment by jgoizueta** [comment]
I find the present implementation inconsistent in that users define the grid size in pixels (screen units) but the grid is actually set in geographic units (onscreen size changes with zoom, size is earth-relative actually as @ernesmb notes).

But I think there might be use cases for both the current behaviour and the previoius one. What I'd like to see is an option in the UI to choose the grid size units:

* If meters (km, etc) are selected, the gridding is earth-wise (as now, pixel size will change with zoom)
* If pixels are selected, the grid is screen-wise (earth-relative size in meters will change with zoom)

Just my 2c.

**Comment by ramiroaznar** [comment]
What do you think? @alonsogarciapablo Also ccing @zingbot because some of our clients are using this feature.

**Comment by jgoizueta** [comment]
Well, now I see a good reason why we're using only the first option, earth-relative grid size (but still I think we should use meters etc.). Otherwise our ramps would now work properly:

When we choose a grid representation we also select an aggregated measure (count, sum of some column, etc) And by default a ramp on that measure is used for styling. The ramp break points are computed for the data distribution of the measure. For aggregate functions such as AVG (average) the ramp would work well if the grid size changes in relation to the geography, but for others like COUNT (which is the default) it won't: for some zoom range the ramp will be OK but for zoom levels below that range most values will be in the higher end of the ramp (because grid cells are big and the COUNTs larger) and for zoom levels above the valid range most values will be in the lower end (since grid cells are now small and COUNTs too)

So it wouldn't be easy to have grid size to maintain the pixel size and have automatic ramps working at the same time.

**Comment by ramiroaznar** [comment]
Let's close this issue.
