### ISSUE TITLE
When you look for a value in a field, JS error appears

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#10831]
### STR

- Create a map with a dataset of polygons.
- Apply an "Filter by column value" analysis.
- Choose the `cartodb_id` column.
- In the filter field, choose "equal to".
- In the input field, open it and type anything in the search.
- Check console, JS throws an error.

**Comment by xavijam** [comment]
Branch: issue-10831

**Comment by matallo** [comment]
fixed in https://github.com/CartoDB/cartodb/pull/12199

it doesn't throw an error anymore, but leaving open to implement an enhancement, when introducing an string the filed must be validated

currently you can introduce any integer, hit apply and it will work, however you can also introduce a string and submit the form, thus causing an analysis error

**Comment by alrocar** [comment]
Stale issue. Closing 👋
