### ISSUE TITLE
Category widget filtering failing with Jenks applied

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#10848]
### Context
Filtering using a category widget with Jenks applied on the style by value fails - it works with other quantification methods'

### Steps to Reproduce
1. Import the attached .CARTO  
[Where we work in Madrid (on 2016-11-28 at 13.53.18).carto.zip](https://github.com/CartoDB/cartodb/files/616427/Where.we.work.in.Madrid.on.2016-11-28.at.13.53.18.carto.zip)

2. Filter using one of the widgets

### Current Result

```
Work by CP: style0:4:4 Invalid value for polygon-fill, the type color is expected. undefined (of type keyword) was given.
```

### Expected result
Filters should work as with other quantif. methods.

cc/ @rochoa

**Comment by inigomedina** [comment]
I'm closing this issue because it has been inactive for a long time. This probably means that it is not reproducible or it has been fixed in a newer version. If it's an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue.

Thank you!
