### ISSUE TITLE
If you add a layer with a sync dataset, it let's you to edit a geometry.

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#10842]
## STR
- Create a map with a layer (points for example).
- Go there and add a new layer, this has to be synced and it has to have rows with geometry.
- When it is imported or added, click over any of the features of that last layer.
- It let's you to edit the geometry and it shouldn't.

**Comment by xavijam** [comment]
We are checking if the source of the layer is synced when we visit that layer. A solution could be to check that at the beginning, but it would involve more requests at the beginning :S.

**Comment by javitonino** [comment]
See PR #10780

**Comment by javitonino** [comment]
Been testing this and it works great 👏 

Only a little issue:
**STR:**
 1. Create a sync dataset and share it with the org
 2. From another org user, create a map with that dataset
 3. Go to the layer view, at the top you should see "View options" for the sync
 4. Click that and change the sync period
**Actual:** It fails (forbidden, as expected) because you do not have permission to modify the sync for another user.
**Expected:** The button to view options is not there.

![out](https://cloud.githubusercontent.com/assets/7569673/20888265/674219b4-bafe-11e6-8812-4b782bfe3798.gif)

Do you think we should address this in this PR, or better to open a different ticket?
@matallo @xavijam

**Comment by xavijam** [comment]
That's a good one @javitonino. In my opinion we should try to merge this and open a new one, adding it in the board, because this PR is big enough right now...

**Comment by javitonino** [comment]
Agreed, doing it.

New ticket -> https://github.com/CartoDB/cartodb/issues/10967

This is 🍏 for merge.
