### ISSUE TITLE
On-boarding for Layer view

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#10905]
Design issue: https://github.com/CartoDB/design/issues/238
InVision: https://projects.invisionapp.com/d/main#/console/9712702/207784149/preview

Let me know if you need anything else :)

**Comment by ivanmalagon** [comment]
Public link for the InVision project: https://projects.invisionapp.com/share/CK9H1EBVP#/screens/207784157

**Comment by ivanmalagon** [comment]
Just to remark one thing.

In case the map has widgets, the last step of the layer data onboarding will end up like this.

![image](https://cloud.githubusercontent.com/assets/1078228/22587909/d92b9d5a-ea03-11e6-97da-f551dd46e043.png)

Is this the expected look & feel of this step?

**Comment by ivanmalagon** [comment]
I ran into a case not in the design.

When we create a map based on lines the style onboarding copy has no sense.

![image](https://cloud.githubusercontent.com/assets/1078228/22692984/af69688a-ed41-11e6-894e-5cead6e096b9.png)

The text refers to the fill property that doesn't exist in line layers. We can remove the second sentence and leave only `Use these options to style your data in beautiful ways.` Any other suggestion is welcome.

Moreover, in lines and polygons, the first step of style onboarding, the aggregation one, has no sense since that option is not available in those kind of maps. I've removed that step.

**Comment by arianaescobar** [comment]
Uh, good catch. Go ahead a remove the second line of the copy :)

**Comment by arianaescobar** [comment]
One more thing @ivanmalagon could you reduce the horizontal space between the buttons to 16px instead, pleeeease? :)

**Comment by ivanmalagon** [comment]
Another case found.

When a user enters a read-only layer (for instance, an analysis is applied), the geometry edition is not available.

![image](https://cloud.githubusercontent.com/assets/1078228/22739569/73d10a6e-ee0c-11e6-946e-b1841b2e0618.png)

We can do three things:

1. Adapt the current copy, adding a suffix like `you can add points, lines and polygons to non read-only layers.`
2. Show another copy in this case, removing any reference to geometry edition.
3. Leave it as it is right now. The copy refers to something that's not now available but it'll be in another layers.

Any thoughts?

**Comment by matallo** [comment]
My vote for 1. Maybe some warning test.

**Comment by saleiva** [comment]
+1 but the buttons are there, right?

**Comment by ivanmalagon** [comment]
In the above screenshot, there are no buttons for geometry edition, only the one for switching between data and map views.

**Comment by saleiva** [comment]
Then, I'd skip this step on this kind of dataset

**Comment by saleiva** [comment]
OR, we can add the buttons always and keep them deactivated so when the user puts the mouse hover them, we can say that is read.only and so on...

**Comment by arianaescobar** [comment]
I like that last idea!

**Comment by xavijam** [comment]
I suggested several changes in the PR and I started doing them with @matallo, but I have to take other task so whoever takes it, please ask @matallo or me 💋 .

**Comment by noguerol** [comment]
Guys, reviewing this I met some inconsistencies in the copywriting. ccing @brittanymicek as she made the original proof read.

_

> "Welcome to layer view
> Edit, analyze, style and enhance your data with pop-ups and legends."

_

Is not pop-ups and legends what edit, analyze and style your data. Besides, with the exception of the add geometry button, I would don't say we edit the data but transform it because Builder is built around a non-destructive paradigm, right? So I would better say something like **"Analyze and style your data and enhance it with pop-ups and legends"**

_

> Layer options
> Layers can be renamed by double clicking on the layer name. Data layers can be exported, duplicated, and flattened.

_

We don't yet support layer flattening or duplication.


_

> Data tab
> Edit, style, and add analysis, pop-ups, and legends to layers. To further explore your data add widgets.

_

I would remove the "edit" there: "**Style and add analysis, pop...**"

_

> SQL Editor
> Data layers can be edited and processed by using the SQL editor at the bottom of the screen.

_

You cannot edit the data from the sql view, but you can transform it, right? I would also rather say "view" instead of "editor" because currently is a readonly viewer when there is something to edit.



_

> Add geometry and switch to dataset view
> You can switch between map or table view. In map view, you can add points, lines, and polygons.

_

Shouldn't we say "geometries" instead? Maybe i'm too picky.

**Comment by matallo** [comment]
back to CR / Acceptance, I'd leave @noguerol comments for further work on this, let's 🚢 🇮🇹

**Comment by xavijam** [comment]
About your second bullet @noguerol, how does it should this text?

`Layers can be renamed by double clicking on the layer name. Data layers can be exported or map centered.`

**Comment by noguerol** [comment]
I would rather say "Layers can be renamed by double clicking on the layer name, centered by clicking in the crosshair, and exported through their contextual menu"

**Comment by xavijam** [comment]
Sounds marvellous 👍
