### ISSUE TITLE
timeslider filtering dates error

### ISSUE THREAD

**Issue by nygeog** [CartoDB/cartodb#10946]
### Context
I loaded a dataset for 2016 w/ new signups. Noticed that I could select range in timeslider that is in the future, and when looking at points and their pop-ups, time in pop-up did not match the time in the infoWindow. 
 

### Steps to Reproduce

1. Add dataset (or ask me for .carto)
2. Add timeslider
3. Select time ranges. 

### Current Result
![screen shot 2016-12-01 at 3 21 22 pm](https://cloud.githubusercontent.com/assets/2790599/20811168/a4ab0652-b7da-11e6-9a3d-8f85bc2c79c0.png)

![screen shot 2016-12-01 at 3 22 36 pm](https://cloud.githubusercontent.com/assets/2790599/20811171/a7207084-b7da-11e6-907c-580f531e54bf.png)
 
![screen shot 2016-12-01 at 3 21 01 pm](https://cloud.githubusercontent.com/assets/2790599/20811167/a10219b4-b7da-11e6-9da8-44dcb8da5d6d.png)

### Expected result
Expecting the slider to select the correct dates. 

### Browser and version
Chrome Version 54.0.2840.98 (64-bit)

### .carto file
Ask me on slack to send, contains some sensitive data.

**Comment by ztephm** [comment]
related? https://github.com/CartoDB/cartodb/issues/9746

@CartoDB/support check this for S/B 9922620

**Comment by noguerol** [comment]
Related to https://github.com/CartoDB/cartodb/issues/11294

**Comment by xavijam** [comment]
Well, this is related with the timezone issue -> https://github.com/CartoDB/cartodb/issues/12088. It will be solved soon I feel 💋  :heart:.

**Comment by matallo** [comment]
can we confirm this is already fixed @ztephm @noguerol ? we've pushed the fix recently

**Comment by ztephm** [comment]
LGTM, I tested w/[this dataset](https://team.carto.com/u/stephaniemongon/dataset/stephaniemongon.twitter_t3chfest_reduced):
* I'm not seeing Time Series widget show future dates - last date in dataset is Feb 13, last date on widget label is Feb 14 but that's just because it's the end of the Feb 13 bucket:

  ![timeserieslabel](https://user-images.githubusercontent.com/1779444/29277911-22598306-80e1-11e7-8292-cb7e47ba2dc3.gif)

* I'm seeing Pop-Up dates fall within the timespan selected via Time Series widget
