### ISSUE TITLE
Edit text from "Give us Feedback" form

### ISSUE THREAD

**Issue by csobier** [CartoDB/cartodb#10974]
Simply a doc, text edit requirement. I need to find and edit the content from the feedback survey form to match our style guide.

**Comment by csobier** [comment]
Gave my edits to @noguerol , he will let me know when it is merged. Thank you!

**Comment by noguerol** [comment]
I applied the changes, @csobier, with some edits:

· In question 7, widgets are not only interactive filters but actual visualizations themselves, so "charts" fits better IMO.
· Also in question 7, under "CartoCSS view", I think there's no need to give extra detail about TurboCarto, as the goal here is not to explain the feature but identify it in a short sentence. 
· Finally, in Question 10, the question should not change because the goal is not measuring the experience but the market fit, in order to somehow predict traction.

Thank you for your help, btw.
