### ISSUE TITLE
The color of the icon in the input UI gets lost after the first change of color

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#11016]
### Context

In the input interface of the fill component, there's a preview of the icon that should be colored with the selected color. There's a problem with this icon… the color gets lost after a new color is chosen.

![screen shot 2016-12-12 at 16 02 26](https://cloud.githubusercontent.com/assets/4933/21103822/471277d4-c084-11e6-911f-0c582621e570.png)

![screen shot 2016-12-12 at 15 59 06](https://cloud.githubusercontent.com/assets/4933/21103774/1787d874-c084-11e6-8685-1f8540d7d314.png)

Animated gif of the issue: 

![color](https://cloud.githubusercontent.com/assets/4933/21187059/e996bdce-c216-11e6-9fee-114394e024f1.gif)

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

0. [Optional if the feature is not released yet, checkout the `10746-image-input-fill` branch]
1. Enable the `icon-styling` feature flag.
2. Go to the style tab.
3. Select a color for the the `fill` property of the map geometries.
4. Pick an icon and see how the color is correctly set in the input UI.
5. Pick a new color. 

### Expected Result

The input UI should show the icon with the selected color.

### Current result

The icon appears in black and white.

**Comment by nobuti** [comment]
No one seems to be assigned, moving back to todo.

**Comment by ivanmalagon** [comment]
It went back to Development from CR because of this, buy work's already been done https://github.com/CartoDB/cartodb/pull/11067#pullrequestreview-13160333

**Comment by gfiorav** [comment]
Hi! I'm doing some acceptance for this but I can't get the icon to get any color at any time. It's always black. Could someone help me?

**Comment by ivanmalagon** [comment]
💀  The issue doesn't pass acceptance.

Two issues (one minor, one major)

A. I had to clear the caché to be able to see the icons. After seeing it with Matallo, it was because I already had the icons with a bad caché conf due to be working in the issue before. Just cleaning the caché solved the problem. Since no user has the feature set in production this won't be a problem.

B. Chrome is blocking the file because the page is served via HTTPS but we request a non secure HTTP file.

![image](https://cloud.githubusercontent.com/assets/1078228/21389389/baf192d0-c781-11e6-8efe-425ab3b23a61.png)


Since the resource it's not loaded, the code doesn't continue with the workflow of updating the map and hence, no icon is visualized in the map.

**Comment by ivanmalagon** [comment]
Issue B solved (see previous comment).

Now the assets get served from HTTPS always. For that to work, I changed also the S3 URL from virtual host style to path style. That's because Amazon certificate fails if using a domain with dots.

More info about that S3 general issue in [http://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html](S3 Virtual Hosting)

Excerpt from the AWS document.

```
When using virtual hosted–style buckets with SSL, the SSL wild card certificate only matches buckets that do not contain periods. 
```

Passing it again to CR.

**Comment by ivanmalagon** [comment]
Last change:

Instead of having a template with an `IMG` tag and then replace it with the result of the Ajax call for a SVG resource, now it renders `IMG` or `SVG` after knowing the resource type.

This avoids icon flickering, resulting in a smoother experience and less console errors.

The container also adapts now to bigger icons than 18x18.

Passing the issue to Code Review.

**Comment by xavijam** [comment]
Checking it!

**Comment by jorgesancha** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Style With Icons](https://trello.com/c/ehXyg2nE/1-style-with-icons)
