### ISSUE TITLE
Changing colors reset the legend type

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#11036]
![legend change](https://cloud.githubusercontent.com/assets/1078228/21148072/59567fd4-c157-11e6-9a81-533ed865e3af.gif)

 
### Steps to Reproduce
1. Style by value.
2. Create a custom legend.
3. This custom legend inherits the color ramp from the styling.
4. Go back to Style tab.
5. Change the color ramp. Only the color ramp, because you're not ok with the current selection and you want to try other combination.
6. The legend changes to a gradient one.
 
### Expected result
What I expected was to not lose my custom legend. What is weirder is that the legend doesn't dissapear but gets rendered as another type.

**Comment by javierarce** [comment]
I've been working on this issue for the past day and a half, but couldn't make it work without breaking other legend-related stuff (there aren't enough specs to test this part of Builder I'm afraid) and didn't want to submit an incomplete solution.

Since I'm leaving for holidays, I'll detail my findings in case some takes this issue before I come back and need some information: 

There are two main components that take care of loading the legends. The first one is the [LegendManager](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb3/deep-insights-integration/legend-manager.js) and the other one is the [LegendFactory](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb3/editor/layers/layer-content-views/legend/legend-factory.js).

Whenever the CartoCSS is changed, we trigger an event that removes the legends and tries to create them again using the information stored in the `styleModel`.

The thing that is causing this issue is [this line](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb3/deep-insights-integration/legend-manager.js#L65). When the CSS is changed and the layer is colored by value, we removed the legend and create it again calling the `createColorLegend` method.

The problem is that the `createColorLegend` method [always create a category legend](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb3/deep-insights-integration/legend-manager.js#L31). That means that if the user creates a choropleth legend, that method will create a category legend in any case.

I attempted to fix this, but found several issues along the way:

- In my opinion, we should try to avoid [this kind of callback nesting](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb3/deep-insights-integration/legend-manager.js#L16). Instead, I propose to remove and then create the legends again.
- We should fix the [LegendFactory.isEnabledType](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb3/editor/layers/layer-content-views/legend/legend-factory.js#L134) method, which is always returning `true` no matter what type is passed as an argument. 
- I found that the `removeAllLegend` method in that factory is not used and could be removed (obviously, this is a super minor thing)
- We should increase the spec coverage to avoid breaking stuff.

I hope this information give some light to the next person that takes this issue. Specially if that person will be me.

**Comment by ivanmalagon** [comment]
After continuing with the research done by @javierarce, I agree with him. Fixing this issue would imply whether a bad hack or a rewrite of how legends work.

One easy fix (1) is once a user has created a custom legend, any change in styling won't trigger a recreation of legends. After checking it with @saleiva and @xavijam it's a weird behaviour: sometimes legends get recreated, sometimes not.

Closing the issue.

(1) This fix implies only two changes:

at `legend-factory.js` create a new function

```
    callIfLegendDoesNotExist: function (layerDefModel, type, cb) {
      var legend = this.legendDefinitionsCollection.findByLayerDefModelAndType(layerDefModel, type);
      if (!legend) {
        cb && cb();
      }
      return legend;
    },
```

at `legend-manager.js` call this function when `color` and a `custom` legend exists.

```
  if (LegendFactory.isEnabledType('color')) {
    if (color && color.attribute !== undefined) {
      LegendFactory.callIfLegendDoesNotExist(layerDefModel, 'custom', createColorLegend.bind(null, layerDefModel, color));
```
