### ISSUE TITLE
be able to serve uncompressed javascript resources with a url flag

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#1109]
in production all the javascript files are compressed and it's impossible to debug.

we should be able to add ?debug=true to the url so the assets are served without ofuscation

**Comment by viddo** [comment]
Since we have had some cases of problematic troubleshooting, should we prioritize this one (reassign and/or put on next milestone)?

IMHO, would be better to enable source maps for production files (but keep the map files separate to not increase payload ofc), rather than an explicit flag. This would also give us more useful error reports in [TrackJS logging](https://trackjs.com/javascript/) as a bonus.

To generate and extract source maps these projects looks legit:
  - [grunt-concat-sourcemap](https://www.npmjs.com/package/grunt-concat-sourcemap) - for JS files (browserify modules include sourcemaps generation already)
  - [grunt-extract-sourcemap](https://www.npmjs.com/package/grunt-extract-sourcemap) - extract generated source maps from the JS concat'ed bundles
  - (grunt-exorcise)[https://github.com/mikefrey/grunt-exorcise] - extract the inlined source maps from browserify bundles

**Comment by xavijam** [comment]
We need it, so no matter how to do it. @rambo you decide if it is worth to include in the following millestones

**Comment by alonsogarciapablo** [comment]
+1 to doing this. It's really hard (or impossible) to debug track.js errors in production right now.

**Comment by viddo** [comment]
bump ;)
