### ISSUE TITLE
SAML username collision workaround

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11142]
### Context

Organization with SAML authentication.

_Edit by gfiorav: You must have an existing user, whose username is the result of `CartoDB::UserAccountCreator.email_to_username(email)` with the new user's email. This will provoke the collision._

### Steps to Reproduce

1. Attempt your first login with a SAML user.
2. CARTO will try to autocreate the user within the organization (see #11073).

### Current Result

"Signup issues: username is already taken" error.

### Expected result

Allow picking a different username.

### Additional info

Current solution (crashing) is good enough for onpremise (both LDAP and SAML) environments. Nevertheless it's not for SaaS (#11108).

This is somehow related to #11087, although a workaround for collisions is a must.

**Comment by gfiorav** [comment]
I've been exploring some solutions. I think 2 of them are good enough to be discussed:

1. We allow the user to choose a new username. It's more complex, we need to store state somehow (SAML response passing around might do the trick)
2. We autogenrate a valid, available username for the user. It's far easier, no state required since we generate it on the spot. Downside is that we're assigning a possibly "ugly" username to users but they won't have to use it if they're on SAML anyway.


For me, 1 is the way to go except that it adds complexity to an overcrowded session management and signup flows. 2 seems to be the best bang for the buck and maybe we shouldn't even bother until some user complains about autogenerated usernames (unlikely, IMHO).

**Comment by juanignaciosl** [comment]
I'd really go for 1 if this were used in the SaaS. In fact it's the current strategy for Google signup. But, as you say, it's not trivial. As this is an onpremise only, and the collision is really unlikely, I'd go for 2.
