### ISSUE TITLE
Disable "Apply" button when CARTOCSS or SQL has not changed after last time it was applied. 

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#11140]
### Steps to Reproduce

1. Go to the cartocss/sql panel within a layer/dataset view
2. Click on `Apply` 

### Current Result
The `Apply` button seems enabled even tho the sql/cartocss is still the same.
 

### Expected result
The `Apply` button should be disabled until the sql/cartocss changes

This should be fixed in 
- [ ] cartocss panel for a layer
- [ ] sql panel for a layer
- [ ] sql panel for a dataset

**Comment by arianaescobar** [comment]
We are getting a lot of dead and rage clicks in Builder (seen via FS) and most of them happen in our different advanced modes (SQL, CARTOCSS, HTML...) because of this issue. 

Expanding a bit on this original ticket and noting different behaviors between SQL/CARTOCSS and HTML. 

### Current Result

#### Data
![sql](https://user-images.githubusercontent.com/16247628/36974680-c56f5076-2077-11e8-86d1-05abdfe57d96.gif)
- The button always looks active
- The button is actually active and you can click on it even when no change has been made
- Feedback is given to the user when a change is applied

#### Style
![style](https://user-images.githubusercontent.com/16247628/36974692-d0c9c0d2-2077-11e8-9b93-70ccbea63b24.gif)
- The button always looks active
- The button is actually active and you can click on it even when no change has been made
- Feedback is given to the user when a change is applied

#### Pop-up
![popup](https://user-images.githubusercontent.com/16247628/36974696-d7003e22-2077-11e8-8fad-ce212546692d.gif)
- The button always looks active
- The button is actually active and you can click on it even when no change has been made
- **No feedback is given** 

#### Legend
![legend](https://user-images.githubusercontent.com/16247628/36974698-dad62764-2077-11e8-977d-afb81de8ecc4.gif)
- The button always looks active
- The button is actually active and you can click on it even when no change has been made
- **No feedback is given** 

### Expected result

1. The Apply button should only appear and be active when a change is made in the code and there is something new to apply (similar behavior to the analyses). When there's none, the button should look and be disabled. 
2. Every user action requires feedback. In this case, we need to add the same kind of notification we have on the SQL and CARTOCSS editors to the HTML ones in Pop-up and Legend.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
