### ISSUE TITLE
Enrich error messages

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#11143]
Related - https://github.com/CartoDB/design/issues/415

https://docs.google.com/a/cartodb.com/document/d/1Y1gYsSgcGW4G4VuCgnU0bqkI7eTsP5W55Fl69484aX8/edit?usp=sharing

I suppose @brittanymicek can help us with this :)

cc @vuxita

**Comment by vuxita** [comment]
yup! @brittanymicek  - can you have a look at them and fix what's needed? They are error messages from Builder UI

**Comment by saleiva** [comment]
hey @brittanymicek any update?

**Comment by saleiva** [comment]
@jorgesancha yay!

**Comment by brittanymicek** [comment]
@saleiva On it!

**Comment by saleiva** [comment]
cool thanks!

**Comment by brittanymicek** [comment]
Hey all,

Thanks for being patient here!

Some thoughts and questions below. ;)

1. For our validation process to alert users of errors in their submissions:
Have we considered using "instant validation"? 
EX: When the user is uploading a table, etc. there can be a green indication that signals the action is processing successfully. Say, for "install error" when the components are all set they should be outlined or highlighted in green before they can select "install". 

2. How instant are these validation messages appearing? I suggest they appear instantly before the load, otherwise a user goes through the whole process and then might get frustrated or feel compelled to resubmit everything, when it is just one thing that needs to be fixed.

This does not eliminate the need for error messages, just a thought.

3. How unified are these messages across mobile, desktop, in a variety of different situations?

4. How effective is the location of the messages? When does the error message occur: before or after the load? Maybe place in approximation near the input in question. We should try to always display validation within the context of the action.

5. How popular is our documentation?
I don't know if linking to documentation is _that_ helpful. Most people don't read documentation on any website. (EX: I bought a bed from IKEA. I just start making it without reading directions, something is wrong, I go back and try to examine and fix what/where I think I made a mistake (I might repeat this process twice), finally - out of frustration I read the instructions). -- This same process applies to just about anything (internet use, applications, practical). 

**About copy changes:**
We should always try to reassure the user, not blame them for their mistakes. It is all too common that users blame themselves for errors. Compounding that further with aggressive and unhelpful language only pushes them off site. We should stipulate particular requirements for a field, make the requests clear and upfront to save everyone the hassle of reminding them through validation. We should focus on concise, directional, friendly copy.

This should be communicated in the messages:

1) What went wrong?
2) Why it went wrong?
3) Solution/CTA
4) Contact support or read docs (as a last resort)

I am making suggested edits in the Google doc provided.

Again, thanks all for your patience!

B

**Comment by brittanymicek** [comment]
@piensaenpixel @vuxita DONE! Thanks for being so patient!
https://docs.google.com/document/d/1Y1gYsSgcGW4G4VuCgnU0bqkI7eTsP5W55Fl69484aX8/edit#heading=h.bmm5hi184dmw

**Comment by noguerol** [comment]
@CartoDB/design any new updates for the document? I would like to start implementing it

**Comment by piensaenpixel** [comment]
@noguerol for our side it was ok so we can start to implement it

**Comment by arianaescobar** [comment]
I couldn't find this error in the document that Britt created. 

![screen shot 2017-12-07 at 13 40 00](https://user-images.githubusercontent.com/16247628/33715923-8f4f64ee-db54-11e7-9e06-ebe1243da20c.png)

It happened when the user tried to make a SUM operation with a string column. 

Are there more errors like that one that we haven't reviewed and rewrite?

**Comment by arianaescobar** [comment]
- [ ] Add [this error](https://github.com/CartoDB/support/issues/1337) to the list.

**Comment by alrocar** [comment]
Stale issue. Closing 👋
