### ISSUE TITLE
Include the cartodb folder in the "pluggable frontends" functionality.

### ISSUE THREAD

**Issue by jorgesancha** [CartoDB/cartodb#11176]
Recently mighty @matallo implemented in #10724 a mechanism that enables changing the builder UI (CSS, HTML, text, JS, etc...) without changing the core files; this is great because customized implementations should be able to pull from the cartodb master branch without conflicts.

However, we missed a few things as outlined by @danicarrion in #10724. 

As part of this issue, it should be possible to customize also files in the cartodb folder, just like it is now possible to customize those in the cartodb3 folder.

**Comment by nobuti** [comment]
It should be nice to optimise some tasks, from the development point of view. Right now it's common to run `grunt && grunt dev`, but this process ends up running `browserify` twice.

**Comment by matallo** [comment]
deprioritizing this, as per discussion with @jorgesancha

**Comment by matallo** [comment]
to be tested along with https://github.com/CartoDB/cartodb/issues/11009

**Comment by ivanmalagon** [comment]
Accepted:

- Custom template: created a client template with an inline-style.

<img width="652" alt="screen shot 2017-01-26 at 12 13 28" src="https://cloud.githubusercontent.com/assets/1078228/22329889/ad6a1034-e3c3-11e6-8e56-a2e04d9adf84.png">

- Custom JS: created a client version of icon picker with more visible icons.

<img width="664" alt="screen shot 2017-01-26 at 12 15 12" src="https://cloud.githubusercontent.com/assets/1078228/22329917/ca2b9ada-e3c3-11e6-861e-7fb6556135cb.png">

- Custom CSS: CSS files are not in the client pipeline but as @matallo told me, it's easy to override our own styles due to CSS specificity. I added to `organization` assets folder a file that gets compiled in last place, so due to CSS specifity, last style wins. Put a pink border.

<img width="650" alt="screen shot 2017-01-26 at 12 33 06" src="https://cloud.githubusercontent.com/assets/1078228/22329978/166cfc54-e3c4-11e6-9e34-8e8afd381da5.png">

**Comment by ivanmalagon** [comment]
This issue doesn't need deploy as it's a matter of developer tooling. It's already in master branch as part of #11009 code.

Moving to Done.
