### ISSUE TITLE
Adding a point when manually setting the lat/lon values in the form doesn't get saved properly

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#11189]
### Steps to Reproduce

1. Add a points layer 
2. Click on add a feature button
3. Set lat as '0' and lon as '0' (for example)

### Current Result
Sometimes save button is no activated after entering data in the lat,lon fields (it gets activated when modifying any field on the metadata)
Other times, it gets activated corectly. But, in both situations, when saving the feature, lat and lon get persisted as null.

 ### Expected result
Feature lat/lon should be saved correctly.

**Comment by saleiva** [comment]
Prioritizing due to amount of times seen in last recorded sessions

**Comment by javierarce** [comment]
In order to test the issue, follow the instructions in the description of the ticket. It's very important that you don't place the point using the mouse or trackpad. Just click on the icon to create a new point geometry and directly update the `lat` and `long` values. 

Please, at least test:

1. Adding a point in the NULL island (0, 0).
2. Adding a point in a place with `lat` and `long` != 0.
