### ISSUE TITLE
Weird behaviour of Category widget while searching

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#11245]
So I have this category widget

![image](https://cloud.githubusercontent.com/assets/9017165/21900625/d25ec77e-d8f4-11e6-85d3-6af564919931.png)

With this config
![image](https://cloud.githubusercontent.com/assets/9017165/21900634/daa7ca48-d8f4-11e6-9f7a-20e8195ba924.png)

But when I perform a search...
![image](https://cloud.githubusercontent.com/assets/9017165/21900655/ed91bc4a-d8f4-11e6-8cf3-44311dd5b371.png)

And then, when I select the MOTORWAY and click on apply...
![image](https://cloud.githubusercontent.com/assets/9017165/21900683/044a18ce-d8f5-11e6-995d-41b54e06816b.png)

**Is it displaying COUNT during the search instead of the defined aggregation?**

.

**Comment by ztephm** [comment]
*Related: S/B 11190615* 

We thought this 2.9M number was a COUNT:

  ![screen_shot_2017-01-25_at_2 41 02_pm](https://cloud.githubusercontent.com/assets/1779444/22346625/bf85869a-e3d2-11e6-8761-8ee04a620975.png)

Because widget is set up this way:
  
  ![screen shot 2017-01-26 at 2 26 22 pm](https://cloud.githubusercontent.com/assets/1779444/22346837/89df4d68-e3d3-11e6-8378-7812d2fe8642.png)

But when user:
* Sets up a COUNT Formula widget that can interact with Category widget
  
  ![screen_shot_2017-01-25_at_3 07 54_pm](https://cloud.githubusercontent.com/assets/1779444/22346651/d44498b4-e3d2-11e6-8632-64b5254ad08c.png)

* Selects 2005 in the Category widget
* 2.9M is not the result:
  
  ![screen_shot_2017-01-25_at_2 31 10_pm_360](https://cloud.githubusercontent.com/assets/1779444/22346588/9df968a2-e3d2-11e6-8c6c-183c67a8b4eb.png)

I could not replicate with small dataset—if we need to use this client data for testing I can report in private repo.

@CartoDB/support let client know when fixed please.

**Comment by joeyscully** [comment]
We are having a similar issue with the category widget.  The strange behavior we have:
1) Category Widget does not show all of the categories - this would be okay if the search worked as expected.
2) On selecting a category from the list - the widget filters results to show only the selected category. 
But on selecting a category from the returned search results, the widget filters to show all results EXCEPT the selected category.

This is actually visible in @AbelVM post above in addition to the numbers being incorrect.

**Comment by matallo** [comment]
Indeed the values for category widgets are different in search and filter mode, the urls are different, but I'm not sure if this _weird_ behaviour is intended, it returns the resulting number of occurrences when searching.

This is the search url (find attached)

http://matatageom.localhost.lan:8181/api/v1/map/ed3080892b7bc3214bc20fa7eb425bef:1499173664221/dataview/30f62ab4-21d2-4498-8fdc-9f9212fdbbcd/search?q=9&api_key=2ccd3fe047d99a8e8c97771aa396692c6510221f

![screen shot 2017-07-04 at 15 08 20](https://user-images.githubusercontent.com/36676/27831583-931b3872-60cb-11e7-98c2-47af3e023e16.png)

This is the filter url (find attached)

http://matatageom.localhost.lan:8181/api/v1/map/c9cabc3215bdc6aadde2cd89c72dc351:1499173664221/dataview/30f62ab4-21d2-4498-8fdc-9f9212fdbbcd?bbox=-15.508092641830446,27.7838613115335,-15.505174398422243,27.787961749415377&own_filter=1&api_key=2ccd3fe047d99a8e8c97771aa396692c6510221f

![screen shot 2017-07-04 at 15 13 11](https://user-images.githubusercontent.com/36676/27831588-9857470e-60cb-11e7-8013-847f12681e3a.png)

actually when digging in the code I can see a `getSearchCount` method which makes me think *this* is the intended behavior

https://github.com/CartoDB/deep-insights.js/blob/master/src/widgets/category/stats/stats-view.js#L26-L33

please @kevin-reilly @noguerol can you shed light on this issue?

**Comment by saleiva** [comment]
@matallo that's a bug. The values should be the same IMO

**Comment by noguerol** [comment]
They do.

**Comment by dgaubert** [comment]
Acceptance: OK

![screen shot 2017-07-10 at 15 55 55](https://user-images.githubusercontent.com/1936888/28021487-58c38d2a-6588-11e7-9fe6-64ec8c2e34e2.png)

Search:
![screen shot 2017-07-10 at 15 56 53](https://user-images.githubusercontent.com/1936888/28021527-726cafae-6588-11e7-9083-f005468b9e67.png)

**Comment by AbelVM** [comment]
:heart:
