### ISSUE TITLE
Box deletion of SAML auto created users

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#11240]
### Context

Right now, if a user wants to delete her own account, she can't since the autogenerated password is never shown. I will now summarise the 2 approaches discussed to this problem:

1. A user shouldn't be able to delete her account. Only admin can do that from the appropriate panel. We substitute the "Delete my account" link with an explanatory message.
2. A user can delete her account without specifying a password (as it is with Google signings now).

@CartoDB/builder-backend

**Comment by juanignaciosl** [comment]
@saleiva what do you think about this? TL;DR: I think that option 1, blocking "self deletion" (only organization owner can delete SAML user accounts) is the better approach.

We have mixed feelings. Option 2 feels more consistent with existing approaches (Google, as @gfiorav says). Nevertheless, as a security measure within an organization 1 can be better (otherwise, anybody could delete open sessions accounts), and since SAML is SSO, as soon as the user goes to /login, the account will be regenerated (not even displaying login screen), which is weird.

**Comment by saleiva** [comment]
Why don't we let users to delete their own accounts? I think option 2 feels more –natural
