### ISSUE TITLE
Dashboard shows old, cached previews

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11271]
### Steps to Reproduce

1. Create a new map.
2. Go back to the dashboard. The preview is ok.
3. Open the map and change features color.
4. Go back to the dashboard.

### Current Result

Preview image is the cached one.

### Expected result

Preview is updated.

### Additional info

The image is displayed from browser cache. Here are the headers:

![screen shot 2017-01-17 at 10 31 18](https://cloud.githubusercontent.com/assets/932968/22014910/1d382566-dca0-11e6-98c2-bc781203a74f.png)

The `Cache-Control` header, with `public,max-age=...` is likely to be the cause. This looks related to the previous discussion at #11094.

@rochoa , will this be fixed when this is merged? CartoDB/Windshaft-cartodb/pull/615

cc @xavijam

**Comment by rochoa** [comment]
This is again only happening on Google Chrome. It's again the same "from disk cache" behavior.

Yes, https://github.com/CartoDB/Windshaft-cartodb/pull/615 should fix this problem. However, I don't understand why this changed suddenly in Google Chrome.

I will try to dig a bit more on the headers combination because this started to happen after Google Chrome 55 was released, IIRC.
