### ISSUE TITLE
Allow to style categories with patterns when the geometry is not points

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#11275]
We have detected some issues when styling categories with icons when the geometries are not points. 

Currently, this is something that's not working correctly in Editor (at least with lines), so we propose to disable the functionality for the time being by hiding the icons of the fill component **for both lines and polygons**.

![screen shot 2017-01-17 at 11 10 07](https://cloud.githubusercontent.com/assets/4933/22016776/b52a8088-dca7-11e6-8ae2-245707202e27.png)
![screen shot 2017-01-17 at 11 10 24](https://cloud.githubusercontent.com/assets/4933/22016779/b65c9428-dca7-11e6-96c8-004267ad8a3e.png)

### Steps to Reproduce

0. Enable the `icon-styling` flag.
1. Create a map
2. Add a layer with several lines (and/or polygons)
3. Style by categories

### Current Result

The fill component UI shows a list of icons. Using them to style the map doesn't work correctly.

### Expected result

In this case (geometries not being points) the UI of the fill component shouldn't offer to option of styling with icons.

**Comment by xavijam** [comment]
Hey, we should allow it, but instead of being icons we should allow only patterns.

**Comment by xavijam** [comment]
So, we should change the style-converter in order to setup the proper code in the CartoCSS. So, for example, for polygons, if an image is selected for a category, we should start using the `polygon-pattern-file` property. For lines we should use `line-pattern-file`.

**Comment by MariaCheca** [comment]
I think it would be interesting to let the users choose for what purpose do they want to use the assets. I mean, based on the assets manager we already have, show them the possibilities without tell about "these ones are for markers and these others for polygons fill". So the mandatory change we have to apply, as @xavijam says, is to decide the Cartocss property to build.

**Comment by saleiva** [comment]
Hi guys, I don't think we should merge this - that's why the feature doc only talked about points.

Having this property will create future problems when the vector integration, since this property is going to be unlikely implemented in the mid-term. Even tho this would be still possible to do by writing custom cartocss, having this in the UI will increase the number of maps using this properties.

The solution for this at the UI level would be just not showing the IMG option when editing lines or polygon layers.

**Comment by xavijam** [comment]
:+1:, ok, let's disable the image icons for the moment. Moving to development again, it will take us minutes to change it.

**Comment by saleiva** [comment]
no, image icons yes. Background for polygons and for lines, no

**Comment by xavijam** [comment]
Yeah, I wanted to mean that.

**Comment by matallo** [comment]
Noted the comments in https://github.com/CartoDB/cartodb/pull/11327#issuecomment-274893149. 

Reverted the changes and also made some further modifications. Right now you could open the image dialog going through the flow below:

1. Styles
1. Click fill component
1. Click "By value" (at this point is true that IMG tab wasn't appearing anymore)
1. Click a column to style by value, i.e. name
1. In the fill component for every category the IMG link would still appear

Besides the `_iconStylingEnabled` method which would check the icon style at user's featureflag level I'm now passing a `imageEnabled` options from the `editorAttrs`

/cc @xavijam @saleiva ^^^

**Comment by matallo** [comment]
back to development, I just found this branch introduces a bug with syntax 😞

**Comment by matallo** [comment]
spotted, it was caused because `marker-file` with empty `url()` was causing errors with polygon fill, but as we are reverting this, we don't need it anymore thus preventing the syntax error

![screen shot 2017-01-25 at 18 49 35](https://cloud.githubusercontent.com/assets/36676/22302510/70254aa2-e32f-11e6-8362-26e8e29a86e2.png)

after https://github.com/CartoDB/cartodb/pull/11327/commits/f86025197e169185deb118153016a7b3054ec29d

![screen shot 2017-01-25 at 18 48 52](https://cloud.githubusercontent.com/assets/36676/22302509/702447b0-e32f-11e6-97b3-0374e3638305.png)

**Comment by xavijam** [comment]
There is a ticket https://github.com/CartoDB/cartodb/issues/11283 about that.

**Comment by xavijam** [comment]
I'd like to review this ticket but I have several browns before, so if someone takes it, ask me for some details.

**Comment by matallo** [comment]
After last discussion with @xavijam I think this should be moved straight to acceptance

**Comment by xavijam** [comment]
Yes please 💋

**Comment by ivanmalagon** [comment]
Deployed to production.
