### ISSUE TITLE
Fix for _CDB_UserQuotaInBytes public for existing orgs

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11281]
The fix #10987 fixes future users, but existing organizations users probably need it as well.

In addition, consider reducing `public` to `CDB_Organization_Member_Group_Role_Member_Name`, it might be enough (although @javitonino pointed that code is using `public` in other similar cases).

On close, onpremise team should be pinged, so they run it on upgrades.

**Comment by javitonino** [comment]
I think there is no need for an upgrade task for onpremise, since the latest version already includes this fix.

**Comment by juanignaciosl** [comment]
Yes, but older installations have the bug, isn't it?

**Comment by javitonino** [comment]
Tested using the organization role and it works fine. The only case where this could be an issues is for non-authenticated calls to the SQL API (i.e: updates without api_key) which I don't think it would be possible here or in the future.

So I'd go for changing the code to only grant permission to the organization role. There are some instances where this trigger can have permissions to public, but I now think this is a bug rather than a feature (caused because the revoke public is done before creating the quota trigger).

What do you think?

**Comment by juanignaciosl** [comment]
LGTM 👍

**Comment by MariaCheca** [comment]
Waiting for @CartoDB/systems to solve issues preparing the onpremises.

**Comment by rporres** [comment]
@MariaCheca Fixed!

**Comment by matallo** [comment]
what happened? :S

**Comment by javitonino** [comment]
Oh nothing, it got autoclosed on merging the PR and I reopened until the deploy and the rake have finished running. Nothing to worry about 😄, sorry for the little fright.

**Comment by matallo** [comment]
phew 😅

**Comment by javitonino** [comment]
Please CR https://github.com/CartoDB/cartodb/pull/11395 (needed for running the rake), and we can go to deploy directly again.

**Comment by juanignaciosl** [comment]
@javitonino I'll merge and deploy #11395, stay tuned to trigger the rake again

**Comment by javitonino** [comment]
Deployed and task ran successfully.
