### ISSUE TITLE
Improve Edit Widget form copy

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#11301]
When you're editing a widget we may want to change the "Fill" copy to something like: "Bar Fill" and also a good improvement would be not to crop the text below: "Custom ramp" which IMHO is not clear enough. 

![image](https://cloud.githubusercontent.com/assets/596509/22027105/045d662c-dcd3-11e6-8b89-4406782b6bf7.png)

**Comment by saleiva** [comment]
I propose we change them to:
- BARS FILL
- RAMP

**Comment by namessanti** [comment]
Hey both, this caught my eye. Mamata and Marketing have been working very hard on terminology and making sure we don't run into any language issues in the UI and with our content. If possible, can we try to keep the color terminology consistent or updated in tandem with our/Mamata's [guidelines](https://github.com/CartoDB/learn/wiki/Color-Terminology-in-Builder) as Sergio and I discussed?

We want to make sure language decisions are consistent to avoid future issues like we've had in the past.
 
As an example, Marketing and Mamata specifically determined that the term "ramp" should not be used, as it is reserved for speaking about TurboCARTO.

Happy to help find a way of doing this more effectively. 

@makella @iancwalsh for input.

**Comment by makella** [comment]
Yeah, that was my suggestion to keep the word ramp for TurboCARTO because that syntax is already used (i.e. `ramp[attribute],...`). Not only can you ramp color, but you can also ramp other things like symbol size, line width, etc.

In the product doc I recommended 'color scheme'. This is another way color ramps are referred to.

I'm open to other ideas but I think that it is helpful to differentiate between TurboCARTO ramps and CARTOColor (or other) color schemes.

mamata

**Comment by xavijam** [comment]
So, how should we call those terms then? What do you propose?

**Comment by makella** [comment]
@xavijam for the "Custom Ramp" to be consistent with our terminology, I think we could say "COLOR SCHEME" that way we can still keep "ramp" for TurboCARTO.

Is there a limit on the number of letters we want to use?

**Comment by noguerol** [comment]
@CartoDB/design to have a look at this and unblocking it. I suggest the obvious "Widget color" and "Map colors". It should fit, tight?

**Comment by arianaescobar** [comment]
[On June](https://github.com/CartoDB/cartodb/pull/12282#issuecomment-306808161), @makella and I decided to rename the "Custom ramp" label to "Custom color", IMO we should keep that name. 

Regarding the FILL label, [we just renamed it to COLOR](https://github.com/CartoDB/cartodb/issues/12564) and again, I think we should keep it that way... 

What do you think @josecruz? since you were the one that originally opened the ticket

**Comment by namessanti** [comment]
@csobier for visibility

**Comment by josecruz** [comment]
@arianaescobar yep makes sense. This was before that ticket so if we already made that change we can keep the same approach.

Thanks!!

**Comment by nobuti** [comment]
So @josecruz @arianaescobar, the only thing to do in this issue is to get rid of the ellipsis in `Custom colors`, right? Do we have any solution for the layout of those fields?

**Comment by piensaenpixel** [comment]
Custom color is ok @nobuti the only solution is show the tooltip

**Comment by nobuti** [comment]
So are we done? The label has been changed in https://github.com/CartoDB/cartodb/issues/12788
