### ISSUE TITLE
Invite to georeference proactively when detecting non-georeferenced data.

### ISSUE THREAD

**Issue by carlostallon** [CartoDB/cartodb#11316]
### Context
When you enter non georeferenced data, we are adding a new enhancement to avoid a user could end up not seeing anything on the map and not knowing he must georeference the data, which
would end up in a blocker

### Step by step mockups
![01 initial state](https://cloud.githubusercontent.com/assets/1712650/22145563/3671b66e-df02-11e6-9090-5a0c5ae22c80.png)
![02 added new layer - take action](https://cloud.githubusercontent.com/assets/1712650/22145567/36761894-df02-11e6-9e42-9234ae5d0109.png)
![03 new layer added](https://cloud.githubusercontent.com/assets/1712650/22145566/36729070-df02-11e6-8672-8fcf64c355e7.png)
![04 any georeferenced layer](https://cloud.githubusercontent.com/assets/1712650/22145562/36717c30-df02-11e6-8933-72cd7479664d.png)
![05 not georeferenced layer hover](https://cloud.githubusercontent.com/assets/1712650/22145565/36726afa-df02-11e6-86d0-5a78ef8c83f1.png)
![06 layer style](https://cloud.githubusercontent.com/assets/1712650/22145564/36720704-df02-11e6-84e7-da6bb5fa5811.png)
![07 layer legend](https://cloud.githubusercontent.com/assets/1712650/22145569/36877990-df02-11e6-90fe-554448447ad6.png)
![08 layer pop-up](https://cloud.githubusercontent.com/assets/1712650/22145568/3685c974-df02-11e6-98e5-c4a17706df81.png)

### Design ready
Sketch archive here: `Dropbox / CartoDB / Projects / 01-webapp / 03-Map-editor / 02-mockups / 3.x / _issues / 465 proactive georeference `

### Related design issue
https://github.com/CartoDB/design/issues/465

**Comment by xavijam** [comment]
Oido cocina!

**Comment by saleiva** [comment]
While fixing this, we should also fix another issue which is that when not having georeferenced data, we shouldn't let people to add widgets from that layer.

**Comment by xavijam** [comment]
But it is possible that the user wants to connect a widget to that "node", where at the same time, it is connected to another node by an analysis. Make sense?

**Comment by saleiva** [comment]
I don't think widgets work without georef data...

**Comment by xavijam** [comment]
Arg, you are right, I was blind by the data stats.

![screen shot 2017-02-08 at 14 29 13](https://cloud.githubusercontent.com/assets/132146/22739224/0c007be6-ee0b-11e6-85c0-60290e287cfa.png)

**Comment by matallo** [comment]
already started working on this, on top of the work done for the onboarding, I have some doubts, though

- Shouldn't we show this screen *once* the user has entered the layer?

It could be hard to approach the case where *several* layers have non-georeferenced data. Also, once the user enters the layer that tab (style) would be the one selected. I think this will be more consistent with the rest of the onboardings, like analysis, and easier to handle (Maybe I'm a bit biased).

![8d05ac15-1df4-4061-85ad-87a7470cc32e](https://cloud.githubusercontent.com/assets/36676/23071537/faa9eb9a-f52e-11e6-81bf-070b386d9740.png)

- The same case happens with the warning box, I'm used to see them *inside* the layer.

- The placeholder image beside the georeference button looks weird to me, it looks like a layer block, but you are already inside the layer.

Finally, is this the final copywriting?

Thanks!

**Comment by saleiva** [comment]
cc/ @CartoDB/design

**Comment by matallo** [comment]
wip on this issue has been done in the next branch https://github.com/CartoDB/cartodb/tree/11316-georeference

**Comment by arianaescobar** [comment]
Let me try to give a bit more of information: 

The message _à la onboarding_ will only be shown the first time ever you add a non-georeferenced layer to a map on your account. After marking that message on the "Don't show me this again", the next time you add a non-georeferenced layer to a new map (and ONLY if it's the first non-georeferenced layer of that map), we'll show you the notification + icon.  

So we'll only give this information once per map because it's possible that our users might like to add a non-georeferenced layer to use on an analysis without needing it to be georeferenced and we don't want to bother anyone with the same message over and over again. 

That's why we want those messages to appear on the layer list, instead of inside the layer itself. If we show it inside the layer, we might also have issues when mixing the layer onboarding with that first initial message, so that's another reason in favor of doing it on the layer list. 

I didn't understand this part:

> "The placeholder image beside the georeference button looks weird to me, it looks like a layer block, but you are already inside the layer" 

Could you elaborate on it? @matallo 

Regarding the copywriting being final, yes it is. It was already reviewed by @brittanymicek and approved by Design. Are you seeing anything strange that we should take a look at? 

I hope this solves your doubts :)

**Comment by matallo** [comment]
Sure, that was the case when you are in the layer view, and you are presented with a card whith a resemblance to the layer card i.e.

![08 layer pop-up](https://cloud.githubusercontent.com/assets/1712650/22145568/3685c974-df02-11e6-98e5-c4a17706df81.png)

that reminds me of the layers view cards

<img width="306" alt="screen shot 2017-02-20 at 11 44 48" src="https://cloud.githubusercontent.com/assets/36676/23121927/93cd026e-f762-11e6-922f-3551764610d3.png">

which look weird to me, since in my mental model you are already *in* the layer view, and you are presented with the layer card, being the georeference an analysis, I'd go with the same style than analysis placeholder, but idk

<img width="311" alt="screen shot 2017-02-20 at 11 50 24" src="https://cloud.githubusercontent.com/assets/36676/23122009/db6ad83a-f762-11e6-8481-2e5a93befa82.png">

---

OK to the rest of comments, and thanks for the extensive explanation

**Comment by arianaescobar** [comment]
Oh, got it! You are right, let us take a look and we'll get back at you on that.

**Comment by arianaescobar** [comment]
Ok, green light on making it look like the analysis placeholder instead of the layer one. Great catch @matallo :)

**Comment by xavijam** [comment]
:clap:

**Comment by matallo** [comment]
Coming back to this, what happens when the user hasn't gone through the builder onboarding? I break down the steps below:

1. User enters in her newly created account
1. add a non georeferenced dataset from dashboard
1. goes through builder onboarding
1. goes through georeference data onboarding ?

I'll stick to the design but I just wanted to bring up this quite common case

**Comment by matallo** [comment]
Also there's still the point about how to approach the case where several layers have non-georeferenced data, as the user can select several dataset at the moment of create the map in the dashboard.

What has to be shown in the onboarding, then?

**Comment by arianaescobar** [comment]
After discussing it with the team...

To your first doubt, yes, the Georeference "onboarding" would appear after Builder's main onboarding. 

To your second doubt, the onboarding would show the information of the first non-georeferenced layer and the main button will take you to georeference that layer.

**Comment by matallo** [comment]
Advanced with this, this is looking good 🙂

btw, I'm just showing it in case there are rows (it makes no sense to georeference an empty dataset, despite it will say it has no geometry 🙈 I will elaborate on this in the PR, but maybe you'd like to think in *another* onboarding to add rows to an empty dataset 😬 )

thanks for bearing with me!

**Comment by xavijam** [comment]
Back to development again (and hopefully the last one). We will tackle last small details on monday and then, 🚀 .

**Comment by xavijam** [comment]
Ready to be deployed! 🎉  🎉  🎉

**Comment by matallo** [comment]
:_)

**Comment by xavijam** [comment]
Annnnddddddddd DEPLOYED!

**Comment by saleiva** [comment]
Is this finally instrumented? @noguerol
