### ISSUE TITLE
Can't Edit A Polygon: Read Only Despite No SQL Query Applied

### ISSUE THREAD

**Issue by tbirdman86** [CartoDB/cartodb#11356]
### Context
*Please explain here below what you were doing when the issue happened*

After creating a polygon I am unable to edit it both the map view and the data view. I get error message "Feature editing is disabled in layers with custom SQL applied......"

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Import the .carto file attached
2. Draw polygon anywhere on the map. Add and save polygon.
3. Return to layer selector view, select layer the polygon was added to. Click on Polygon to edit.

![screen shot 2017-01-25 at 11 33 16 am](https://cloud.githubusercontent.com/assets/11561481/22301704/f2578296-e2f9-11e6-9189-85722df4a081.png)

### Current Result
*Please describe here below the current result you got*

 Error message "Feature editing is disabled in layers with custom SQL applied......"

### Expected result
*Please describe here below what should be the expected behaviour*

Ability to edit in both map view and data view

### Browser and version
*What internet browser (Chrome, Firefox, etc) and version was you using and version* 

 Chrome

### .carto file
*Don't forget to rename .carto file to .zip file to be able to upload to github*

.carto file can be downloaded from "resources". Too big to attach here...
https://carto.com/learn/guides/data-and-sql/create-and-manage-data-by-drawing-geometries
 

### Additional info
*Please add any information of interest here below*

I also cannot delete points or lines....

**Comment by csobier** [comment]
@xavijam ,  this behavior only happens when you do this in a team account. When I did this using a personal, free account, I had no issues.  Can you help us figure this out?

**Comment by xavijam** [comment]
I'm just checking it.

**Comment by xavijam** [comment]
There is one issue, but it is related to other thing. If you check the layers view:

![screen shot 2017-01-26 at 17 19 53](https://cloud.githubusercontent.com/assets/132146/22339847/c14c100c-e3eb-11e6-996e-2ba4dc20ffda.png)

We consider that a custom query is applied because it is not qualified (with the username before the table name, being imported in an organization account). That means we should not let the user edit or add a feature, that's the bug.

**Comment by xavijam** [comment]
If you clear the query of any of those layers, the behaviour should be working.

**Comment by csobier** [comment]
This is weird, no SQL query appears the SF_Parks map layer (when viewing it in my free account). 

When testing with the team account (builder-demo), the map layer is imported showing `SELECT * FROM "builder-demo".untitled_table_15`, so maybe it thinks a SQL query is applied, but it isn't.

**Comment by xavijam** [comment]
Yes, that's due to the thing I've explained two comments above.

**Comment by csobier** [comment]
Ok, so it's a bug. Is it going to be fixed?  
These are .carto files that we're sharing in the public Guides. Ideally, Enterprise and Free users can step through the guides without having to use different workflows.  Let me know if I'm misunderstanding something.

**Comment by csobier** [comment]
I got more confirmation that this happens when importing .carto files from non-org to org accts.  @juanignaciosl, can you add this to your queue when fixing .carto file behavior?

**Comment by juanignaciosl** [comment]
I'm speaking with @xavijam about this. The .carto import is right, we need to review the "custom query applied" checking.

**Comment by javitonino** [comment]
@tbirdman86 @csobier An easy workaround: You should be able to see there is an SQL indicator in the layer view. If you go to the layer, to the SQL view, and click on "Clear", you should be able to edit this.

**Comment by xavijam** [comment]
So finally, we are going to fix the frontend problem (https://github.com/CartoDB/cartodb/issues/11442), and about the thing you are mentioning, we can't change the behaviour right now. It is:
"If a standard user exports his/her map, and then another organization user imports that map, those imported layers will appear with a query applied". Because the query is not qualified (username.table_name) and it is necessary in order to consider it like the default one in this kind of organization accounts.

**Comment by kaeladickens** [comment]
Hello, I'm actually having this issue now, but I never uploaded a workbook; just downloaded my layer. Help?! @jaimecartodb
![20210730_184119](https://user-images.githubusercontent.com/22648841/127721581-4594a409-4094-4450-9585-5c8e2b688724.jpg)
