### ISSUE TITLE
Ability to export/import only metadata at .carto files

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11388]
As tables can already exist in a user account, visualization export/import api should support exporting/importing only the metadata.

**Comment by juanignaciosl** [comment]
Added to TODO because this make sense for many use cases beyond importing. In fact, this should be documented in NEWS, and in the public import API docs when it's released.

**Comment by juanignaciosl** [comment]
On hold. This is not strictly needed as long as a "skip existing datasets" strategy is implemented on import. See #11385.

**Comment by javitonino** [comment]
I still this would be useful (and could even be considered a bug). Right now, the parameter is there and can be used to export only some datasets. The problem is that there is a `present?` check that treats an empty array the same way as a null (param not present), so if an empty array is passed to the list of tables to export, it exports all datasets instead of none.

**Comment by juanignaciosl** [comment]
It's slightly different: current user table selection also changes the exported layers. Layers with tables that are not exported are not exported. And user table selection is not documented.

This can be useful for a performance point of view (and some customer requested it time ago, check #8211), but #11385 covers the most common scenario from a user point of view.

**Comment by javitonino** [comment]
Oh, I didn't know that it also affected layers 🤐

**Comment by juanignaciosl** [comment]
Closing automatically because of inactivity. If anybody considers that this still important, please reopen and it'll be prioritized.
