### ISSUE TITLE
Address table duplication on .carto importing

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11385]
### Context

If we want to take advantage of .carto for migrations, we should address current table duplication on collision. A `strategy` parameter, allowing duplication (current behavior) or skipping would be fine. 

Overwriting might also be useful, but it's an overkill for current needs. Extracted here: #11389.

 

### Steps to Reproduce

1. Create two maps based on the same table.
2. Export them and import it into another account.

### Current Result

Table is duplicated.

 

### Expected result

There should be a way to avoid duplication.

Please note that this only addresses _table_ duplication. Map duplication is not a problem (not right now, at least).

- [x] .carto
- [x] Normal imports.
- [x] Connectors.

**Comment by juanignaciosl** [comment]
Pending:

- [ ] Documentation.

**Comment by javitonino** [comment]
Have you considered the case when the imported dataset exists in your dashboard but is not owned by you, i.e: it is shared with you by someone else?

**Comment by juanignaciosl** [comment]
Yep, I'll only look for physical tables in my schema (just like importer does, when it has to rename tables).

**Comment by javitonino** [comment]
I am mentioning that because for using `.carto` import for migrations, we might need to look at shared datasets as well (to avoid copying shared dependencies into your account). I don't see a clean solution for this (as you may need to look into the .carto.json in order to determine if the dataset came from your account ot not). But if we do not implement something like this, we would be duplicating datasets, which we might not want.

As I said, I do not have a solution for this. Implement your solution instead of overcomplicating this might be the best solution.

**Comment by juanignaciosl** [comment]
Oh, I was focusing on the opposite scenario, good catch! I just opened an issue: #11434. I think that it's not critical, though. Let's wait for feedback before adding it to the milestone.
