### ISSUE TITLE
onboarding responsive steps breaking layout

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#11444]
### Context
onboarding screens are not prepared for mobile (see attachment)

### Steps to Reproduce

1. create a map
2. change viewport

### Current Result

the onboarding steps may break depending on the viewport
 

### Expected result

the onboarding steps should adapt to mobile viewports ideally, or at least not break in desktop for several viewports

### Additional info

![3b2ae910-699b-4a53-abc1-51550be85c2f](https://cloud.githubusercontent.com/assets/36676/22586577/d428a57e-e9fd-11e6-9e20-567786f77429.png)
![2725aa10-7056-4151-9f8a-160c5d4cf054](https://cloud.githubusercontent.com/assets/36676/22586576/d424605e-e9fd-11e6-97af-3f3333811da1.png)
![e66da728-e8ad-4a67-adc4-827f8542e405](https://cloud.githubusercontent.com/assets/36676/22586578/d429da16-e9fd-11e6-8866-57b61ea26079.png)

**Comment by ivanmalagon** [comment]
As a side effect, I found that analyses onboarding behaves badly in small sizes.

![image](https://cloud.githubusercontent.com/assets/1078228/23129813/6e829a42-f784-11e6-9cfe-ad7bd5249c35.png)

Since this is related somehow with this ticket I add it here.

Moving back to dev to fix this, so we have all onboardings nailed.

**Comment by ivanmalagon** [comment]
🇯🇲

**Comment by ivanmalagon** [comment]
Deployed to produ.
