### ISSUE TITLE
consider republishing map after layer deletion (or another approach)

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#11441]
### Context
when removing a layer with analysis involved in a map, the embeds are returning an instantiation error until the map is republished again, we should consider this or another approach to prevent further errors 

### Steps to Reproduce

1. create a map with two layers, A with an analysis join to B 
2. publish and open embed
3. removed layer A dataset (the one with analysis)
4. refresh embed (map instantiation error)
5. republish and refresh embed

### Current Result
you have to republish again to get rid of errors 

### Expected result
no further actions out of the deletion layer flow need to be executed to prevent errors in the embed

one approach would be confirm republish at deletion layer modal, further approaches need to be explored

/cc @saleiva @xavijam @juanignaciosl

**Comment by saleiva** [comment]
wow, wow catch. This is something I experienced but couldn't reproduce.
shouldn't we keep the old map working until you publish it again. Only deleting the dataset from your account should give this error

**Comment by javitonino** [comment]
I tried the STR and nothing broke. Actually, I think this only happens when deleting a dataset. @matallo can you confirm? We came into this during an acceptance, but it was caused by dataset deletion. Maybe he found another way to make it break.

**Comment by matallo** [comment]
indeed, I updated the **str** to "removed layer A dataset", sorry for the hassle

**Comment by gfiorav** [comment]
Interesting: when I first demoed the mapcap, I deleted the dataset to show the embed still showed.

Something must have changed since.

**Comment by gfiorav** [comment]
For deleting a dataset I would pass on republishing: this would bring a broad range of changes to the public view without the user realising it. I don't think it's natural for a user to think that some maps will be published if she removes a dataset!

I'd suggest we rewrite the name map template to avoid the instantiation error or even the whole layer. I'd only remove the layer if we can warn the user beforehand, though.

**Comment by juanignaciosl** [comment]
@gfiorav what about blocking the deletion of a dataset that has a published layer that depends on it? A map that is published should never change (only the data)l, that's the whole point of publishing. If a user tries to delete it we should check not only the "live" layers but also the published mapcap. It shouldn't be _that_ hard and it's informative and actionable for the user.

**Comment by gfiorav** [comment]
@juanignaciosl Sounds cool. I don't know if we should add a mapcap dependency to dataset, but if it makes "product sense" I'm all for it :)

**Comment by javitonino** [comment]
IMHO, if we do block deletions, there should be always a button to override (or else, it would be a pain to go manually to all maps and remove the affected layers from then, which is hard in complex maps). 

We could also use the production-tested (only in rakes though) mapcap rewriter to remove the layers from the mapcap as well, so at least there is something displayed in the embed, instead of an instantiation error.

Also @juanignaciosl opened another box by mentioning that right now we only check the live map for dependencies, not the mapcaps.

**Comment by juanignaciosl** [comment]
I was thinking about asking the user for confirmation and then deleting the layer + republishing, but republishing can have unexpected outputs, because user could've changed it.

I'd ask for confirmation: "ey, these published maps have layers that depend on this dataset. If you press continue the dataset and those layers will be deleted".

And, internally, I'd duplicate the mapcap and remove the layers (keeping the previous one, just in case).

**Comment by javitonino** [comment]
People are already warned that the map will be affected. (although there is no specific warning for the published version). We could also update the published version of affected maps when deleting a dataset, manually deleting the layer, widget and analyses from the mapcap (without republishing changes in other layers), but maybe this is too complicated for something that doesn't happen too often and already has a big warning on it.

**Comment by juanignaciosl** [comment]
Even though there's a warning, no action should lead to broken maps. Deleted maps after confirmation are a valid outcome, broken ones are not (IMHO).

I think that your proposal is more or less what I suggested. I just said to duplicate the existing published version before changing it to have a rollback strategy.

**Comment by javitonino** [comment]
> Even though there's a warning, no action should lead to broken maps.

We cannot guarantee that without keeping a layer<->user_table cache for mapcaps as well as the live maps (or checking affected tables on the mapcaps of all maps in the org on dataset deletion).

**Comment by juanignaciosl** [comment]
In the moment of the dataset deletion, the layer <-> user_table relationship for that dataset is there. Can that be used to get the layer and check whether the layer is in the published mapcap?

**Comment by javitonino** [comment]
Think the opposite case. You create a map with two layers (A, B), you publish it, and then remove one of the layers (B) without republishing. If you delete the dataset linked to B, you will not get a warning (since the live map is not using it), but the embed will break.

**Comment by juanignaciosl** [comment]
Oh, of course :-\ Then, there can't be an actual control without an additional caching (calculating it live is not an option, it'd be too slow).

As people are warned, then, I'd choose caching it (maybe not now, it's not critical).

**Comment by juanignaciosl** [comment]
@saleiva TL;DR: in order to do the same with _published_ maps than we do with maps (accurately warning the user and being able to delete affected layers) we must cache the relation between the mapcap and the dataset, which is not trivial. From our point of view, this shouldn't be prioritized now because, as you said, deleting the dataset from your account could trigger this error. Do you agree?

**Comment by juanignaciosl** [comment]
Closing automatically because of inactivity. If anybody considers that this still important, please reopen and it'll be prioritized.

**Comment by juanignaciosl** [comment]
FYI a renamed table caused a spike of errors today because of this (a popular, broken embed). I contacted @CartoDB/support about this. Nothing that we're not aware of, but maybe tracking if this happens often is useful.

cc @CartoDB/builder-backend @jorgesancha
