### ISSUE TITLE
Listing table names for adding tables or merging is very slow

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#1147]
I have 1030 tables in my account, and if I try to merge some tables, the selector for the table takes 60 seconds to load (literally).

What about showing first the last updated tables and then load the rest?

**Comment by andrewxhill** [comment]
Hey, I'm told it doesn't matter for team accounts. @auremoser has maybe 10 in her team.cartodb.com account. I'm guessing that it has to index all accounts in this organization to populate the menu. This needs a fix. It is killing me in live demos. I'll have to stop using my team account, which is terrible since it is where I have a legacy of examples and use-cases stored up.

Feel the pain (20MB)

https://dl.dropboxusercontent.com/u/1307405/CartoDB/trash/table_index.mp4

**Comment by xavijam** [comment]
This is already fixed and with the new modals, this problem will not happen anymore! :)
cc @Kartones
