### ISSUE TITLE
Viewport in embed does not always respect viewport in Builder

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/cartodb#11486]
### Context
Trying to fit the view to a layer in a dashboard

### Steps to Reproduce
* Any map, any layer
* "Fit to layer"
![image](https://cloud.githubusercontent.com/assets/9017165/22731206/1dce6a52-edea-11e6-86b7-cef89fe5417f.png)
* Publish
* The viewport can be quite odd. Mainly because of zoom levels
![image](https://cloud.githubusercontent.com/assets/9017165/22731216/2571f558-edea-11e6-9902-f394b38148e0.png)

### Current Result
The view is zoomed out 1 step in embed when zoom level in Builder is <= 6 

### Expected result
Best fit of viewport, keeping center and same zoom as Builder, or best fit for BB

### Browser and version
Any, but could it be related to screen aspect ratio? 
 
cc @javitonino

**Comment by xavijam** [comment]
Well, we can save center + zoom, there is no problem. Are we sure of that?

**Comment by saleiva** [comment]
what are we storing now?

**Comment by javitonino** [comment]
The view bounds in Builder (longitude and latitude of the NE and SW corners of the screen). The idea being to keep the same viewport in screens of different sizes, even if it means changing zoom.

**Comment by saleiva** [comment]
Yes, I do think we will have to switch to zoom + center.

**Comment by xavijam** [comment]
👍 . We could store both things, bounds and center+zoom, and then decide what to use in the embed view, sounds good? It would be possible with the state model in backend, wouldn't it @CartoDB/backend? I've checked it just expects a json so...

**Comment by javitonino** [comment]
No problem adding it to state, as you said it's just a JSON and it is presented fully in embeds. No filtering or validation going on, so it should be ok.

I'd keep using map bounds, at least for much different screen sizes (mobile), otherwise you only see a very small portion of the map.

**Comment by xavijam** [comment]
I agree with @javitonino, but you decide.

**Comment by talos** [comment]
Agreed we need to resolve this, right now depending on if you're on retina/mobile/non-retina our [recently published blog post](https://carto.com/blog) has maps centered on totally different areas (sometimes not even over the USA).

<img width="1680" alt="screen shot 2017-03-30 at 11 01 37 am" src="https://cloud.githubusercontent.com/assets/415831/24511153/2ed2b846-1539-11e7-88b2-7322a4daeb21.png">

**Comment by jgoizueta** [comment]
I see no perfect solution for this, the problem being, is that what should ideally preserver is some Area of Interest that the user has in mind, and preserving either the bounds or the center/zoom will produce unwanted results in general:

![img_20170403_111210](https://cloud.githubusercontent.com/assets/5909/24602839/cf64b728-185e-11e7-814b-e8e5a8f47f71.jpg)

**Comment by xavijam** [comment]
Very nice explanation man! 💋

**Comment by saleiva** [comment]
let's go with c+z since it's what covers most of the corner cases

**Comment by AbelVM** [comment]
I used to use a hybrid solution for aspect-independent bbox:
* Get BBox
* Calc the "max square within bbox". I mean, cut the rectangle shaped BBox to get a squared one with the same center and the the side the same size as the shortest size of the original BBox
* Save this as your Builder BBox
...
* FIt bounds to this square in Embed

**Comment by jgoizueta** [comment]
It seems like reasonable compromise to me, should work for most AOI (unless it is too tall or too wide)

**Comment by xavijam** [comment]
Hey guys, after fixing [this issue](https://github.com/CartoDB/cartodb/issues/11894) and [this issue](https://github.com/CartoDB/support/issues/605), I feel the experience will be totally different. Could you give us one day to fix, merge, deploy and then test it the behaviour is consistent and good enough? I'm pretty confident we will be happy, promised.

**Comment by xavijam** [comment]
In any case, we have to block it until we have those issues fixed.

**Comment by saleiva** [comment]
What are we doing with this then?

**Comment by AbelVM** [comment]
![image](https://cloud.githubusercontent.com/assets/9017165/25803189/08904d48-33f6-11e7-81ed-eb052906c559.png)

**Comment by alonsogarciapablo** [comment]
Bump!

https://github.com/CartoDB/cartodb/issues/11783 breaks this (a bit more) so I'm having to investigate how all this works behind the scenes. I'm going to describe my understanding of how this currently works:

Once the viz.json and map has been loaded (this is what we're changing in #11738), [`deep-insights.js` reads the state from URL (or given opts)](https://github.com/CartoDB/deep-insights.js/blob/master/src/api/create-dashboard.js#L66-L72) and:

1. If bounds are present in the state, it instructs cartodb.js to calculate and adjust the zoom level to the given bounds (via `Map#setBounds`). [This is the method that performs the zoom calculation for some given bounds](https://github.com/CartoDB/cartodb.js/blob/develop/src/geo/map.js#L528-L558). I think this is default behaviour for BUILDER since state now also includes `bounds`. This requires the map view to be ready because the new zoom level is directly related to the size of the map's container.

2. If bounds are not present in the state but zoom and center are present, it instructs cartodb.js to set some new zoom and center (via `Map#setView`). I guess this is the behaviour we had before bounds were stored in the state. There's no need to do this explicitly [here](https://github.com/CartoDB/deep-insights.js/blob/master/src/api/create-dashboard.js#L70). Instead, we could set the initial center + zoom [here](https://github.com/CartoDB/deep-insights.js/blob/master/src/api/create-dashboard.js#L55-L59).

So now that this is a bit more broken (in our PR), I see two options:

1. Forget about trying to automagically adjust zoom for given bounds and render the map with `center` and `zoom` values from state (if present). Many of you are suggesting this. We can then find a way to do this better.
2. I can change things in my PR and leave things as they were, although we'll still have this issue.

@saleiva @noguerol this is a product decision so I guess you guys should decide how to go with this. Thanks!

**Comment by alonsogarciapablo** [comment]
cc: @donflopez ☝️

**Comment by saleiva** [comment]
I'd go with **option 1** @alonsogarciapablo 

I do think that user expect maintaining the center more than the "aspect ratio" of the map – and the behaviour is easier to explain and understand.

**Comment by alonsogarciapablo** [comment]
👍  Thanks @saleiva!

**Comment by nobuti** [comment]
In production.
