### ISSUE TITLE
Add SSLmode parameter to postgresql connector

### ISSUE THREAD

**Issue by luisbosque** [CartoDB/cartodb#11527]
As described in the public doc (https://carto.com/docs/carto-engine/import-api/database-connectors#the-postgresql-connector) I 'm trying to connect to a remote PostgreSQL database. This database requires SSL connection.
The import is failing with Unknown error. 

After a debugging process thanks to @jgoizueta I have learnt that the connector does not support passing a sslmode parameter. It should accept and honor this parameter in order to be able to connect to PostgreSQL servers through SSL.

In this case the value of SSLmode parameter would be "require".

Doc about the accepted SSLmode values https://www.postgresql.org/docs/9.5/static/libpq-ssl.html#LIBPQ-SSL-SSLMODE-STATEMENTS

**Comment by jgoizueta** [comment]
We'll need to decide what's the most sensible default for this parameter in our connectors. The odbc driver default is "disable". We could have better default security by making it "prefer" (although it may incur in some overhead).

**Comment by zenitraM** [comment]
IMO we should try to enforce SSL and then maybe add an option for the client to be able to "unenforce" it if needed. 

SSL is usually enabled OOTB in Postgres, I think asking the clients to have their data encrypted on transit is a reasonable request

**Comment by jgoizueta** [comment]
This is the plan:

1. [ ] 1. Decide the default value for the new parameter (require? prefer?) and prepared changes to public docs.
2. [ ] 2. Detect current users making use of the PG connector; prepare a  message to inform them.
3. [ ] 3. Implement the new parameter, CR.
4. [ ] 4. Write acceptance instruccions; check acceptance.
5. [ ] 5. Inform users (via support?). Deploy Builder changes & public docs;

**Comment by jgoizueta** [comment]
For the default value I'll follow @zenitraM's advice so we get better security by default, since it will likely not affect existing users. So the default value will be `require` and should this not work for the user, they can add the new parameter with the value `disable` to restore previous behaviour, or, better yet, `prefer` so that they can use non-SSL connections now, but switch automatically to SSL if their server supports it in the future.

**Comment by jgoizueta** [comment]
I've been looking at the situation of our other connectors respecting SSL connections:

### MySQL

(See https://dev.mysql.com/doc/connector-odbc/en/connector-odbc-configuration-connection-parameters.html)

The driver has `SSLMODE` parameter since version  5.3.7 (of the drive) with values  `DISABLED`, `PREFERRED`, `REQUIRED`, `VERIFY_CA`, or `VERIFY_IDENTITY`
which seem equivalent to those of PG (except that there's no `allow` option)
(see Additional information: https://dev.mysql.com/doc/refman/5.7/en/secure-connection-options.html and https://dev.mysql.com/doc/refman/5.7/en/secure-connections.html)

In prior versions (we're using 5.1 & 5.2) we have to use other parameters, but we can emulate most of the values for `SSLMODE`:

* `DISABLED` : `SSL_ENFORCE=0; DISABLE_SSL_DEFAULT=1;`
* `PREFERRED` : `SSL_ENFORCE=0; DISABLE_SSL_DEFAULT=0;` (this is the default behaviour)
* `REQUIRED` : `SSL_ENFORCE=1; DISABLE_SSL_DEFAULT=0;`
* `VERIFY_IDENTITY` : `sslverify=1``
* `VERIFY_CA` : this requires setting `sslca` or `sslcapath`

Additionally the versions of TLS accepted can be narrowed with the parameters `NO_TLS_1_0`, `NO_TLS_1_1`, `NO_TLS_1_2`.

The default values are `SSL_ENFORCE=0` and `DISABLE_SSL_DEFAULT=0` which is equivalent to `SSLMODE=PREFERRED`.
So it is not critical that we add a `sslmode` parameter to our MySQL connector since SSL conections would now be used if available.

### SQL Server

(See https://odbc.postgresql.org/docs/config-opt.html)

I'm not quite sure after looking at the docs, but it seems to me that to use SSL we should set these parameters:
`Encrypt="yes"; TrustServerCertificate="yes"`

### Hive:

(See https://hortonworks.com/wp-content/uploads/2015/10/Hortonworks-Hive-ODBC-Driver-User-Guide.pdf)

To use SSL (which is not the default) we should set: `SSL=1; AllowSelfSignedServerCert=1`

Other relevant parameters are: `TrustedCerts`, `TwoWaySSL`, `ClientCert`, `ClientPrivateKey`, `CAIssuedCertNamesMismatch`.

### Redshift

(See http://docs.aws.amazon.com/redshift/latest/mgmt/configure-odbc-options.html)

We don't have a Redshift connector yet, but it's interesting to look at it.

Same parameters as the PG driver, but here the default for SSLMode is `require` (just like we intend to do for our PG connector).
More information: http://docs.aws.amazon.com/redshift/latest/mgmt/connecting-ssl-support.html#connecting-ssl-support-odbc

# Conclusions

* For Hive and SQL Server we'd need some testing before adding any options for SSL connections. So I'd leave them as is at the moment.
* For MySQL we could have options equivalent to those of PostgreSQL, but this is not urgent since by default the MySQL should be able to use SSL if available. So I'd reconsider this after we gain experience with the new parameters for PG in production.

For PG, now I think we shouldn't expose all the values of `SSLMode` to the user:

* `allow` seems of little utility; use `prefer` instead.
* `verify-ca` and `verify-full` would need that we configure the CA certificates on our side, so I'd avoid avoid exposing them as long as we don't take care of that.

That would simplify use, documentations and ease having consistent SSL parameters for all our connectors.

**Comment by jgoizueta** [comment]
# Acceptance instructions

I suggest using a dedicated staging host here for the convenience of having a metadata db in localhost to copy data from. Since we need to connect to an "external" PostgreSQL dabase for the tests we'll use the metadata database. We'll make a connetor import without the new parameter and check that it uses de new default SSLmode of "require" and another with an explicit SSLmode parameter that should be accepted and applied properly.

1. Deploy the [11527-sslmode-pgconn](https://github.com/CartoDB/cartodb/tree/11527-sslmode-pgconn) branch in your dedicated staging server ded0N-st.
2. Create a user account on that host; activate the `carto-connectors` flag for it.
3. Check the user database has the odbc_fdw extension, and check that the host `app_confing.yml` has the postgres connector enabled.
   If the extension is missing you can either do `CREATE EXTENSION odbc_fdw;` in the user db or use this Jenkins task:
   http://deploy.int.cartodb.net/view/Dataservices%20API/job/Install%20odbc_fdw%20in%20staging/
4. Configure the dedicated PG logs to show all statements: set `log_min_duration_statement = 0` in `/etc/postgresql/9.5/main/postgresql.conf`
5. Execute connector import with default SSL mode. Execute this import which creates an `st_users` dataset with data from the local metadata db: (you'll need to be in the VPN)
```
   curl -v -H "Content-Type: application/json" \
-d '{"connector":{
        "provider":"postgres",
        "connection":{
        "server":"localhost",
        "username":"postgres",
        "database":"cartodb_staging"},
        "encoding":"iso88591",
        "sql_query":"select username from users",
        "table":"st_users"}}' \
"https://$USER.carto-staging.com/api/v1/imports/?api_key=$API_KEY"
```
6. Check the import succeeded: the user should now have a dataset `st_users` with the dedicated host user names.
7. Check that by the `require` SSL mode was used: look for a `IMPORT FOREIGN SCHEMA` in the ded0N-st SQL log that should look like this (notice the `"odbc_SSLmode" 'require'` option):

```
IMPORT FOREIGN SCHEMA "public" FROM SERVER postgresqlprovider_xxxxxxxx INTO "cdb_importer"
  OPTIONS ("odbc_SSLmode" 'require', "odbc_ByteaAsLongVarBinary" '1', "odbc_MaxVarcharSize" '256',
           "odbc_BoolsAsChar" '0', encoding 'iso88591', table 'users', schema 'public',
           prefix 'postgresqlprovider_xxxxxxxx_');
```
8. Now execute an import with explicit SSL mode (not using SSL)
```
   curl -v -H "Content-Type: application/json" \
-d '{"connector":{
        "provider":"postgres",
        "connection":{
        "server":"localhost",
        "username":"postgres",
        "database":"cartodb_staging",
        "sslmode":"disable"},
        "encoding":"iso88591",
        "sql_query":"select username from users",
        "table":"st_users2"}}' \
"https://$USER.carto-staging.com/api/v1/imports/?api_key=$API_KEY"
```
9. Check that `st_users2` has been imported
10. Check that the SLL mode was as requested: look for another `IMPORT FOREIGN SCHEMA` in the log with an `"odbc_SSLmode" 'disable'` optionn.

**Comment by ethervoid** [comment]
## Acceptance results

- [x] Imported using the PostgreSQL connector and SSLmode is  [require](https://www.postgresql.org/docs/9.5/static/libpq-ssl.html#LIBPQ-SSL-SSLMODE-STATEMENTS):

```
Feb 21 10:19:47 ded04-st postgres[7084]: [137-2] #011          IMPORT FOREIGN SCHEMA "public"
Feb 21 10:19:47 ded04-st postgres[7084]: [137-3] #011            FROM SERVER postgresqlprovider_4540fe80f81f11e682d504014675d001
Feb 21 10:19:47 ded04-st postgres[7084]: [137-4] #011            INTO "cdb_importer"
Feb 21 10:19:47 ded04-st postgres[7084]: [137-5] #011            OPTIONS ("odbc_SSLmode" 'require',
Feb 21 10:19:47 ded04-st postgres[7084]: [137-6] #011"odbc_ByteaAsLongVarBinary" '1',
Feb 21 10:19:47 ded04-st postgres[7084]: [137-7] #011"odbc_MaxVarcharSize" '256',
Feb 21 10:19:47 ded04-st postgres[7084]: [137-8] #011"odbc_BoolsAsChar" '0',
Feb 21 10:19:47 ded04-st postgres[7084]: [137-9] #011encoding 'iso88591',
Feb 21 10:19:47 ded04-st postgres[7084]: [137-10] #011sql_query 'select username from users',
Feb 21 10:19:47 ded04-st postgres[7084]: [137-11] #011table 'st_users',
Feb 21 10:19:47 ded04-st postgres[7084]: [137-12] #011schema 'public',
Feb 21 10:19:47 ded04-st postgres[7084]: [137-13] #011prefix 'postgresqlprovider_4540fe80f81f11e682d504014675d001_');
```

- [x] Imported with SSLmode to  [disable](https://www.postgresql.org/docs/9.5/static/libpq-ssl.html#LIBPQ-SSL-SSLMODE-STATEMENTS):

```
IMPORT FOREIGN SCHEMA "public"
Feb 21 11:10:24 ded04-st postgres[25701]: [61-3] #011            FROM SERVER postgresqlprovider_57858c8af82611e6a4b104014675d001
Feb 21 11:10:24 ded04-st postgres[25701]: [61-4] #011            INTO "cdb_importer"
Feb 21 11:10:24 ded04-st postgres[25701]: [61-5] #011            OPTIONS ("odbc_SSLmode" 'disable',
Feb 21 11:10:24 ded04-st postgres[25701]: [61-6] #011"odbc_ByteaAsLongVarBinary" '1',
Feb 21 11:10:24 ded04-st postgres[25701]: [61-7] #011"odbc_MaxVarcharSize" '256',
Feb 21 11:10:24 ded04-st postgres[25701]: [61-8] #011"odbc_BoolsAsChar" '0',
Feb 21 11:10:24 ded04-st postgres[25701]: [61-9] #011encoding 'iso88591',
Feb 21 11:10:24 ded04-st postgres[25701]: [61-10] #011sql_query 'select username from users',
Feb 21 11:10:24 ded04-st postgres[25701]: [61-11] #011table 'st_users2',
Feb 21 11:10:24 ded04-st postgres[25701]: [61-12] #011schema 'public',
Feb 21 11:10:24 ded04-st postgres[25701]: [61-13] #011prefix 'postgresqlprovider_57858c8af82611e6a4b104014675d001_');
```

- [x] Check the SSL mode is used to make the connection:

  - Make sure `ssl=true` in postgresql.conf
  - Add `hostnossl all all 0.0.0.0/0 reject` to your pg_hba.conf
  - If you try to import using the [disable](https://www.postgresql.org/docs/9.5/static/libpq-ssl.html#LIBPQ-SSL-SSLMODE-STATEMENTS) option you get:
    ```
    DEBUG:  00000: CONN STR: SSLmode=disable;ByteaAsLongVarBinary=1;MaxVarcharSize=256;BoolsAsChar=0;Server=localhost;Database=carto_db_development;Port=5432;DRIVER=PostgreSQL Unicode;UID=postgres
    LOCATION:  odbcConnStr, odbc_fdw.c:786
    DEBUG:  00000: Error result (-1): Connecting to driver
    ```
  - If you try to import using an unknown option, like `wadus`, you get:
    ```
    DEBUG:  00000: CONN STR: SSLmode=wadus;ByteaAsLongVarBinary=1;MaxVarcharSize=256;BoolsAsChar=0;Server=localhost;Database=carto_db_development;Port=5432;DRIVER=PostgreSQL Unicode;UID=postgres
    LOCATION:  odbcConnStr, odbc_fdw.c:786
    DEBUG:  00000: Error result (-1): Connecting to driver
    ```
  - If you try to import using the [allow](https://www.postgresql.org/docs/9.5/static/libpq-ssl.html#LIBPQ-SSL-SSLMODE-STATEMENTS) option, you get:
    ```
    DEBUG:  00000: CONN STR: SSLmode=allow;ByteaAsLongVarBinary=1;MaxVarcharSize=256;BoolsAsChar=0;Server=localhost;Database=carto_db_development;Port=5432;DRIVER=PostgreSQL Unicode;UID=postgres
    LOCATION:  odbcConnStr, odbc_fdw.c:786
    DEBUG:  00000: Successful result: Connecting to driver
    LOCATION:  check_return, odbc_fdw.c:691
    DEBUG:  00000: Successful result: Executing ODBC query
    ```

## Results

Looks good to me! 🇸🇿

**Comment by jgoizueta** [comment]
Thanks @ethervoid!! Great checking, glad you tested the actual usage of SSL.

Regarding the unknown options behaviour, we have a #11555 that will take care of that. Since that doesn't seem worrying I'll go ahead with deployment.

**Comment by jgoizueta** [comment]
Test corrections were missing :S They have been done in #11602

**Comment by jgoizueta** [comment]
This is now deployed and working in production, public docs updated [here](https://carto.com/docs/carto-engine/import-api/database-connectors#encoding-connection-parameters-1) and users being notified.
