### ISSUE TITLE
Geometry edition buttons misplaced in small breakpoint.

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#11542]
### Context
The buttons for geometry edition and dataset switching doesn't place right when in the smaller responsive breakpoint.

### Steps to Reproduce

Set the screen to 1024px width and play with different widget combinations. For example:

1. Add a time series widget and resize the screen to 1024x768

![image](https://cloud.githubusercontent.com/assets/1078228/22969395/b01b87b2-f36e-11e6-8ce0-939dd9a4226c.png)

1. Add a normal widget

![image](https://cloud.githubusercontent.com/assets/1078228/22969456/dfe6e504-f36e-11e6-8ea4-e56eee537896.png)

### Expected result

Buttons should be placed always in the same position relative to map dashboard. Look at the zoom buttons to check the proper result.

**Comment by rjimenezda** [comment]
I was about to write that this might be fixed already, but it's not. 

Every time we alter the height of the widgets we have to check this in acceptance, sometimes it's very very subtle. What I usually do is inspect the zoom controls container & see if it lines up. It's kind of a PITA, because we have to test all combinations of:

- No widgets
- Regular Widgets
- Time series
- Time series + Widgets

against all media queries. Fortunately this only affects builder, not embed as well.

The problem is we are positioning these icons absolutely, which is very brittle. We could use this issue to refactor the buttons to be positioned differently, but they might be like this for a reason, I haven't looked too much into it.

**Comment by xavijam** [comment]
Agree. We should make use of CartoDB.js and how to add new "elements" over the map. That would be a nice idea but it would require some work here and there.

**Comment by alonsogarciapablo** [comment]
We could do something similar to what Leaflet does with L.Control. [Here's an example](http://leafletjs.com/examples/extending/extending-3-controls.html).

**Comment by rubenmoya** [comment]
In production 🚀
