### ISSUE TITLE
The fill component gets closed when clicking in the icon modal window

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#11686]
Doing the acceptance [for this PR](https://github.com/CartoDB/cartodb/pull/11638) we found that if an user selects an icon from the asset modal window and clicks in the modal itself (that is, not on an icon or button but anywhere else), and then closes the modal window, the fill component gets closed.

### Steps to Reproduce

1. Open a map with some points.
2. Style the points with an icon using the modal window.
3. Click anywhere on the modal window.
4. Close it (by selecting an icon or pressing the esc key)

### Current Result

The fill component gets closed. 

### Expected result

The fill component should remain visible.

**Comment by xavijam** [comment]
Found on that PR, but happening at that moment in production. The reason is, when a component (any dropdown) is opened, we enable a listener over the document in order to close that component if the user clicks out. 
So the solution should be disable that listener when the modal is opened, and when it is closed or the icon is chosen, enable it again.

**Comment by xavijam** [comment]
Thanks @javierarce for the report 💋 .

**Comment by xavijam** [comment]
Deployed!
