### ISSUE TITLE
privacy_text_for_vizjson method fix

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11705]
Fix properly this quick one: #11704

- [x] `privacy_text_for_vizjson` shouldn't be called both on `::Table` and `Carto::UserTable`.  That might lead to a refactor at the presenter of at the caller. [How come sometimes `options[:table]` is used and other times `visualization.table` is?](https://github.com/CartoDB/cartodb/blob/5578d84a3a4038589ad598335771591103d6f83c/app/models/visualization/presenter.rb#L13). Try to reproduce it.
- [x] Test covering this.

**Comment by javitonino** [comment]
The issue is a difference in `related_tables` between visualization models:

Old model (returns table services):
```
      def related_tables
        @related_tables ||= layers(:data).flat_map { |layer| layer.user_tables.map(&:service) }.uniq(&:id)
      end
```

AR model (return table models):
```
  def get_related_tables
    return [] unless map

    map.data_layers.flat_map(&:user_tables).uniq
  end
```

This should only triggers when a canonical visualizations has multiple dataset associated to it (can happen with custom SQLs in visualizations from editor), but I haven't been unable to confirm with the Rollbar examples (one has deleted the table, and the other one seems fixed :/).

About the `option[:table]`, this presenter is only used from `::Table.public_values` and it is not being passed there, so it's never used (can be removed).
