### ISSUE TITLE
Presenter error with map without view bounds

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11711]
[Trace](https://rollbar.com/vizzuality/CartoDB/items/21876)

```
JSON::ParserError: 419: unexpected token at ', ]'
+ 2 non-project frames
3
File "/home/ubuntu/www/production.cartodb.com/releases/20170306113803/app/controllers/carto/api/vizjson3_presenter.rb", line 117 in bounds_from
4
File "/home/ubuntu/www/production.cartodb.com/releases/20170306113803/app/controllers/carto/api/vizjson3_presenter.rb", line 82 in calculate_vizjson
5
File "/home/ubuntu/www/production.cartodb.com/releases/20170306113803/app/controllers/carto/api/vizjson3_presenter.rb", line 62 in block in generate_vizjson
```

```
irb(main):004:0> "[#{map.view_bounds_sw}, #{map.view_bounds_ne}]"
=> "[, ]"
```

- [x] Check what might've happened to that map and if it's an isolated case.
- [x] Make the presenter nil-proof.

**Comment by javitonino** [comment]
Quick scan shows that most maps older than 2015 have this set to null. So this is probably an issue with migrations.

However:
- This is an old one: https://rollbar.com/vizzuality/CartoDB/items/20174/ It just changed Rollbar grouping with the refactor
- The presenter is protected against this, and returns null bound maps, but everything else works as expected (JS handles this cleanly)
- It's automatically fixed when changing touching the data part of the map in builder (adding layers, for example).

So I think there is nothing to do here. We could set some dummy bounds for old maps with a massive update, but I don't think that it's worth it since the current approach is working fine. I think we can close this with no action.

**Comment by juanignaciosl** [comment]
I dislike handling known scenarios through exceptions: it's not explicit for the reader, and other issues might go under the radar.

In this case, I'd consider returning `nil` if `view_bounds_sw` or `view_bounds_ne` are `nil`.

Anyway, minor. No need to multitask because of this, as it's correctly handled.

**Comment by javitonino** [comment]
Ok, let's put this in development and let's make the handling more explicit, so we don't have to investigate this again in the future.
