### ISSUE TITLE
Geometries cannot be edited from the dataset view

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#11855]
### Context

I was just doing some testing.
 
### Steps to Reproduce

1. Create a new map with an empty layer.
2. Click on the layer.
3. Draw any geometry.
4. Refresh (because of https://github.com/CartoDB/cartodb/issues/11857)
5. Click on the layer again.
6. Open the dataset view.
7. Double click on any of the editable cells for the geometry you just created (eg: name)
8. Type something and hit Enter.

### Current Result

This:

<img width="358" alt="screen shot 2017-03-27 at 17 05 41" src="https://cloud.githubusercontent.com/assets/390398/24363275/a989b8cc-130f-11e7-9cb4-5ac3963b2027.png">

Backend is returning the following error:

```
{"errors":["PG::Error: ERROR:  parse error - invalid geometry"]}
```

This is the payload that is being sent to the server:

```
{
  "cartodb_id": 1,
  "the_geom": "{\"type\":\"Point\",\"coordinates\":[4.921875,9.10209674]}",
  "the_geom_webmercator": "{\"type\":\"Point\",\"coordinates\":[547900.61874814,1017529.72067584]}",
  "name": null,
  "description": "b"
}
```

### Expected result

Geometry is updated and no error message appears.

**Comment by xavijam** [comment]
Could it be a backend issue @juanignaciosl @javitonino? Could you take a look whenver you can?

**Comment by alonsogarciapablo** [comment]
Just to clarify, the problem persists after page is reloaded.

**Comment by javitonino** [comment]
It seems the problem is that the frontend is sending the webmercator column, which is not sent from anywhere else (for example, `/dataset` or geometry edition). 

I think the easiest solution would be for the frontend to stop sending `the_geom_webmercator` in that view if we do not care about supporting edition of `the_geom_webmercator`. If not, we can take a deeper look, it seems it could be a problem with projections.

**Comment by xavijam** [comment]
Let me take a look tomorrow @javitonino :kiss:.

**Comment by xavijam** [comment]
Fixed!

**Comment by alonsogarciapablo** [comment]
👏👏👏
