### ISSUE TITLE
On hover infowindows not refreshing when adding for the first time

### ISSUE THREAD

**Issue by josecruz** [CartoDB/cartodb#11871]
### Context
The first time that you add a onhover pop-up it does not refresh on the map until you refresh the page.

The next infowindows that you create are autorefreshed, but happened sporadically that just shows the updated info when refreshing the page.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Create a map
2. Enter on the layer before adding any other onhover pop-up
3. Check and uncheck fields
4. Check if it refresh the info on the map

### Current Result
![bug2](https://cloud.githubusercontent.com/assets/596509/24403227/2cbdd190-13bc-11e7-9e74-0b67780246b3.gif)

### Expected result
Autorefresh the info without having to refresh the page

### Browser and version
Chrome 56.0

#### SMOKE_ MG44

**Comment by donflopez** [comment]
Good catch @josecruz!

This is not related with https://github.com/CartoDB/cartodb.js/issues/1603

**Comment by alonsogarciapablo** [comment]
I think the problem here is that the columns that @josecruz selected are actually empty and, there's indeed "No data available". I'll still display "No data available" after you refresh the page. If you edit the feature/geometry and enter some values for those columns (right now there's a bug and cells cannot be edited -> https://github.com/CartoDB/cartodb/issues/11855, but you can use SQL), you won't see this again. I'll close this and please @josecruz re-open it if what I just explained is wrong. Thanks!

**Comment by josecruz** [comment]
@alonsogarciapablo I'll upload the full workflow here, because it also happened me with filled tables:

![bug3](https://cloud.githubusercontent.com/assets/596509/24412516/f7869814-13d8-11e7-8d10-39ef8f3125df.gif)

**Comment by saleiva** [comment]
It also happened to me

**Comment by arianaescobar** [comment]
to me too
