### ISSUE TITLE
Switching between basemaps providers produces static maps without basemaps

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#11910]
### Context

When using the Image Export feature, we've seen that switching from a Google Maps basemap to another one from a different provider (Positron, for instance) produces images with just the geometries and no basemaps.

On a first analysis, it seems that is a problem with the map instantiation (it doesn't occur when switching the basemaps).

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Enable the `static-maps` feature flag.
2. Create a map with a Google Maps basemap.
3. Export an image.
4. Change the basemap (to Positron, for example)
5. Export an image again.

### Current Result
The first image is exported with the Google Maps basemap, but the second doesn't have any.

### Expected result

Both images should have basemaps.

### Browser and version
Any browser and version.

cc: @xavijam @alonsogarciapablo @rochoa @noguerol

**Comment by xavijam** [comment]
Taking a look right now.

**Comment by xavijam** [comment]
After some time of researching with @javierarce, we checked that the problem about export image is not the real issue. It is a problem related with how we manage the basemap change.

*You need to check [this piece of code](https://github.com/CartoDB/cartodb/blob/master/lib/assets/core/javascripts/cartodb3/deep-insights-integrations.js#L666-L722) in order to understand the bullets:

Those have been our steps:
- First thing we noticed is there are several instantiation requests when a basemap is changed: that is happening because we are doing several changes in the layers collection. Remove labels layer, or add the labels layer, for example (but there are more cases).
- Another important thing is, we force a silent change when basemap type has changed (from gmaps to a leaflet one, for example), but that doesn't work in the CARTO.js side because we are not taking it into account, and instantiation happens in any case ([CARTO.js code 1](https://github.com/CartoDB/cartodb.js/blob/v4/src/geo/map/layer-model-base.js#L20), [CARTO.js code 2](https://github.com/CartoDB/cartodb.js/blob/v4/src/geo/map.js#L145-L156)).
- Although we fix the previous bullet (^^^), there is another place in [CARTO.js](https://github.com/CartoDB/cartodb.js/blob/v4/src/vis/vis.js#L388) where visualization is listening for the layer-removed event, and the instantiation is also launched, because (and this is fun) we are using 'destroy' event and backbone understands that 'remove' is gonna happen.
- After "patched" both, we have checked that the instantiation is not happening anymore when basemap has changed in several situations, like changing from one provider to another. 

## Conclusions
In my honest opinion, this is NOT a problem with CARTO.js, it is a problem in general about how we decided to manage when a new basemap is selected (Builder and CARTO.js), because if you follow the code shared at the beginning, we can distinguish it is difficult to follow and understand.
And also, [this ticket](https://github.com/CartoDB/cartodb/issues/8906) is related 100%.

**Comment by xavijam** [comment]
Adding @javisantana and @noguerol in the loop.

**Comment by alonsogarciapablo** [comment]
Yes, we have some issues here:

1. Yes, the way BUILDER updates layers / provider in CartoDB.js is a bit (or very) HACKY. Basically, when a new basemap is selected, base and labels layers are added / updated / removed depending on the new basemap / new provider. It's hacky because we do things "silently" when the provider has changed (eg: Leaflet -> Google Maps) so that CartoDB.js doesn't notice until the provider is explicitly changed ([code is here](https://github.com/CartoDB/cartodb/blob/master/lib/assets/core/javascripts/cartodb3/deep-insights-integrations.js#L666-L722)). CartoDB.js didn't and still doesn't provide a mechanism to do things differently, and perhaps that's something we should improve.

2. This worked at the time, but we recently introduced some changes that are having some side effects. Basically, we changed things and now the "map" is also instantiated when Tiled layers are added / remove / update ( https://github.com/CartoDB/cartodb.js/pull/1598/commits/d7239887ef79825061dee0b7dfa3771a9c8244ea and https://github.com/CartoDB/cartodb.js/pull/1598/commits/3b832337dd561d917ac6bd4cf91bddcd06196477). As @xavijam and @javierarce discovered, this is triggering some extra requests to the Maps API, which users might not notice, but are not needed at all.

And, this is affecting the Image Export functionality as @javierarce and @xavijam described (good catch guys).

**Comment by alonsogarciapablo** [comment]
cc: @jorgesancha @rochoa

**Comment by xavijam** [comment]
Finally decided with @javisantana to fix it in an easy way due to it is a specific case (change from one provider to another only happens in Builder). We will spend time in https://github.com/CartoDB/cartodb/issues/8906 in the near future 🎱 .
