### ISSUE TITLE
Find Nearest analysis

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#11933]
Implement the new **_Find nearest_** analysis.

**User story:**
To be able to look for a limited number of closest points, organized by categories, to my points of origin, e.g. _"I have this table of competitors and I want to find the 5 stores of this brand that are closer to my stores"_

**Functionality:** 
Find N closest points, based on the linear distance, from a target point table per every point in a source table, with the possibility of finding N points for each of the categories in a selectable target's table column.

The resulting table will include the target geometries with their related _source_cdb_id_ so they could afterwards be joined with the source table. In the case of a categorized analysis, output geometries will be maybe duplicated but will have different _ids_.

**UI**

![image](https://cloud.githubusercontent.com/assets/70603/24750226/657a9fb6-1ac6-11e7-8ff8-d63e4acd48a1.png)

cc @rochoa

**Comment by AbelVM** [comment]
**Nearest Neighbors** may be a confusing name for this analysis, because it's usually used for Voronoi cells

On the other hand, we are not looking for "neighbors" (lookalikes or relatives) but features from other node (target) that are the closest to our source. Kurz und gut: hydrants are not neighbors of houses, but this is the natural analysis you would apply them

 cc @noguerol

**Comment by saleiva** [comment]
I propose we use "Find nearest" as it is how it's called in some other tools

**Comment by ivanmalagon** [comment]
What category does 'find nearest' belong to?

![image](https://cloud.githubusercontent.com/assets/1078228/24964416/83c70d9e-1fa1-11e7-9200-6ba1b934c5ed.png)

**Comment by noguerol** [comment]
Analyze and predict

**Comment by saleiva** [comment]
- [ ] I've found an issue (it might be our problem). It's that the UI was wrong in the mockup (attaching the correct one – I hope it doesn't become very difficult).
![analysis - nearest neighbours 01](https://cloud.githubusercontent.com/assets/132149/25182112/ea1e1278-2513-11e7-98dd-430c17a08c69.png)

- [ ] We should review the policy about duplicated data generated by this analysis ( @rochoa , @AbelVM, @javisantana, @noguerol). Since it's very easy to end up with tons of duplicated points (one each time a point is nearest to more than one feature in the source layer), and that would require post-processing the data for analysis. – I still need to think in a solution

Nothing else found so far! Implementation working like a charm!

**Comment by ivanmalagon** [comment]
The first issue is fixed. You can test it in ded01.

**Comment by noguerol** [comment]
While we figure out (2) we can tweak the the subtitles for those new two sections in (1):

"Define your criteria" --> "Select the target point layer"
"Define and limit your result" --> "Define and categorize the number of results"

Plus there is a tweak to do that we discussed in the past (and was unfortunately not reflected on the design) that now with two blocks makes even more sense: to put the "categorized" dropdown *below* the "max results" slider -'cause is optional- and change its literal from "categorized" to "per category" -because it may be confusing wether those max results are to all categories or per category.

**Comment by xavijam** [comment]
Hey mates, could we add the things we should change in the PR please? 💋

**Comment by saleiva** [comment]
I've found something. It looks like there is a column called ranking and another one called source_rank. What is the different between those? @rochoa @AbelVM

**Comment by AbelVM** [comment]
You're right:
* Ranking: it's always there. (not needed as output, actually)
* Closest_rank: if the user asks for N>1 results (globally or per category), then this is the ranking of each result (within the category if any)

**Comment by saleiva** [comment]
so, should we remove that column from the output then?

**Comment by jorgesancha** [comment]
maybe it can be solved as part of what's left to do in https://github.com/CartoDB/camshaft/pull/281 ? cc @rochoa

**Comment by rochoa** [comment]
https://github.com/CartoDB/camshaft/pull/281 is finished and deployed to production.

**Comment by xavijam** [comment]
_máquina!_ ^^^

**Comment by saleiva** [comment]
@noguerol @xavijam rememeber we need to instrumentate this UI properly!

**Comment by xavijam** [comment]
So blocked until https://github.com/CartoDB/cartodb/issues/12040 is implemented in the current PR.

**Comment by xavijam** [comment]
Not blocked anymore since we have decided to go on with the PR and then add the needed track classes.

**Comment by xavijam** [comment]
Deployed
