### ISSUE TITLE
Multiple administrators PoC

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#11945]
[Feature doc](https://docs.google.com/document/d/1e9mtqIFaxmkL-S0UCJGpzZc8eUKbSmmUqtWsHgy2PCY/edit#heading=h.a3a7noahiqbt).

As feature doc is still evolving, please check the document for the information.

This issue is only the implementation of a PoC that might not be even merged into master. We need to know an estimation about the full feature, and this might get tricky because of PG role management

**Comment by javitonino** [comment]
Summary of findings:
- There is some JS redirection from /organization to /profile if the user is not the org owner (by some definition that does not match backend's).
- From the UI, eveything works ok permission-wise without changes. All group management queries are run with org owner permissions (instead of current user)
- Groups API needs some permissions, but the extension is prepared to give/revoke them with `CDB_Organization_AddAdmin`.

The changes I made:
- Hack `User.organization_owner?` to return true for a specific user
- Hack `lib/assets/javascripts/cartodb/models/user.js` -> `isOrgAdmin` in a similar way
- Run `SELECT CDB_Organization_AddAdmin('username')` (only needed for direct usage of groups API)

**Comment by javitonino** [comment]
So I think I've seen enough for an estimation. Changes needed:
- Migration to add new column to users
- Superadmin migration, API, sync code
- A systematic change of organization owner checks for organization admin checks. There are a lot of these and not all of them do the check in the same way (most use `User.organization_owner?` but others inline that method or o something similar).
- Same for frontend + minimal UI changes.
- Calling an SQL function when switching the `admin` flag of a user, to allow direct use of the groups API

Overall, I did not hit any major roadblocks and it seems the tricky part (DB) is already prepared for multiple admins. So, not too bad.

The code from this PoC goes to the 🔥 (too hacky).
