### ISSUE TITLE
Make changes in the assets build process

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#11962]
#What does it mean? Basically improve the way we prepare the assets for development or production. 
The main purposes are:

- Improve development speed: watch, bundle, initialization,...
- Improve deployment speed: don't uglify already minified vendor files, for example, don't run unnecessary development tasks here, etc.

It has a lot of implications, but the main tasks should be:

## Main tasks
- [x] Migrate from Browserify to **Webpack**: already done in the test part thanks to @ivanmalagon.
- [x] Taking into account the previous bullet, we should not migrate the old code (editor) to this new "workflow". That means only, for the moment, **builder**, **dataset** and **public** embed views will be "migrated".
- [x] Start using **lib-sass** for compiling the CSS instead of **~compass~** for the whole project. We should leave this last one only for the old assets.
- [x] We should check if new tests task needs to be revisited after those new changes.

## Caveats
- [x] We need to keep using the **core <> client** behaviour for assets touched "outside" of our usual workflow (mainly for solutions engineers).
- [ ] ~Vendor files (like tangram) don't need to be uglified, we should avoid this in order to gain time in the deploys~ _Decided to leave it as it is for now (follow thread)_.
- [x] When a new file is added, it should be taken by the watch process.

## Improvements
- [x] Research how to improve javascript source-map support for staging and production.

## Issues:
- [x] Some modals are not properly rendered.
- [x] CSS sourcemaps are not working.
- [x] Revamp cartodb.js and deep-insights to include cartoassets in bundle time. Right now we have this dependency twice in those styles -> https://github.com/CartoDB/cartodb/pull/12203.
- [x] As a continuation from above, use partials `_whatever` to include code not compilable directly -> https://github.com/CartoDB/cartodb/pull/12203.

## Nice to have
- [ ] Hot module replacement
- [ ] Smart build: only build touched code. If the edited/new code belongs to Builder, only build the Builder. If the code belongs to Editor, only build the Editor. If there is code for both sides, build Builder and Editor.

@CartoDB/frontend

**Comment by matallo** [comment]
considering editor js code won't be migrated, does this imply we can split now the bundling tasks for them? i.e.: now to start developing you need to do `grunt && grunt dev` which will create the sprites from css, ...

could we have something similar *just* for builder? in any case, the build task would take editor into account when releasing new versions

**Comment by xavijam** [comment]
IMO:

- For editor we should use `grunt editor dev`.
- For builder we should use: `grunt builder dev`.

**Comment by xavijam** [comment]
open for discussion ^^^ @CartoDB/frontend

**Comment by nobuti** [comment]
About the vendor's minification, why we should avoid it? do we know which of them we should avoid to pass through uglify? I know one of them is tangram, but @donflopez is it posible to load it uncompressed?

**Comment by nobuti** [comment]
I'm passing all through uglify and I can see any error, not sure whether it's a mangle issue related, but it seems to work.

**Comment by xavijam** [comment]
Well, there was no error before, the problem is we are "uglifiying" something already uber-minified and uglified.

**Comment by nobuti** [comment]
Then we need to compare the cost of excluding those modules from the chunking process and after the uglify task, merge them with the common build vs re uglify them.

**Comment by nobuti** [comment]
In a second thought, we probably lose the sourcemap for those modules or worst, with a broken sourcemap after the merge.

**Comment by matallo** [comment]
> In a second thought, we probably lose the sourcemap for those modules or worst, we end up with a broken sourcemap, after the merge.

totally, if we prefer to have the sourcemaps we'd better have it uncompressed, then uglify it ourselves

that would be the case with cartodb.js and deep-insights, eventually

**Comment by matallo** [comment]
as discussed, I'm removing `cartodb3-specs` from browserify, to rely only in `webpack` tests and going on with the plan to split js and css for editor/builder (this is going to hurt)

**Comment by nobuti** [comment]
I've found some issues:
- [ ] Some modals are not properly rendered.
- [ ] CSS sourcemaps are not working.
- [ ] The dashboard is not built anymore using the `builder`. We knew that, but we need to discuss the need to generate the files initially but not to watch them later.

**Comment by ivanmalagon** [comment]
**ES6**

I've tried to include Babel to transpile ES6 and check the impact in the build process. So far, no success.

The main problem is that we already have a shim loader for `.js` files. This is because of `cartodb.js`. Since it doesn't provide a single library yet for v4 we need to bundle it with Webpack. For it to work we need to provide a shim for several `cartodb.js` dependencies.

Webpack allows to have several loaders for a type of file but `include` and `exclude` options are common for all the loaders from a same test. In our case:
- We need `shim-loader` to run only including `node_modules/cartodb.js` for performance reasons.
- We need `Babel` to run everywhere excluding `node_modules`.

As you can see, these two conditions are exclusive.

My second approach has been to mark a file with another extension `.es6.js`. This allows us to set another `test` section.

```
        {
          test: /\.es6.js$/,
          exclude: /node_modules/,
          loader: 'babel-loader'
        },
```

I think this could be a good approach to tackle a transition to es6. It'd allow us to set different workflows or tools for each type of file.

It transpiles correctly the code but we need to be superdupercareful with Backbone and arrow functions. To check that the code gets transpiled I've used arrow function in a Backbone model and in `editor.js` in 'normal' code.
- Within the Backbone model the context is lost. Further research is needed here but arrow functions are likely not to work with Backbone models (without another refactors).
- Within normal code, it works ok.

**Comment by nobuti** [comment]
Any benchmark?

**Comment by ivanmalagon** [comment]
No sensible benchmark since I only used 2 es6 files [1]. With this amount it didn't introduce any noticeable lag. It was as immediate as before.

[1] Since I entered a regex for only `.es6.js` files, only two were in the transpiling process.

**Comment by ivanmalagon** [comment]
**Modals**

- Tabs: tabs don't show up correctly.
- Basemaps: also appears at the bottom.
    - Nasa: the calendar doesn't present proper styling.

I think we can affirm that no modal relying in `Dialog` class works properly.

**Comment by ivanmalagon** [comment]
+1 on Buti's suggestion of generating all files initially but not watching them.

It's a PITA to develop only in `dev:builder` relying in saving the map URLs. Since the maps cards are built by JS we don't have any mean to navigate in our maps. It's not only a matter of styling.

**Comment by ivanmalagon** [comment]
Another suggestion regarding grunt.

Trying to follow the last changes in `gruntfile` (and doing the same thing while developing the affected specs ticket) is quite hard. In today's file version there 35 tasks. Most of them are internal tasks, only expected to be called from within another, ore important tasks. But they clutter the file, anyway and it's very hard to understand the file.

I haven't thought on any particular solution to this but if we need to maintain grunt we should think on a way to ease its understanding. Now you have to study the file in order to make any change.

First, it should be clear what are the tasks that are meant to be called from CLI. This can be a starting point. Including only these one in the main file and then requiring the subones. Or perhaps
 having a task to show the ones to call (there's a `availabletasks.js` file that returns an empty object).

On top of that, we should include comments above every task to express what to want to achieve with that task. For instance:
```
Invalidate:
invalidates fastly CDN.
Secondary task
Target: only production

config
generates assets config for current configuration
Secondary task
Target: staging, production
```

I know there's already a description of the task in `registerTask`but you get the idea. Documenting not only what the task does, but also if it's a main or secondary task, targets, sub-configurations... to get a better idea.

My 2 cents.

Any thoughts?

**Comment by xavijam** [comment]
Agree with you @ivanmalagon, we could document them better. Let me add it like a new point to do. Also, I'm going to add all the pending things @nobuti metioned some comments above 💋 .

**Comment by matallo** [comment]
btw, I'm updating this with last changes in https://github.com/CartoDB/cartodb/pull/12203

**Comment by xavijam** [comment]
And sorry, I feel this is not the moment to start using ES6, we could try to move there in a second iteration, sounnds good?

**Comment by xavijam** [comment]
> btw, I'm updating this with last changes in #12203
Nice

**Comment by xavijam** [comment]
In order to fix the problem with the legacy CSS, we have created a new ticket -> https://github.com/CartoDB/cartodb/issues/12256.

**Comment by xavijam** [comment]
Hey @nobuti, why do you want CSS sourcemaps? I haven't found the need to use them, but it is likely you missed them.

**Comment by nobuti** [comment]
Well, for the same reason we want js sourcemaps I guess, at least in development. But I can live with them for sure if it's a pita.

**Comment by xavijam** [comment]
I don't have the need to "look for" any CSS clue in staging or development, but in any case, it is ok, @matallo has achieved it although there are some caveats...

**Comment by matallo** [comment]
I'm updating the PR with the discussion but I wouldn't spend much more time on it.

**Comment by xavijam** [comment]
\o/
