### ISSUE TITLE
Deprecated SQL Function analysis UI

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#12018]
To support https://github.com/CartoDB/camshaft/pull/280 at builder level, we need to pull a new UI for it.

cc @xavijam

**Comment by rochoa** [comment]
Our initial proposal would be something like:

![screen shot 2017-04-18 at 18 36 24](https://cloud.githubusercontent.com/assets/45346/25142245/8b253434-2466-11e7-996d-285798f4d0e6.png)

**Comment by saleiva** [comment]
Like this :dab:

![analysis - deprecated sql node](https://cloud.githubusercontent.com/assets/132149/25142387/fbe3f6ec-2466-11e7-9086-221a49fff1f6.png)

I don't think we need more designs since this will be automatically generated.

**Comment by saleiva** [comment]
cc/ @noguerol @xavijam

**Comment by xavijam** [comment]
Let's not forget the onboarding text and the animation.

**Comment by saleiva** [comment]
Not sure we can have an onboarding text since it will depend on the function... About the animation. Ok, we can prepare something quick

**Comment by noguerol** [comment]
Update: we have just decided we will have no animation nor onboarding.

**Comment by xavijam** [comment]
Before doing this task, [this ticket](https://github.com/CartoDB/cartodb/issues/12025) is absolutely necessary.

**Comment by xavijam** [comment]
Basically this analysis will let the user use a function "created" in the DB with parameters. The use case is how @saleiva and @rochoa have explained it.

- We need to make a query in order to take all the available functions under the user (query will be done by @rochoa 💋 ).
- That query will give us three things:
   - the name of the function.
   - the name of the arguments accepted.
   - the type of the arguments accepted.
- With that, the second part of the form will be created, giving the user the possibility to fill up all those arguments and launch the analysis.

That's all!

**Comment by xavijam** [comment]
Yep, looks like it is ok! One question, the order of the `params_name` is the one the analysis API is waiting to receive?

**Comment by rochoa** [comment]
Yes.

**Comment by ivanmalagon** [comment]
Even not having animation nor onboarding I think we need some graphic to show in the analyses view.

![image](https://cloud.githubusercontent.com/assets/1078228/25333736/c101cac0-28eb-11e7-9d49-cad645b38a5a.png)

If not, it feels unfinished. Perhaps only a graphic like `y = f(x)` in the same colors as the rest (but no animation).

What do you think @saleiva @noguerol ?

**Comment by xavijam** [comment]
My opinion: add an image saying "[SQL]" or "[Function]".

**Comment by saleiva** [comment]
+1 to that. @CartoDB/design any quick idea?

**Comment by urbanphes** [comment]
Maybe we can make it as a typewriter. As if the text is written.

**Comment by ivanmalagon** [comment]
Hi.

While developing this ticket I run a lot of times into problems while sending the analysis parameters. As they're dynamic we can't force validators. We don't get the custom validation for every field. So it's quite easy to send a badly formed analysis if you don't know the nature of the analysis.

These analyses errors were swallowed. I've modified the visualizations error notification to show the actual error message. Until now, It showed a generic body `Please refresh the page and contact us if the error persists`. Now, the error gets appended.

![image](https://cloud.githubusercontent.com/assets/1078228/25487534/cd55b2d4-2b64-11e7-94b7-b2aa6646932f.png)

I don't know if there were a reason to not show the actual error but the generic message. Showing the actual error has helped me a lot to get this issue up'n'running since I didn't have any idea about the SQL function behind.

If you know about any reason not to show the message, please tell me.

**Comment by xavijam** [comment]
cc @alonsogarciapablo

**Comment by alonsogarciapablo** [comment]
> These analyses errors were swallowed

Maybe these errors could be properly categorised by Maps API? This way they'll be properly displayed in the UI (as errors on the particular analysis node).

**Comment by ivanmalagon** [comment]
I've made the changes for that error visualization at [this PR](https://github.com/CartoDB/cartodb.js/pull/1631)

**Comment by xavijam** [comment]
PR: https://github.com/CartoDB/cartodb/pull/12036

**Comment by xavijam** [comment]
DEEEEEPLOYED!
