### ISSUE TITLE
Color picker in cartocss editor is not working properly

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#12097]
### Context

The color picker in the cartocss editor is not working properly. When you click on a hex value, it opens but disappears instantaneously. It's possible to keep it open if you click and drag somehow but then when you select a new color, that new color is not applied to the code. 

### Steps to Reproduce

1. Go to the CartoCSS editor
2. Click on any hex value

### Current Result

![rfgegre](https://cloud.githubusercontent.com/assets/16247628/25751630/027acc9a-31b6-11e7-88fe-baaf4481f1eb.gif)

### Expected result

- Color picker should remain open when you click on the hex value 
- When you select a new color, that color should be applied on the CartoCSS

### Browser and version
Chrome Version 57.0.2987.133 (64-bit)

**Comment by ivanmalagon** [comment]
One thing to remark here. (and a note for my future self).

This was working depending on how you click on trackpad. In order to reproduce this bug you have to click all the way down. If you are used to click with a smooth touch, this was working perfectly.

The way that the events are triggered are different in each case so take this into account when handling mouse events.

**Comment by ivanmalagon** [comment]
Shipped! :shipit:
