### ISSUE TITLE
Improve copy of "Export map" and "Export as image"

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#12114]
There's a lot of confusion in our users from the similarity between both names and actions. We propose the following changes to avoid this confusion: 

Change **Export map** to **Download map**
Change **Export as Image** to **Export image**

**Comment by saleiva** [comment]
Prioritize this since it looks like a perfect task for onboardings! – and it's related to the jus released export image feature cc/ @noguerol

**Comment by xavijam** [comment]
:+1:

**Comment by xavijam** [comment]
Leaving for new hires then 👯‍♂️

**Comment by rjimenezda** [comment]
What about ellipsis? Should we keep them? It's 'Export as image...' right now

**Comment by xavijam** [comment]
That's a good one, what do you think @arianaescobar ?

**Comment by rjimenezda** [comment]
There's also 'Delete map...' & 'Edit metadata...'

**Comment by saleiva** [comment]
Ellipsis should be there if an extra step is coming after clicking on the link.

**Comment by arianaescobar** [comment]
Then it is: 

Change **Export map** to **Download map**
Change **Export as Image** to **Export image...**

:)

**Comment by rjimenezda** [comment]
There's an extra step for downloading as well, although it's just clicking on a button to confirm you want to download it 🤔

**Comment by noguerol** [comment]
True, we need to change this modal also: 

![image](https://cloud.githubusercontent.com/assets/70603/26237837/0bca038a-3c77-11e7-84d7-3bf630cfc4cb.png)

With `Download` and `Downloaded` in the title, explanation and button.

**Comment by xavijam** [comment]
> Ellipsis should be there if an extra step is coming after clicking on the link.
 
Interesting to know.

**Comment by nobuti** [comment]
up and running.

**Comment by arianaescobar** [comment]
Thank you guys!

**Comment by csobier** [comment]
Just found out about this change through a user that reported it to Support. Can you give me a heads up next time while it's still under the feature flag? A little change like this requires a significant amount of content changes (multiple guides, images, SEO titles, etc.), since this is one of the more popular features.

Also, the related piece on the public profile page still shows the "Export map" text and button name. You might want to change it to be consistent. Just let me know so that I can doc accordingly.

![image](https://cloud.githubusercontent.com/assets/13319925/26683290/4eceb52e-46b1-11e7-8fba-36f970fa66fc.png)

**Comment by arianaescobar** [comment]
Sorry @csobier :( you're completely right and we totally forgot to ping you on this. Our bad :( 

Also, yeah, 100% agree on having to change it as well on the public profile, but that's @xavijam call I guess! :)
