### ISSUE TITLE
`NaN`s and `infinity`s are displaying as null

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartodb#12154]
### Context

`NaN`s and &pm;`Infinity`s ([possible float values in PostgreSQL](https://www.postgresql.org/docs/9.5/static/datatype-numeric.html#DATATYPE-FLOAT)) are displayed as null values, leading to problems with summaries (e.g., max(column) will strangely say `null` is the largest value of a dataset). Even further, they cause the widgets to break.

### Steps to Reproduce
1. Import a dataset (which is a CSV but GitHub won't let me do CSVs) with `NaN`s and `Infinity`s: [inf-nan-values.txt](https://github.com/CartoDB/cartodb/files/1010832/inf-nan-values.txt)
2. Change the column type of column `val` to 'number' in the Builder
3. Observe that the `val` column has values `1.2`, `null`, and `null`.
4. Run this query to see if those values are actually null-valued:
    `SELECT val is null FROM inf_nan_values`
5. Observe that the results are all `false`, indicating that the values are not null valued.
6. Casting `val` to text produces `infinity` and `NaN`.
7. Calculate the max of the dataset produces `null`, but casting to text gives `NaN` again.
8. Create a widget on the column `val` and observe that the widget does not work.
<img width="301" alt="screen shot 2017-05-18 at 08 30 32" src="https://cloud.githubusercontent.com/assets/1041056/26202141/48e4fe74-3ba4-11e7-9507-0d062a912107.png">

### Current Result

`Infinity` and `NaN` are shown as `Null` when they are actually not and produces different information when used in calculations. These values break the widgets.

### Expected result

The values of `infinity` and `NaN` are displayed in the builder what they really are to avoid confusion. These values should also not break the widgets, but the user should be able to remove these values easily so that the widgets can work as expected. For example, a broken widget could say 'Cannot make widget because `column` has values of Infinity'.

### Browser and version
Chrome 58.0.3029.110 (64-bit), macOS 10.12.4

### .carto file

None, but this 'csv': [inf-nan-values.txt](https://github.com/CartoDB/cartodb/files/1010832/inf-nan-values.txt)

### Additional info

Information can be displayed to communicate that there are NaNs and Infinitys in the dataset, and that they are removed when constructing the widgets. NumPy has very good behavior for dealing with these two values.

**Comment by xavijam** [comment]
Well @andy-esch, that's the result SQL provides to the UI. I feel that issue doesn't belong to this repository. In fact, [this is the SQL](https://xavijam.carto.com/api/v2/sql?rows_per_page=40&sort_order=asc&page=0&order_by=cartodb_id&q=select+%22cartodb_id%22%2CCASE+WHEN+GeometryType(the_geom)+%3D+%27POINT%27+THEN+ST_AsGeoJSON(the_geom%2C8)+WHEN+(the_geom+IS+NULL)+THEN+NULL+ELSE+GeometryType(the_geom)+END+the_geom%2C%22latitude%22%2C%22longitude%22%2C%22val%22+from+(SELECT+*+FROM+xavijam.inf_nan_values)+__wrapped), and this is the result:

```json
{
rows: [
{
cartodb_id: 1,
the_geom: "{"type":"Point","coordinates":[-3.7038,40.4168]}",
latitude: 40.4168,
longitude: -3.7038,
val: 1.2
},
{
cartodb_id: 2,
the_geom: "{"type":"Point","coordinates":[-3.7048,40.4178]}",
latitude: 40.4178,
longitude: -3.7048,
val: null
},
{
cartodb_id: 3,
the_geom: "{"type":"Point","coordinates":[-3.7058,40.4188]}",
latitude: 40.4188,
longitude: -3.7058,
val: null
}
],
time: 0.002,
fields: {
cartodb_id: {
type: "number"
},
the_geom: {
type: "string"
},
latitude: {
type: "number"
},
longitude: {
type: "number"
},
val: {
type: "number"
}
},
total_rows: 3
}
```

**Comment by andy-esch** [comment]
Thanks @xavijam, do you recommend SQL API repo then?

**Comment by xavijam** [comment]
I'm not sure, but looks like, @rafatower could you help us here?

**Comment by andy-esch** [comment]
@rafatower, want me to open separate tickets about this elsewhere?

**Comment by rafatower** [comment]
@andy-esch there are several places that could be the source of this issue and at the moment I don't really know where the ticket for the fix should belong. So no need for you to open separate tickets until we further investigate the issue.

How often do you reckon this issue is happening to our users?

**Comment by dgaubert** [comment]
Actually I see two different issues here:
  1) Queries to API SQL should not cast `Infinity`  and `NaN` values to `null` (SQL-API)
  2) Widgets should support `Infinity` and `NaN` values or, at least, does not break (Windshaft-cartodb)

**Comment by andy-esch** [comment]
Sorry for the slow response @rafatower, I was going to leapfrog to see how many of my tables had `NaN` and `Infinity` values, but haven't gotten around to it yet. I actually don't have a good sense of this, but I wouldn't be surprised if these values cause unexpected behavior that's not easy to debug in the widgets.

I think I was seeing this clearly because in cartoframes, pandas DataFrames are exported to CSVs and then sent to CARTO via the Import API, and the `numpy.nan` were changed to `nan` in the CSV in numeric columns.

I also agree on both points that @dgaubert makes. On `Infinity` in the widgets, we maybe should have a warning to filter them out if they exist and flag that in the filter that there are `n` Infinities. Otherwise, the scales/y-axis we use won't work.

**Comment by dgaubert** [comment]
PR in CartoDB-SQL-API: https://github.com/CartoDB/CartoDB-SQL-API/pull/420

**Comment by dgaubert** [comment]
PR in Windshaft-cartodb: https://github.com/CartoDB/Windshaft-cartodb/pull/700

**Comment by jgoizueta** [comment]
Acceptance plan:

* Install the branches of SQL-API & Windshaft Cartodb in a staging dedicated server
* Prepare two datasets containing Infinities & Nans, one of them with overviews
* Create a map with Builder and try all widget types on both tables; check widgets run without errors and results are correct (infinities ignored for min/max ranges, etc.)

**Comment by dgaubert** [comment]
Hey @jgoizueta! This acceptance is kind of tedious, any help you need.. you know! ;)

**Comment by jgoizueta** [comment]
Preliminary Acceptance Results (to be completed next monday)

@dgaubert has kindly join me checking this and what seemed to be just a routine and tedious test became a bug-hunting session through multiple CARTO components 😅 

Regarding the changes done here in the sql-api & windshaft-cartodb PRs we found a couple of issues that are already solved:

* Initially count behaviour was different without overviews (NaNs, Infinites where excluded), but dani has promptly changed tha, now the behaviour with or without overviews is including all records (Nulls, NANs, Inifinities) in the count.
* The dataview specializations for overview failed to forward the new `queries` parameter to the base class (generic dataviews) (and formula wasn't using it)

But we also found some problems affecting other components. We'll open tickets in the corresponding repos for them:

* Pop ups show NaNs and Infinities as `null` (because of having been converted to JSON).
* Overview tables are created averaging numerical columns for all the rows (including NaNs, Infinities), so in columns with NaN values the lower level overviews quickly became full of NaNs.
* That problem compounds with a bug in the UI: when a histogram is empty (0 bins), this error occurs: `histogram-data-model.js:80 Uncaught TypeError: Cannot read property 'start' of undefined`. (for tables with NaNs lower-level overview tables are full of NaNs, yielding empty historgrams and triggering this problem)
* When a formula widget is added to the map, the fourmula is `avg` initially, but it is show as COUNT in the UI. (STR: create a map, add a widget, leave default parameters; if you edit it, it shows COUNT, but the values displayed are averages).

**Comment by dgaubert** [comment]
Hey @jgoizueta 

Please, let me know when this PR is ready to deploy. 

💌

**Comment by jgoizueta** [comment]
I'm moving this to deploy, since the acceptance tests are successful regarding the fixes done here to SQL-API and WIndshaft-Cartodb and having this in production is a big improvement over the current situation (where widgets break in the presence of NaNs, etc).

The issues revealed during acceptace affecting various CARTO components can be handled independently in separate tickets.
