### ISSUE TITLE
Max layer limit error

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#12161]
### Context
Already known, but now based on https://github.com/CartoDB/support/issues/701, we need to change the copy of the max layer error. 

_From the support ticket:_ 

When trying to import a layer past the account's limit (8 for FREE and PERSONAL, 10 for ENTERPRISE), the user gets the following error: `Could not add layer. Reload the page again. If the problem persists contact us at support@carto.com`

![image](https://cloud.githubusercontent.com/assets/70603/26240327/e40347b2-3c80-11e7-9ccb-be8883da0e8e.png)

Obviously, refreshing the page doesn't help and the problem persists. An error code like the following one would be a lot more helpful:

`Woops! It seems you've reached the maximum number of layers for this map. Consider merging layers or deleting unnecessary ones`

**Comment by rjimenezda** [comment]
@noguerol Even though that's the only error that can happen using the UI, It's tricky to differentiate between all possible errors and pick the appropriate copy. The response is essentially a human readable error text.

What I can do is always display that copy when something (anything) wrong happens when adding a new layer, but if in the future a new error case is added, we'll face the same problem.

Alternatively, we could just disable the button when an user has reached its maximum number of layers.

Alter-alternatively, we could fix our error responses, but that's opening another whole can of worms 😄

**Comment by noguerol** [comment]
So there's no way to differentiate the max amount of layers error from other future ones but we can disable the button if the limit has been reached, right?

While disabling the button is smart and neat, it would not solve the problem because layers could also be created by dragging one node outside its parent. We can maybe also disable that behavior? Even in that case it would be tricky because we could not provide any UI feedback.

**Comment by saleiva** [comment]
hey, wait, we designed a solution for this. -> https://github.com/CartoDB/design/issues/634 :D

**Comment by xavijam** [comment]
Hey guys, this is great because that dialog is "old" and we have planned to change it (right @saleiva). So better to change it in the builder UI than in the dialog. If you don't mind, closing this one and adding the other in the project 💋 .

**Comment by xavijam** [comment]
https://github.com/CartoDB/cartodb/issues/12167
