### ISSUE TITLE
Map center and zoom are different in viz.json and state

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#12163]
I noticed that, as I pan / zoom the map, the state is updated with the right `zoom` and `center`, but these attributes are updated in the `Maps` table (and are not updated in the viz.json).

You can easily see this in the embed:

![image](https://cloud.githubusercontent.com/assets/390398/26243202/561f0cbe-3c8b-11e7-94e7-d05808ae3487.png)

Also, checking the DB:

```
irb(main):030:0> v = Carto::Visualization.find('053a69e6-0f0f-11e7-b310-080027a55d4d')
  Carto::Visualization Load (0.6ms)  SELECT "visualizations".* FROM "visualizations" WHERE "visualizations"."id" = '053a69e6-0f0f-11e7-b310-080027a55d4d' LIMIT 1
=> #<Carto::Visualization id: "053a69e6-0f0f-11e7-b310-080027a55d4d", name: "Untitled Map 2", description: nil, type: "derived", tags: nil, privacy: "public", created_at: "2017-03-22 14:51:24", updated_at: "2017-03-22 14:53:16", encrypted_password: nil, password_salt: nil, map_id: "2cb7ba13-42d2-4926-854c-a09288a6f97c", active_layer_id: nil, user_id: "3e573cb0-4499-47f9-b786-b3de19f7f4a7", permission_id: "e4bfa941-632f-4d62-89c5-49d34344a7ac", source: nil, locked: false, license: nil, title: nil, kind: "geom", parent_id: nil, prev_id: nil, next_id: nil, slide_transition_options: "{\"time\":0}", active_child: nil, attributions: nil, bbox: nil, display_name: nil, auth_token: nil, version: 3>
irb(main):031:0> v.map.zoom
  Carto::Map Load (0.5ms)  SELECT "maps".* FROM "maps" WHERE "maps"."id" = '2cb7ba13-42d2-4926-854c-a09288a6f97c' LIMIT 1
=> 1
irb(main):032:0> v.map.center
=> "[0.0,0.0]"
```

☝️ map has the default zoom and center.

cc: @javitonino @juanignaciosl @xavijam

**Comment by javitonino** [comment]
Wanted to open a little discussion. Three options:
1. Fix the bug: read `map` and `zoom` from the `states`.
2. Remove `map` and `zoom` from the vizjson altogether
3. Remove `map` and `zoom` from the vizjson, add `state` instead

The point with 2 and 3, is to make more obvious the separation between content and presentation. Meaning that we would have vizjson as the description of the map, and a separate state.json in order to indicate the initial viewport + widgets state.

If we want the vizjson to be useful on its own, we should go for 3 rather than 1. This is because otherwise, other state information (such as the default widget selection) won't be displayed in vizjson maps. In other words, if we want the vizjson to behave as similar as possible to the embed, we must include `state` in the vizjson, so widget configuration is preserved.

Also, @xavijam, do you remember why do we include `layersData` into the embed? I think it has to do with autostyling of widgets. If we want `viz.json` to be a full representation of the visualizations, maybe we need to include that as well.

**Comment by xavijam** [comment]
> Also, @xavijam, do you remember why do we include layersData into the embed? I think it has to do with autostyling of widgets.

Yes, it has to do with that @javitonino

**Comment by juanignaciosl** [comment]
First of all, we're only speaking about v3, aren't we?

I'd vote for 3 as well, because `state` can contain more stuff, so this way vizJSON would be more open, but I guess that @alonsogarciapablo has the last words on this.

**Comment by alonsogarciapablo** [comment]
Yes, we're talking about v3 @juanignaciosl.

I'd go with 1. so that people who will be able to use CARTO.js (someday) only depends on one "artifact" (the viz.json) to load a map. Not sure if folks using CARTO.js would also want to set some initial state for the widgets, in which case we might need to include the state in the viz.json as @javitonino said.

**Comment by alonsogarciapablo** [comment]
Same goes for bounds, I'd keep them synced for now.

**Comment by rafatower** [comment]
Unless somebody tells me otherwise, I'll take the option 1 as the one to be implemented.

> 1. Fix the bug: read map and zoom from the states.

**Comment by rafatower** [comment]
I cannot reproduce this issue anymore:

![image](https://user-images.githubusercontent.com/1914276/27833743-4da2bf6e-60d4-11e7-8b2c-0eb251d38d5e.png)

Is it valid yet?

**Comment by ivanmalagon** [comment]
While doing a PoC to use vizJSON v3 with CARTO.js, this issue has jumped again.

The problem it's not with `vizJSON` and `stateJSON` objects in `window`. It's with the written `vizJSON` in `window` vs the returned JSON when calling to the vizJSON endpoint.

Embed page:
![image](https://user-images.githubusercontent.com/1078228/36108342-eda51dfc-101c-11e8-9cf1-544ff69aae04.png)

vizJSON endpoint
![image](https://user-images.githubusercontent.com/1078228/36108377-071ab634-101d-11e8-8e54-aeb2b1b8dbca.png)

This stops us from giving to our current Editor users relying on vizJSON an alternative to pass to Builder.

Anyone can shed a bit of light about what's different between how vizJSON is written in the `window`object vs what it's returned from the endpoint? Shouldn't they return the same payload?

**Comment by javitonino** [comment]
Yes, vizjson shows incorrect data. Vizjson center/bounds/zoom is taken from the map models which is not updated for builder maps. We should really take it from state if available.

For editor maps migrated to builder, this will be correct until they move the map around for the first time (where the migration to state will take place and everything breaks 💥). It's an easy fix on our side, but we should decide if we want to:
- Present the state object directly (put stateJSON inside of vizJSON) and remove center/zoom/bounds - - Fill the vizjson fields with information from the state (probably need to add some info to widgets as well), and remove stateJSON.

First one is more straight-forward, but is more coupled to the structure of the state. But, I think we are already pretty coupled on that regard, since the URL `?state=` parameter has the same structure. So maybe it's the quickest way to do it. The second approach is more compatible with vizjson2 (which we probably don't care about) and hides the fact thar stateJSON is a thing.

This is also slightly related to the snapshot features, since that consists mostly of saving different stateJSONs for each map, so it might inform our design here.
