### ISSUE TITLE
Make “Scroll Wheel Zoom” a default when creating a new map

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#12205]
### Context
There is a common request about making the scroll Wheel Zoom activated by default when creating a new map. I cannot find the old issue tho.

### Steps to Reproduce

1. Create a new map.
2. Try to use the scroll wheel to zoom in/out

### Current Result
You need to activate it

### Expected result
It should be activated by default

**Comment by javitonino** [comment]
Before doing anything, `scrollwheel = true` was the default a couple of years ago. But it was was changed in https://github.com/CartoDB/cartodb/pull/2421, because of https://github.com/CartoDB/blog/issues/176. Basically, when scrolling in a page with embeds, it was easy to stop scrolling the page, and start zooming the embed.

After all that, can you confirm the go-ahead for this @saleiva?

**Comment by saleiva** [comment]
cc/ @zingbot @kevin-reilly
