### ISSUE TITLE
Increase and Decrease with arrows doesn't respect the minimum and maximum size

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#12212]
### Context

![size](https://cloud.githubusercontent.com/assets/1214201/26453159/11262e9e-4163-11e7-973b-2760ffcd88b0.gif)

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*
1.  For example, try to change the size in the hexbis aggregation method
2. Increase and decrease with arrows
3. If I go to less than 10 (the minimum size) it still decreases the number

**Comment by xavijam** [comment]
For new hires!

**Comment by rubenmoya** [comment]
What should we do in this scenario?

1. The user types 5 in the input (min value is 10).
2. The user uses the arrow key to go up, it works, because it's not bigger than the maximum, but the value still wrong.

Should we keep the actual behaviour of increasing the amount or should we set the value to the minimum permitted?

![number_editor](https://cloud.githubusercontent.com/assets/905225/26720887/1358750a-478a-11e7-9240-299b31275525.gif)

Same case when the user types 10000 and the maximum permitted is 10, should we set the value to the maximum?

Maybe we shouldn't allow to type a number bigger/smaller than the min/max permitted, any thoughts?

**Comment by xavijam** [comment]
@piensaenpixel ^^^ ?

**Comment by piensaenpixel** [comment]
Hi @rubenmoya 
IMO if the user types 5 in the input and (min value is 10) when you increase when the arrow the next step should be 10.

**Comment by xavijam** [comment]
Ok, we accept an 🐙  as a pet!
