### ISSUE TITLE
Analysis form is being rendered more than once

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#12299]
Thanks to this [PR](https://github.com/CartoDB/cartodb/pull/12249), we fixed the problem of rendering several times the analysis form when it was added.

Basically the steps to reproduce the thing are:

- Create a map of points.
- Open the Chrome dev tools and add a debugger breakpoint in layer-content-analyses-view.js render function.
- Add a new analysis and check how many times that view is being rendered.

We should review if the problem has come back again.

cc @nobuti

**Comment by rjimenezda** [comment]
Can't reproduce on `master` 🤔 

Whenever you add an analysis, `analyses-view.js` is re-rendered, so `layer-content-analyses-view.js` renders again, but only once. Another re-render happens if you switch around on the workflow items, but that's necessary.

@nobuti can you give me some case in which it happens?
