### ISSUE TITLE
Time-series aggregations

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#12324]
### Context
As discused in #12087 and in the document [Time-Series Milestone (1)](https://docs.google.com/document/d/1rPgCk8BiHXsNM4BQPb82ImQzVzs0UTTiWXF8vsuCXRw/edit#heading=h.eilx4ykmr119) Builder has to provide time aggregations in time-series widgets.

Engine has a version implementing the changes outlined in doc (1). We need to:
- Modify the existing widget form to provide the new options.
- Be able to instantiate the widget through cartodb.js -> Maps API 

Designs and discussion about this work is hold in https://github.com/CartoDB/cartodb/issues/12087

### Missing steps

- Allowing the user to choose the widget timezone will be done in https://github.com/CartoDB/cartodb/issues/12088 This ticket is to have a first version working.
- We still have to discuss how to provide smart aggregations to the user in order to avoid more than 256 buckets.

**Comment by xavijam** [comment]
About the second bullet in the missing steps:

> We still have to discuss how to provide smart aggregations to the user in order to avoid more than 256 buckets.

The original discussion is happening [here](https://github.com/CartoDB/Windshaft-cartodb/pull/698#discussion_r120586106), but after talking offline with @dgaubert we have two good options:

- 1st option: When the time-series widget is added, we wouldn't allow the user to change the aggregation (the automatic one would be selected by default) after making a request to the Maps API, returning the MAX and MIN values from the selected column. With that, we could display in the aggregation dropdown only the options we consider are valid.

- 2nd option: Let the user choose any aggregation, and then, the Maps API could return in the instantiation that widget can't be rendered because it needs more bins than allowed. Then Deep-insights could render that text or other error over the widget.

- Extra ball: what about if we implement both? Making that check in frontend and then having the limitation in the Maps API endpoint.

Adding all frontend team and involved mates in that PR.
@CartoDB/frontend @dgaubert @rochoa @jorgesancha @saleiva @ethervoid

**Comment by dgaubert** [comment]
I'd like to add a third option:
- Let the user choose any aggregation, and then, after fetching data from histogram Builder could check the number of bins through `bins_count` property. If that number is greater than the maximum accepted to be renderer properly in the component then Builder (deep-insights) could display an error message over the component.

Thus, we can decouple dataview's service from a UI limitation. We can provide a large time-series for further use cases or another kind of clients. However, this approach could be a little inefficient due to the dataview's service could perform work that, at the end, is not going to be displayed.

**Comment by jorgesancha** [comment]
Not my call to make (summoning @saleiva and @kevinreilly) but my vote would
go to option 1: with it we wouldn't need option 2 and we would save our
already battered DBs the pain of computing what could potentially be a huge
number of records and bins.

> --
*Jorge Gómez Sancha*
VP of Engineering
CARTO <http://www.carto.com/> - Turn Location Data Into Business Outcomes

+34 626 126 821
@jorgesancha

**Comment by xavijam** [comment]
well @jorgesancha, the request would be done in any case using the SQL API so... but whatever you decide it is ok for us.

**Comment by dgaubert** [comment]
The first option requires a call to SQL-API asking for the interval between the max and min date of date the column. Since we do a lot of those request (a SQL defined as template in Builder) it seems the way to go (I'm still seeing it a little bit weird 😈 ). The SQL would be:

`SELECT DATEDIFF('second', max(date), min(date)) as interval from ( ... ) _cdb_query`

It will return:

```
{
   rows: [{
     interval: 45872 // seconds
   }]
}
```

Thus, Builder is able to disable/hide aggregations that are not going to be displayed.

**Comment by AbelVM** [comment]
Related to https://github.com/CartoDB/solutions/issues/874

**Comment by saleiva** [comment]
I'd try to show errors as much as we can, if we avoid users to make them :)

I'd go with option 1 but... why don't we put that extra request to look part of the first instantiation of the widget, so it shows a loader indicator while we receive that data in both, the widget, and the lateral panel? how fast is that call?

**Comment by stuartlynn** [comment]
This might be out of scope here, but one thing that would be really useful is being able to do aggregations for multiple categories in the time series widget. So for example, if you have multiple companies and you want to compare their profit over time. 

This could then be displayed as either a stacked bar chart or as a series of lines of different colors showing the trend over time. I think both of these should be options if we can. 

Stacked Bar chart: 

https://bl.ocks.org/mbostock/3886208

![image](https://user-images.githubusercontent.com/209838/27588011-a0c6041e-5b14-11e7-8693-bb109c122db8.png)


Multiple lines 

https://bl.ocks.org/mbostock/3884955

![image](https://user-images.githubusercontent.com/209838/27588019-ab1f64d2-5b14-11e7-9184-7e80223fb3a5.png)

This would be hugely useful for investment firms, brand owners etc and allows visual comparison of key values over time that is only do-able right now by filtering the time series and noting the result on a formula widget.

**Comment by ivanmalagon** [comment]
Hi.

We're implementing the suggestion of aggregations according to the underlying data and we have a question.

As an example, we have a dataset with a date column that would aggregate as this:

4 years
16 quarters
47 months
201 weeks
1406 days and so on.

Our first approach is to filter every options that goes above 256, that it's the current maximum number of buckets available now in the widget. So that left us with 4 possible aggregations: years, quarters, months and weeks.

What aggregation should we choose automatically?

- The one closer to 256? (In this case 201 weeks)
- The one in the center? (In this case it could be 16 quarters or 47 months)

Thanks!

**Comment by saleiva** [comment]
One thing... 
Why don't we make the max to 365 so we can aggregate per day if having 1-or-less years of data?

Now, responding to your question :D, I'd try to add the one with more granularity, yes.

**Comment by noguerol** [comment]
365 buckets would be great, indeed. As per @stuartlynn suggestion, I this is always preferable to make that kind of visual analysis with a plot chart than a stacked histogram, both things being out of the scope of this issue. For the moment we can always filter per category for comparison, as you suggest.

**Comment by AbelVM** [comment]
My two cents:
* I'd go with 366 buckets as max (leap years anybody?)
* Transition from pure histogram to column chart with aggregations by any numeric field ---> and apply this to histograms widgets later
* Stacked chart, taking into account the limited vertical space of the time series widget, would lead to a lot of visual noise

**Comment by stuartlynn** [comment]
:+1: for 365/366 buckets.

I think having more plot charts, in general, is a good thing. Regardless of the implementation, we need a way to visually compare two or more time series, I don't think using the filter my category widget to do comparisons is a sufficient solution.

I think if we are finding that the space in the time series widget limits us in terms of the information that can be displayed there, then we might want to think about increasing its size on the page. I know the map needs to be the dominant thing but for many applications I  understanding the temporal nature of the data is just as important as the spatial nature of it.

**Comment by ivanmalagon** [comment]
Regarding the aggregation options pointed by @xavijam 

The time-series widgets API doesn't have any automatic 'bucketing' for date columns. The existing automatic one treats the data as numeric.

@dgaubert is going to research if it's feasible to add this automatic option with the criteria commented above: pick the aggregation closer to 366.

Thanks Dani!

**Comment by jorgesancha** [comment]
One thing to bear in mind (if I remember correctly my conversation with @urbanphes) is the max space available for the mobile widget. (E.g. 2px per bar is already 512px)

**Comment by jorgesancha** [comment]
Ignore my previous comment - it was a minimum, not a maximum 🙈

**Comment by noguerol** [comment]
2px per bucket, but on smaller screens mobile linear version could be triggered, so no problem with the size.

**Comment by rubenmoya** [comment]
Hi!

I've found a use case we didn't think about. Right now the aggregation select is populated only with the aggregations which have less than 366 buckets, so when you change between them everything works fine. But what happens when:

We have a dataset which only allows aggregate by year, quarter and month and change the SQL query to filter the data so it allow us to aggregate by minutes and seconds, we save the widget with seconds, and then change the SQL query again, to get all the data. The widget will break because we're aggregating by seconds, which give a lot more buckets than we allow.

What should we do in this case?

**Comment by dgaubert** [comment]
After applying any filter builder should re-fetch the histogram (w/o aggregation: automatic mode) in order to know what aggregations are allowed with the new data.

Does it work for your side?

**Comment by ivanmalagon** [comment]
One doubt for @noguerol or @CartoDB/design team.

Now that we have time aggregation we can provide meaninful selection tags. If aggregating by year, showing the whole date makes no sense, it's better to show the years.

The thing is that we don't have a clear idea of what to show as the end. Our previous code always show the starting point of the next bin as the end. That makes complete sense for numeric buckets, like 'Select what goes between 1 and 3',  but we feel that it doesn't make so much sense in date contexts. I'll show you some examples:

If selecting only two months from the whole year, Jan and Feb, we write `Selected from Jan 2014 to Mar 2014` Should it be `from Jan 2014 to Feb 2014`? 
![image](https://user-images.githubusercontent.com/1078228/27831833-99ebbac2-60cc-11e7-9c2f-d797087a58a6.png)

Selecting 12 months of 2014 we say that the end is Jan 2015
![image](https://user-images.githubusercontent.com/1078228/27831770-5d4c4564-60cc-11e7-86f1-8466ed933785.png)

Only 1 year
![image](https://user-images.githubusercontent.com/1078228/27831359-a307c6ca-60ca-11e7-8b7d-9738dcb85a46.png)

4 quarters of 2016
![image](https://user-images.githubusercontent.com/1078228/27831713-2884b3ca-60cc-11e7-8283-8f8bc21854ea.png)

You get the idea.

Should we show as end in time aggregations the starting point of the next bucket (as we do in numeric aggregations)? Or should we limit to the last bucket of the selection?

Any thoughts?

**Comment by noguerol** [comment]
Good one. The last bucket, certainly.

**Comment by arianaescobar** [comment]
Last bucket for sure.

**Comment by urbanphes** [comment]
@ivanmalagon I have a question: 
Why do the vertical lines not match with bars size? 
On these examples (images) it can be seen how the bars for months are something more wide that the vertical lines.

**Comment by ivanmalagon** [comment]
Good catch @urbanphes I'll take a look on that. We need to revise also the legends on the X axis.

**Comment by noguerol** [comment]
Additionally to the vertical limit lines, it seems there is also an inconsistency between bucket width, the grid below and the labels.

![image](https://user-images.githubusercontent.com/70603/27956657-117b6cb8-631b-11e7-9fc9-383a2c410192.png)

**Comment by saleiva** [comment]
the vertical lines are for the legend x-axis.

**Comment by ivanmalagon** [comment]
As @saleiva says, the vertical lines are for the legend x-axis.
When dealing with time buckets they can be misleading, yes. And now we show in the labels what the user is selecting, so we can get rid of the vertical lines, I think.

This is how the widget it's behaving with time aggregations and no vertical lines so far. First with a time aggregation by quarter and then by year.

![select](https://user-images.githubusercontent.com/1078228/27965337-c3c84024-633b-11e7-9868-f5569024a572.gif)

**Comment by saleiva** [comment]
I would not get rid of the vertical lines, since that will only work with some aggregation levels, don't you think? Imagine you aggregate by day in a 5 months dataset. It would be great to have a guide for when the month changes, don't you think?

**Comment by ivanmalagon** [comment]
Blocked until Windshaft correspondant PR gets merged. First, they have to solve some not straightforward conflicts between it and master.

**Comment by xavijam** [comment]
Deployed!
