### ISSUE TITLE
[feature request] Import API: include resultant schema in job response

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartodb#12331]
After an Import API job is complete, it would be very helpful for application developers to receive the final schema of a table so that explicit mappings between original/final column names and data types can be better tracked.

As far as I know, there is no explicit way to track the schema updates that CARTO applies. E.g., getting the schema back from the SQL API does not preserve the order of the column names in the response, and CARTO adds utility columns.

In cartoframes, we send dataframes to CARTO, but while pandas allows for capitalization and special characters in column names, CARTO normalizes column names.

Adding a `schema` key to the [import status response](https://carto.com/docs/carto-engine/import-api/standard-tables#check-the-status-of-an-import-process) would be really helpful:

```JSON
{
    "schema": {
        "col_name_1": {
            "original_name": "Col Name 1",
            "final_type": "numeric"
        },
        "vendorid": {
            "original_name": "VendorID",
            "final_type": "text"
        },
        ...
    }
}
```

cc @juanignaciosl

**Comment by juanignaciosl** [comment]
As adding a new feature in the roadmap is not always feasible, and this feels more related to SQL API (more on this later), I'd like to suggest some alternatives:
- *Column names*: instead of receiving the new names in the response, I'd suggest preprocessing the column names so they're valid identifiers (we could provide a guide on this). This way we could avoid the need to return that information in the response, and you would avoid the need for post processing the response as well. The main problem is that names must be valid PostgreSQL identifiers.
- *Types*:
  - Sometimes types are not needed. Remember that [you can disable type guessing](https://carto.com/docs/carto-engine/import-api/standard-tables).
  - If types are not only needed but important, consider disabling type guessing and then setting the actual type that you want with SQL API.
  - You can also use guessing and then use the SQL API to get the types.

One of the best things that CARTO has is keeping concerns isolated in different services. As you know, everything related to _tables_ is usually handled by the SQL API. Import API is about importing _files_ into CARTO. The physical table is only one of the outputs: tables (often several of them), visualizations, metadata, etc. Everything related to tables should probably be an SQL API concern, and it can be solved with SQL. For example, this request returns the full schema, including the utility columns added by CARTO:

```
https://juanignaciosl.carto.com/api/v2/sql?sort_order=asc&rows_per_page=0&page=0&api_key=*****&q=SELECT+*+FROM+(SELECT+*+FROM+juanignaciosl.dont_delete_sync)+__wrapped
```

(... although it's true that it doesn't keep the order).

Nevertheless, if a different approach as suggested is not possible, we could return the schema information, of course. @stuartlynn , @kevin-reilly , what do you think?
