### ISSUE TITLE
Edit profile is showing error message

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#12399]
### Context
Updating my profile is not working

![edit-profile](https://user-images.githubusercontent.com/1214201/27637336-a925f0b4-5c0f-11e7-95fb-93cb1c4bfd39.gif)

**Comment by xavijam** [comment]
Guys, this is not frontend, it belongs to backend.

**Comment by xavijam** [comment]
Already checked what was happening, the twitter username was being used by another user, and the "save" was failing due to that. If you select another one, it will work (tested) :D.

![screen shot 2017-07-13 at 10 37 06](https://user-images.githubusercontent.com/132146/28157663-8293260c-67b7-11e7-826c-c234906325a6.png)

**Comment by xavijam** [comment]
Opened ticket in order to improve this case ^^^.
