### ISSUE TITLE
[vector] Custom color on icons not being reflected properly on the embed

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#12474]
### Context

I changed the color of an icon and inside Builder the change was made perfectly but on the embed it didn't. Seems like the colored icon is being shown underneath the original icon. 

### Steps to Reproduce

1. I added a layer 
2. Performed a Georeference analysis which returned a geometry of points 
3. Styled it with a marker icon and painted it blue 
4. Published it 

### Current Result

![screen shot 2017-07-14 at 21 34 08](https://user-images.githubusercontent.com/16247628/28260387-21b20fb6-6adb-11e7-8a9e-2f77dc35ddc8.png)

### Expected result

![screen shot 2017-07-14 at 21 34 02](https://user-images.githubusercontent.com/16247628/28260393-28579a7a-6adb-11e7-9d19-37d3e8b9df47.png)

### Browser and version
Chrome Version 59.0.3071.115 (Official Build) (64-bit)

### .carto file

[Donde votar el 16J en el exterior (on 2017-07-17 at 08.24.38).carto.zip](https://github.com/CartoDB/cartodb/files/1151950/Donde.votar.el.16J.en.el.exterior.on.2017-07-17.at.08.24.38.carto.zip)

**Comment by arianaescobar** [comment]
@noguerol

**Comment by saleiva** [comment]
After testing for a while, It's something that only happens when rendering using vectors. It might have something to do with the way we are drawing icons on features

**Comment by makella** [comment]
reported by @MichaelSpichiger in #cartography-help he's noticing this happening with CartoCSS attachments too. For example, putting a circle as an attachment as a frame for an icon.

Attaching Ariana's .carto file again with the attachment CartoCSS included.
[Donde votar el 16J en el exterior (on 2017-07-19 at 18.14.28).carto.zip](https://github.com/CartoDB/cartodb/files/1160033/Donde.votar.el.16J.en.el.exterior.on.2017-07-19.at.18.14.28.carto.zip)

Michael's images:

Current Result:
<img width="872" alt="screen shot 2017-07-19 at 11 17 13 am" src="https://user-images.githubusercontent.com/1566273/28382522-42739c1c-6c73-11e7-885c-4abdbb9cde0b.png">

Expected Result:
![screenshot 64](https://user-images.githubusercontent.com/1566273/28382496-2ae9012c-6c73-11e7-9de2-a84dd8cd9e37.png)

cc @MichaelSpichiger @ztephm

**Comment by ztephm** [comment]
Here's @MichaelSpichiger 's original too: 
[Billboard Ads (on 2017-07-19 at 18.36.43).zip](https://github.com/CartoDB/cartodb/files/1160150/Billboard.Ads.on.2017-07-19.at.18.36.43.zip)

**Comment by noguerol** [comment]
What is the situation with this one, @rubenmoya?

**Comment by rubenmoya** [comment]
@noguerol I was going to start with it, but I realised @IagoLast and @rochoa were already working on it

**Comment by IagoLast** [comment]
## Current Status
After a little research we found that tangram.js doesn´t have the capability to replace the color in an svg image and since our [icons](https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/marker-18.svg) are gray by default they are going to be displayed in a darker color than the desired.

<img width="1285" alt="screen shot 2017-07-21 at 20 11 33" src="https://user-images.githubusercontent.com/2657897/28562342-25d18142-7122-11e7-90dc-b1bd99432446.png">
Raster rendered with the color set to white.


<img width="677" alt="screen shot 2017-07-21 at 20 11 39" src="https://user-images.githubusercontent.com/2657897/28562349-29dff7fa-7122-11e7-9deb-26a768cc8253.png">
Tangram rendered with the color set to white


## Options

### a) Remove image-marker support for vector maps
Since we want all our maps to be vector-based this this option makes no sense long term.

### b) Limit the scope of this feature
Warn the users: To use colored markers in svg maps they should upload white/transparent assets.

### c) Try to fix this in tangram.js
This will be nice but it takes a lot of work and as we have found out the tangram.js team is not in favor of implementing this feature.

### d) Fix tangram.js and create a fork
IMO forks should be always the last option...

**Comment by noguerol** [comment]
B for sure, but I don't like it either. Wild question: can't we programmatically change every uploaded svg icon bg to transparent? Because to be honest, our users have very little control about their icon's background so warning them about it it's going to be confussing and unexpected.

In any case, I HEREBY SUMMON @CartoDB/design for:

1. Changing every icon in our library to transparent :tada: 
2. In the case we cannot do what I propose, to properly show the warning ("Transparent .svg icons recommended") when uploading a custom icon.

**Comment by IagoLast** [comment]
> Wild question: can't we programmatically change every uploaded svg icon bg to transparent?

Good point here, whats the API managing the file uploads?

**Comment by saleiva** [comment]
changing every icon could affect every map. Also, we cannot enforce our users to upload transparent icons since that's not the standard. I'd go with c

**Comment by IagoLast** [comment]
I just created an [issue](https://github.com/tangrams/tangram/issues/574) asking tangram for help to style markers. I think we should continue this discussion once we get a response.

**Comment by IagoLast** [comment]
According [the response from tangram: ](https://github.com/tangrams/tangram/issues/574#issuecomment-318174478)

> We don't currently support these other modes but they are in development now.

So IMO we should use raster-mode as a fallback while tangram does not implement this.

**Comment by saleiva** [comment]
+1

**Comment by noguerol** [comment]
ok!

**Comment by rochoa** [comment]
We are already falling back to raster in this scenario.
