### ISSUE TITLE
Implement responsive behaviour for time series

### ISSUE THREAD

**Issue by rjimenezda** [CartoDB/cartodb#12470]
Time series elements positions & apperance varies a lot with screen size.

Sample:

<img width="717" alt="screen shot 2017-07-14 at 18 51 01" src="https://user-images.githubusercontent.com/446970/28221882-69332572-68c5-11e7-887e-159473105e5d.png">

**Comment by xavijam** [comment]
Oh, why was it blocked?

**Comment by xavijam** [comment]
Blocked until we release https://github.com/CartoDB/cartodb/issues/12088.

**Comment by rubenmoya** [comment]
I've deployed it to `ded04` if someone wants to have a look.

cc @CartoDB/design

**Comment by josecruz** [comment]
I'll take a look :D

**Comment by josecruz** [comment]
Hey guys! I don't know if it's a late change but:

Can we show the handlers on that bar by default and also activate the option "Show Totals" so that way we make it look more like an "interactable bar with data"

![pasted image at 2017_08_16 01_32 pm](https://user-images.githubusercontent.com/596509/29361698-0e4daf96-8289-11e7-95d0-01c8a6943b43.png)

vs

![image](https://user-images.githubusercontent.com/596509/29361683-f9cbb84c-8288-11e7-84ce-a762791e09c4.png)
(but orange)

**Comment by rubenmoya** [comment]
Let's open a new issue with that change, since this is being merged already

**Comment by noguerol** [comment]
@josecruz can you open it? :*

**Comment by josecruz** [comment]
@noguerol sure thing

**Comment by noguerol** [comment]
Reference it here, please

**Comment by xavijam** [comment]
Guys, closing this one because it was already added in production.
