### ISSUE TITLE
Validate if layer source exists when layer has changed

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#12549]
If there is any change (PUT request) over the layer endpoint, we should check if the `source` attribute exists in the analysis definition. In not, we should trigger an error.

Related to ghost nodes and [this ticket](https://github.com/CartoDB/cartodb/issues/12548).

cc @juanignaciosl @javitonino

**Comment by javitonino** [comment]
A couple of things regarding this:
- We need to make sure we don't break editor (as it uses the same layer endpoint). As long as we don't do any validations if the `source` attributes is not present, it should be alright.
- This will cause crazy amount of breakage in frontend (and we are aware of that). But this change can be useful as a guide of what needs to be fixed in frontend.
- We should also add this same validation to the analysis endpoint. In the case we delete a layer, the layer should be deleted before deleting the node (and it's not the case right now). Although most ghost node problems are caused during layer dragging, I detected at least one problem with layer deletion. Keep in mind that there are multiple cases of layer deletion, some of them involve renaming nodes (when a layer pointing to an intermediate node is removed).

**Comment by nobuti** [comment]
We found some stoppers in order to tackle this. This needs to analyze and probably change how the requests are made in order to fix the issue properly.

**Comment by juanignaciosl** [comment]
What's the current status of this? Do you plan addressing it?
