### ISSUE TITLE
Allow database connectors to transform WKT to geometry during import

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb#12566]
Currently, when user import a table using the MySQL connector with a column named "the_geom" set as a VARCHAR data type that contains geometries in WKT text like (LINESTRING(15.24 51.23, 12.43 51.41)), during the import, the table is imported correctly but the_geom column is not
being populated with the geometries of the WKT text, instead it adds an invalid_the_geom column with the WKT values.

According to  @jgoizueta , this is the expected behaviour because **_the geometries are not automatically detected. You'll need to cast the column after importing._**

It would be good to improve the connectors in order to be able to cast WKT to geometry types during the import.

**Comment by rochoa** [comment]
Summoning @kevin-reilly for prioritization.

**Comment by jgoizueta** [comment]
If we implement this we could accept and convert to geometry various formats:
* WKT, EWKT
* WKB, EWKB as hex string

That would work if the data select as `the_geom` is a geometry column in a PostGIS external database, so it would be a workaround also for the case of users with geometries in their external dbs.

**Comment by alrocar** [comment]
Hey, on the BigQuery connector branch I had to enable geometry guessing. It works with our regular [georeferencer](https://github.com/CartoDB/cartodb/blob/master/services/importer/lib/importer/georeferencer.rb). Take a look at [this commit](https://github.com/CartoDB/cartodb/commit/c94e97f45c7198aabaadef26576aea35184cfac3)

Let me know if that commit is suitable for preparing a PR.

cc @jgoizueta

**Comment by jgoizueta** [comment]
Thanks @alrocar that looks good!

I think that using the Georeferencer will detect WKT in `the_geom` columns and cast it to geometry, but if the contents is WKB (as an hex string) it won't. We should handle that as well, since when a PostGIS geometry column is imported through a connector it ends up as WKB text string.

It seems that supporting WKB in `Georeferencer` was considered at some point: https://github.com/CartoDB/cartodb/blob/master/services/importer/lib/importer/column.rb#L157

**Comment by alrocar** [comment]
Hey @jgoizueta thanks for pointing that out

Adding support for WKB/EWKB in `column.rb` seems quite straight forward. Do you know of any reason it is not there yet? (just wondering if I'm missing something not obvious)

**Comment by jgoizueta** [comment]
I don't know why it wasn't implemented. One reason could be the current identification of WKB by regular expression is too simplistic (which may not be a problem, since we're only looking at columns with names that suggest they contain geometries). Checking properly for a WKB would be more complex/costly, and non-geometry numeric/binary columns would still be likely accepted as geometries.

I would go for trying to convert anything that looks like a WKB (just checking the proper number of hex digits, and maybe the header bytes) and is named the_geom, wkb_geometry, etc.

**Comment by alrocar** [comment]
Yep, it looks like we are supporting `wkb` by [casting to geometry](https://github.com/CartoDB/cartodb/blob/master/services/importer/lib/importer/column.rb#L70) See this [test](https://github.com/CartoDB/cartodb/blob/master/services/importer/spec/unit/column_spec.rb#L40-L43) as well.

Just tested locally and it properly imports a table with a string column that contains a WKB as long as it is named like one of [these](https://github.com/CartoDB/cartodb/blob/master/services/importer/lib/importer/georeferencer.rb#L14)

Adding a PR -> #12753

Not adding support for ewkt/ewkb yet, but IMO we should tackle that in a different issue.

Thoughts? @jgoizueta

**Comment by jgoizueta** [comment]
Oh, I had missed the unconditional cast to geometry, good point.

I agree to deal with ewkb/t in a separate ticket, let's deploy the current PR here first, which is a huge improvement in its own.

**Comment by alrocar** [comment]
@oriolbx #12765 merged and deployed in production.

Feel free to close this when you consider.

**Comment by oriolbx** [comment]
Thanks! 😃

**Comment by alonsogarciapablo** [comment]
☝️ @alasarr @alvaro some interesting background here related to detecting and casting geometries during imports from databases (via @oriolbx). @jgoizueta take a look at https://github.com/CartoDB/cartodb/issues/12566#issuecomment-326540036.
