### ISSUE TITLE
Error importing broken canonical visualizations

### ISSUE THREAD

**Issue by mayoral** [CartoDB/cartodb#12588]
### Context

Currently, when we export canonical visualizations for users, we aren't checking if they have a table associated with them. But we try to import this information, we are getting the following exception:

```
RuntimeError: Cannot import a dataset without physical table
```

Since we check for the table in the import.

### Steps to Reproduce

1. Export user visualizations without table associated (broken ghost tables, manually delete the UserTable model) with `UserMetadataExportService.export_user_to_directory`
2. Try to import them with `UserMetadataExportService.import_user_visualizations_from_directory(user, Carto::Visualization::TYPE_CANONICAL, path)`

### Current Result

You'll get the RuntimeError mentioned above.

**Comment by juanignaciosl** [comment]
Uhm. I'm working on this and I have reproduced it in a test, but I think that there's not a good solution. I first thought about just exporting it and then not importing that dataset, but as the dataset is likely to be related to visualizations, many things might break. I think that exporting a user with a dataset without physical table should fail. What do you think, @javitonino ?

**Comment by javitonino** [comment]
> I think that exporting a user with a dataset without physical table should fail.
I thought we were not talking about physical tables themselves here, only metadata. I agree with this part though, maybe we could enforce a ghost tables execution before exporting a user to ensure this is not a problem. This should be safe since we do it each time the user visits the dashboard.

🤔 About metadata only:

I think it may be safe not to export the incomplete dataset. As the relation between a map and a dataset is done through the Layer <-> UserTable association, the dependency is already broken in the source metadata (since UserTable does not exist).

On the other hand, this should be pretty rare nowadays. Throwing an error could be useful so we can manually jump and fix/check if the migration should succeed. But that's more manual work for us.

I'm leaning towards not exporting canonical visualizations without UserTable. The more I think about it, the more it feels safe.

**Comment by juanignaciosl** [comment]
But, being safe or not, tables should be in sync, and ghost tables fix that. Not having a physical datable matching metadata means that user has been messing its datasets with SQL API (or that there's been an error), and ghost tables are meant for that. Do you think that we should allow exporting a user whose tables are not synched?

**Comment by juanignaciosl** [comment]
Even more, checking the sync fixes this issue and also avoids other issues with derived visualizations.

**Comment by javitonino** [comment]
I updated my comment, I think you may have missed my first paragraph due to a formatting error (I had quoted my own text, oops). To be clear:
- I think we should not allow exporting users when metadata <-> data is not synced. Either we run ghost tables before, or throw an error.
- I think we should try to allow exporting when the metadata is broken in a known way. In this case, if a canonical visualization exists, without a valid UserTable nor a physical table, we should just skip the visualization. Without UserTable and physical table, no maps can reference this dataset, so it could just be deleted.

**Comment by juanignaciosl** [comment]
Oh 😅  Yes, I totally skipped the quoted part xD

> I think we should not allow exporting users when metadata <-> data is not synced. Either we run ghost tables before, or throw an error.

Agreed. I'd prefer not to trigger ghost tables automatically (yet). I'd first release a check.

> I think we should try to allow exporting when the metadata is broken in a known way. In this case, if a canonical visualization exists, without a valid UserTable nor a physical table, we should just skip the visualization.

Do you think that supporting explicitly these situations pays off? I might agree if that situation happens for many users, but I have doubts for exceptions.

**Comment by javitonino** [comment]
> Do you think that supporting explicitly these situations pays off? I might agree if that situation happens for many users, but I have doubts for exceptions.

Then we are in agreement. Let's first add a check which detects the issue, logs an error (including visualization id) and blocks the export. Let's track this error and if it is frequent, we can add the specific code to deal with this situation. This should only happen for old-ish users, since we now have tests to ensure this kind of partial deletion don't happen.
