### ISSUE TITLE
Improve error message when SQL API returns limits error

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#12597]
When the user has reached its limits and he/she tries to run a SQL, we should display the error in the notification area. If Maps API error fits our requirements we could not do anything, but if not, we should overwrite it and return whatever we consider.

**Comment by dgaubert** [comment]
Actually the following response is provided by SQL-API when a user reaches the response time limit:

```js
STATUS: 429, 
BODY:  {
    error: [
        'You are over platform\'s limits. Please contact us to know more details'
    ]
}
```

Is this the expected behaviour? If not, please, let me know.

**Comment by rubenmoya** [comment]
When working on the widgets error messages I created an [error enhancer](https://github.com/CartoDB/deep-insights.js/pull/597/files#diff-4ca04c0601545a531c57422151c6c86e) which overrides data in an error based on the type, I used it to change the message provided by the SQL API, maybe we could move it to cartodb.js so every error triggered is already with the data we want, I didn't do it in cartodb.js because there are things specific of widgets, like the error level to use a different CSS class.

**Comment by rubenmoya** [comment]
Limits error works like a charm:

![screen shot 2017-10-06 at 11 17 59](https://user-images.githubusercontent.com/905225/31271512-152e56c2-aa88-11e7-87be-2d2b4b0168c9.png)

But I found out this:

![screen shot 2017-10-06 at 10 20 28](https://user-images.githubusercontent.com/905225/31271525-1cf4af6e-aa88-11e7-9105-71379c010b10.png)

Seems like the key should be `notifications.sql.unknown`
