### ISSUE TITLE
Autostyle doesn't work on category widgets on number columns

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#12615]
### Context
Autostyle doesn't work on category widgets on number columns. Based on https://github.com/CartoDB/support/issues/923

**Comment by xavijam** [comment]
Sorry, but I don't get this. I've tried to create a category widget over an integer column and it is working.

![screen shot 2017-08-21 at 13 20 16](https://user-images.githubusercontent.com/132146/29517093-a36d54a8-8673-11e7-9512-4d8a69fca57c.png)
![screen shot 2017-08-21 at 13 21 13](https://user-images.githubusercontent.com/132146/29517094-a373d328-8673-11e7-8557-66419c69d209.png)

Am I missing something? (that is probably the problem, sorry)

**Comment by noguerol** [comment]
Sorry, my fault. Is not number columns what is not working but **autostyle** on those category widgets.

**Comment by makella** [comment]
I want to comment that I've noticed this in several cases as well and have narrowed down what is going on.

Basically, TurboCARTO is writing the numeric values as strings, which is breaking the CartoCSS.

For example,
 
I have 4 walktime polygons with values of 5,10,15,20 minutes
![screen shot 2017-12-14 at 8 38 02 am](https://user-images.githubusercontent.com/1566273/34000325-349dedee-e0aa-11e7-9fbb-5e8a7e78a64c.png)

For this map, I want to use a **Category widget** instead of a histogram, when autostyle is activated, the CartoCSS is:
```
#layer {
  polygon-fill: ramp([data_range], ("#7F3C8D", "#11A579", "#3969AC", "#F2B701"), ("20", "15", "10", "5"));
}
#layer::outline {
  line-width: 1;
  line-color: #FFFFFF;
  line-opacity: 0.5;
}
```
the resulting map is blank:
![screen shot 2017-12-14 at 8 37 06 am](https://user-images.githubusercontent.com/1566273/34000357-4239b4c4-e0aa-11e7-8bc4-7399ad2a035d.png)

The reason is because we are putting numeric values (`data_range`) into strings with `""`. If you remove the `""` so the values are true to what they are, numbers, the styling works:

```
#layer {
  polygon-fill: ramp([data_range], ("#7F3C8D", "#11A579", "#3969AC", "#F2B701"), ("20", "15", "10", "5"));
}
#layer::outline {
  line-width: 1;
  line-color: #FFFFFF;
  line-opacity: 0.5;
}
```

![screen shot 2017-12-14 at 8 42 02 am](https://user-images.githubusercontent.com/1566273/34000492-b1e1ab10-e0aa-11e7-8560-5c597c02a92b.png)

cc @ramiroaznar @arianaescobar

**Comment by ramiroaznar** [comment]
Ey Mamata, after reading your comment I realize there are several open tickets related to the same issue. The same conclusion was achieved [in one of my tickets](https://github.com/CartoDB/support/issues/611). Let's promote mine and close this one (and also [this other](https://github.com/CartoDB/support/issues/993)). Fixing this will close [this issue](https://github.com/CartoDB/support/issues/923) as well.

**Comment by makella** [comment]
@ramiroaznar great!
