### ISSUE TITLE
Research the implications of implementing out-of-bounds filtering in histograms

### ISSUE THREAD

**Issue by noguerol** [CartoDB/cartodb#12620]
In order to implement the [out of bounds filtering in histograms](https://github.com/CartoDB/design/issues/878) we first need to research the technical implications of supporting similar behaviors product-wide.

**Comment by ivanmalagon** [comment]
Writing here to document the case that 'opened the can of worms' and that it's not tackled in [the design discussion](https://github.com/CartoDB/design/issues/878) related to all this problem.

Imagine that we have a widget showing data with total range of [0 -50] divided in 5 buckets and we apply a filter from 10 to 20.

```
|-----|-----|-----|-----|-----|
0     10    20    30    40    50
      ^·····^
```

Then, we filter in another widget and that other filters cause that the data range of this widget goes [3 - 28] instead of [0 - 50]. What happens with the filter?

```
|-----|-----|-----|-----|-----|
3     8     12    18    23    28
         ?^··········^?
```

Now the filter [10-20] does not make any sense. Visually we don't have a solution to reflect this. Mathematically, we cannot calculate the stats of buckets correctly, etc...

**Comment by noguerol** [comment]
For the visual problem I would consider always fixing the original number and distribution of buckets in the filter and consequentially loosing the ends of the dynamic range, making them less precise. By doing it this way I guess stats will also remain true, right?

**Comment by alrocar** [comment]
Stale issue. Closing 👋
