### ISSUE TITLE
Add CORS headers to /api/v3/me response

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#12685]
In order to be able to request `/api/v3/me` from a different host.

In this first phase the accepted hosts can be configurable from `app_config` but eventually it would need to be available from any host.

**Comment by mayoral** [comment]
Hi!

We currently only add CORS headers for the host configured in `Cartodb.config[:account_host]`.

One possible solution for this issue is to add a new param in config, something like `cors_enabled_hosts` or similar, where we add a list of domains to be allowed. Then, we can merge `account_host` and `cors_enabled_hosts` and iterate that array to add elements to whitelist_referer and whitelist_origin in `ApplicationController#check_cors_headers_for_whitelisted_referer`.

Sounds good to you, @matallo?

**Comment by matallo** [comment]
sounds awesome
