### ISSUE TITLE
Bug adding a custom legend

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#12733]
### Context

I tried to add a custom legend in the` Neighbourhood` layer of the map added below and Builder wouldn't do it. 

### Current Result

![custom-legends](https://user-images.githubusercontent.com/16247628/30066904-98499270-9259-11e7-91f4-61b118213fb9.gif)

### Browser and version
Chrome Version 60.0.3112.113 (Official Build) (64-bit)

### .carto file

[Airbnb Madrid listings (on 2017-09-05 at 13.25.37).carto.zip](https://github.com/CartoDB/cartodb/files/1277782/Airbnb.Madrid.listings.on.2017-09-05.at.13.25.37.carto.zip)

**Comment by rubenmoya** [comment]
I've been messing around a few minutes and I couldn't reproduce it:

![legends](https://user-images.githubusercontent.com/905225/32009169-9093d58c-b9ae-11e7-9fa8-2b68b227365c.gif)

Any specific steps you followed or any previous thing you did? I'll try a few minutes more

**Comment by arianaescobar** [comment]
I don't remember anything in particular. I will try again in my account, maybe it was a temporal glitch or someone fixed it indirectly since then.

**Comment by arianaescobar** [comment]
Now the one that isn't working is the category one 😐 

![2017-10-25 18 11 46](https://user-images.githubusercontent.com/16247628/32009766-46985d98-b9b0-11e7-97a8-bd8c7106100d.gif)

**Comment by ramiroaznar** [comment]
Maybe related to [this Support ticket](https://github.com/CartoDB/support/issues/1029).

**Comment by arianaescobar** [comment]
Maybe!

**Comment by rubenmoya** [comment]
Yes, it's because of that, if your internet connection is slow, and you change between legends fast we send 2 `POST` requests, instead of the normal cycle which is `POST -> DELETE -> POST -> DELETE`, this end up in an error thrown by the backend, which breaks everything:

![screen shot 2017-10-25 at 18 24 36](https://user-images.githubusercontent.com/905225/32010392-f4e2f10a-b9b1-11e7-9a34-fc3c26864289.png)

**Comment by arianaescobar** [comment]
@rubenmoya can we fix it?

**Comment by rubenmoya** [comment]
I hope so 😂  I'll try a few things and see if that fix it

**Comment by rubenmoya** [comment]
Deployed to `ded15` :)

**Comment by rjimenezda** [comment]
Re-deploying to ded-15

**Comment by rjimenezda** [comment]
Deployed

**Comment by ramiroaznar** [comment]
@rjimenezda LGTM!!! Bravo!

**Comment by ramiroaznar** [comment]
It looks like something is wrong. Now no legends are showing.

**Comment by Jesus89** [comment]
I found that in production custom legends can not be added even without other legends:
![custom-legend-missing](https://user-images.githubusercontent.com/2227572/32178878-2e449266-bd8e-11e7-898c-5fb22cd4be4c.gif)

Btw, I cannot view any legend in ded-15.

**Comment by ramiroaznar** [comment]
In production is showing this error message: `Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)`

**Comment by rubenmoya** [comment]
As I said in my previous comment, in production the error is given when you send a post request when the first one hasn't finished, this happens with a slow connection when clicking in 2 different legends, since it's validated in backend the second one cannot be created, because it's the same type as the first one (color), and throws a `422` error (valid request but unable to process it), the "types per attribute" are this ones:

```
LEGEND_TYPES_PER_ATTRIBUTE = {
    color: %w(category choropleth custom custom_choropleth torque),
    size: %(bubble)
}.freeze
```

I solved this by adding a queue which waits for the last request to finish before adding a new one, it also checks the types of the new legend and removes the previous one if it's the same type, so the queue doesn't fill up and you end up waiting for 100 requests.

On Friday afternoon it was working, but we found that we needed to wait for the delete request too, which was my last commit. This morning it seemed to be working on `ded15` so I don't know what happened to not be working now :(

**Comment by Jesus89** [comment]
Deployed previous version v4.10.56 in ded10. Category legends are working. Custom legends are not working.

**Comment by rjimenezda** [comment]
In production 🚀

**Comment by ramiroaznar** [comment]
Rock&Roll @rubenmoya @rjimenezda :-)
