### ISSUE TITLE
Error in embed maps

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartodb#12881]
Some embed maps are not visible. Example: https://matallo.carto.com/builder/b1acfcd2-f8d0-11e3-aa4e-0e230854a1cb/embed

Console error:

![captura de pantalla 2017-09-28 a las 16 29 56](https://user-images.githubusercontent.com/3824953/30972486-efa643ce-a46a-11e7-9bbc-42baedc30362.png)

**Comment by nobuti** [comment]
The source is missing from the vizJSON.

**Comment by alonsogarciapablo** [comment]
We introduced a new internal check to ensure layers of type "CartoDB" have a `source` option in https://github.com/CartoDB/cartodb.js/pull/1755.

In theory, all "CartoDB" layers should have a `source` option in the viz.json, but this is not the case in the maps that are triggering these errors. They're probably maps that were created before analyses were introduced and are protected or have some private datasets (named maps). That's why they are a bit outdated... republishing them fixes the problem cause "sources" analyses are created and viz.json will include the `source` option.

This problem is related to https://github.com/CartoDB/cartodb.js/issues/1754.

We're reverting the PR in CARTO.js and will investigate later.

**Comment by ivanmalagon** [comment]
New insights about this.

What happens now is that we're making the error noticeable. The maps were already broken but they didn't throw any error.

Setting a previous version of Builder with no `source` checks the map is rendered somehow but broken with no error trace in the browser console.

![image](https://user-images.githubusercontent.com/1078228/31003478-317c86de-a4f0-11e7-8af5-486aefb5e969.png)

For me, we should leave this as it's right now and fix it through backend. If someone complains about this error, Support knows how to answer the customer (republishing the map).

Reverting the check would be overkilling to get non-working maps anyway.

Any thoughts?

**Comment by javitonino** [comment]
Quick script to fix maps which are missing analysis in the mapcap (please don't judge the code)
```
class MCVU
    include Carto::VisualizationsExportService2Exporter

    def export_in_memory_visualization(visualization, user)
      {
        version: CURRENT_VERSION,
        visualization: export(visualization, user, with_mapcaps: false)
      }
    end
end

def create_analysis_for_mapcap(v)
    mc = v.mapcaps.first
    rv = mc.regenerate_visualization

    rv.data_layers.each_with_index do |layer, index|
        analysis = Carto::Analysis.source_analysis_for_layer(layer, index)
        rv.analyses << analysis
        layer.options[:source] = analysis.natural_id
        layer.options[:letter] = analysis.natural_id.first
    end

    mc.export_json = MCVU.new.send(:export_in_memory_visualization, rv, rv.user)
    mc.save
end
```

**Comment by Jesus89** [comment]
:rocket:

**Comment by gred4** [comment]
![image](https://user-images.githubusercontent.com/10450360/42590900-5bbe6df0-8545-11e8-83c1-403d8e88b519.png)
The issue still exists with embedding maps.

**Comment by ramiroaznar** [comment]
Hi @gred4, could you send us the link of your map to support@carto.com?
