### ISSUE TITLE
URL generation for the FE/BE Split

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartodb#12993]
In the `public_map.html.erb` it makes use of `CartoDB.url` function to build different urls. We've a big problem here, because nowadays there's no way to build this urls in the front side.

https://github.com/CartoDB/cartodb/blob/c1c5f402390421c46dbd8889d447a4b7cc237ab6/app/views/admin/visualizations/public_map.html.erb#L43

I've been talking with @javitonino and we need to be able to build this URLs by getting the information through the API. A good start point will be to have a `templateUrl`, such as we're getting a `baseUrl`, but with a format so we can build the needed URLs from it. In addition, we'll need kind of a 'list of' pages. 

I think it's something we've to discuss Front and Back together.

**Comment by javitonino** [comment]
Some concerns that I raised, for discussion:

- URL generation is a complicated topic in CARTO. I would like to avoid replicating the behaviour in backend and frontend, because we are likely not to get it right on the first pass.
- We should avoid having to maintain a shared routes file between rails and JS is possible.
- Putting things in all presenter is also not great.

Something that @juanignaciosl mentioned, we can use relative URLs for a lot here, since those links are always to the same user. Although we may don't have the `base_url` for the viewed user here (as me returns the base_url for the logged user), we can obtain it from the window.location, and just link to the relative path.

🤔

**Comment by elenatorro** [comment]
We're currently using the ` window.location` in many places, and it's something that I'd like to avoid as much as we can. For instance, I'm doing so here to get the vizId:

https://github.com/CartoDB/cartodb/blob/daaa87cc525578693dbfb6213ca6521ca1d5dc27/lib/assets/javascripts/cartodb/helpers/map_options.js#L58-L66

I also did something *tricky* here: https://github.com/CartoDB/cartodb/blob/12867-static-public-maps/lib/assets/javascripts/cartodb/helpers/mapcard_preview.js

I'd like to find a good solution all together :) A reason to avoid these examples above is that it won't scale very well, and having lots of "api/vX/whatever" as strings all around the code makes me feel uncomfortable.

**Comment by javitonino** [comment]
> We're currently using the window.location in many places, and it's something that I'd like to avoid as much as we can.

I think that's unavoidable. I mean, if we want stateless static pages, they may have to load the basic information (identifiers) from the URL. The other option would be to load from the `/me` endpoint, but then, that endpoint has to receive the URL and do the same thing, so I don't see the advantage.

An idea to help with that would be to have different bootstrappers (one per URL) and include the URL parsing code there, but I don't know if that makes sense.

Anyway, back to my point. A good option to generate the URLs for public pages may be to do something like `extract_base_url(window.location) + '/viz/uuid/public_map`, where extract_base_url keeps the domain and the `/u/user/` part.

We could add the URLs to the visualization presenter, but there is a lot of sub-URLs there (like `/likes`, `/public_map`, etc.). So in order to avoid sending half a dozen URLs in each presentation (which seems overkill to me), I started to think about sending the base url for the visualization (user.carto.com/viz/uuid/`, and JS can concatenate the sub-urls to the end. But in that case, JS is already doing some URL generation, why not also port the `/viz/<uuid>` part to it?

**Comment by matallo** [comment]
not saying this is the solution, but surfacing another issue. I think there's a `cdb.config.get('base_url')` attribute in the cdb config object, that is used for url generation in several models, if any it should be addressed at that point and then pull from that single source of truth

**Comment by javitonino** [comment]
A little issue with that, is that there are multiple base_urls in public pages, so to speak. As the base url contains the org/user name, we have the base url for the logged in user, and the base url for the viewed user (visualization owner). URLs to go to the dashboard use the former, links to explore related maps, use the latter.

**Comment by elenatorro** [comment]
Closing it. The current solution is to handle this urls in each view, but having it in mind in order to find a better solution while developing the rest of static pages.
