### ISSUE TITLE
Are we tracking any of these already?

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#13008]
For our [engagement measurement system](https://github.com/CartoDB/design/issues/1003), we need to track several actions within Builder from Segment. Some are already being tracked. But we have doubts with the following ones:

- Add a second layer
- Add a third layer or more
- Download a layer
- Take a node out of a layer
- Change default geometry (size, color)
- Aggregate geometries
- Style by value
- Use of advance mode (Apply code in the SQL, CartoCSS or HTML editors) 

Are we tracking them? 

If not, we would need to add those missing events.

**Comment by rubenmoya** [comment]
As far as I know, we're not tracking them, so we have to add them, but I have one question, when should we send the event? For example, in the case of "Add a second layer" should I send it when the user clicks "Add", or when the server returns a "layer added correctly" response?

Another question I have is, what happens if users add a second layer, then they delete it, and add it again? We are going to send multiple "Add second layer" events, is this handled by Segment?

**Comment by msaenzde11** [comment]
Talking with @rubenmoya about this, names of events can be changed, just needed that they are understandable enough. 
* Suggestion: Make them in past tense: Eg: "Dragged layer", "Added layer", as current events are using this convention.

Also for repeating events (as "Added first layer", "Added a 2nd layer", etc) I would suggest adding instead an event like "Added layer" with fields as _vis_id_, _user_id_ and _layer_id_, so we can then track its usage and whether it is the second layer added, etc.

cc @arianaescobar @kevin-reilly @noguerol

**Comment by msaenzde11** [comment]
btw if you could ping me when this is ready that would be awesome, so we could discuss few more fields to add/remove (from the beginning) and be able to rock a lot!

**Comment by rubenmoya** [comment]
In the case of "Use of advance mode" we're only tracking CartoCSS with `Applied Cartoss` and SQL with `Applied sql`, what should we do for the HTML editors? Different events for each one like `Applied custom popup` and `Applied custom legend`?

**Comment by matallo** [comment]
waiting for more details before moving on

**Comment by arianaescobar** [comment]
Ideally, they should all count as "Use of advanced mode"... for the sake of this metric system.

**Comment by rubenmoya** [comment]
In that case, should we rename the ones we already have to `Use of advanced mode`, or send 2 events for the same action with different names?

**Comment by msaenzde11** [comment]
IMHO it'd be better creating two separated events, as although for the goal of this project they will both mean the same, ther're actually different behaviors. 

The other option would be creating an "Used Advanced Mode" Event, and added a field like `mode` which could be CartoCSS, SQL, Popup Legend... but I acutally like 1st approach more, as this would mean sharing fields that in specific cases would be None.

**Comment by arianaescobar** [comment]
Whatever @msaenzde11 thinks is best :)

**Comment by rubenmoya** [comment]
I changed it to `Used advanced mode`, it sends a type depending on the editor used (`sql|cartocss|popup|legend`).

You can check the rest of the events in the PR :)

**Comment by msaenzde11** [comment]
For the scope of this project I think it's nice! I don't know if you @arianaescobar or any other miss any field on this events that could be nice to have added so we deeper analyze users behaviour. For instance I thought that having `vis_id` (dataset/map id where it is applied) would be nice (eg: in case we wanted to get more knowledge on # of maps where cartocss is applied or something like that)

As well, talking with @rubenmoya we realized we are currently sending `Applied CartoCSS` and `Applied SQL` to Hubspot. Although these events are containing some more fields (as `layer_id`, `sql_query`, `dataset_id`, etc) I'm not sure Hubspot allows this deeper analysis. Just to leave it written because I didn't know it. :)

**Comment by arianaescobar** [comment]
Yes, I guess `vis_id` would be great to have. I just don't want to overcomplicate it.

**Comment by rubenmoya** [comment]
By default every event has `user_id` and `visualization_id`

**Comment by arianaescobar** [comment]
awesome :)

**Comment by msaenzde11** [comment]
Yep, I am very stupid lately... Thanks @rubenmoya. Last annoying thing: In order to be consistent with [other events in Segment](https://docs.google.com/a/cartodb.com/document/d/1AOdfVMbuXmmS1zhbDq8SxgiewyEGDU0evX1pf3JwQ8Q/edit?usp=sharing) could we rename `visualization_id` to `vis_id` and `Download layer` to `Downloaded layer`?

Maybe it's very stupid change but would keep same format as current events. Thanks and sorry for being the annoying one :sweat_smile: 

Rest LGTM

**Comment by rubenmoya** [comment]
To be honest I don't know, since it's the backend the one who send the events, let's ask @CartoDB/backend

**Comment by juanignaciosl** [comment]
Backend has always sent `vis_id`, I think that @msaenzde11 comment was about renaming the attribute from frontend.

**Comment by rubenmoya** [comment]
Ohhh, I see what happened here, it's just a misunderstanding. The events I wrote in the PR is the information we send to the backend, in frontend we send `visualization_id`, but when the event is sent to (in this case) segment there is a "transformation", you can check what the final keys will be here:

https://github.com/CartoDB/cartodb/blob/f5cc9dc61efc70faa4dbcd3a433e54f7ca66aff1/lib/carto/tracking/formats/segment.rb#L39-L54

**Comment by msaenzde11** [comment]
I see! Awesome, thanks a lot and sorry for driving you crazy :sweat_smile:
