### ISSUE TITLE
Improve geocode flow

### ISSUE THREAD

**Issue by urbanphes** [CartoDB/cartodb#13046]
### Context
Refer to this ticket 
https://github.com/CartoDB/design/issues/1032

**Comment by matallo** [comment]
back to development

**Comment by rjimenezda** [comment]
Documenting this because it's friday and we might forget. 

There are a few things missing

- [ ] When the geocoding analyses finishes correctly, navigate towards the style tab.
- [ ] When the geocoding finishes, view should re-render. You're currently locked out of the other tabs.
- [ ] We should remove a bunch of dead code that's around, like all the georeference placeholders that show on the other tabs.
- [ ] The current solution marks empty layers as layers that need georeferencing. This doesn't make sense, but on the layer list we don't know if a layer has any rows.

First 3 are most likely straightforward. Fourth one requires doing an arbitrary number of requests on the layer list view, for all layers that:

- Don't have a geocoding applied
- Don't have a geometry
- Don't have a custom query

Having no rows is the fourth condition that needs to pass, so we should fetch it if all of the above are true.

Bonus points: It would be interesting to know if users use the add empty dataset button often, and / or also what percentage of the datasets that users have without geometry are also datasets that have no rows.

**Comment by matallo** [comment]
I discussed this issue with design and they are already aware of the new states for the layers in the layers list. Feel free to ping them directly to ask for those new styles @rjimenezda 

/cc @urbanphes @piensaenpixel

**Comment by rjimenezda** [comment]
I already did the asynchronous loading, so I'm open to implementing a new style / add a transition or whatever for the layer component 🤗

**Comment by arianaescobar** [comment]
In case you'd like to track our work for that: https://github.com/CartoDB/design/issues/1074

**Comment by rjimenezda** [comment]
@urbanphes

There's a case that's not covered on the mocks. What happens if the user deletes the geocoding analysis? I see two options:

A) After it’s deleted, the user is immediately presented with an unsaved georeference analysis. This is what happens when the user clicks on the layer now.

B) There’s an intermediate step in which we tell the user: Hey, you have to georeference the layer, with a button that causes A)

`B)` is what we have on the analysis tab right now (for a non-geocoded layer), but with disabled tabs.

**Comment by urbanphes** [comment]
@rjimenezda In that case, I think we go with the **option A**. Our premise here is that the layer will be geocoded and the best way to gain this is with the _option A_.

**Comment by rjimenezda** [comment]
Here they are in motion, I like A because there are less steps and is consistent, but it might be a bit weird for the user?

This is option A):
![directly](https://user-images.githubusercontent.com/446970/33141582-e67b541e-cfb3-11e7-97d4-c0eab3cc03be.gif)

This is option B):
![intermideate](https://user-images.githubusercontent.com/446970/33141600-f106cb7a-cfb3-11e7-834d-f0143e8858fe.gif)
(please ignore the bug with the selected tab)

**Comment by rjimenezda** [comment]
I've uploaded this to ded15

**Comment by urbanphes** [comment]
I'm sorry for not answering before. This was talking between @rjimenezda and me, at last, we are going with the B Option, it's more natural.

**Comment by rjimenezda** [comment]
Acceptance on ded12:

I've left a map prepared with 3 layers there, on user ruben-ded12:
- An empty layer
- A Layer that needs geocoding
- A regular layer (airbnb listings)

Things to look out for:

- The empty layer and the layer that needs geocoding should show the new 'loading' state for a bit.
- When clicking on the layer that needs geocoding, only the analysis tab is enabled, already showing a geocoding analysis that can't be canceled.
- After applying this analyisis (for instance, geocode with coordinates, use cartodb_id for both lat/lon), it should redirect to the style tab. Tabs should be reenabled
- On the layer list, the layer should display as a regular layer now.
- Removing the geocoding analysis should show an intermediate step to let the user know that they should apply an analysis, which won't show if the user goes back to the layer list and back to the layer.

All of this new behavior should not affect regular layers & old behaviour.

**Comment by rjimenezda** [comment]
@urbanphes or someone from design, can you give it a try?

**Comment by rjimenezda** [comment]
While writing the above I noticed that I forgot to disable the add analysis button, so the user can change the analysis. I'll fix that at some point today, but I would appreciate if anyone can give it a look, since I have to switch back to this issue 💋

**Comment by urbanphes** [comment]
Hi @rjimenezda, I've tested the following steps:

- [x] The empty layer and the layer that needs geocoding should show the new 'loading' state for a bit.
- [x] When clicking on the layer that needs geocoding, only the analysis tab is enabled, already showing a geocoding analysis that can't be canceled.
- [x] After applying this analyisis (for instance, geocode with coordinates, use cartodb_id for both lat/lon), it should redirect to the style tab. Tabs should be reenabled
- [x] On the layer list, the layer should display as a regular layer now.
- [x] Removing the geocoding analysis should show an intermediate step to let the user know that they should apply an analysis, which won't show if the user goes back to the layer list and back to the layer.

... and the feature works well.

My only concern is when I've deleted the analysis, the following screen say something like this.

<img width="346" alt="captura de pantalla 2017-11-29 a las 16 31 28" src="https://user-images.githubusercontent.com/14546701/33383334-52bec538-d523-11e7-9118-6b4f9abc60b2.png">


At this point, I would remove the part " or manually add data to visualize" Because we look forward that the layer will be geocoding. But It will be great if anybody from @CartoDB/design can help us here.

**Comment by rjimenezda** [comment]
Truth be told, I didn't even read that copy, it's the same that we used to show on the other tabs. While it's techincally true, user could manually add geometry, I think it doesn't make any sense to show that there. I'll remove the 'add data' 👍  and also fix the bug that I mentioned before

**Comment by piensaenpixel** [comment]
What do you think something like? "There's no geometry in your data, please georeference it"

**Comment by rjimenezda** [comment]
@piensaenpixel @urbanphes What should I do with the add analysis button, on the horizontal list. It shouldn't do anything. Do we prefer removing it or adding a disabled state?

**Comment by piensaenpixel** [comment]
We are changing it, so the easiest thing for you

https://github.com/CartoDB/design/issues/1071

**Comment by urbanphes** [comment]
I don't know if the new add buttons (the ticket sharing https://github.com/CartoDB/design/issues/1071) will release this ticket. These are the examples:

**Current button:**

<img width="327" alt="captura de pantalla 2017-11-30 a las 8 12 29" src="https://user-images.githubusercontent.com/14546701/33418513-837e1cd6-d5a6-11e7-90d8-a3648a761481.png">

**New button:**

<img width="343" alt="captura de pantalla 2017-11-30 a las 8 12 52" src="https://user-images.githubusercontent.com/14546701/33418514-866f438e-d5a6-11e7-998c-c090d37186c2.png">


Apart from that, I think we can do:

- If the new buttons release after, we can disable the current button (blue box with "+") with a 24% opacity. The same that we use in all UI.
- If the new buttons release before; we can add the new buttons with the same disabled state: 24% opacity.


What do you think?

**Comment by rjimenezda** [comment]
I think this'll release before, hopefully today 🤔 

Since it was going to be changed at some point & @piensaenpixel gave me the choice, I removed the button completely. It's simpler than adding a new state to the button, because of how the code is

**Comment by rjimenezda** [comment]
@urbanphes On ded12 one more time, with the button gone in that particular case

**Comment by piensaenpixel** [comment]
I'm not sure if this is related to, but... in ded12 I only can geocode it with lat and long.

![image](https://user-images.githubusercontent.com/1214201/33486208-7acb85b6-d6a9-11e7-8ea9-5972759f769b.png)

**Comment by piensaenpixel** [comment]
Only one very small thing, if you think we can do it know ok, if not we can do it later: 

- [] To be consistent, could we put latitude and longitude in the same order?
![image](https://user-images.githubusercontent.com/1214201/33487711-6ea030d4-d6ae-11e7-8d70-62df247856d1.png)

**Comment by rjimenezda** [comment]
Label or controls?

**Comment by piensaenpixel** [comment]
y prefer the select (type)

**Comment by piensaenpixel** [comment]
The rest is ok!
