### ISSUE TITLE
csv table export not available for polygon datasets

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartodb#13196]
### Context
I'm not able to export datasets as CSVs if the table is made of polygons.

<img width="657" alt="screen shot 2017-12-07 at 12 04 30" src="https://user-images.githubusercontent.com/1041056/33727688-cfe6444a-db46-11e7-94e6-1f96b369d384.png">

### Steps to Reproduce

1. Open a table that's only polygons
2. Click 'export' in the dataset page
<img width="261" alt="screen shot 2017-12-07 at 12 05 19" src="https://user-images.githubusercontent.com/1041056/33727917-ebb2ebd8-db46-11e7-9aa1-11312a9407e4.png">
3. Notice that the CSV option is greyed out / not selectable

### Current Result
Cannot export datasets to CSVs in the dashboard. There is no reason given for it not being available either.

### Expected result
Datasets should be exportable as CSVs

### Browser and version
macOS Sierra, Firefox 57.0

### .carto file
Not a map, but a sample dataset is here: https://team.carto.com/u/eschbacher/dataset/brooklyn_poverty

### Additional info
Export as CSV works through the SQL API if `format=csv` is passed

cc @stuartlynn

**Comment by ramiroaznar** [comment]
Duplicated: 
https://github.com/CartoDB/support/issues/1106 
https://github.com/CartoDB/support/issues/1052
https://github.com/CartoDB/support/issues/1023

Explanation about why we remove the `.csv` option [here](https://github.com/CartoDB/cartodb/issues/9855). Also, when customer opened the csv in Excel some of the geometry values were cut off.

IMO we could roll back because we made [a proper fix for that](https://github.com/CartoDB/cartodb/issues/12022). 

@jorgesancha @noguerol IMO and based on several Support, Customer Success and Research tickets (like this one), we should allow users to download line/polygon data as csv as well.

**Comment by jesusbotella** [comment]
Shipped 🚀

**Comment by ramiroaznar** [comment]
:boom:

**Comment by andy-esch** [comment]
Thank you!!
