### ISSUE TITLE
Only one type of widget is available

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#13285]
With this .carto file

[Elecciones Cataluñas 21D (on 2017-12-23 at 18.33.21).carto.zip](https://github.com/CartoDB/cartodb/files/1584363/Elecciones.Catalunas.21D.on.2017-12-23.at.18.33.21.carto.zip)

 if i try to add a widget there is only one time-series available
![image](https://user-images.githubusercontent.com/1214201/34321863-6e74c860-e818-11e7-9c36-99328b98b304.png)

**Comment by ramiroaznar** [comment]
We need STR because it looks like the issue is related to the layer nodes. I was not able to replicate the issue replicating your map from the ground up:

![image](https://user-images.githubusercontent.com/5215798/34481424-5f904922-efb2-11e7-8a50-37e16be529a3.png)

![image](https://user-images.githubusercontent.com/5215798/34481432-6c8bef6e-efb2-11e7-8c36-495df3ad3e5d.png)

Do notice that the layer nodes are different (I suppose you change or remove layers during the map creation process).
