### ISSUE TITLE
Disable following analysis steps

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#13311]
To avoid confusion when the analysis is sequential we are going to disable the next step until the previous one is filled.

cc @alonsogarciapablo @inigomedina @matallo 

Related -https://github.com/CartoDB/design/issues/1113
Invision - https://invis.io/HFF50XBE7

**Comment by rjimenezda** [comment]
@CartoDB/design 

Some analyses have multiple steps, but a second step does not depend at all on what you input on the first one. 

For instance: 

Centroid
![image](https://user-images.githubusercontent.com/446970/34868238-61ec4508-f783-11e7-97be-847a4c5bc07b.png)

Group points into polygons
![screen shot 2018-01-12 at 10 35 58](https://user-images.githubusercontent.com/446970/34868525-67d2740a-f784-11e7-9c12-7b24644d04c1.png)

Also, there are some analyses that have steps that require no input, so maybe not a step after all:

![screen shot 2018-01-12 at 10 41 16](https://user-images.githubusercontent.com/446970/34868774-2c8096a6-f785-11e7-9ad5-f881a5edd3c7.png)

I guess it makes no sense to gray out anything on these cases.

I just wanted to point it out because I was going through all analyses to consider which were affected, and it might be a good idea to reconsider how we display these.

**Comment by arianaescobar** [comment]
Yes! We shouldn't disable those steps in those cases. 

Regarding the last one (and also: the "Create areas of influence" and "Detect outliers and clusters" analyses), our idea is to merge both steps so it's only one. If you could do that with this ticket, awesome, if not, we'll open a new ticket for it :)

**Comment by rjimenezda** [comment]
Like this?

![image](https://user-images.githubusercontent.com/446970/34872911-28bac6aa-f793-11e7-8190-dcd719d9ea30.png)

No problem, it's easy enough 👍

**Comment by arianaescobar** [comment]
yaaaaaaasssssssss 💖

**Comment by rjimenezda** [comment]
Shipped 🚢
