### ISSUE TITLE
Inconsistent style in infoboxes

### ISSUE THREAD

**Issue by rubenmoya** [CartoDB/cartodb#13355]
### Context
We're using two different styles for the infoboxes in advanced mode:

![screen shot 2018-01-09 at 10 56 29](https://user-images.githubusercontent.com/905225/34720443-066bfffc-f53f-11e7-8661-f83a48f82010.png)

![screen shot 2018-01-09 at 10 56 47](https://user-images.githubusercontent.com/905225/34720444-068620b2-f53f-11e7-80ce-cc07be72f1d9.png)

### Current result
Some infoboxes are using the correct styles, some of them are using the wrong ones.

### Expected result
All of them follow the style guide.
![screen shot 2018-01-09 at 13 15 44](https://user-images.githubusercontent.com/905225/34720504-3bbcdbc2-f53f-11e7-9f98-cd5816e269f7.png)

### Additional info
I'm guessing the problem is one of the infoboxes is shown ONLY in advanced mode, and the other one is shared between advanced and normal modes.

**Comment by Jesus89** [comment]
Yes. There is only one case: when you apply a CartoCSS style it keeps the advanced mode because. So if you go back to the layer list and hide the layer, after entering again in the layer, the `Layer hidden` notification will be shown in all the tabs (and also in the Style tab with advanced mode).

The best solution for me is to update this notification style to the mode of the selected panel (in this case the mode of the style panel).

**Comment by Jesus89** [comment]
Done in CartoDB/cartodb#14349
