### ISSUE TITLE
Hover popups do not disappear after mouse leaves

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartodb#13387]
### Context
Hover popups in Builder are still visible when the mouse leaves the marker. 

### Steps to Reproduce

1. Open any map with data.
2. Hover a marker -> a popup should appear.
3. Move the mouse to a different part of the map without any marker.
4. The popup does not disappear.

### Current Result
![more_popup_hover](https://user-images.githubusercontent.com/3824953/34933038-adda18a6-f9d5-11e7-941c-c082db86c0a7.gif)

### Expected result
Popup must disappear when mouse leaves.

**Comment by ramiroaznar** [comment]
This is a vector related bug and AFAIK we do not have a proper solution for solving this. cc @dv343 if the user complains we can move him/her to raster.

**Comment by dv343** [comment]
We are dropping support for Tangram. Therefore, it doesn't make sense to waste time fixing it, we should move everyone with problems to raster, since we are going to move everyone to raster soon anyway.

Since @elenatorro reported it and the client didn't and since it seems that it is a problem with all vector maps we probably can ignore this.
