### ISSUE TITLE
cartodb:db:load_functions : multi-threading option is buggy

### ISSUE THREAD

**Issue by vmanohar1** [CartoDB/cartodb#13433]
### Context
When attempting to parallel process [if you have many users, it can help!]

### Steps to Reproduce
Using 15 threads in this case (from cartodb directory) -
bundle exec rake cartodb:db:load_functions[localhost,0.18.5,15,0.25,1,180000]

### Current Result
Look into log/rake_db_maintenance_cartodb:db:load_functions_localhost.log --
I see some exceptions as -
[2018-01-22 09:52:38 -0500] FAIL user1           (132 /309 ) PG::Error: ERROR:  tuple concurrently updated
...
[2018-01-22 09:52:38 -0500] FAIL user10            (132 /309 ) PG::Error: ERROR:  tuple concurrently updated
...

### Expected result
No failures should be there in log/rake_db_maintenance_cartodb:db:load_functions_localhost.log

### Browser and version
Unrelated to browser! It is rake task execution using multiple threads related issue

### .carto file
unrelated

### Additional info
It should help complete execution of this rake task faster when you have many users in the environment under consideration..

**Comment by gfiorav** [comment]
Hey @ramiroaznar , this issue is quite important for Bloomberg. Do you think we could get someone from Infrastructure to weigh in?

Thanks!

**Comment by ramiroaznar** [comment]
@antoniocarlon can you have a look at this one?

**Comment by alrocar** [comment]
Thanks for reporting.

We've been taking a look and the issue comes when running the task in multi-threading mode for organizations. This is because the users of the same organization share the same database, thus there can be concurrency problems when creating the extensions.

Indeed the task is being executed several times per organization database while it should be enough being executed once. Feel free to send a PR if you feel this can be enhanced.

We are updating our UPGRADE guide to point to a different rake [upgrade_postgres_extension](https://github.com/CartoDB/cartodb/blob/master/UPGRADE#L12) which should be the one to be used (_this one does not support multi-threading though_).
