### ISSUE TITLE
Modify color ramp in style by value is broken

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#13537]
![image](https://user-images.githubusercontent.com/1214201/36066956-e04ba49c-0eb3-11e8-86d8-886d61de75c8.png)

cc @alonsogarciapablo @oriolbx

**Comment by jesusbotella** [comment]
Going go fix this along with #9002, as it is closely related to that issue.

**Comment by jesusbotella** [comment]
@piensaenpixel What do you prefer, to apply an ellipsis when it takes more than the assigned space or the text breaking into two lines like below?

![screen shot 2018-02-12 at 16 02 34](https://user-images.githubusercontent.com/4319728/36103013-5af8630a-100e-11e8-9479-473afebb783a.png)

We need to take into account that because of the maximum width and the margins on the dropdown there is not so much space available to put the label when it is too long.

**Comment by piensaenpixel** [comment]
+1 to ellipsis and we make hover on it we can show a tooltip

**Comment by alonsogarciapablo** [comment]
@jesusbotella are we finally fixing this? If so, let's please add it to the RT project so that we can track it. Thanks!

**Comment by jesusbotella** [comment]
Yes, I am working on it, almost done. I asked @piensaenpixel if the tooltip is actually needed because we have the attribute title in the view before the color picker.

**Comment by alonsogarciapablo** [comment]
Perfect! Thanks @jesusbotella! 🔝

**Comment by ramiroaznar** [comment]
![image](https://user-images.githubusercontent.com/5215798/36389215-abda8a2e-159e-11e8-8820-b688c03d8104.png)

LGTM!

**Comment by matallo** [comment]
in production!
