### ISSUE TITLE
Automatic geocoding with California and coordinates is off

### ISSUE THREAD

**Issue by jaakla** [CartoDB/cartodb#13779]
Imported CSV dataset finds a field which has namedplaces, and all the rows in the table happen to have "California" there.  Two issues here really:
1) It geocodes (using internal geocoder I guess) the location to completely wrong "California" somewhere in New England:
<img width="819" alt="screenshot 2018-03-31 13 20 31" src="https://user-images.githubusercontent.com/5609650/38162386-03b8a474-34e9-11e8-8723-31f181640451.png">

2) guessing of the column  (in import log: `2018-03-31 10:19:00 UTC: Found namedplace column: {:column_name=>"gmaps_region", :data_type=>"character varying"}` is not optimal for specific dataset, as the dataset has latitude and longitude columns also (named client_latitude, client_longitude, server_latitude, server_longitude), and I would imagine one of these pairs to have higher priority than any textual field. It seems that imported does not even try to find them, it only tries some fixed simpler lat/long fields as OGR parameter?

Data is in account 'jaakl', import ID 4bb2245a-0196-42fa-9c45-081b90eb9209 for example.

**Comment by ramiroaznar** [comment]
Hey, @jaakla good catch! BUILDER city geocoding analysis uses first Mapbox, and then the internal one. Don't know if the behavior is the same with imports. Can you have a look? @javitonino

**Comment by jaakla** [comment]
This issue came from the automatic import geocoding. I did not try geocoder analysis with this field, as this does not really make sense here, as there are already client_latitude and client_longitude columns as given in second issue. 

Mapbox direct geocoder for "California" - https://api.mapbox.com/geocoding/v5/mapbox.places-permanent/California.json?access_token=pk.eyJ1IjoiY2FydG8tYml6LW9wcyIsImEiOiJjamNjbGk5cW0xN2J2MndwNWdrcWdvZXA0In0.v-cmdvJ7OADDPTi2nrSkKg&limit=1 seems to give California state as first response, and this makes sense. Tried this in mapbox [api-playground](https://www.mapbox.com/api-playground/#/forward-geocoding)

**Comment by javitonino** [comment]
1) Automatic geocodings are done with the internal geocoder only. Since it's automatic, we don't want to use the users credits. And yes, it's not great in some cases, since it's hard to know which named place is more important.
2) We detect the following latitude column names: `latitude lat latitudedecimal latitud lati decimallatitude decimallat point_latitude`. Yes, we delegate this to ogr2ogr with this list of names. It's hard to autodetect latitude/longitude without looking at the name (since there are a lot of numbers in similar ranges).

Best I can come up with would be to do a second pass during content guesser with some regex looking for latitude/longitude. Still, all of this is very prone to error, so I'm really not sure if it's worth the effort to support all these cases. The workaround is as easy as naming your columns latitude and longitude.

So, this is working as expected. I would say that if we want to improve this, we should gather some data first, rather than just adding support for each special case we encounter.

**Comment by ramiroaznar** [comment]
> So, this is working as expected.
Closing then.
