### ISSUE TITLE
Auth API: block master API key access in SQL/Maps API

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#13919]
Now that is possible to use different API keys, it would be nice to limit the potential use of your master API key for your end-user applications.

If you could block your master API key to be used in SQL API and Maps API, you could not start developing a new application using your master API key. Forcing you to create a new regular API key with the adequate permissions. Your application won't work without that step, this will prevent leaking the master API key.

**Comment by inigomedina** [comment]
Yes, we have seen this possible feature request through different conversations with clients: the concern about a misuse of the master API key.

@enekid from the perspective you have after participating in the design and implementation of the entire auth system, how do you see this? Do you think it's something that we can tackle (taking into account the legacy)?

**Comment by enekid** [comment]
We could start by creating a new type of API key that only grants access to the `Auth API`.

Something like:

```json
"grants": [
   {
      "type": "apis",
      "apis": [
            "auth"
      ]
  },
]
``` 

In order to prevent the creation of *master-like* API keys, this `auth` option should be exclusive (no `maps`or `sql`allowed). You should **not** be able to set it like: 

```json
"grants": [
   {
      "type": "apis",
      "apis": [
            "auth",
            "maps"
      ]
  },
]
``` 

OTOH I don't know if it will be possible to deny access to Maps and SQL APIs when using the `master` API key. -> Doesn't Builder make use of this API key?
