### ISSUE TITLE
Filter most recent files in GDrive, Box and Dropbox connectors

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/cartodb#14118]
### Context

* [GIS SE question](https://gis.stackexchange.com/questions/287583/syncing-to-a-box-file-via-carto).

### Steps to Reproduce

1. Go to your dataset dashboard
2. Click on New dataset
3. Click on Box

### Current Result

* A maximum number of 200 files are shown.

### Expected result

* Users should be able to see the 200 most recent files.

### Browser and version
* Any.

### .carto file

* Not needed.

### Additional info

* Related to https://github.com/CartoDB/cartodb/issues/13259

cc @alrocar 

@javitonino what do you think?

**Comment by javitonino** [comment]
Box API does not support ordering: https://developer.box.com/reference#searching-for-content and the maximum page limit is 200 items.

Our only alternative would be to retrieve the entire list of files, and then order them in our end (or just display everything as it comes). The tradeoff is that it could be very slow, depending on the amount of files by the user.

Since this is not a quick solution, I'd rather do this well, and implement some search/browse functionality.
