### ISSUE TITLE
Random message when styling by value

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/cartodb#14129]
### Context

![image](https://user-images.githubusercontent.com/1078228/42159496-4741eeae-7df4-11e8-839b-b95b62c4b2be.png)

When styling by value, the list of ramp options is not filled properly sometimes. It's random, it doesn't happen all the time.

### Steps to Reproduce

- Style by value
- Select a column
- Color ramps are not filled.

### .carto file
[bicimad.zip](https://github.com/CartoDB/cartodb/files/2154847/bicimad.zip) <- Rename to bicimad.carto

Select column `begin`. It happens more frequently with that column.

**Comment by VictorVelarde** [comment]
This is a problem on **string fields having just one value** in the whole column domain (e.g. all rows with empty strings).

In the bicimap dataset, it manifests the first time that such a column (e.g. *begin*, but also *draworder*, *_end*...) is used in a `Polygon color by value` visualization.

After using another column (successful in getting some ramps), there is some *"sort of internal fallback"* that can give the randomness behaviour, but the problem is clear: "builder can't find a suitable color ramp for just one value, as the minimum number of colors is 3" [we are using `cartocolor` ramps here].

As getting some ramps seems good enough, I'm creating a quick fix with this https://github.com/CartoDB/cartodb/pull/14132

**Comment by ramiroaznar** [comment]
@VictorVelarde could we hide those (one category or empty values) columns as we do with the numeric ones?

**Comment by ivanmalagon** [comment]
I'm not sure about this but I bet that we don't know in advance how many different values a row has. We query it once we've selected the column. So we can't hide those columns.

Correct if I'm wrong @VictorVelarde
