### ISSUE TITLE
Org user can't be deleted if it has non-cartodbfied tables in their schema

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#14288]
Related https://github.com/CartoDB/support/issues/1742

An organizational user can't be deleted if the user has tables in their schema.

Rollbar error: https://rollbar.com/carto/CartoDB/items/23564/

**Comment by javitonino** [comment]
This is a "feature". We decided to go this way because we cannot know if non-cartodbfied tables are in use in maps, shared, etc. We also assumed that if a user is savvy enough to create tables manually, he should be savvy enough to delete them. That was the reasoning at the time to keep it like this, we may want to reconsider, specially in the context of the new dashboard.

**Comment by ethervoid** [comment]
Closing then
