### ISSUE TITLE
[Dashboard] [Maps] Persist current filters and ordering in URL

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14385]
To be done after https://github.com/CartoDB/cartodb/issues/14317 and https://github.com/CartoDB/cartodb/issues/14316 are completed.

Tasks:

- [x] When a user filters the list of maps, the current filter must be persisted in the URL (as a "directory")
- [ ] When a user orders the list of maps, the active ordering must be persisted in the URL (as a parameter).
- [ ] When a users pastes a URL with filter and ordering, the list of map is filtered and ordered correctly.

cc: @jesusbotella

**Comment by jesusbotella** [comment]
I have setup the filters URLS, and they are this ones:

Your Maps: `/dashboard/maps` / `/dashboard/mine`
Shared: `/dashboard/maps/shared`
Favorited: `/dashboard/maps/favorited`
Public: `/dashboard/maps/public`
Private: `/dashboard/maps/private`
Link: `/dashboard/maps/link`
Password: `/dashboard/maps/password`

And page is persisted in the URL Query Parameters, like: `/dashboard/maps/favorited?page=2`

Ordering is not ready yet because it's not ready in the API, but it can be configured with no effort whenever it's ready :)

**Comment by alonsogarciapablo** [comment]
Looks (and works) great @jesusbotella! 👏
