### ISSUE TITLE
[Dashboard] Include link to feedback form

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14410]
I created a form so that whoever is seeing the New Dashboard can submit feedback (ideas, suggestions, bugs, rants...). We can include some sort of button, so that people can submit feedback. Unless @kukukaka has a better suggestion, we can use something like the icon we have in the Developer Center now:

![image](https://user-images.githubusercontent.com/390398/48129466-debb1680-e289-11e8-9016-e1681e6f6e09.png)

Whoever works on this, please ping me and I will send you the URL of the form.

**Comment by kukukaka** [comment]
Hi!

A couple of random thoughts about this. 

We need to decide which kind of feedback we want to get from this. If we are going to ask for feedback we need to be able to commit to that feedback and be transparent about it. There is nothing more frustrating than making the effort to write to someone and not listening back (I think we had something like this in the dev center and nobody is answering?). 
Also, we  already have a huge backlog of things that need to be done, so we need to now how this is going to work with our roadmap. We probably don't want to ask for ideas if we are not going to have resources in the next months because there are things we must do before.

Other point is that we need to be clear about the communication options we are giving to the user. Should this not be handled by support? Is it clear for the user when she needs to use the support link, the contact administrator one, or this one? Is it better to have just one pipeline or different ones with different interactions in different places? 

And about the design I'm not a big fan of having a bright floating button always on screen. It would look like the most important thing you can do in the dashboard, and it's not. Usually this kind of "feedback" CTAs have a poor conversion (not much quality feedback) and even poorer maintenance . I could understand using them in marketing sites where conversion is king, but not in transactional sites where the user has better things to do. If we add something I'll suggest this action to be much more subtle and be close to the support entry points to be clear of the purpose of each one.  

P.S. I'm also slightly concerned about releasing our shinny new dashboard and using a Google Form to gather feedback. I understand it during a beta phase, but not for GA release.

**Comment by alonsogarciapablo** [comment]
Great points @kukukaka. I can't agree with you more. I didn't explained myself very clearly 😞.

My idea is to provide a way to submit feedback to the (internal) people "dogfooding" the New Dashboard, while it's being developed. For instance, anyone testing it in Staging, or in Production if we let some people opt-in to become beta-testers.

> P.S. I'm also slightly concerned about releasing our shinny new dashboard and using a Google Form to gather feedback. I understand it during a beta phase, but not for GA release.

Basically ☝️ THIS.

Once we put it out there for everyone we should think about channeling feedback in a more standard and classy way :)

The transparency part that you mentioned is important. A form is a one-way communication channel, unless we collect email addresses and somehow reply back. Another option are Github issues, where we can interact more with the person that opens an issue. @kukukaka do you have any other ideas?

**Comment by kukukaka** [comment]
Cool! Sorry for the misunderstanding :)

**Comment by alonsogarciapablo** [comment]
> I'm missing the form screen but we can redirect the user to an external form (I think Pablo already did that one) or build our own feedback page (a simple form).

Let's start by linking to [this form](https://docs.google.com/forms/d/e/1FAIpQLScBQUWd-TP3Qy514DOCNg-KoLrViHijUR5giLAMS-3jmDnrPg/viewform) so that we can start to gather feedback internally ASAP. We can iterate later and implement the form, etc.

**Comment by alonsogarciapablo** [comment]
Closing in favor of https://github.com/CartoDB/product/issues/222.
