### ISSUE TITLE
[Dashboard] Limit access to the dashboard when the 30-day trial ends

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#14440]
Users who signed-up for a 30 day trial should have limited access to CARTO (eg: they shouldn't be able to manage their maps/datasets, etc.). When their trials have expired, the new dashboard should _kindly_ let them know about this by:

1. Saying "Thank you" to them for taking the time to give CARTO a try.
2. Letting them know what's the status of things and will happen next if they don't upgrade (eg: your maps and datasets are still there and you have X days to recover them.). We could point them to an entry in the Help Center explaining this.
3. Giving them some reasons to upgrade.
4. Giving them clear instructions to upgrade or cancel the account.

This is what we have right now:

![screen shot 2018-03-19 at 11 54 12](https://user-images.githubusercontent.com/390398/48551153-fec78700-e8d4-11e8-9c5b-231d99c8fc6b.png)

cc: @jorgesancha @inigomedina @kukukaka

**Comment by inigomedina** [comment]
I believe that we must treat the  "expiration workflow" as something specific and fundamental. I assume we are here focusing on UI workflow, and thus not talking about email workflow although we all know that in this particular case (signups, trials, etc.) it plays a critical role on people experience. So, let us not miss it.

Well, focusing on the UI, I don't see the benefits of using a modal window in this case. If we accept my guiding principle (above), the expiration workflow demands a specific screen: enough room to clearly convey the goals @alonsogarciapablo mentioned, enough room to give main and secondary actions.

If I put the ink on the paper, I see something like this

![img_2876](https://user-images.githubusercontent.com/856319/48553753-be6c0700-e8dc-11e8-8b3d-2ed7d5e1b4ba.jpg)

That's it, a screen that clearly says to me:
1. I cannot use CARTO anymore (apart from this screen, I don't see anything else)
2. Since when I cannot use CARTO anymore.
3. My things are safe, so I can recover them.
4. I can easily upgrade clicking on the main button.
5. I also can make some secondary actions (export?, contact, cancel)

Regarding the last point, "export" would be a nice feature, one that builds confidence and trus. We still don't have a contact workflow for CARTO (I'm pushing it on our what's next spreadsheet), but we now have the Help Center and it would work as a good addition. And "cancel" should also be a clear workflow, similar to this one with its specific screen, clear communication, etc.

**Comment by kukukaka** [comment]
We can reuse the welcome module and remove the rest of the modules (I would prefer to create an inactive state and keep the modules) and navigation if we want to block the map and dataset management.

**Comment by alonsogarciapablo** [comment]
As part of this issue, we could tackle a really common issue with students. Many of them sign up for the 30-day trial period, probably because they visit https://carto.com/signup directly. When their trial period ends, they are prompted to enter a payment method, but they are students so they are eligible for a student account. It'd be nice to solve the root of this problem, but we can also let students know how they can solve this. Right now support handles this manually (cc: @jsanz).

**Comment by alonsogarciapablo** [comment]
[This SB ticket](https://cartodb.supportbee.com/tickets/19881700) is a classic example of a request from a student that signed up for a 30-day trial instead of using the Github Student Developer Pack.

**Comment by alonsogarciapablo** [comment]
If the account is still not locked:

![screenshot 2018-12-05 at 13 20 07](https://user-images.githubusercontent.com/390398/49513250-a6125b00-f890-11e8-86fb-10fe1d2c20f9.png)

Actions:

1. Contact sales.
2. Add payment method.
3. Delete account.

![image](https://user-images.githubusercontent.com/390398/49513165-5e8bcf00-f890-11e8-88be-18d227d59b98.png)

And then, once the account is locked:

![image](https://user-images.githubusercontent.com/390398/49513285-d1954580-f890-11e8-9107-d3e0f8306bc1.png)

Actions:
1. Contact sales.
2. Delete account.

**Comment by jesusbotella** [comment]
I was revisiting this issue now that we started to develop it, and I have one concern about this view.

Right now, Backend is the one that decides to render one page or another when it comes to locked accounts. I've thought of moving that logic to Frontend, but it has one major problem.

One "smart" user will be able to access the rest of the pages in the dashboard by making some changes within the first 41 days when the account has not been deleted yet. I assume that we are not OK with that. Why would that happen?

If we move that logic to the Frontend part, JS code will determine which page is the one to be loaded and that code can be tweaked. It might not be that easy but if any of our users is smart enough, they will be able to use dashboard 41 more than expected.

So the solution I propose is to create another separated bundle containing this page only, so that users cannot access this page even if they make those "smart" changes. So that RoR renders that lockout page, will be included within the new dashboard source code, but the code that loads the page doesn't know anything about those other pages.

It might a take more time (not that much) but I think it is worth. What do you think?

**Comment by jesusbotella** [comment]
After talking with @albertoac, I noticed that we're doing the same troublesome behaviour within the static pages.

So the question now is, do we want to potentially allow users to access the dashboard by changing logic in JS code at runtime (i.e. accessing carto.com dashboard)?

**Comment by kukukaka** [comment]
Leaving here the designs for future reference:

https://invis.io/J7OPHL18HUR#/336549682__73_Trial_-_Expired

**Comment by jesusbotella** [comment]
Merged!

**Comment by alonsogarciapablo** [comment]
OLE! 👏
