### ISSUE TITLE
Frontend redirects to dashboard on SQL API error

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#14543]
### Steps to Reproduce
1. Got to a dataset view, open the SQL panel
2. Insert a SQL query that will produce an error. e.g: `CREATE ROLE wadus`
3. Click apply

### Current Result
You are redirected to login (and then automatically back to dasboard)

### Expected result
An error is displayed in the SQL panel

### Additional info
This is probably related to the request interceptor: https://github.com/CartoDB/cartodb/pull/13988
We should review all uses of SQL API and Maps API (tiler). Since those are authenticated by API key, we probably want to ignore those APIs for the interceptor.

cc @CartoDB/rt-managers (already added to the RT board)

**Comment by jesusbotella** [comment]
Yes, that was caused by the network interceptor. Previous to the MFA changes, we had a check to be sure that the error that redirected to the login was the `session_expired` one. But now, whenever an error comes to the interceptor, we redirect the user to `/login` no matter what.

So, to fix that, I check that the error that comes is well-known, and if it's not we don't redirect the user.

**Comment by ramiroaznar** [comment]
LGTM!
