### ISSUE TITLE
Analysis API grants

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartodb#14737]
We'll need new [API grants](https://github.com/CartoDB/cartodb/blob/1b5953d4ba2d1d6c66bf13aecdf38ac8367222f9/app/models/carto/api_key.rb#L55-L66) for the Analysis API.

Actually I think we need three different grants for it:
* Authoring grant to access endpoints to register new analyses
* User grant to use existing analyses
* ~~Trigger grant to access internal endpoint to trigger analyses (we could also discuss alternatives to this third AA grant)~~ [I agree this wasn't a good idea: users don't trigger analyses, this is only internal]

@javitonino we'll need your expert advice on this

**Comment by rafatower** [comment]
> Trigger grant to access internal endpoint to trigger analyses (we could also discuss alternatives to this third AA grant)

To make sure what comes from TIS actually comes from TIS? will you want to grant or revoke to arbitrary users.

**Comment by rafatower** [comment]
> User grant to use existing analyses

think about granularity of this and where to manage/store it

**Comment by jgoizueta** [comment]
I've realized that I was missing something:
I'm working on adding API Key grants for the Analysis API, and that should be enough to get us started with using some analysis for team, but we'll need some means to enable the feature to users, like we do now for Builder or Engine, so that those users master keys have the grants, and can assign them to the keys they create.

**Comment by javitonino** [comment]
Oh, I didn't know you were thinking of implementing this so soon. I have some concerns (related to other ongoing projects), in short: if you need to CREATE/ALTER tables you may be out of luck with regular keys. And if we are going to use the master key for now, I don't think we should worry about implementing the grants at this point, I'd wait until OAuth/Auth API is a bit more mature, since there are changes in the horizon that may affect this.

**Comment by jgoizueta** [comment]
I agree to wait till OAuth/Auth API advances in that sense.
