### ISSUE TITLE
Review TrackJS 

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/cartodb#14895]
### Context

Related with https://github.com/CartoDB/cartodb/issues/14890 & https://github.com/CartoDB/cartodb/pull/14894

We've to monitorize if the current changes in TrackJS are working for us. 

## Steps to Reproduce

* Log in in TrackJS (LastPass - Frontend)
* Check logs since https://github.com/CartoDB/cartodb/pull/14894 was merged

**Comment by csubira** [comment]
The final changes about TrackJS configuration were merged the 7th of June in https://github.com/CartoDB/cartodb/issues/14890 via loading Track.js 20% of the time on embeds.
Since then, the errors in Builder Embeds and CartoDB embeds have been tracked. The following table sums up the most important figures:

<img width="438" alt="Screen Shot 2019-06-17 at 10 48 19" src="https://user-images.githubusercontent.com/26403479/59591834-0b23f480-90ef-11e9-8beb-df091ec8bd09.png">
And the following screenshots from TrackJS dashboard show the whole picture:

- Builder Embeds:
![Screen Shot 2019-06-17 at 10 53 47](https://user-images.githubusercontent.com/26403479/59591926-47575500-90ef-11e9-9df5-a68f7c4d0a6c.png)
- CartoDB Embeds
![Screen Shot 2019-06-17 at 10 53 23](https://user-images.githubusercontent.com/26403479/59591888-2bec4a00-90ef-11e9-8f5e-42f74a169252.png)

The figures confirm that the load has been decreased to the desired 20% and working below the quota limit.
