### ISSUE TITLE
'email_address' gem behaves inconsistently for MX validation

### ISSUE THREAD

**Issue by nballenger** [CartoDB/cartodb#15056]
In f702e42da4eeab75298a55dad3354998fb898f60, the `email_address` gem got added to do additional email validation. You may want to rethink using that library--it returns inconsistent validation results based on network status. If you have an outbound network failure or timeout during validation, it rejects the address as invalid based on the MX being absent or misconfigured, rather than raising a warning about being unable to request DNS records. It also behaves strangely once connectivity is restored, reporting valid domains as rejected because `"This domain is not configured to accept email"`.

See the following issue for details/repro: https://github.com/afair/email_address/issues/43

If you want to use the gem, you should probably turn off MX validation until that issue is resolved. It's on by default, so you would have to use:

```
EmailAddress::Config.configure(host_validation: :syntax)
```

somewhere in the code (currently that only happens in the specs).

@gonzaloriestra, @ethervoid

**Comment by gonzaloriestra** [comment]
Hi @nballenger,

Thanks for reporting it. We added the MX validation to avoid syncing problems with Hubspot, which seems to have a similar validation. Also, we ensure it raises an error with typos like `@gmali.com`. 

Maybe we could get rid of this validation by sending a confirmation email instead, but for now, I think it's not a big issue, because if the server loses connectivity, this would be the least of the troubles.

Anyway, we'll watch the gem to update it if they fix it.
