### ISSUE TITLE
[OAuth] New scope `datasets:r:*`

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/cartodb#15130]
### Context
In the context of external apps integration, we've found the need of a coarse-grained scope related to datasets, to have a fluid UX

After some conversations between @rjimenezda and @alrocar, the decision was to implement: `datasets:r:*` --> it will allow to read all datasets in the user account.

See https://github.com/CartoDB/kepler.gl/issues/16 for more context

**Comment by gonzaloriestra** [comment]
What about if we add `schemas:r` instead? It would be easier for us, but also more natural in my opinion. @alrocar?

**Comment by alrocar** [comment]
Let's clarify first the convenience of having that scope for potentially any app requesting permissions to read any data from a user account. 

Ideally we talked about supporting some kind of mechanism to not grant read access over the whole user schema. Not sure if we want to consider an approach like this.

On the other hand, `schemas:r` looks like the most straight forward way of solving the issue, but I'd consider this scope to be restricted just for certain applications. The reason is we would be giving apps the ability to read the contents of datasets (existing or newly created) that the user might want to be private.

I've seen [Google Drive has `Restricted` scopes](https://developers.google.com/drive/api/v2/about-auth). Apps that want to request that scope need to pass a security assessment.

Thoughts about this?

1. Think on a different approach?
2. Allow `schemas:r` but restricted for certain apps (and properly documented it).

**Comment by gonzaloriestra** [comment]
After discussing with @alrocar, we have 4 alternatives:
1. Initial plan: unrestricted access to read all datasets.
2. Restrict access like Drive. It would require us to manually enable each app to be able to use this new scope.
3. Filter by regular expressions.
4. Filter by tags.

We would prefer to avoid 1), as the user wouldn't have a way to limit access to other apps, and they could even read stuff from other apps. If we really need to allow reading anything, we prefer option 2.

The solution we like the most is 4), but only cartodbfied tables can have tags. The number 3 seems a bit complicated (we would need to add another trigger for the tables to check each regular expression), but it could work with non-cartodbfied tables.

Also, allowing access to non-cartodbfied tables sounds a bit unsafe because there could be some "hidden" tables that users usually don't know about (like the ones used for analyses).

**Comment by VictorVelarde** [comment]
Then it looks like option 2 could be the best one, cause we do need to deal with non-cartodbfied tables.

In the short term, only this kepler app will be enabled. And probably the next ones will be from our side, so I don't see a big problem in manually enabling apps.

**Comment by VictorVelarde** [comment]
Hopefully these have just been implemented (`datasets:r:*`). Thx @amiedes !

**Comment by rjimenezda** [comment]
![84 years](https://media1.giphy.com/media/FoH28ucxZFJZu/giphy.gif)

**Comment by VictorVelarde** [comment]
Better late than never... 😄 !
