### ISSUE TITLE
[BQ Connector] Authentication Feasibility

### ISSUE THREAD

**Issue by jgoizueta** [CartoDB/cartodb#15151]
To implement a new Import API BigQuery connector available in the SaaS we need to provide an authentication method that is acceptable from a security point of view and which can be integrated into our [DB connectors](https://carto.com/developers/import-api/guides/database-connectors/), ideally using [bigquery_fdw](https://github.com/gabfl/bigquery_fdw).

This task consists in updating and testing the existing odbc connector #14790 to analyse it in order to either reuse its authentication method or learning from it for our implementation. In case that using the specific fdw for our connector ends up not being possible, this work will also serve to try to put the odbc connector in production as a backup plan.

**Comment by manmorjim** [comment]
# Configuration

## Installing the BigQuery ODBC Driver

The steps to install and configure the driver are the following:

1. Downloading the Simba ODBC Driver from the webpage

```bash
wget https://storage.googleapis.com/simba-bq-release/odbc/SimbaODBCDriverforGoogleBigQuery_2.2.2.1007-Linux.tar.gz
```
2. Putting the driver into `/opt` following this structure:

```bash
opt/
└── simba
    ├── driver
    │   ├── ErrorMessages
    │   │   └── en-US
    │   │       ├── DSMessages.xml
    │   │       ├── DSOAuthMessages.xml
    │   │       ├── ODBCMessages.xml
    │   │       ├── SimbaBigQueryODBCMessages.xml
    │   │       └── SQLEngineMessages.xml
    │   ├── lib
    │   │   ├── cacerts.pem
    │   │   ├── GoogleBigQueryODBC.did
    │   │   ├── libbigqueryhtapi_sb64.so
    │   │   └── libgooglebigqueryodbc_sb64.so
    │   ├── third-party-licenses.txt
    │   └── Tools
    │       └── get_refresh_token.sh
    └── setup
        ├── odbc.ini
        ├── odbcinst.ini
        └── simba.googlebigqueryodbc.ini

```
```bash
sudo mkdir /opt/simba && sudo tar zxvf SimbaODBCDriverforGoogleBigQuery_2.2.2.1007-Linux.tar.gz -C /opt/simba --strip-components 1
```
```bash
sudo mkdir /opt/simba/driver && sudo tar zxvf /opt/simba/SimbaODBCDriverforGoogleBigQuery64_2.2.2.1007.tar.gz -C /opt/simba/driver --strip-components 1
```
```bash
sudo rm /opt/simba/SimbaODBCDriverforGoogleBigQuery*
```
```bash
sudo rm -rf /opt/simba/docs
```
```bash
sudo mv /opt/simba/GoogleBigQueryODBC.did /opt/simba/driver/lib/
```

:warning: **IMPORTANT:** Adding ownership to `ubuntu`:

```bash
sudo chown -R ubuntu:ubuntu /opt/simba
```

4. Adding the BigQuery ODBC Driver to the ODBC drivers in the machine:

Listing all the drivers installed:

```bash
odbcinst -q -d
```
```bash
[PostgreSQL ANSI]
[PostgreSQL Unicode]
[MySQL ANSI]
[MySQL]
[FreeTDS]
```

Adding the driver by editing the `odbcinst.ini` file. To know where it is execute:

```bash
odbcinst -j
```
```bash
DRIVERS............: /etc/odbcinst.ini
SYSTEM DATA SOURCES: /etc/odbc.ini
FILE DATA SOURCES..: /etc/ODBCDataSources
USER DATA SOURCES..: /home/ubuntu/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8
```

Editing the `odbcinst.ini` file to add the driver:

```bash
sudo vim /etc/odbcinst.ini
```

Adding the following:

```bash
[Simba ODBC Driver for Google BigQuery 64-bit]
Description=Simba ODBC Driver for Google BigQuery(64-bit)
Driver=/opt/simba/driver/lib/libgooglebigqueryodbc_sb64.so
DriverManagerEncoding=UTF-16
```

:warning: **IMPORTANT:** The encoding has to be configured to use `UTF-16` because by default uses `UTF-32` and this might cause problems with certains API clients.


5. Configuring error messages produced by the driver:

```bash
vim /opt/simba/setup/simba.googlebigqueryodbc.ini
```
```bash
[Driver]
DriverManagerEncoding=UTF-16
ErrorMessagesPath=/opt/simba/driver/ErrorMessages
LogLevel=0
LogPath=/home/ubuntu/
```

:warning: **IMPORTANT:** The encoding has to be configured to use `UTF-16` because by default uses `UTF-32` and this might cause problems with certains API clients.

:beetle: Setting the `LogLevel` to a higher number will help us to debug driver erros by logging them into two files called `simbaodbcdriverforgooglebigquery_connection_0.log` and `simbaodbcdriverforgooglebigquery.log`. The higher number, the more detailed logs.

6. Setting the variable `SIMBAGOOGLEBIGQUERYODBCINI` pointing to the previous file:

```bash
export SIMBAGOOGLEBIGQUERYODBCINI=/opt/simba/setup/simba.googlebigqueryodbc.ini
```


## Testing the driver

To test the driver we can use the `isql` command, but previously we have to creating a _DSN (Data Source Name)_ which uses the driver. 
We're going to test our driver against a Catalog of a BigQuery account so we need the following info:
- _Client Id_ of the BigQuery account
- _Client secret_ of the BigQuery account
- _Catalog_ we'll use for the test
- A genereated _refresh token_ which grants the BigQuery account to access to the Catalog.

1. Once we have this info we'll edit the file `odbc.ini` included in the driver in order to add the _DSN_:

```bash
vim /opt/simba/setup/odbc.ini
```

We have to focus on the `[Google BigQuery 64-bit]` secion:

```bash
[Google BigQuery 64-bit]
Description=Simba ODBC Driver for Google BigQuery (64-bit) DSN
Driver=/opt/simba/googlebigqueryodbc/lib/64/libgooglebigqueryodbc_sb64.so
Catalog=<CATALOG>
SQLDialect=1
OAuthMechanism=1
RefreshToken=<REFRESH TOKEN>
ClientId=<CLIENT ID>
ClientSecret=<CLIENT SECRET>
AllowLargeResults=0
LargeResultsDataSetId=_bqodbc_temp_tables
LargeResultsTempTableExpirationTime=3600000
```

:beetle: Setting the `Trace` property to `yes` and setting a file into the property `TraceFile` under the section `[ODBC]` at the begining of the file will help us to debug ODBC erros by logging them into a file.

```bash
[ODBC]
Trace=yes
TraceFile=/home/ubuntu/odbc.error
```

2. Export the DSN file as _DataSource_ file:

```bash
export ODBCINI=/opt/simba/setup/odbc.ini
```

Checking if the DSN has been installed successfuly:

```bash
odbcinst -q -s
```
```bash
[ODBC]
[Google BigQuery 32-bit]
[Google BigQuery 64-bit]
```

3. Testing the driver:

```bash
isql 'Google BigQuery 64-bit'
```
If everythin went well the previous command will show the following message:

```bash
+---------------------------------------+
| Connected!                            |
|                                       |
| sql-statement                         |
| help [tablename]                      |
| quit                                  |
|                                       |
+---------------------------------------+
SQL>
```

Now we can test a query:

```bash
SQL> select name from f1.circuits limit 10;
```


# Changes in Builder

All changes made to use ODBC driver have been included into the branch `bq-connector-sas`.

**Comment by jgoizueta** [comment]
To use the BQ Storage API we must take this into account: https://www.simba.com/products/BigQuery/doc/ODBC_InstallGuide/linux/content/odbc/bq/configuring/ht-api.htm
