### ISSUE TITLE
You should be able to edit your data in this mode

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#152]
JIRA ref: https://cartodb.atlassian.net/browse/CDB-238

**Comment by Xatpy** [comment]
We have just received another ticket about it (SB / 3432212).

**Comment by pkej** [comment]
Hi,
I guess it is my support ticket you refer to, Xatpy. I'd like to stress that we have 48 000+ long table, which is just for one of three territories which are of interest for us, I'm awaiting a doubling of our database when it comes to names, though I might prune it for non-Sami-language place names.

**Comment by iriberri** [comment]
One more time, we've just been asked about this again. :smile:

**Comment by iriberri** [comment]
One more time! @saleiva push? :)

**Comment by ztephm** [comment]
Hi, another user asking for this, S/B: 5454984

**Comment by iriberri** [comment]
@javisantana  what do you think?

**Comment by alonsogarciapablo** [comment]
There's something that still needs to be done. This how it's working right now:

![edit_while_filtering](https://cloud.githubusercontent.com/assets/390398/7861927/2fd18aa8-0553-11e5-84e1-ef724340bc6b.gif)

As a result of this, the UI is a bit inconsistent because the filters haven't been refreshed/updated and we're still seeing a row that shouldn't be there according to the filters. I think a good solution would be to update the filters so that it shows the new value and "enable" it so that the row is not removed from the table.

**Comment by saleiva** [comment]
+1

**Comment by xavijam** [comment]
Agree

**Comment by iriberri** [comment]
Mola, and :+1:

**Comment by alonsogarciapablo** [comment]
This is now working very good with discrete filters (on string columns):

![filters](https://cloud.githubusercontent.com/assets/390398/7964086/4e8de352-0a16-11e5-893e-025064facf11.gif)

I found a problem with regular filters (numbers and columns) and I'm working on fixing that now.

**Comment by xavijam** [comment]
Supper dupper!
