### ISSUE TITLE
BigQuery connector layout enhancements 

### ISSUE THREAD

**Issue by alejandraarri** [CartoDB/cartodb#15393]
~- If the BigQuery connector is accessed from _Add new layer_ option in Builder maps, the layout is shown as in the image.~ This CSS issue is fixed in the PostgreSQL connector branch.

~- If the BigQuery connector is accessed from _New Dataset_ option, the footer is aligned to the right instead of centered.~ This has been fixed via RT, it was affecting all the footer modals.

- [x] **Billing project**: New dropdown with client's projects. Saving selected option in the browser's local storage is very convenient for the user.

- [x] **Remove SQL parsing** and check if replacing the line breaks with spaces is needed. (BQ & DB connectors)

- [x] **New field** for table name/import_as option (BQ & DB connectors)

- [x] **Dry run** 

- [x] **Fix back button** in `Selected Dataset` view: it should render the sql screen. (BQ & DB connectors)

**Comment by jgoizueta** [comment]
While you're at it: I'd change the placeholder to `SELECT *, ST_GeogPoint(longitude, latitude) AS the_geom FROM my_project.my_dataset.my_table` so that it is clear that the data project and dataset should be entered in the query. (by the way, I'm not fond of those `my_` prefixes and I'd rather removed them but I'll leave it to your consideration)

**Comment by alejandraarri** [comment]
Deployed in production!
