### ISSUE TITLE
when raster import is not active in app_config tiffs raise an exception

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#1628]
- set ``raster_import_active: false`` in app_config.yml
- import a geotiff

you get 9999 unknow error and should say: "raster is not supported in your account" or something like that

**Comment by Kartones** [comment]
After talking with @saleiva I'm directly going to remove `raster_import_active` flag. Is going to be active to everybody so makes no sense.

Also, this throws a nasty error because the way the config works is activating or not the TiffLoader class, so when not active the importer doesn't knows how to handle `.tiff` files, so handling it more gracefully is not so easy.
