### ISSUE TITLE
Multi-color SVG markers in CartoCSS

### ISSUE THREAD

**Issue by robinlambert** [CartoDB/cartodb#1657]
Hi!
Is there a way to set a specific color for each path of an SVG used as a marker in CartoCSS ?
In CSS it is possible with path ids/classes.

Thanks!

**Comment by saleiva** [comment]
Hey @robinlambert you can apply the marker-fill property on CartoCSS to your marker if it's an SVG icon.

**Comment by robinlambert** [comment]
Thanks for your answer @saleiva!

Yes indeed but I was talking about multi-color SVG. I am trying to set two different colors on the same SVG with CartoCSS. I want to target a specific path of the SVG. Is there a way to achieve that? It is possible when I call a SVG with predefined colors, but when I set a marker-fill property, it changes all the paths to the same color.

**Comment by JohnDowler** [comment]
Hi Robin - did you ever figure out how to do this? I would like to have map markers that are black with a white background. I seem to only ever get one color, regardless of whether I create an svg with all fills, all lines, or both.

**Comment by robinlambert** [comment]
Hi John, unfortunately not :(
But I think that if you don't set a marker-fill in cartoCSS, the SVG will keep its predefined colors.

**Comment by x1alpha76** [comment]
Sorry for necroposting but this issue seems to be the only one coming up when you search for this issue. Searching through the Mapnik code for a way around this i saw that there is an alternate path when the fill colour is set to a gradient. So if you set the fill of your svg element to a gradient the symbolizer/marker-fill doesn't override it. This allows you to have only parts of your SVG coloured by cartocss - see below.

**Example using font-awesome duotone icon** 
![chrome_qMvuE2TUnG](https://user-images.githubusercontent.com/10903615/66734661-7fa74e00-eeab-11e9-9527-76cc03f7fae5.png)


**Ugly example with demo SVG**
![image](https://user-images.githubusercontent.com/10903615/66734398-7bc6fc00-eeaa-11e9-9a5a-f2645412653a.png)

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="-40 -40 180 180">
    <defs>
        <linearGradient id="red">
          <stop offset="0" stop-color="#d25400"/>
          <stop offset="1" stop-color="#d25400"/>
        </linearGradient>
        <linearGradient id="green">
          <stop offset="0" stop-color="#27ae61"/>
          <stop offset="1" stop-color="#27ae61"/>
        </linearGradient>
        <linearGradient id="blue">
          <stop offset="0" stop-color="#2a80b9" stop-opacity="1"/>
          <stop offset="1" stop-color="#2a80b9" stop-opacity="1" />
        </linearGradient>
    </defs>
    <circle cx="50" cy="56.9" r="70" stroke-width="16" stroke="white"></circle>
    <circle cx="50" cy="0" r="30" stroke-width="16" stroke="white" fill="url(#red)"></circle>
    <circle cx="0" cy="86.6" r="30" stroke-width="16" stroke="white" fill="url(#green)"></circle>
    <circle cx="100" cy="86.6" r="30" stroke-width="16" stroke="white" fill="url(#blue)"></circle>
</svg>
```
