### ISSUE TITLE
Export multiple tables to a single compressed file

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#1660]
See #1658 for context details

**Comment by viddo** [comment]
@Kartones @javisantana @rochoa @xavijam AFAIK the current APIs don't support exporting multiple files at once, do they? this is required for the new export-datasets dialog (see linked issue)

**Comment by Kartones** [comment]
Currently is the SQL Api the one that exports a table, so the issues here are:
- Can SQL API multiple files? And more importantly, **should** it have batching support and do multiple exports? IMO no, but is not my call.
- Should we (me) implement a new REST api endpoint that you send to multiple table names and it exports the tables, and then zips the file and then returns to the user? I see it a better option, but this raises other serious concerns.

* Current frontend servers have small space. Current import servers are for imports. So either we put this data at import servers or need to add "export servers". 
* This will also mean new code, new jobs to fetch, compress and cleanup data.
* This also means forget about instant download for multi-file downloads (anything that is not a single table download=. UI should be purely async, more like "we'll send you an email when the export is ready", because this will take more even with two small tables, having to spawn jobs, etc..
* How much time do we keep the zipped file available for download? 24 hours? 48?
And probably more issues, but let's first attack "big problems".

ccing @lbosque as this also means changes to systems.

As I told @viddo, this is not trivial, selecting N items for deletion means N calls to a DELETE endpoint, exporting N items in a single file is way harder to do, possible but not quick to implement.

**Comment by javisantana** [comment]
for the moment let's forget this.

The way to implement this would be to have a batch thing in the SQL API

**Comment by saleiva** [comment]
Ok, so we remove the export option from the modal (we keep the text but not the link if there are multiple tables, and we remove this option also from the submenu when selecting multiple datasets)

Hey @viddo close when done :P

**Comment by viddo** [comment]
![screen shot 2015-01-07 at 19 07 38](https://cloud.githubusercontent.com/assets/978461/5650643/7f395a2a-96a0-11e4-8f3c-416dad0c4067.png)
There are no links to export datasets, and the dialog already looks like that, so nothing more to do then, closing issue
