### ISSUE TITLE
Problems with interactivity on Samsung Galaxy S5 (android) and chrome. 

### ISSUE THREAD

**Issue by jatorre** [CartoDB/cartodb#1681]
Reported on support

I am using a samsung galaxy S5 (android) and chrome. 

The markers are not clickable on your example here

http://docs.cartodb.com/tutorials/custom_interactivity.html

& here

http://docs.cartodb.com/tutorials/toggle_map_view.html

Adding to @javisantana

**Comment by Xatpy** [comment]
I've been testing it with emulator Genymotion-->Samsung Galaxy S5 - 4.4.4. 
At first, I was thinking about there would be problems if you were loading the entire map instead of in the documentation. So, I was testing with two links:
- http://docs.cartodb.com/tutorials/custom_interactivity.html
- http://cartodb.github.io/cartodb.js/examples/tutorials/tutorial-2.html

But it seemed to work OK(attached gif):
![bug_mobile_interactivity](https://cloud.githubusercontent.com/assets/3958416/5901434/d93b2158-a572-11e4-99c6-0184f2666c66.gif)

Then I tested it with my phone (iPhone 4S) and it worked too.

The issue that I realised is that if you're using a mobile phone, the load is (much) **slower** than in desktop. And you can click before everything is loaded, so you could think that everything is ok, but no.

I'll ask for more information to the client.

**Comment by Xatpy** [comment]
I'm testing it with bigger points: [Link](http://jaimechapinal.com/test/test_mobile.html)

**Comment by Xatpy** [comment]
Another [link](http://nrkmaps.cartodb.com/u/nrk/viz/1da11f6a-a57c-11e4-a1a7-0e4fddd5de28/embed_map) reported from support.

**Comment by Xatpy** [comment]
Resolved by @javisantana [here](https://github.com/CartoDB/cartodb.js/commit/6029c5d7e0abd5da762b887d22426c54b3dca376)
