### ISSUE TITLE
Imports user or role with big timeout

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#1683]
We need to discuss approaches and implement a solution to avoid the increasing issues we're suffering regarding statement timeouts. Current approach of relying on the user's timeout (and increasing it manually when it is not enough) it is not scalable, not proactive (reactive and a bit ugly, first time it fails we "fix" it) and lately is happening on multiple fronts (raster imports, big tables, big twitter searches...).

* One proposed solution in the past was having an "importer" role or account with huge timeout and use it for all this kind of operations.
The timeout should be in effect for both `cdb_importer` and the user's schemas, as some operations work once the table is on the destination schema (e.g. geocodings).

/cc @lbosque @javisantana @juanignaciosl @zenitraM

**Comment by juanignaciosl** [comment]
I don't think there's a good global approach for this. In my opinion, right after any quick containment measure we should try to fix the slowness. For example, CartoDB/cartodb-postgresql#65 timeout should be workarounded somehow and the whole platform will benefit. Then, batching it seems nice (although I'd like to know the overhead of batching). I think nothing should need anything beyond batching.

**Comment by lbosque** [comment]
The statement_timeout problems don't come only with imports. They come too with common operations we provide from the editor (altering tables, for example). The time it takes for some of these processing operations depends totally on the size or type of data which is something we cannot just control.

I agree with @Kartones about using a different user for these type of cartodb processing operations (not queries that the user run). We have discussed that in the past. Having, for example, a user that inherits the db user but with a really high statement timeout could help.

**Comment by Kartones** [comment]
The problem is no matter how much you batch, there will always be scenarios where is not enough except if you go to batches of 1. And even there, we had a customer months ago to whom each individual row had huge geometries of dozens of MBs.

I agree we have to also try to improve code and provide better solutions and approaches, but right now the timeouts are not a workaround, they are an actual problem and bottleneck... This is like having a "safe paviment" over which to apply other improvements.

That said, increasing timeout is just one approach. Maybe making the QueryBatcher smarter can be another (like it analyzing the table and deciding the batch size based on number of rows, size of each, etc.)...

**Comment by javisantana** [comment]
For me the ideal situation would be to be able to setup a custom timeout per user for long running operations. That can not be done because the way we use pgbouncer (all the set's that we do are reset by pgbouncer)

A question here: what happen when we have a connection with a really big statment timeout in pgbouncer? is the connection kept during all that time? pgbouncer switchs? cc @lbosque

**Comment by juanignaciosl** [comment]
AFAIK switches, but if you want to keep parameters you can open a transaction and pgbouncer will "respect" that session-connection. We tried it a couple of weeks ago and it worked.

**Comment by javisantana** [comment]
we use transaction mode so the connection backs to the pool when it finishes. So until a query does not finish the connection is still in use (as per http://pgbouncer.projects.pgfoundry.org/doc/config.html, ``pool_mode`` section)

Why then we use pgbouncer for those connections ?

**Comment by lbosque** [comment]
Not sure if I understand the question. The connection to postgresql is
closed once it has been idle for about 3 minutes (dont remember exactly the
time). So, the transaction finishes and about 3 min later the conn is
returned to pgbouncer's pool.

However I don't think this avoid us to have a extra user with different
timeout.
Will we have extra connections to pgbouncer? Yes we will, but honestly I
don't think pgbouncer suffers more by having more client connections. Even
in that case, since these type of operations are way less frequent thatn
normal editor requests we can just give them a timeout or something like
that in rails pool so they are not eternally established.

On Thu, Jan 8, 2015 at 3:33 PM, javi santana <notifications@github.com>
wrote:

> we use transaction mode so the connection backs to the pool when it
> finishes. So until a query does not finish the connection is still in use
> (as per http://pgbouncer.projects.pgfoundry.org/doc/config.html, pool_mode
> section)
>
> Why then we use pgbouncer for those connections ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/1683#issuecomment-69186312>.
>



-- 
Luis Bosque
@luisico

www.cartodb.com
Map, analyze and build applications with your data

**Comment by javisantana** [comment]
the question is:

does pgbouncer make sense for long running queries? at the end one connection will remain to the database for each query

**Comment by lbosque** [comment]
Good point.
It probably doesn't make so much sense. We could try to run these directly.

On Thu, Jan 8, 2015 at 5:19 PM, javi santana <notifications@github.com>
wrote:

> the question is:
>
> does pgbouncer make sense for long running queries? at the end one
> connection will remain to the database for each query
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/1683#issuecomment-69203389>.
>



-- 
Luis Bosque
@luisico

www.cartodb.com
Map, analyze and build applications with your data

**Comment by javisantana** [comment]
so if we are able to connect directly we could use ``set statement_timeout`` without any problem.

Other thing to explore is @juanignaciosl proposal: enclose all that stuff in a transaction but I'm not sure about the problems that could cause (performance or others)

**Comment by rafatower** [comment]
Related to https://github.com/CartoDB/cartodb/issues/5009
