### ISSUE TITLE
Changing the order of the slides doesn't change the number

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#1729]

**Comment by michellechandra** [comment]
@saleiva @javisanta - rather than showing a number, would it be possible to show a preview of the content instead similar to what you see in say Google Presentations mode? I think this would be more helpful to the user than a number.

![screen shot 2015-01-14 at 3 07 40 pm](https://cloud.githubusercontent.com/assets/5423288/5746689/5837ea9a-9bff-11e4-819f-ef9c340bb5c3.png)

**Comment by javisantana** [comment]
@michellechandra that would be awesome but for the momment we will use the number
