### ISSUE TITLE
Add tooltip label to map zoom control - user feedback that the number is the current zoom level

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/cartodb#1762]

**Comment by saleiva** [comment]
A tipsy should be shown. If not appearing this is a bug.

**Comment by javierarce** [comment]
What? Where? I'm lost. Plus, is this also happening in the master branch?

**Comment by saleiva** [comment]
@michellechandra is this also happening in production?
I think she talks about the hover on the zoom level numeric indicator within the editor.

**Comment by michellechandra** [comment]
Yes, there is no hover label for the zoom level indicator in the editor. 

![screen shot 2015-01-14 at 12 30 34 pm](https://cloud.githubusercontent.com/assets/5423288/5743774/7cefa0dc-9be9-11e4-9b9d-57cad085d9be.png)

Also missing from the current editor:

![screen shot 2015-01-14 at 12 33 29 pm](https://cloud.githubusercontent.com/assets/5423288/5743791/9c28839c-9be9-11e4-8575-6bcfcceef9c7.png)

**Comment by saleiva** [comment]
Xatpy, a tipsy should be shown in the same way we show it in different places. This was working some time ago.

**Comment by Xatpy** [comment]
@saleiva  I'm so sorry, but I didn't understand the issue.
Do you mean that the zoom level indicator is not showing in the embed maps? 
Because, in my Editor I have:
![screen shot 2015-01-22 at 12 55 02](https://cloud.githubusercontent.com/assets/3958416/5855254/5e879be2-a236-11e4-8759-c97c20f2aa6a.png)
but then, in the embed map there is no number:
![screen shot 2015-01-22 at 12 55 13](https://cloud.githubusercontent.com/assets/3958416/5855264/7642955c-a236-11e4-8954-5e7016495ce7.png)

 Also, I didn't understand what 'tipsy' means here. :confused:

**Comment by saleiva** [comment]
tipsy is a custom tooltip that appears when overing that number on the editor explainning what that number is. This is so minor.

**Comment by Xatpy** [comment]
Ah, ok, thanks! :)
So, I'll add tipsy in the zoom controls. Roger!

**Comment by Xatpy** [comment]
![zoom_level](https://cloud.githubusercontent.com/assets/3958416/6043043/dbb01dc6-ac89-11e4-81f8-98ab47944296.png)

**Comment by Xatpy** [comment]
Closed with https://github.com/CartoDB/cartodb/pull/2073
