### ISSUE TITLE
Design responsive views for the public maps / datasets / folder views

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#1787]

**Comment by piensaenpixel** [comment]
## Ipad

![datasets](https://cloud.githubusercontent.com/assets/1214201/6127274/781f4fee-b129-11e4-942c-15d4cf0b8896.png)
![folder](https://cloud.githubusercontent.com/assets/1214201/6127273/781ddf88-b129-11e4-87e1-14bf707eb30f.png)
![maps](https://cloud.githubusercontent.com/assets/1214201/6127275/78218476-b129-11e4-90e6-780ee851ddf1.png)

## Mobile
![datasets](https://cloud.githubusercontent.com/assets/1214201/6127291/88d8e836-b129-11e4-9f3a-fa462e26f18f.png)
![folder](https://cloud.githubusercontent.com/assets/1214201/6127292/88da705c-b129-11e4-8961-0139ceb3780b.png)
![maps show](https://cloud.githubusercontent.com/assets/1214201/6127293/88daadc4-b129-11e4-8450-51978d77f381.png)
![maps](https://cloud.githubusercontent.com/assets/1214201/6127294/88dd80da-b129-11e4-9bba-8237a921766e.png)

**Comment by viddo** [comment]
Just to clarify (since the "old" pagination keeps appearing in the mockups) we'll use the pagination we have for the private/publish dashboard already, right? I.e.:
![screen shot 2015-02-12 at 12 08 11](https://cloud.githubusercontent.com/assets/978461/6166377/ef0d1370-b2af-11e4-9d17-529eb1cae5f0.png)

**Comment by piensaenpixel** [comment]
Sure @viddo
