### ISSUE TITLE
New dialog is not being removed from the document when it is closed

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#1853]

**Comment by viddo** [comment]
@xavijam Since a owning/parent view, who instantiates a dialog, is also the one that knows whether a dialog is persistent or not I think it's that view's responsibility to do the clean up if the view is not persistent (as is done in the [filters view](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/new_dashboard/filters_view.js#L211)). 

From what I can see in the code this is already the case, so am I missing some use-cases or can we simply close this issue?

**Comment by xavijam** [comment]
Leave it as it is, don't worry.
