### ISSUE TITLE
Possibility to search/filter users to give permissions

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#1923]
From [previous issue #1745](https://github.com/CartoDB/cartodb/issues/1745#issuecomment-71044426), add the search/filter of users to give permissions within an enterprise organization:
![(screenshot)](https://cloud.githubusercontent.com/assets/978461/5859100/14951d12-a258-11e4-86d4-26b828825045.png)

**Comment by alonsogarciapablo** [comment]
I have a couple of questions regarding this issue, which I'm looking forward to implement :)

**1. How do we get to the screen to select which users I want to share with?**

I'm assuming you do it by clicking "Share this dataset with your colleagues". But, when should we display that message? When the user belongs to an organization an there is at least one more user in that organization? What if the user it's the only one in the organization?

![dashboard - user private - datasets privacy with share](https://cloud.githubusercontent.com/assets/390398/7315832/77600d56-ea71-11e4-83da-49f242c64368.png)

**2. What would this link do? Would it just take you back?**

![14951d12-a258-11e4-86d4-26b828825045](https://cloud.githubusercontent.com/assets/390398/7315972/c3e38008-ea72-11e4-8a17-3ef79ff3776f.png)

cc/ @saleiva

**Comment by viddo** [comment]
Both of those views are already implemented (except for the search part which this is the scope of this issue), but you need an organization user to see it. More specifically:

1. [when user is part of organization](https://github.com/CartoDB/cartodb/blob/16d3de69d69728873149cb5753802f78b4b9f390/lib/assets/test/spec/cartodb/new_common/dialogs/change_privacy/view_model.spec.js#L131-L135). it does not take into account if there are users or not, I guess because an item can be shared with whole organization ahead of time (before there are any users). Almost all logic was ported from the old dialog (search for the privacy_dialog.js).

2. Old screenshot, that button is now in the header (consistent with creation dialog):
![screen shot 2015-04-24 at 11 43 11](https://cloud.githubusercontent.com/assets/978461/7316419/29531ff8-ea77-11e4-9aad-d26aa24a12d0.png), takes your back to the start view (your 1st screenshot).

**Comment by alonsogarciapablo** [comment]
@saleiva, I have a UX question related to this. Imagine the following use case:

1. There are three users: user1, user2, user3.
2. I open the "share" dialog, and I change the permissions for user1.
3. I then type "user2" in the search input an hit "enter".
4. (only "user2" is visible now). I change the permissions for user2.
5. I click "Save Settings".

And the question is: should we persist the changes to both "user1" and "user2", or should we only save the changes to "user2" since that's the one I'm seeing right now? In other words, should we "reset" the permissions of every user every time a search is performed?

I'd say we should only save what the user is seeing. What do you think?

cc// @viddo

**Comment by saleiva** [comment]
I think you have to save both, if not, will never be possible to assign permissions to more than one user when searching, right?

**Comment by saleiva** [comment]
Also, do you think that we could do the search here dynamic? I mean, without needing to press enter?

**Comment by alonsogarciapablo** [comment]
Yes, you would never be able to assign permissions to multiple users in that case. I hadn't thought about that use case.

And yes, we can make it so that we filter users on every key stroke. I went with "enter" and showing an "X" if there's a search, to keep it consistent with the map/dataset search.

**Comment by saleiva** [comment]
2nd thing. 
Yes, it's true that is more consistent. Ok leave it that way.
