### ISSUE TITLE
Pluralize text when deletes a map is not correct

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#1953]
![screen shot 2015-01-27 at 10 05 56](https://cloud.githubusercontent.com/assets/132146/5915975/324d8c10-a60c-11e4-9a7d-e2653fbcc5d9.png)

**Comment by xavijam** [comment]
And for example, in this case, this is not an user, it is an organization.

**Comment by viddo** [comment]
Indeed, the ones affected can be both the organization(s?) and/or users. I would go for not complicating the view-logic too much, covering every single case would be a PITA.. Assuming the intention with that banner is to warn the user before he/she deletes the dataset, I would go for simplifying the message, e.g. _"Some users and/or organizations will loose access to your dataset"_, since list on the right would indicate the details. Thoughts?

ping @saleiva

**Comment by saleiva** [comment]
BUT...
This is not an organization, it means that all the users that had permissions will lose it, so we always talk about users, at least for the time being...

**Comment by viddo** [comment]
So, directly or indirectly it will affect users, but in that case the number is not correct either way. So how should the copy be done?

**Comment by saleiva** [comment]
We can try without the number, no problem.
"Some users will loose access to this dataset"
