### ISSUE TITLE
Unify legends behaviour

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2018]
- Labels should be editable on every template
- Design the img/color picker and try on every customization panel - like wizards.
- Checkbox moved to the left as in Map editor - Legends on every state.
- Think if we don't want to unify the template visual language (thumbnails or not) for every component.

**Comment by carlostallon** [comment]
- Labels should be editable on every template
Fixed in map-editor-1.1

- Design the img/color picker and try on every customization panel - like wizards.
Done in map-editor-1.1

- Checkbox moved to the left as in Map editor - Legends on every state.
I didn't find this issue

- Think if we don't want to unify the template visual language (thumbnails or not) for every component.
