### ISSUE TITLE
Odyssey bar is not being taken in consideration for positionning the custom overlays (such as text)

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2042]

**Comment by javierarce** [comment]
I'm not sure if I understand the problem here. We follow the same logic as with a regular header: basically, it has no effect over the positioning of the text overlays. So if you put a text overlay at the top left corner of a map, it will appear at the top left corner no matter what, just like with ta regular header.

**Comment by javierarce** [comment]
Right now we close the slides bar of Odyssey in the Editor whenever the user tries to add a new overlay, so this shouldn't be a problem, I think.

PS: I delete my previous comment because I thought you were talking about the header that appear in the maps.

**Comment by javierarce** [comment]
Bump

**Comment by saleiva** [comment]
I don't get this :( -- I think there is a missunderstanding. I'm talking about the slide indicator that is on the top border of the map.

**Comment by javierarce** [comment]
Haha, well, there was a 50% chance I got that right. It would really help me if there were more information in the description of the ticket, it's difficult to know what you mean by "odyssey bar", it could mean the one in the editor or the one in the embeds :|

Anyways, here's my original message:

I'm not sure if I understand the problem here. 

With the odyssey header we follow the same logic as with a regular header: basically, it has no effect over the positioning of the text overlays. So if you put a text overlay at the top left corner of a map, it will appear at the top left corner no matter what, just like with ta regular header.
