### ISSUE TITLE
Error importing Shapefile converted from GDAL+ogr

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#2108]
`````
Sequel::DatabaseError: PG::Error: ERROR:  function st_force_2d(character varying) does not exist
LINE 2:           SELECT public.GeometryType(ST_Force_2D(the_geom))
HINT:  No function matches the given name and argument types. 
You might need to add explicit type casts.
`````

Import ID: `8b43dfb1-ce6d-4b5d-90d9-b62abebcd546`

`````
What we are doing is taking parcel data from many counties in Colorado 
and merging them all into EPSG:4326 and normalizing the columns and 
data.  This is all being done in ogr GDAL in 2 steps.  First normalizing 
the columns and projects into a series of shp files.  After that we run 
a ogr merge to make one master file. 
`````

Source file can be found at SB/4391807, as well as further info about it's creation from ogr2ogr.
**They were able to upload the Shapefile without reprojecting.**

**Comment by juanignaciosl** [comment]
The problem here is that importing the file creates a the_geom that seems to contain the type. Since geocoder will generate it from a geometry there was a name collision. Will talk to the team about the right fix.

**Comment by juanignaciosl** [comment]
Detailed insights:

This is the error: 
```
PG::Error: ERROR:  function st_force_2d(character varying) does not exist
SELECT public.GeometryType(ST_Force_2D(the_geom))\n                                             ^\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

Here's [the offending code](https://github.com/CartoDB/cartodb/blob/master/services/importer/lib/importer/column.rb#L231):

```
      def geometry_type
        sample = db[%Q{
          SELECT public.GeometryType(ST_Force_2D(#{column_name}))
          AS type
          FROM #{schema}.#{table_name}
          WHERE #{column_name} IS NOT NULL
          LIMIT 1
        }].first
        sample && sample.fetch(:type)
      end
```

It's being called at [this check](https://github.com/CartoDB/cartodb/blob/master/services/importer/lib/importer/georeferencer.rb#L279):

```
      def raise_if_geometry_collection
        column = Column.new(db, table_name, :the_geom, schema, job)
        return self unless column.geometry_type == 'GEOMETRYCOLLECTION'
        raise GeometryCollectionNotSupportedError
      end
```

... which is called [at the end of run](https://github.com/CartoDB/cartodb/blob/master/services/importer/lib/importer/georeferencer.rb#L54):

```
        raise_if_geometry_collection
        self
      end
```

So, what's happening?:
* We're importing a SHP that has valid geometries but also a `the_geom` column that has no geometry but data type information.
* Georeferencer is failing at a supposedly trivial check because `the_geom` is simple text. 
* If we avoid that trivial error, georeferencer would just create an empty `the_geom`, since it's not latlong, ip or countries, and geometry column is not used to create `the_geom` because that column already exists.
* Later, the extension would do nothing but ignore an empty `the_geom` (I think).

So, possible actions here:
* Just rescue from that error, create an empty `the_geom` and tell user to change column name or import their geometry manually.
* Rename current `the_geom` is it's not a geometry before beginning `Georeferencer#run` to ignore that non-valid user column naming.

**Comment by Kartones** [comment]
Yep, you're right about the "what's happening" extension point.

I'm ok with both, 2nd point is a infinitely simple version of [this call](https://github.com/CartoDB/cartodb-postgresql/blob/master/scripts-available/CDB_CartodbfyTable.sql#L322) but would speed up the import process so is not bad either.

**Comment by juanignaciosl** [comment]
Ok, Georeferencer will rename `the_geom` if it exists and it's not a geometry before doing any further work. Thanks :-)

**Comment by javisantana** [comment]
(checking this, this ticket would need a csv file to test)

**Comment by juanignaciosl** [comment]
@javisantana it has one, take a look at the PR: https://github.com/CartoDB/cartodb/pull/2285/files

**Comment by javisantana** [comment]
@juanignaciosl haha, it has after the bug has been fixed :P

**Comment by juanignaciosl** [comment]
I also tested it without the fix, it's an actual regression test. I will do TDD from now on :trollface:
