### ISSUE TITLE
Heatmap dragging isn't performing well

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#2121]
Here is a video of what I'm talking about. Chrome 40.0.2214.111, Mac OS

7mb
https://dl.dropboxusercontent.com/u/1307405/CartoDB/trash/dragging.mp4

**Comment by fdansv** [comment]
Yes, it was a subject of discussion whether or not to release cumulative heatmaps since the performance in large datasets drops significantly. We're now spending some time thinking about ways to improve performance, mainly related to obtaining pixel data from canvas, which is the bottleneck here.

This is a Torque issue, let's keep the conversation in the [corresponding issue](https://github.com/CartoDB/torque/issues/104) at the Torque repo.

**Comment by andrewxhill** [comment]
cool, thanks

**Comment by javisantana** [comment]
heat is thought for small resolutions (it should be 8 or 16 at least) neither for cumulative. In any case the performance problem is not only related to heat but to normal torque rendering
