### ISSUE TITLE
Font from origin 'http://cartodb-libs.global.ssl.fastly.net' has been blocked from loading by Cross-Origin Resource Sharing policy

### ISSUE THREAD

**Issue by talllguy** [CartoDB/cartodb#2139]
Greetings, not sure if this is a domain specific issue, but in Chrome Version 40.0.2214.111 m, I'm getting the infinite loading spin while loading a map I made.

![2015-02-09 12_47_52-baltimore city addresses _ cartodb](https://cloud.githubusercontent.com/assets/1827881/6111866/07e0fc7a-b05a-11e4-91de-4ba3a889dedb.png)

**Comment by Cicuta33** [comment]
I'm surprised no one has answered this issue since February the 9th.
This is preventing from showing the icons on the site.

<img width="717" alt="screen shot 2015-07-10 at 10 27 40" src="https://cloud.githubusercontent.com/assets/1844096/8614889/840ed87a-26ee-11e5-983d-2680ea5e9636.png">

dashboard:1 Font from origin 'https://cartodb-libs.global.ssl.fastly.net' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://cicuta33.cartodb.com' is therefore not allowed access.

**Comment by iriberri** [comment]
@zenitraM just fixed it :) Thanks!
