### ISSUE TITLE
Issues when changing column types

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#2202]
How to reproduce:
1. Create a new table
2. Change the `description` column type to `date`
3. Change the `description` column type to `number`

The server responds with an error:
```
PUT https://team.cartodb.com/u/rtorre/api/v1/tables/untitled_table/columns/description
params: {"name":"description","type":"number"}
response: {"errors":["PG::Error: ERROR:  function cartodb.cdb_datetonumber(timestamp with time zone) does not exist"]}
```
Reproduced in master.

**Comment by rafatower** [comment]
cc/ @Kartones

**Comment by gfiorav** [comment]
The problem seems to be that our date format for tables includes the time zone (UTC) and the `CDB_DateToNumber()` expects `timestamp`, not `timestamp WITH TIME ZONE`.

From the UI it doesn't seem posible to specify the time zone (defaulted to UTC).

The way I see it, we can either:
1. Change `CDB_DateToNumber()` to expect time zones and add an extra cast in case no timezone is present (i.e.: `::TIMESTAMP WITH TIME ZONE`)
2. Change de backend code to try to convert everything to UTC

I'm going for 1. since it's the most format flexible (not enforcing time zones on users' data).

**Comment by rafatower** [comment]
There was a PR, but discarded as there should be a better solution https://github.com/CartoDB/cartodb/pull/5352

**Comment by rafatower** [comment]
for the record: this is not actually closed until we release the new version of the extension

**Comment by gfiorav** [comment]
New version of the extension (`0.11.1`) released. Closing ticket.
