### ISSUE TITLE
"google_analytics" config key should not be required in open-source edition

### ISSUE THREAD

**Issue by santisaez** [CartoDB/cartodb#2218]
`google_analytics` key is used without checking it's present in `app_config.yml` at least on [`app/views/admin/visualizations/public_map.html.erb`](https://github.com/CartoDB/cartodb/blob/master/app/views/admin/visualizations/public_map.html.erb#L241-L246), so visualizations are failing raising a 500 error if the key is missing, a common config on open-source edition.

**Comment by Xatpy** [comment]
From embed_map_error, it can be fixed replacing [this lines](https://github.com/CartoDB/cartodb/blob/master/app/views/admin/visualizations/embed_map_error.html.erb#L22-L23)
with:
```
      ua: (Cartodb.config[:google_analytics].nil? || Cartodb.config[:google_analytics]['embeds'].nil?) ? '' : 
            Cartodb.config[:google_analytics]['embeds'],
      domain: (Cartodb.config[:google_analytics].nil? || Cartodb.config[:google_analytics]['domain'].nil?) ? '' : 
            Cartodb.config[:google_analytics]['domain'] 
```

But, it doesn't seem to be the same case with [app/views/admin/visualizations/public_map.html.erb](https://github.com/CartoDB/cartodb/blob/master/app/views/admin/visualizations/public_map.html.erb#L242-L243) , because I guess that it could be other stuff related, for example `insert_google_analytics`
