### ISSUE TITLE
Map creation with the new dashboard

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2257]
Connecting a dataset should create a new map automagically and take the user to that map view.

**Comment by xavijam** [comment]
cc @Kartones @javisantana

**Comment by Kartones** [comment]
Define "connecting a dataset" please.

If that means "importing a dataset", take into account we're going to affect ALL users, not only new dashboard ones, API users, etc. Are we aware of this?

We already create the canonical visualization, this means creating a derived vis too, so will change behaviour for existing users (who are used to the fact that loading data doesn't creates the "map", only the "dataset") and change the metrics (viz creation stats will go up but due to this, not due to more users visualizing more data).

Concerns apart, it can be done but this will probably imply more subtle changes that it appears.

**Comment by saleiva** [comment]
+ @javisantana

**Comment by javisantana** [comment]
what would be the difference between sending them to a new visualization or the map in the current table?

**Comment by saleiva** [comment]
The Map cannot be shared.
We avoid an extra step when trying to create a map.
We decouple conceptually the map and the dataset.
We leave the dataset view for advanced users.

**Comment by javisantana** [comment]
why the user needs to know it's a dataset?

**Comment by saleiva** [comment]
Already talked to @javisantana. He will explain tomorrow to you guys.

**Comment by xavijam** [comment]
@kartones, let me know when you consider backend part is ready.

**Comment by Kartones** [comment]
New import endpoint param `create_vis` (`boolean`, default `false`)

**Comment by Kartones** [comment]
Also, note to self: Update http://docs.cartodb.com/cartodb-platform/import-api.html#upload-file

**Comment by Kartones** [comment]
Upon successfull import, when the import has finished it will return a new field:
```
{ 
... 
:success=>true, 
:derived_visualization_id=>"ce0f6a72-bcd4-11e4-8910-30f9edfe5da6"
}
```

So the frontend can properly redirect to it

**Comment by Kartones** [comment]
@xavijam [PR](https://github.com/CartoDB/cartodb/pull/2491) is on its way, so you'll have live the backend support in a few hours at most

**Comment by xavijam** [comment]
Taking care of it -> https://github.com/CartoDB/cartodb/commit/ac030eb09e6c130ceef1cfb3a63f7747bf73190a
