### ISSUE TITLE
Can't create a marker image to a point from URL

### ISSUE THREAD

**Issue by Xatpy** [CartoDB/cartodb#2262]
Steps to reproduce:
1. Create an empty table
2. Go to map view, create a point.
3. In wizards, click on simple and marker fill img.
4. Click on upload file
5. I tested with [this image (367x420) ](http://www.cornerfootball.com/5556-large_default/parche-lfp.jpg)
6. The following message is returned in console:
![screen shot 2015-02-16 at 18 50 59](https://cloud.githubusercontent.com/assets/3958416/6216751/104853fa-b60d-11e4-871e-7cc0ba6b4174.png)
7. Clicking on set image, I can't see anything.
8. If I go back to dashboard, and then go into again, I can't see anything:
![screen shot 2015-02-16 at 18 53 23](https://cloud.githubusercontent.com/assets/3958416/6216782/5d4e9a10-b60d-11e4-83b0-340b7737875c.png)

**Comment by rochoa** [comment]
The file, by its extension, claims to be a JPEG file however it is a PNG file:

```sh
$ pngcheck 20150216175907parche-lfp.jpg
OK: 20150216175907parche-lfp.jpg (367x420, 32-bit RGB+alpha, non-interlaced, 87.1%).
```

Once I changed its extension to `.jpg` it started to work. I also saved it as JPEG and uploaded it again and also works as expected.

I think the problem here is that we are uploading the file to S3 and setting the content type in S3 based on the original extension.

```sh
$ curl -s -I https://s3.amazonaws.com/com.cartodb.users-assets.production/production/rochoa/assets/20150216175907parche-lfp.jpg | grep Content-Type
Content-Type: image/jpeg
$ curl -s https://s3.amazonaws.com/com.cartodb.users-assets.production/production/rochoa/assets/20150216175907parche-lfp.jpg | pngcheck
OK: stdin (367x420, 32-bit RGB+alpha, non-interlaced, -62466730.9%).
```

I will check if it's possible to detect this problem and report it as an error when parsing the cartocss for mapnik instead of silently failing at render time.

**Comment by Xatpy** [comment]
Great @rochoa , thanks! ^^
The 'weird' thing was also that I could see the image in thumbnail, but not in the map.

**Comment by rochoa** [comment]
Well, browsers do pretty-clever-and-nasty stuff in order to solve this kind of situations :cry: 

I created a ticket in Windshaft (although most likely is something at grainstore level) but someone else should take care of this in the editor.

**Comment by rochoa** [comment]
I reassigned it to @Kartones as he was working before with file uploads :smile:
