### ISSUE TITLE
Google sign in redirecting to /users

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#2263]
Some users are reporting that clicking login takes them to /sessions/new and then to /users.

**Comment by juanignaciosl** [comment]
Couldn't reproduce. Will wait until being able to reproduce it.

**Comment by juanignaciosl** [comment]
A couple of users have reported issues with Firefox, and one of them say it works if he deletes his history. It might be a combination of the autocomplete with the auto Google login.

cc @matallo

**Comment by matallo** [comment]
probably fixed in CartoDB/cartodb#2263

**Comment by matallo** [comment]
probably fixed in https://github.com/CartoDB/cartodb/pull/3086

**Comment by juanignaciosl** [comment]
If this is fixed with that fix @iriberri would probably like to tell [this user](https://cartodb.supportbee.com/tickets/4718710).

**Comment by matallo** [comment]
waiting til tomorrow to discuss if this quick fix works or going full refactor

**Comment by allthesignals** [comment]
A few co-workers and I are seeing a similar issue. I'm not sure what information you need to reproduce it, but here's the scenario:

A few of us have personal CartoDB accounts, but we all share one CartoDB account for a specific project (I'm not actually sure if this is against policy - we can figure out a different workflow if it is). _At some point, we've all logged in to our personal accounts on our own computers, but when we need to switch to the project-specific account, the site will login to our personal accounts instead of the project specific account_

Here are the steps:
1. Log out of personal account
2. Click "log in" from the front page
3. Enter username and password for project-specific account
4. Hit "Login"
5. Arrive at personal account page

I noticed that the URL for the login page is:
{personal-account}.cartodb.com/login

Even when I switch to:
{project-specific-account}.cartodb.com/login
And login with the project-specific account credentials, it still switches to the personal account. For what it's worth, this behavior occurs for some of my coworkers. We all use Firefox (I'm on a Mac, they're on PCs). 

(Also, sorry if this is described in another issue - I'm not sure how to describe it concisely).

Thank you for any help you're able to provide - we love this tool!

**Comment by iriberri** [comment]
Hi Matt, thanks for the info! Not sure if you have checked already, but are you able to disconnect your CartoDB account from Google as explained [here](http://docs.cartodb.com/faqs.html#how-to-disconnect-my-google-account-that-i-logged-into-cartodb-with)? Another thing that you can do is to log directly into the settings of your project-specific-email-address and revoke the access to CartoDB from there.

Cheers!

**Comment by allthesignals** [comment]
Hi @iriberri 

Thank you for the reply. I am actually not personally connected via Google on either the personal or project-specific accounts. I double-checked this for both accounts according to the docs you linked. However, I think my colleague @japartridge was having this issue with her Google connection.

**Comment by juanignaciosl** [comment]
Then it looks like @allthesignals problem is not Google login related, but multisession handling.
