### ISSUE TITLE
Crop description to max 2 lines in the map cards

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2391]
![screen shot 2015-02-20 at 13 03 11](https://cloud.githubusercontent.com/assets/132149/6285831/de7d5e82-b900-11e4-909e-48bb75279ed3.png)

**Comment by piensaenpixel** [comment]
Take a look this options
- http://jsfiddle.net/danield770/DpQ7e/30/
- http://codepen.io/martinwolf/pen/qlFdp

**Comment by viddo** [comment]
The current approach cuts the desc by length, but as can be seen in the screenshot it is not always reliable.. I propose to go with the CSS approach as @piensaenpixel proposes above (thx, was about to go search for them). Any arguments against, @xavijam ?

**Comment by xavijam** [comment]
test it in all possible browsers, that's it.

**Comment by viddo** [comment]
After also read [about line-clampin](http://css-tricks.com/line-clampin/) in general, I'm not sure about the CSS solution, it is not consistent across browsers and the "fallback" to display the ellipsis is positioned in the corner rather than together with the text (at best).

The quick fix is to shorten the truncation of the string to accodomate larger characters, so it always renders on two lines, e.g.:

![screen shot 2015-02-25 at 14 32 43](https://cloud.githubusercontent.com/assets/978461/6371668/3b41c0bc-bcfe-11e4-8312-7229f34d77bf.png)
![screen shot 2015-02-25 at 14 33 14](https://cloud.githubusercontent.com/assets/978461/6371669/3b47a734-bcfe-11e4-9abb-3c2def29702b.png)
