### ISSUE TITLE
Fix current pagination in new dashboard

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2413]
It should work in the same way that github does
![screen shot 2015-02-20 at 17 53 50](https://cloud.githubusercontent.com/assets/132149/6305172/7a030b54-b929-11e4-9ce7-257361b16ba2.png)

show [X-n,...,X-2,X-1,X,X+1,X+2,...,X+n]

**Comment by viddo** [comment]
The same way as in _exactly_ the same way?

**Comment by saleiva** [comment]
What do yo mean? :)

**Comment by viddo** [comment]
To have it clear what behaviour the pagination is expected to have. E.g. the Github pagination always displays the "Previous" button but with a disabled state:
![screen shot 2015-02-20 at 18 07 36](https://cloud.githubusercontent.com/assets/978461/6305443/91bba2e0-b92b-11e4-8345-4eb491c3a549.png)
![screen shot 2015-02-20 at 18 08 25](https://cloud.githubusercontent.com/assets/978461/6305444/91c07130-b92b-11e4-91e8-600802cbcdf1.png)

Since this kind of things was not brought up earlier on I suppose this is considered a "feature improvement"? Either way, it would help greatly if we would get a list of expected behaviour together with the visual mockups, unfortunately we (developers) cannot read your minds just yet ;)
