### ISSUE TITLE
Error importing geojson exported with CartoDB

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2461]
It says that I have two columns with the same header.

https://team.cartodb.com/u/saleiva/tables/marias.twitter_temblor_terremoto_earthquake/public/map?redirected=true

**Comment by juanignaciosl** [comment]
The error comes from ogr2ogr: it tries to generate a table with two `wkb_geometry` columns, one for text and other for geometry, and fails. It looks like the text one comes from the exported file, which has that column, empty for all rows. After speaking to @Kartones it looks like that column should've never existed in the Twitter import.

So, the workaround is removing that column from the table and exporting again.

And the error I'm going to dig into right now is why is that column created at import time.

**Comment by rafatower** [comment]
Seems related to: https://github.com/CartoDB/cartodb/issues/2107

**Comment by juanignaciosl** [comment]
Since the actual problem was the existence of that `wkb_geometry` column, which is fixed in #2107, I think we can close this issue. `wkb_geometry` is a `ogr2ogr` column that should not exist previously. This  will be documented in importer documentation at #2329 . 

@saleiva reopen this issue if it's not a valid solution for you. In that case we should scale this to ogr2ogr, since it's its limitation.
