### ISSUE TITLE
Send hubspot event when user visits new dashboard

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#2471]
http://developers.hubspot.com/docs/methods/contacts/create_or_update

**Comment by xavijam** [comment]
@viddo, I'll leave this one for you, you have recent experience with those services :dancer:

**Comment by viddo** [comment]
@saleiva what events/data points are really wanted here and in what format? also cc @vuxita, since she worked on this on the public website. 

Btw, we already have mixpanel right now, is that going to be continued to be used in addition to Hubspot? Adding more external libs to the dashboard adds extra weight on the page, could we please talk and try to consolidate what statistics tools to use to avoid this?

**Comment by saleiva** [comment]
We need to update a property that (@vuxita, please correct me) is `dashboard_visited`or something like that

The idea is to start deprecating mixpanel as soon as we have the same info in hubspot.

**Comment by vuxita** [comment]
Hey, 

Yes, that's right - when someone visits the dashboard we should create an event that updates the property we want.

The property hasn't been transferred from the initial import from Alberto as he didn't include all the properties. I have created this one so it can be used: dashboard_viewed

Info here: 
http://developers.hubspot.com/docs/methods/contacts/update_property

**Comment by viddo** [comment]
FYI, reading up on the API documentation it has [quite strict limitations](http://developers.hubspot.com/apps/api_guidelines) (e.g. 10 requests/sec and only 10k calls per 24H...), so it's hardly viable to track this kind of stats. On their forums I found [this reply though](https://groups.google.com/forum/#!searchin/hubspot-api/increment/hubspot-api/5kehP19fuC0/aqWv14o2HpMJ):

> If you're looking to tie a log in to a contact in HubSpot and make sure that you have analytics data for the record, you can associate the tracking data with a contact by using the Events API, which does not have the same rate limit. As long as you have an email address to identify the record with, you can use the JavaScript API to track a log in event for the visitor and also tie the analytics data to a contact record (or create a contact record) with that email address:
http://developers.hubspot.com/docs/methods/enterprise_events/javascript_api

In theory I have this done (created a custom event and code changes ready), but due to the [1-3h](http://help.hubspot.com/articles/KCS_Article/How-do-I-know-if-my-HubSpot-tracking-code-is-working) delay I cannot confirm that the events have been logged until later tonight. So unless I've misunderstood something I should have this done by tomorrow.

**Comment by vuxita** [comment]
Thanks for the info - would it also update any property/record to each contact then?
Let me know the name of the event when you've had the chance to test it.

Thanks!
