### ISSUE TITLE
Allow importing a table with a cartodb URL

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2538]
So it's easier to import data that is on other CartoDB accounts. 

assigned to @Kartones unless @juanignaciosl tell me that he wanna do it.

**Comment by Kartones** [comment]
I guess this means transforming the url to a SQL API call no? (like we do with common data, or at least did until recently)

**Comment by saleiva** [comment]
Exactly. 
Eeeeeasy, This would also mean some changes on the import modal I guess. I have to think a bit about how to integrate cc @xavijam

**Comment by iriberri** [comment]
Also, in the API CALL button of the public maps page we could add the link to the download via SQL API :-)

**Comment by saleiva** [comment]
@iriberri that's the same as exporting, right?

**Comment by iriberri** [comment]
Yeah, it uses the same URL, but I meant to write explicitly the query call to do in order to export the table in any format. This could be useful for people to use it directly in the import process (until we develop the feature of this issue) and also for users that may want to use it in scripts or something.

This is just really a personal request, I'm constantly checking the SQL API docs because I want the download link for a table (often useful in Support) and I never remember the syntax. :disappointed_relieved:

**Comment by saleiva** [comment]
Uhm... will think on how to integrate then!
