### ISSUE TITLE
Make users_controller works with new account and profile page

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#2545]
In branch user-account please

- [x] Split organization and standard user controllers.
- [x] Send errors when account update fails
- [x] Make it work for standard and organization users
- [x] Send flash notifications when needed
- [ ] Add Google+ auth.

**Comment by Kartones** [comment]
Issue https://github.com/CartoDB/cartodb/issues/2542 makes hard to fully test the new routes. 

I'm going to build all routing, test GETs etc. but probably actions won't work until urls are fixed.

**Comment by Kartones** [comment]
Another issue: Password change is not working correctly because the field is not  being sent to the user model, but this raises an issue from my point of view.

Right now Central has user password management and CartoDB only receives a new one and stores, so for example has no validation methods (min. length and the like). By adding this stuff we're going to duplicate logic from Central into the Editor. Are we ok with this @juanignaciosl @xavijam ?

**Comment by juanignaciosl** [comment]
There's some logic and code duplication between them. Maybe we should invest in packaging that common code, but it's expensive (decoupling from libraries and so on).

I'm not ok with code duplication between CartoDB and Central, but I'm afraid we can't get rid of it right now.

**Comment by Kartones** [comment]
- Profile photo uploads page is broken due to the wrong urls (issue #2542) `http://admin.localhost.lan:4000/uploads/development/kartones/assets/20150302170014test.png `
