### ISSUE TITLE
Two torque layers can be created

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#2584]
1. Import populated places table
2. Create a visualization
3. Assign heatmap (static) wizard
4. Add another layer (as an empty one)
5. In my case, I added some manual points as the table was empty.
6. Apply a Torque map. Below the wizard, you get the error "Sorry, but for the moment one Torque layer is allowed". **The Torque layer is there!**
7. Go to the heatmap layer, enable "animated".

Refresh the page:

![image](https://cloud.githubusercontent.com/assets/1730320/6461831/50eb857e-c1a4-11e4-932a-5cc7ef17b088.png)

Result:
https://team.cartodb.com/u/iriberri/viz/2c9ab0b8-c19b-11e4-82e0-0e018d66dc29/embed_map

cc @javisantana  @fdansv

**Comment by saleiva** [comment]
This is specially important on the new-dashboard, I'm sure that with the new UI it can also be done.

**Comment by Kartones** [comment]
My scenario was different, I had an existing vis with 5 layers (all points) but got same result:
- I went layer by layer changing to Torque Heatmap each
- I had no Chrome Dev tools open, and the UI didn't notify me any error on layers 2-5 change
- Upon reload, the Vis was dead and I got the same message as the screenshot above

**Comment by iriberri** [comment]
New dashboard procedure:

1. Select two tables with Torque applied
2. Create map
3. 
![image](https://cloud.githubusercontent.com/assets/1730320/6893744/c90dad80-d6cf-11e4-8556-12d30ff34e82.png)
4. Click OK
5. 
![image](https://cloud.githubusercontent.com/assets/1730320/6893747/d934df94-d6cf-11e4-871e-e2c97d33d705.png) 
If you refresh, step 4 again.
Accessing the map through the dashboard also goes to 4.

**Comment by alonsogarciapablo** [comment]
I'm taking a look at this. It seems that we have two different issues here:

1. The editor is not correctly tracking and preventing multiple torque layers from being created.
2. The new dashboard is not preventing users from creating a map from multiple torque layers.

Right?

@iriberri, perhaps we can open a separate issue for (2.), since it will probably involve some UI changes. What do you think?

**Comment by alonsogarciapablo** [comment]
We have a couple different scenarios in which multiple torque layers can be associated to a visualization:

1. When the user adds a new layer to a [map](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/table/actions_menu.js#L346) / [visualization](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/table/actions_menu.js#L373). In those cases, we're cloning the layer which is in position 1. We should ensure that the layer is converted to a simple visualization. I don't think this is currently working properly.
2. When the user selects "Torque" in the wizards panel. We now [warn users that they can only have on torque layer](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/table/menu_modules/wizards/torque.js#L67-L69), but multiple torque layers are actually there.

We're seeing that error message and no layers when we load the visualization because of [this](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/models/map.js#L314-L317).
