### ISSUE TITLE
Changing a table from public to private delete visualizations that still have permission

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#2586]
1. User A creates a private table and gives read permission to user B.
2. User B creates a visualization based on A.
3. User A switches table to public.
4. User A switches table to private without revoking user B permission.
5. User B visualization has been deleted in spite of having permission.

Making the table private should check for existing permissions.

cc @iriberri

**Comment by iriberri** [comment]
Is this related to the case of the table that cannot be deleted?

**Comment by juanignaciosl** [comment]
No idea. I don't think so, since this actually does "its complementary": it deletes a visualization that is legit.

**Comment by iriberri** [comment]
Ah ok, sorry! I was confused as I was reading about "table", "delete" and "permissions" :smile:

**Comment by juanignaciosl** [comment]
Ok, the problem is that a change to private [clears permissions](https://github.com/CartoDB/cartodb/blame/master/app/models/visualization/member.rb#L708) and then [permission check on dependent visualizations delete it](https://github.com/CartoDB/cartodb/blob/master/app/models/permission.rb#L429) without previous warning.

@javisantana , if I'm not missing any detail this looks like a product decision. I think there're two alternatives:
1. warning about deletion (similar to dataset deletion).
2. don't clear permissions.

I'd do 2. I should do more testing to check that doesn't break anything, but since per-user permission is independent from global permission it should be safe.

**Comment by javisantana** [comment]
Probably that use case was not taken into account, I'm agree with you on 2) but not sure if not clearing permissions could drive to a security problem (I don't see it but you know)

@Kartones is the one who worked more on that, do you see any issue?

**Comment by juanignaciosl** [comment]
I'll check if you both agree, but I don't think so: since permission switch for that user is on a user can just disable it (and disabling it has a nice warning message).

**Comment by Kartones** [comment]
I told @juanignaciosl by chat. If everything works fine and the tiler responds ok to the tokens, etc.... I'm ok with changing this logic.

I just recall that we added this "feature" as a user security feature, if you make something private it just unshared itself, so is not that we cannot do the opposite, it was just decided as that.

My only concerns were tiler access or "redundant auth tokens" making it fail, but we're also now always having a named map on all vis, so probably everything will be fine. If testing goes fine... I'd say go forward because that's the only critical area I can think about right now...

**Comment by juanignaciosl** [comment]
Great, stay tuned. Thanks!
