### ISSUE TITLE
add tests for oembed endpoint

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#2602]
- ask to andrew about the requirements
- add tests to that endpoint 

cc @andrewxhill @danicarrion

**Comment by andrewxhill** [comment]
URL Patterns to support

Individual account

1. osm2.cartodb.com/viz/0652ec10-861b-11e4-b6b6-0e853d047bba/public_map
2. osm2.cartodb.com/viz/0652ec10-861b-11e4-b6b6-0e853d047bba/embed_map
3. osm2.cartodb.com/viz/0652ec10-861b-11e4-b6b6-0e853d047bba/map

Organizational 

1. [organization].cartodb.com/u/[username]/viz/[map-id]/public_map
2. [organization].cartodb.com/u/[username]/viz/[map-id]/embed_map
3. [organization].cartodb.com/u/[username]/viz/[map-id]/map


Example response http://services.cartodb.com/oembed?url=https://osm2.cartodb.com/viz/08aef918-94da-11e4-ad83-0e0c41326911/public_map

```json 
{
type: "rich",
version: "1.0",
width: "100%",
height: "520px",
title: "Rivers of Europe",
html: "<iframe width='100%' height='520px' frameborder='0' src='https://osm2.cartodb.com/viz/08aef918-94da-11e4-ad83-0e0c41326911/embed_map' allowfullscreen webkitallowfullscreen mozallowfullscreen oallowfullscreen msallowfullscreen></iframe>",
author_name: "osm2",
author_url: "https://osm2.cartodb.com",
provider_name: "CartoDB",
provider_url: "https://www.cartodb.com/"
}
```

**Comment by andrewxhill** [comment]
It should accept a ```maxwidth``` and ```maxheight``` parameter. as well as ```format```

http://services.cartodb.com/oembed?url=https://osm2.cartodb.com/viz/08aef918-94da-11e4-ad83-0e0c41326911/public_map&maxheight=200&maxwidth=200

http://oembed.com/

**Comment by andrewxhill** [comment]
?

**Comment by javisantana** [comment]
I think this is done, @Kartones ?

**Comment by Kartones** [comment]
Not that I know... 

At the [URL Rewrites branch](https://github.com/CartoDB/cartodb/pull/1933) I've added some low-level tests (but yet have to stabilize that branch due to the heavy backend changes) to check that URL generation works ok, but definetly high-level/black-box tests would be nice (the ones that Andrew propose, checking correct input-output).

**Comment by javisantana** [comment]
Hey @danicarrion, this is specially important, we included oembed support quick without tests but we should have at least the most basic ones.

We are changing urls schemas and we need to be sure everything works

**Comment by danicarrion** [comment]
@javisantana @Kartones if you want me to do this i'll need to talk to some of you guys to tell me about all the URL changes and their implications, and about how to actually code the tests (first time) :-/

**Comment by Kartones** [comment]
url changes shouldn't affect you because saas (cartodb.com) will remain same as it is, and the oembed endpoint has little use AFAIK for custom installs. As long as you honour the patterns described by andrew it'll be ok, I'm covering low-level tests.

About how to write tests, sadly the only real info we have is [here](https://github.com/CartoDB/cartodb/blob/master/TESTING.md). But the best way to go is usually go and check existing tests (`/spec/`, `/spec/requests/` and so on).
We use [Rspec](https://www.relishapp.com/rspec/rspec-mocks/v/2-13/docs/) as the testing framework.

**Comment by danicarrion** [comment]
cool, thanks!

**Comment by juanignaciosl** [comment]
Already done by @javisantana
