### ISSUE TITLE
user: profile, return 404 if new_dashboard == false

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#2604]
if the user tries to access new profile url https://jacathon-huracan.cartodb.com/profile but `new_dashboard`feature flag is false, we should return 404 instead of 500

**Comment by Kartones** [comment]
@juanignaciosl  I'm struggling with this probably due to some autoload change.

Somehow `ApplicationHelper` doesn't gets loaded, which is where `account_url` exists, and as I get lots of errors requiring me to reload Rails due to GooglePlusConfig it smells it is related to those require_relative + no autoload.

I'll check possible solutions but the same code works in all other places except here :/

**Comment by juanignaciosl** [comment]
I've sometimes hit against legit circular dependencies that throws this errors. Do a trace of the dependencies you load with "require" and "require_relative" and you'll probably find it. Probably, in some obscure (or not) path, somebody requires ApplicationHelper who requires GooglePlusConfig who can require ApplicationHelper as well. If you want help with this please upload the branch and tell me how to reproduce, but this is a usual suspect.

**Comment by Kartones** [comment]
no no, in this case... there's not a single line in the code requiring ApplicationHelper :cry: 
In any case I'll see what I can do.

**Comment by juanignaciosl** [comment]
I see UsersController require both `google_plus_api` and `google_plus_config` but doesn't use GooglePlusAPI, so you should be able to safely remove google_plus_api. Since api loads config as well that could be the source of your problems.

**Comment by Kartones** [comment]
In the end made it gracefully go to the old account page if you don't have the new dashboard user flag.
