### ISSUE TITLE
Delete your account is not available in the new-dashboard account pages

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2622]
- [x] Delete modal window
- [x] Make it work with the backend part (cc @juanignaciosl)
- [x] Delete button for organization user form

**Comment by xavijam** [comment]
So true...

**Comment by saleiva** [comment]
You might need the confirmation modal design. If so, talk to @carlostallon although with the elements we already have it should be easy.

**Comment by xavijam** [comment]
Ok, also, personal note. Don't provide "delete" link to organization owners.

**Comment by xavijam** [comment]
@juanignaciosl, frontend part is done, but if you need any help, let me know. Branch [issue-2622](https://github.com/CartoDB/cartodb/tree/issue-2622).

**Comment by juanignaciosl** [comment]
- [X] Make it work with the backend part (cc @juanignaciosl)

Things I think are still missing:
- [ ] Goodbye redirection page (see `app/controllers/admin/users_controller.rb#delete` redirection).
- [ ] Should "enter" delete user when focus is in old password confirmation?
- [ ] Should org owner see delete account link? Error is caught, but it can't...
- [ ] Google logged in users that have not changed password (see `last_password_change_date`) should not see "normal" password change or account deletion, since they have no password yet.

Please feel free to assign any of those to me.

**Comment by xavijam** [comment]
@saleiva, being in our central was easy to redirect when a user was deleted, but now, doing that in the editor, we don't know what to do, should we create a new "bye bye" page? what do you think?

**Comment by xavijam** [comment]
Answering you @juanignaciosl:

-  Goodbye redirection page (see app/controllers/admin/users_controller.rb#delete redirection) -> asking @saleiva.
- Should "enter" delete user when focus is in old password confirmation? -> yes.
- Should org owner see delete account link? Error is caught, but it can't... -> I will "hide" it and put a "text"
- Google logged in users that have not changed password (see last_password_change_date) should not see "normal" password change or account deletion, since they have no password yet. -> we will manage that case when I start with google disconnect

**Comment by saleiva** [comment]
About 1. Create a ticket and leave it redirecting to cartodb.com for the time being. Sounds that good?

**Comment by xavijam** [comment]
@juanignaciosl, could you take care of the redirect please? Take into account open source way (It should go to 404 for the moment... maybe?).

**Comment by juanignaciosl** [comment]
Ok, just uploaded it:

```
-    # TODO: redirect to goodbye page
-    redirect_to "http://www.cartodb.com"
+
+    if Cartodb::Central.sync_data_with_cartodb_central?
+      redirect_to "http://www.cartodb.com"
+    else
+      render(file: "public/404.html", layout: false, status: 404)
+    end
```
