### ISSUE TITLE
Update in multi-user account is not being recognized

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#2743]
`update example SET latitude = latitude / 1000000`

is transformed to:

`update "username".example SET latitude = latitude / 1000000`

and:

![image](https://cloud.githubusercontent.com/assets/1730320/6618253/9b612a72-c8c1-11e4-9b07-f4e50137499e.png)

From: SB/4754950

**Comment by iriberri** [comment]
And Explain Analyze :-) From SB/4764650

**Comment by Xatpy** [comment]
It only fails with users that has an "-" in his username. 
In my local environment, I tried with user *xatpy* and it worked. But I created an user called "ey-tu", and it fails.
Kudos to @iriberri , because she pointed it. :clap:

**Comment by Xatpy** [comment]
@javisantana I think that the error could be [here](https://github.com/CartoDB/cartodb/blob/dc3cbba77d26c0acbcf5d70476199df76aaa5d55/lib/assets/javascripts/cartodb/table/menu_modules/sql.js#L394)

But my question is: this would be an error from cartodb or CartoDB-SQL-API ?? 
I mean: I don't know if the error here is that frontend is sending data wrongly, or cartodb-sql-api should accept that kind of data. I think this because of the error stack:
```
{
  error: [
    "syntax error at or near ".""
  ],
  stack: "error: syntax error at or near "." at Connection.parseE (/CartoDB-SQL-API/node_modules/cartodb-psql/node_modules/pg/lib/connection.js:566:11) at Connection.parseMessage (/CartoDB-SQL-API/node_modules/cartodb-psql/node_modules/pg/lib/connection.js:395:17) at null.<anonymous> (/CartoDB-SQL-API/node_modules/cartodb-psql/node_modules/pg/lib/connection.js:104:20) at Socket.EventEmitter.emit (events.js:95:17) at Socket.<anonymous> (_stream_readable.js:746:14) at Socket.EventEmitter.emit (events.js:92:17) at emitReadable_ (_stream_readable.js:408:10) at emitReadable (_stream_readable.js:404:5) at readableAddChunk (_stream_readable.js:165:9) at Socket.Readable.push (_stream_readable.js:127:10)"
}
```
Also, I've been "playing" with several URL (without *-* or *.*, encoding, etc.) but I couldn't find a correct request with a username who contains *-*.

**Comment by Xatpy** [comment]
Closed with commit https://github.com/CartoDB/cartodb/commit/057904a6ce9194292f8ecf6de7d11cb2c28ca5a3
