### ISSUE TITLE
Incorrect parameters sent to WMS proxy for WMTS URLs

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#2749]
http://leafletjs.com/reference.html#tilelayer-tms

This can be useful in order to get tilelayers directly exported from gdal into CartoDB (with y axis inverted). :-)

@rochoa @javisantana @javierarce @zenitraM

**Comment by javisantana** [comment]
this is supported in the api for years, we only need to add it to the design. Not sure about static maps api support

**Comment by jatorre** [comment]
WMTS I believe support also the regular X/Y/Z type of formats, so there is no need to have TMS support.

The WMS Proxy also should be able to handle this in any case, and it seems it does more or less. For example trying our own DigitalGlobe service

http://wmts.maptiler.com/aHR0cDovL2NkYl90aWxlc3RvcmFnZS5zdG9yYWdlLmdvb2dsZWFwaXMuY29tL2luZGV4Lmpzb24/wmts

When using it on WMS (which should be renamed to WMS/WMTS) does this.

https://cartodb-wms.global.ssl.fastly.net/api/check?url=http%3A%2F%2Fwmts.maptiler.com%2FaHR0cDovL2NkYl90aWxlc3RvcmFnZS5zdG9yYWdlLmdvb2dsZWFwaXMuY29tL2luZGV4Lmpzb24%2Fwmts%3F%26request%3DGetCapabilities%26service%3DWMS&type=wms&callback=jQuery17203532266339752823_1431467908150&_=1431467947256

And it returns the layers available behind that WMTS service.

When I click on one I see this request being done

https://cartodb-wms.global.ssl.fastly.net/api/add?url=http%3A%2F%2Fwmts.maptiler.com%2FaHR0cDovL2NkYl90aWxlc3RvcmFnZS5zdG9yYWdlLmdvb2dsZWFwaXMuY29tL2luZGV4Lmpzb24%2Fwmts%3F%26request%3DGetCapabilities%26service%3DWMS&type=wms&callback=jQuery17203532266339752823_1431467908151&_=1431468197006

And this error returned:

jQuery17203532266339752823_1431467908151({
  "error": "Missing layer parameter"
})

So, my guess is that our JS on the WMS modal window is not working properly on this case. And by the way, there is no error catch in that modal window, so after doing that the modal gets stacked with no error displayed to the user.

![screen shot 2015-05-13 at 12 06 34 am](https://cloud.githubusercontent.com/assets/127803/7599622/fbd01c84-f903-11e4-8f8f-efba69e0000c.png)

**Comment by jatorre** [comment]
The correct URL to call would be

https://cartodb-wms.global.ssl.fastly.net/api/add?url=http%3A%2F%2Fwmts.maptiler.com%2FaHR0cDovL2NkYl90aWxlc3RvcmFnZS5zdG9yYWdlLmdvb2dsZWFwaXMuY29tL2luZGV4Lmpzb24%2Fwmts%3F%26request%3DGetCapabilities%26service%3DWMTS&type=wmts&callback=jQuery1720013245485257357359_1431468930030&_=1431513448726&layer=everest&matrix_set=GoogleMapsCompatible


where things that are different:

-use wmts instead of wms
-set the layer that has been selected
-set the matrix_set taking whatever it has been return on the mapproxy before

**Comment by viddo** [comment]
I just started on implementing the new basemap modal (see #3633), I guess this stuff should be taken into account, @saleiva are you aware of this?

**Comment by viddo** [comment]
TMS option will be done as part of #3694, renaming issue to match the error report by jatorre instead

**Comment by viddo** [comment]
Even when sending correct params to the proxy, the [generated URL with the `mapproxy_id`](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/table/basemap/basemap_dialog/wms_basemap_pane.js#L64) (e.g. http://cartodb-wms.global.ssl.fastly.net/mapproxy/wmts_maptiler_com_everest_GoogleMapsCompatible/wmts/map/webmercator/0/0/0.png) for the example above fails due to 500 errors on the proxy. So either this format URL is not valid for WMTS tiles, or something else is wrong. We sent an email to the developer who implemented the proxy to know where the culprit might be.

**Comment by jatorre** [comment]
Well. I can tell you that is very likely that tile 0/0/0 does not exist as this is a very zoom in tileset. So the proxy likely does not find the tile on origin and fails. 

Try to retrieve a tile around Everest for zoom 16
