### ISSUE TITLE
Placeholders for emtpy map dashboard rows are missing

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2766]
Remember we had some in the designs with a random CTA

**Comment by viddo** [comment]
@javierarce @jaimecartodb since this was working previously, any ideas on what might have changed recently?

**Comment by javierarce** [comment]
I'm not sure what are you referring to :|

**Comment by viddo** [comment]
my bad, I thought @saleiva was referring to the placeholder we added (and still have atm). He is referring to change these to: 
![screen shot 2015-03-13 at 19 03 05](https://cloud.githubusercontent.com/assets/978461/6644381/9a39e682-c9b3-11e4-962d-395568636ece.png)

**Comment by javierarce** [comment]
Oh, ok. I went to my production account and couldn't see them either.

**Comment by viddo** [comment]
Currently we have these "empty" cards on public pages:
![screen shot 2015-03-13 at 19 09 00](https://cloud.githubusercontent.com/assets/978461/6644483/80a451d4-c9b4-11e4-958c-35806a897dd3.png)

But when logged in they don't show up anymore it seems:
![screen shot 2015-03-13 at 19 09 17](https://cloud.githubusercontent.com/assets/978461/6644484/80aa77bc-c9b4-11e4-9d88-d34efd44673d.png) (they did previously).

Anyway, I guess with this issue that should be taken care of it, and have the additional icon, text, and CTA, then.

**Comment by saleiva** [comment]
Hey, not changing, Just adding these ones when having wholes in a row

**Comment by viddo** [comment]
> ... wholes in a row

You mean _holes_, right? :)

More questions:

1. Where should those `(Go for it)`-buttons point to? 
1. What combinations of icons/texts/link (depends on prev question I guess) should there be? Or are there only these two? If not, where can I find the others?
1. How important is this? Since we started investigating the new-editor this morning I feel we have priority conflicts. Either I work on this to try to finish it in time for this sprint (i.e this week), or we'll push it to the next sprint.

**Comment by saleiva** [comment]
:trollface: 

1. The video state on the create modal with that video activated
2. The same than in the video state, @xavijam knows about that.
3. This, please - Let's get the new dashboard done and release it

**Comment by viddo** [comment]
E.g.:
![screen shot 2015-03-17 at 14 40 00](https://cloud.githubusercontent.com/assets/978461/6688489/03fc81f8-ccb4-11e4-90ec-64d863e408d2.png)

See https://github.com/CartoDB/cartodb/commit/ee05d47e432696990a93cd142dc709bd52d27f5c for changes, reassigning to @xavijam to implement the "Go for it"-button to open in the create dialog since he's currently refactoring that.

**Comment by xavijam** [comment]
![placeholders](https://cloud.githubusercontent.com/assets/132146/6690289/1212162a-ccc0-11e4-8bc9-69aec2026b1a.gif)

cc @saleiva and @viddo
