### ISSUE TITLE
Sync tables has created a duplicate

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#2772]
cc @javisantana @saleiva 

Just logged into my dashboard to see this

![screen shot 2015-03-13 at 8 20 40 pm](https://cloud.githubusercontent.com/assets/370259/6650112/8f25276a-c9be-11e4-8deb-72faca51f13e.png)

I know only from my memory that last_1_hours is the table that should have been syncing. Something changed in the past day or two to make a duplicate that is now syncing. This is a major issue if it is widespread.

**Comment by iriberri** [comment]
cc @juanignaciosl @Kartones

**Comment by juanignaciosl** [comment]
I've done a couple of checks and I think we can dismiss it being widespread (although we should take a look). This is that I've checked:
* I've got many sync tables with files I don't use to modify and there's no new duplicate (not others than the ones I created from the very beginning).
* I've created a new sync table with a csv in Dropbox. After modification of the file and manual sync data is updated and no duplicate appears.
* I've then modified the file again and modified the dates of the sync in the database going 1 day back and waited for automatic sync to be triggered. Data was updated and no new duplicate is generated.
* Since ghost tables checks are triggered when you enter the dashboard, I've reloaded the page many times to see whether there were hidden tables that would be registered later, but no duplicate arised either.

I've taken a look at your account and there's only one sync beginning with "last_1_hours", which is named "last_1_hours_2", created 15-01-10 and looks ok. You also have 3 matching tables (last_1_hours, last_1_hours_1, last_1_hours_2). "0" and 1 were created in 2014 have not been updated in 2015, _2 did (today).

I've seen the log of the only sync matching, and it's a file called 'last_1_hours", but since you have 2 previous tables whose names collide being renamed to "last_1_hours_2" is the expected behaviour.

We'll keep an eye on it, and Carla can report here any similar incidence. If we discard human mistake, my guess would be that ghost tables were triggered during a sync, and that might interfere. But right now everything looks fine to me. It looks like you imported that file twice and then you added a sync table without deleting existing ones.

**Comment by iriberri** [comment]
I also took a look at it in my own accounts, including common data, and I didn't spot any duplicates. I'll keep an eye on this.

**Comment by Kartones** [comment]
Same here, 5 syncs and no duplicate data.

*Diego / Kartones  |  *Developer*  |  *CartoDB <http://www.cartodb.com>*  |
 *diego@cartodb.com

**Comment by juanignaciosl** [comment]
No news, good news.
