### ISSUE TITLE
Markdown is not being rendered in public dashboard items

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#2817]
Example, look at [this map](https://team.cartodb.com/u/xavijam/viz/6f84f354-cd51-11e4-b358-0e49835281d6/public_map), it has a link in the description.
But if you check my [public dashboard](https://team.cartodb.com/u/xavijam) the link is not appearing

**Comment by viddo** [comment]
This is no different from existing behavior on current/old public pages, the difference seems to be that this page uses [`description_md`](https://github.com/CartoDB/cartodb/search?utf8=%E2%9C%93&q=description_md) instead of [`description_clean`](https://github.com/CartoDB/cartodb/search?utf8=%E2%9C%93&q=description_clean) (which strips HTML tags). Do you know what was the reason for stripping tags in the first place?

**Comment by viddo** [comment]
closing by request of author ;)
