### ISSUE TITLE
Going to page 1 in the public dashboard goes to the org dashboard, and not the one for the user.

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2833]
https://team.cartodb.com/u/saleiva/page/2 try to go to page 1

**Comment by viddo** [comment]
My guess is that the Rail's [`url_for` method which is used to create a URL template is not resolving to the expected URL](https://github.com/CartoDB/cartodb/blob/master/app/views/admin/pages/shared/_pagination.html.erb#L15-L17), probably due to how the [routes](https://github.com/CartoDB/cartodb/blob/master/config/routes.rb) are resolved in priority. Also see ["Rails Routing from the Outside In"](http://guides.rubyonrails.org/v3.2.21/routing.html)
