### ISSUE TITLE
Delete tables/visualizations without opening them first

### ISSUE THREAD

**Issue by pramsey** [CartoDB/cartodb#2835]
For data management purposes, having to open a table or visualization before you can delete it is a PITA. Can you fit a wee trashcan into the standard listing? Or a dropdown of optional actions, including delete/rename/privacy/metadata, all the things that are only available once you've opened the table/viz right now?

**Comment by viddo** [comment]
Agree, but all these concerns are already solved (or at least will be) in the new dashboard, which will be launched promptly. :) More specifically:
- A menu with secondary actions is revealed by selecting at least one item
- Some actions can be done in bulk (i.e. when selected more than one item), e.g. deletion
- Privacy/sharing can be accessed directly by clicking the privacy indicator
- Edit metadata (e.g. rename) is on the roadmap, see #1437, planned for current sprint

Closing the issue since all your concerns are addressed, but feel free to re-open if you think I overlooked something.

**Comment by pramsey** [comment]
Hm, I left the commented because I was using the new dashboard and didn't see the options. My eyes were on the thing I clicked, so I totally missed the fact that the top bar was modally switching to allow new options. So on the one hand: yay! the feature I wanted. On the other hand: hmmm, will other folks be as feature-blind as me? Thanks for the quick response!

**Comment by viddo** [comment]
yes, I think you might have a point there. cc @saleiva @carlostallon since they designed this interaction, we should probably keep an eye out for this kind of feedback once we open up the access to the new dashboard.
