### ISSUE TITLE
Default heatmap calculation should be investigated

### ISSUE THREAD

**Issue by andrewxhill** [CartoDB/cartodb#2865]
Hey, 

Steps to reproduce,

1. Create an empty table
2. Run, insert into untitled_table_26 (the_geom) SELECT CDB_LatLng(-50,30) FROM Generate_Series(1,100)
3. Run, insert into untitled_table_26 (the_geom) SELECT CDB_LatLng(0,0)
4. Create a heatmap

You can see that some things are a bit funny in the outcome,

http://team.cartodb.com/u/andrew/viz/4df2c2b6-d166-11e4-bf59-0e853d047bba/public_map

For example, even as a minimum, they aren't equal dots but one is smaller and less colored than the other
The issue that led me to look at this was that in fact, a user that does this would expect that 100 overlapping points would weight a lot more in a heatmap than a single one. 

cc @javisantana @fdansv

**Comment by fdansv** [comment]
Leaving aside the fact that heatmap "bubbles" should be more intense the higher the value (in this case given by ```count(cartodb_id)```, in your example the correct behaviour would be to see *two equally intense balls*<sup>1</sup>.

After a bit of sherlockholming, I noticed this when increasing the resolution quotient to 128:

![screen shot 2015-03-23 at 19 26 20](https://cloud.githubusercontent.com/assets/3707222/6787377/95fab164-d192-11e4-8d25-012489834b7e.png)

So, the problem here seems to be that when we paint stuff at *```(0, 0)```* with Torque, actually two adjacent points are calculated instead of one. Proof, you say? Running this on the editor:
```sql
insert into untitled_table_3 (the_geom) SELECT CDB_LatLng(-50,30) FROM Generate_Series(1,100);
insert into untitled_table_3 (the_geom) SELECT CDB_LatLng(30,20);
```
Will yield the following map:

![screen shot 2015-03-23 at 19 35 18](https://cloud.githubusercontent.com/assets/3707222/6787558/f51e5f14-d193-11e4-88ae-102d4dccc818.png)


<sup>1</sup> *RAUR*

**Comment by fdansv** [comment]
Cc'ing @rochoa as this is most likely a Windshaft issue.

There's the other issue of adding weight to the heatmaps according to the value passed, but that is already being tracked at #2125. Feel free to close this and track from Windshaft.

**Comment by rochoa** [comment]
This is not new, we already had some issues with points in tile boundaries, see https://github.com/CartoDB/Windshaft/issues/186

Having something like:
```
     ---------
    | TL | TR |
    |--(0,0)--|
    | BL | BR |
     ---------
```
Right now the behaviour is that a (0,0) point belongs to two tiles: BL and BR. We can change this behaviour and eliminate the point from all (TL,TR,BL,BR) but one tile. That means we will lose some (more) points in the boundaries of the map.

What do you think?

**Comment by rochoa** [comment]
We should follow the discussion here: https://github.com/CartoDB/Windshaft/issues/308

**Comment by andrewxhill** [comment]
Okay, then we should leave this one about the fact that we don't render points that overlap as multiple instances on the heatmap right?

**Comment by rochoa** [comment]
I closed it because IIRC that's what @fdansv was talking about: https://github.com/CartoDB/cartodb/issues/2125

Feel free to reopen if I got it wrong.

**Comment by fdansv** [comment]
@andrewxhill isn't that the same as #2125? I mean we can keep tracking here, but it looks like a duplicate to me.

**Comment by andrewxhill** [comment]
perfect

On Tue, Mar 24, 2015 at 1:08 PM, Francisco Dans <notifications@github.com>
wrote:

> @andrewxhill <https://github.com/andrewxhill> isn't that the same as #2125
> <https://github.com/CartoDB/cartodb/issues/2125>? I mean we can keep
> tracking here, but it looks like a duplicate to me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/2865#issuecomment-85602332>.
>



-- 

andrewxhill <http://twitter.com/andrewxhill>
http://cartodb.com
