### ISSUE TITLE
Table issue: undefined method `public_values' for nil:NilClass

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#2881]
From SB/4883769: "Unable to delete a table"

https://rollbar.com/vizzuality/CartoDB/items/4794/occurrences/4569252508/

* Table cannot be accessed from the dashboard, although is listed correctly: "Ooops! This is an unexpected error. Please come back in a while. (500 error)"

cc @Kartones @javisantana

**Comment by javisantana** [comment]
can you complete a little bit?

**Comment by iriberri** [comment]
Happening also for other user, received it in Support right now: (SB/4896453)

https://rollbar.com/vizzuality/CartoDB/person/?environment=production&person_id=394c8e5b-5885-4ac1-899d-9dc3285ec02c

**Comment by Kartones** [comment]
Just so that you know @rafatower , this looks like some flow is leaving "ghost visualizations" :((( 

My bet: A rename of a table (don't know exact flow) renames the physical table (and I have to check but probably also `user_tables`) but visualization item keeps the old one, because I've seen at least one.

I'll update the ticket with more details but sadnly I've seen this kind of issues in the past while changing some callbacks or related_xxx methods.
