### ISSUE TITLE
making visualizations with shared data does't show in public view

### ISSUE THREAD

**Issue by namessanti** [CartoDB/cartodb#2947]
With private data shared, public visualizations will not show data on map.

here's a map built with Andrew's shared data that in my editor I can see styles, but not in the public view.

https://team.cartodb.com/u/santiagoa/viz/80e8d236-c767-11e4-b054-0e4fddd5de28/public_map

**Comment by saleiva** [comment]
This is important

**Comment by Kartones** [comment]
I'll try to take a look later... else tomorrow morning

**Comment by Kartones** [comment]
Narrowed the issue thanks to @javisantana: Vizjson is incorrectly displaying the `user_name` of a `torque` layer with data coming from a named map/private.

Being user `A`:
```
{
	...
	type: "torque",
	...
	options: {
		user_name: "B",
		...
	}
	...
}
```

Only happens with torque layers from my tests.

**Comment by Kartones** [comment]
Ok, depriorizing it more.  

After going crazy because it worked at development and staging, it was failing in live with one Andrew table (the only one that is private & shared). I tried with other private shared tables... and it works with all of them. 
It seems Andrew's table got borked (or its permissions ACL) but there's no issue in the system itself. Just try with another dataset @namessanti, or ask Andrew to change the table privacy to public and private again, and if persists to reset the sharing options and re-share it.
