### ISSUE TITLE
Clicking on the small quota bar on the account pages should go to the plan tab

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#2949]

**Comment by saleiva** [comment]
I mean this one 
![screen shot 2015-03-29 at 17 53 28](https://cloud.githubusercontent.com/assets/132149/6886392/8d885d70-d63c-11e4-9313-bf405e0cc5da.png)

**Comment by matallo** [comment]
to be done in cartodb-central dropdowns, too

**Comment by xavijam** [comment]
It is not the dropdown matallo, it is this one!
![screen shot 2015-04-06 at 17 59 31](https://cloud.githubusercontent.com/assets/132146/7007089/be073728-dc86-11e4-9961-2a610e8b729d.png)

You don't have to do anything because it doesn't make any sense to add the link being in that page...
So, you are done!
