### ISSUE TITLE
Support partial match search in viz endpoint

### ISSUE THREAD

**Issue by rafatower** [CartoDB/cartodb#3056]
- [x] partial match method at query builder
- [x] add missing tests
- [ ] move existing tests to shared pool?

**Comment by rafatower** [comment]
If I type `test_string` in the search box, the query that fails is:
```
GET api/v1/viz/

Query string params:
tag_name:
q:test_string
page:1
type:
exclude_shared:false
per_page:20
tags:
shared:yes
locked:null
only_liked:null
order:updated_at
types:table,remote
```

and the error:
```
ActiveRecord::StatementInvalid (PG::Error: ERROR:  invalid input syntax for type boolean: "null"
LINE 1: ...."type" = 'table' AND "visualizations"."locked" = 'null' AND...
```
a priori I'd say it makes more sense to fix it than exclude it.

**Comment by rafatower** [comment]
Current behavior:
- `locked=true` => locked visualizations
- `locked=false` => non-locked visualizations
- `locked=null` => both locked and non-locked
- absent => both locked and non-locked

**Comment by rafatower** [comment]
Removing [this line](https://github.com/CartoDB/cartodb/blob/editor_backend_refactor/app/controllers/carto/api/visualizations_controller.rb#L42) would partially fix it.
(Anyway, the parameter should not be passed straight to the query builder)

Then [adding this](https://github.com/CartoDB/cartodb/blob/editor_backend_refactor/app/models/visualization/collection.rb#L447-L450) equivalent code to the new controller would make the search work.

cc/ @juanignaciosl to make sure I understood correctly the intent of this issue.

**Comment by juanignaciosl** [comment]
Oh, I see. It looks like `.with_locked(locked)` is duplicated, since [later it's added just if it should be added](https://github.com/CartoDB/cartodb/blob/editor_backend_refactor/app/controllers/carto/api/visualizations_controller.rb#L45). 

I think you're right, deleting that line and adding a partial match method at query builder is the way to go.

It'd be great to move tests covering that part (if any) to the common examples suite before fixing it.

Great!

**Comment by rafatower** [comment]
I'm getting a handle on your code and I do agree with the tests part. That said, I'm finding way harder to write the tests than the working code itself XD

**Comment by juanignaciosl** [comment]
That's a pretty common concern :_). I have two huge pain points:
- Setting test data: many simple test require no less than two users, sometimes an organization, and a couple of tables and visualizations with permissions. That's A LOT of setup. And data coherence is relevant, the use of FactoryGirl is not always straightforward because it skips validations and sometimes validation errors are triggered later because of initialization errors.
- Checking output: validating a whole JSON response is fragile (dates, for example). I've done a "normalization method" but it's far from perfect.

Don't hesitate investing time improving test tooling, it's invaluable. For example, being able to use tests of the previous endpoint on the new is a great safety net, and the simpler they get the more we'll write. During the early stages of refactoring I've done some work but also taken some shortcuts to focus on what I was attempting...

**Comment by rafatower** [comment]
That's a big task in itself

**Comment by juanignaciosl** [comment]
I know, I know ;-) . As usual, unless you have a great idea in mind, I'd just do small steps.
