### ISSUE TITLE
Add option: search for city names in admin1

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3105]
The option to look for city names in adm. regions of level 1 is available in a function, but we're not using it.

This means that we'll be able to search cities in a specific state.

More details here: https://github.com/CartoDB/data-services/issues/128

**Comment by alonsogarciapablo** [comment]
I'm working on implementing this. It involves changes in both the frontend and backend, since our endpoints don't support this option yet. I've tested the PostgreSQL function and it works as expected.

This is how the UI will look like with this change:

![captura de pantalla 2015-04-20 a las 13 32 36](https://cloud.githubusercontent.com/assets/390398/7229247/e0ad3fbc-e761-11e4-978a-793d1966b279.png)

cc/ @iriberri @saleiva

**Comment by iriberri** [comment]
Part of data-services is here: https://github.com/CartoDB/data-services/blob/master/geocoder/namedplace/geocode_namedplace.sql#L22

**Comment by alonsogarciapablo** [comment]
@iriberri I've deployed this to staging (I can chat you the environment). I'd love to have your input and see if it's working as expected :). I've tried with Dover (Minnesota, New Jersey, etc), and it seems to work fine. There are now many different combinations when georeferencing by city:

- Region can be empty, the name of a column with regions, or a concrete region typed by the user.
- Country can be empty, the name of a column with countries, or a concrete country typed by the user.

Also, other types of georeferenciations should still work as before. Thx
