### ISSUE TITLE
metadata offset in profile pages - new dashboard

### ISSUE THREAD

**Issue by auremoser** [CartoDB/cartodb#3245]
I love the new dashboard, but on the profile page, full-screen mode, Chrome browser, the metadata below the map thumbnail in the maps view gets smushed. Not sure why, if it's a character count issue, maybe there should  be a warning about the display limitations when you "Edit Metadata". 

Screenshot:
![metadatafail](https://cloud.githubusercontent.com/assets/1559703/7185359/3376d206-e430-11e4-8fcd-2c6446962c92.jpg)

**Comment by viddo** [comment]
Should be rendered like this: 
![screen shot 2015-04-16 at 18 59 17](https://cloud.githubusercontent.com/assets/978461/7186573/0b2f0ef4-e46b-11e4-8ed3-686be5396238.png)

Seems the requires CSS got changed recently, and this context was not updated accordingly: https://github.com/CartoDB/cartodb/commit/551e2d6b75c2051ce039539d5787d0784576155c#diff-e26124222b6f088b1625d8f7d1dbcb60L59 cc @alonsogarciapablo to be aware

**Comment by viddo** [comment]
..another detail I notice now: we should never override styles from one module to another like done there:
`MapCard-desc { .DefaultDescription { ...`, probably that rule should be moved to a `.DefaultDescription-ellipsed` modified class instead if it needs to be done on that element instead of map card description element.

**Comment by alonsogarciapablo** [comment]
Working on it. I will release a fix pretty soon.

**Comment by auremoser** [comment]
omg you are all so fast! gracias!
