### ISSUE TITLE
CARTODB_UI_VERSION is "undefined" in embed maps and IE

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#3359]
https://my.trackjs.com/messages/filtered?message=%27CARTODB_UI_VERSION%27+is+undefined

**Comment by xavijam** [comment]
So, the option we have chosen is create another JS group for only the embeds, containing:

```
embed: [
    'vendor/assets/javascripts/cartodb.uncompressed.js',
    'vendor/assets/javascripts/cartodb.mod.torque.uncompressed.js',
    'vendor/assets/javascripts/cartodb.mod.odyssey.uncompressed.js'
]
```

**Comment by viddo** [comment]
Another thing I notice now (well I noticed earlier but could not reproduce): when localstorage gets cleared, things like the "onboarding" views gets reset and displayed again (e.g. on create dataset, create map modals). That would also happen when the user login on various devices since it's not persisted on the user profile... Not critical perhaps but rather annoying, especially when the cache is clearer on every version change.

**Comment by javisantana** [comment]
please, do the app.js thing

**Comment by javisantana** [comment]
better in another ticket https://github.com/CartoDB/cartodb/issues/3365
