### ISSUE TITLE
"Share dialog" won't open from the "Change Privacy dialog" when choosing "Password protected" and password is empty

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#3441]
Steps to reproduce:

1. Login with a user that belongs to an org.
2. Open the Change Privacy dialog.
3. Click "Password protected".
4. Click "Share this dataset with your colleagues" on the banner at the bottom.
5. Nothing happens (Share dialog remains hidden).
6. Type a passord.
7. Click "Share this dataset with your colleagues" again.
9. Share dialog is now visible.

[Here's the reason why it's not working](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/new_common/dialogs/change_privacy/start_view.js#L73). Do you remember why we added that @viddo. I'd say we can remove it.

**Comment by viddo** [comment]
It was added because a password is a requirement to be able to change the privacy settings (sharing settings save together with the privacy setting. 

I don't see it as a solution to remove the check, because then the user won't be able to save because the password is still missing, and there's no feedback on why. I figured it was better/simpler to not allow the user to leave the view in an inconsistent state in the first place than having to complicate the other views (share and footer) more with handling this state.

As to make it more clear, I think we could give some visual cue that the sharing link is disabled when switching to the password view and password is missing, or show some message in the footer if empty and not on the start view (but like I said, that complicates the view states). 

Other ideas?

**Comment by alonsogarciapablo** [comment]
As a user, I'd personally expect the Share Dialog to behave as a completely separate dialog (which is the case in all cases except the "Password protected" one). So, if I'm on the "Password protected" tab and I hit "Share this dataset with your colleagues", I would expect the app to let me go ahead and "share with my colleagues". Don't you think? We can get some input from design here.

**Comment by viddo** [comment]
Yep, I think you have some good points. I also brought that up, that these two dialogs should really be separated (because they are separate settings really) when it was implemented, but if I recall correctly it was done like this to be consistent with old modal behavior. 

cc @saleiva

**Comment by viddo** [comment]
Talked with @saleiva and it was one of those things we left as "nice to have" at the time we implemented the new dashboard. So technically not a bug but an enhancement ;)

The correct behaviour is similar to what you suggest:
- "Save" button on share view only persist permission ACL changes
- After sharing changes are successfully changed, takes one back to the start view
- Start view should display amount of users that shares the dataset/map (there should be a sketch screen w/ this state)

Added it to the next milestone (Navacerrada).
