### ISSUE TITLE
Importer can't manage valid SQL API exports

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#3626]
## STEPS TO REPRODUCE:
-------------------------------------------
1. Go to your dashboard/datasets.
2. Click over "New dataset".
3. Add a valid sql export url, for example:
```http://xavijam.cartodb.com/api/v2/sql?q=SELECT * FROM instagram_xavijam&format=geojson```
  - It is public and valid, and you can confirm that trying to download from the the browser.
4. Click over "submit".
5. And then click over "connect dataset".
6. Import fails.

**Comment by javisantana** [comment]
is this because of https://github.com/CartoDB/CartoDB-SQL-API/issues/204

**Comment by rochoa** [comment]
Hey, I don't think that was related to https://github.com/CartoDB/CartoDB-SQL-API/issues/204, because that was a problem with ogr2ogr formats (csv, kml, shp). @xavijam did you get any kind of error message?

**Comment by rafatower** [comment]
I tried to reproduce with this url and it works now: `http://xavijam.cartodb.com/api/v2/sql?q=SELECT+*+FROM+instagram_xavijam&format=geojson`

Mind the spaces, otherwise you'll get a 400 download error, which is correct.

There's been many changes since then and honestly I don't know which one broke/fixed it.

**Comment by xavijam** [comment]
:_) :dancer:
