### ISSUE TITLE
Using OneClick app with a API SQL export url is giving timeouts in the import

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#3645]
## STEPS
- Go [to this public dataset](https://team.cartodb.com/u/xavijam/tables/saleiva.andrew.us_states_hexgrid/public/map) and click over "Create Map" button.
- Once you either create a new account or login to your account, the import fails.
- Checking import log, trying to download from a browser tab or just clicking over any of the export options, it says:
```
error: [,…]
0: "Your query was not able to finish. Either you have too many queries running or the one you are trying to run is too expensive. Try again."
```

I know it is a platform limitation, but it is a pity that new "create map" feature will not work as expected. Could we change public timeout for this kind of operations?

cc @rochoa @javisantana @saleiva @rafatower

**Comment by rochoa** [comment]
Another reference: https://github.com/CartoDB/CartoDB-SQL-API/issues/204

**Comment by javisantana** [comment]
For me this is duplicated

**Comment by xavijam** [comment]
Ok, shall i close it?

**Comment by rochoa** [comment]
One question: is the "create map" only using queries like `select * from table_name`?

If so I would close it as duplicate because you are hitting "Your query was not able to finish" false positives, if you plan to do anything else we will have to think about it. We could still have `select * from table_name` queries taking longer than statement timeout and it's the same problem.

**Comment by xavijam** [comment]
Yep, only ```select * from table_name```, closing then :). Thanks for pointing me to the initial issue.
