### ISSUE TITLE
Creating a visualization from a dataset view doesn't refresh the UI

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#3825]
only does it after refreshing the page. 
Important to fix @javisantana  @Kartones @juanignaciosl

**Comment by Kartones** [comment]
Cannot reproduce in live.

Having 'https://team.cartodb.com/u/kartones/tables/TABLENAME', I click on "Visualize" and I correctly go to `https://team.cartodb.com/u/kartones/viz/VIS_ID/table`.

Maybe something related with new modals? I don't have them active, so will try

**Comment by Kartones** [comment]
Having `new_modals` flag enabled:
From Dataset view, I click "publish" -> "Ok, create a map", the url changes to `https://team.cartodb.com/u/kartones/viz/VIS_ID/table` and if I click cancel I'm already at the Map view.

So, for me this is the expected behaviour and everything is normal.

If fails to you please reopen & provide me with detailed instructions of how to reproduce, expected and actual behaviour and if there's any other special feature flag I should have activated.

**Comment by saleiva** [comment]
It fails. You are not getting the details UI related on this. Gonna show to @xavijam

**Comment by xavijam** [comment]
Taking care of it,

**Comment by xavijam** [comment]
Seems like we have VISUALIZE - PUBLISH button always as "publish", no matter if it is a dataset or map view. Should we change or leave it as it is?

Dataset:
![screen shot 2015-06-01 at 12 02 04](https://cloud.githubusercontent.com/assets/132146/7910569/355eea1e-0856-11e5-9731-9b61d7408ec8.png)
---
Map: 
![screen shot 2015-06-01 at 12 04 09](https://cloud.githubusercontent.com/assets/132146/7910580/5489d2e6-0856-11e5-9567-1d332d7818cd.png)

**Comment by saleiva** [comment]
Yep thats a bug

**Comment by xavijam** [comment]
![dataset-to-map](https://cloud.githubusercontent.com/assets/132146/7911289/53a2d85e-085c-11e5-83f1-b5a6424433a8.gif)
