### ISSUE TITLE
Syncs get queued and blocked

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#3914]
Example:

                  id                  |              name              | interval |               url                |  state  |          created_at           |          updated_at           |
                  1d2d04d8-d8a1-11e4-a11d-0e9d821ea90d | intelcenter_cti                |     3600 |                                  | queued  | 2015-04-01 18:58:41.893565+00 | 2015-06-02 23:13:35.295962+00

Error is:     99999 | Unknown

This happened a week ago in ~15 cases in the total system that I set up to "success" manually according to @Kartones instructions.

**Comment by iriberri** [comment]
Reported again today with 114 new queued syncs in the system

**Comment by Kartones** [comment]
I'm checking and once an import is set as `enqueued` [because is too big for direct frontend upload](https://github.com/CartoDB/cartodb/blob/master/app/helpers/file_upload_helper.rb#L46), the only logic that puls/loads them and operates with them once enqueued is [a Rake](https://github.com/CartoDB/cartodb/blob/master/lib/tasks/import.rake#L26) that should be called by devops, `cartodb:upload_to_s3`.

That rake should be called by some cron. Somebody from devops should check that the cron didn't failed, or if all failed syncs were from the same machine, etc., but APIs don't do anything outside that rake.

**Comment by santisaez** [comment]
We've been logging `cartodb:upload_to_s3` task output during the last week and we have not seen anything. As agreed with @Kartones and @iriberri we're going to move this ticket to the next milestone :)

**Comment by iriberri** [comment]
0 queued!
