### ISSUE TITLE
Can we reduce redis commands [from the editor]?

### ISSUE THREAD

**Issue by rochoa** [CartoDB/cartodb#3943]
In development environment with SQL API, Maps API and Rails app running (resque was stopped) I started `redis-cli monitor` and tracked the number of commands.

I got:
```
cut -d ' ' -f 4 | sort | uniq -c | sort -nr
780 "ZSCORE"
  26 "get"
  10 "del"
   6 "select"
   6 "info"
   4 "unwatch"
   4 "hmget"
   4 "hget"
   2 "HMSET"
   1 "hset"
```

ZSCORE commands are requesting things like `"ZSCORE" "user:development:mapviews_es:stat_tag:3d5ce24a-c907-11e4-b2fc-6476ba93d4f6" "20150507"`. Do we need that somewhere in the editor for the map?

**Comment by lbosque** [comment]
That query is probably run by the visualizations list view because it needs the last 30 days of map views in order to draw a small graphic in the visualization preview.

/cc @xavijam

**Comment by xavijam** [comment]
yep

**Comment by rochoa** [comment]
Sorry if I didn't explain myself really well, I meant went you open a Map in the editor view, like in:

![screen shot 2015-06-15 at 16 47 58](https://cloud.githubusercontent.com/assets/45346/8162552/5c2694de-137e-11e5-9f79-41789ea55951.png)

**Comment by rochoa** [comment]
@javisantana I'm reassigning to you so you can decide who can handle it.

**Comment by javisantana** [comment]
the problem is, everytime we load Visualization model the extended stats (*) are fetch from redis, that launch 60 ZSCORE commands.

The proposal is not load extended stats on public pages (since they are not needed) and doing it in /api/v2/vis endpoints.

In a second phase we will add a flag in /api/v2/vis so frontend can request or not the extended stats.

The extended stats could be also cached for some time since it's not that important to know minute by minute the visualization count per day.


(*) there are 2 kind of stats:
  - extended which get stats for every day
  - count: only fetch the count (see the PR https://github.com/CartoDB/cartodb/pull/3719/files)

**Comment by juanignaciosl** [comment]
Team maps page is also very slow, probably because of this as well.
