### ISSUE TITLE
Infowindow on hover is not rendering any data outside the editor

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#3949]
http://team.cartodb.com/u/saleiva/viz/saleiva.9395c832-ea0b-11e4-9dfc-0e9d821ea90d/embed_map

vs 

https://team.cartodb.com/u/saleiva/viz/9395c832-ea0b-11e4-9dfc-0e9d821ea90d/map

**Comment by alonsogarciapablo** [comment]
How did this happened? When did I become Mr.Infowindow? :-P

**Comment by saleiva** [comment]
I thought you fixed this the last time!

**Comment by alonsogarciapablo** [comment]
It wasn't related to what I fixed last time. The problem here is that the layer with the police districts is on top of the other two layers and interaction isn't working properly cause we're always hovering that layer. If you reorder the layers and send that layer "to the back", it will work.

I'll fix it in `cartodb.js` anyway :smile:
