### ISSUE TITLE
Unlock/lock dialog appears when visits a shared dataset.

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#4005]
#### STR:
1. Having two users (A and B) in an organization.
2. Create a dataset with user A, and then lock it.
3. Share that dataset with user B.
4. Log in with user B.
5. Visit the dataset that user A has shared with you (B).
6. Lock/unlock dialog appears saying it is locked.

#### WHAT SHOULD HAPPEN:
- Dialog should not appear because lock or unlock should only affect owner user.

**Comment by javierarce** [comment]
Which dialog are you referring to?

**Comment by viddo** [comment]
I think this one:
![screen shot 2015-06-15 at 14 51 10](https://cloud.githubusercontent.com/assets/978461/8160213/01810204-136e-11e5-8224-140b0a163cf7.png)

**Comment by xavijam** [comment]
No, the dialog that says: "This visualization/dataset is locked, do you want to unlock it?"

**Comment by xavijam** [comment]
![screen shot 2015-06-15 at 14 52 16](https://cloud.githubusercontent.com/assets/132146/8160224/24343e92-136e-11e5-96b1-5f4378274768.png)

**Comment by javierarce** [comment]
Ok, thanks!

**Comment by viddo** [comment]
Ah, I forgot about this one… 

however:
> Dialog should not appear because lock or unlock should only affect owner user.

I'm not sure this is really the expected/desired behavior here. This modal replaced the old one, both the new and old works in the same way, i.e. block the user (owner) from even seeing the dataset until it's unlocked.  How did this work using the old modals for a shared dataset?

**Comment by javierarce** [comment]
I agree with @viddo, the problem is not the dialog itself, but allowing to continue and make changes to a dataset was locked by the owner.

**Comment by xavijam** [comment]
As I said, there is no problem with old/new dialogs, it is just the behaviour. Not sure what should we do, but definitely that shared user should not know about if the vis is locked or not...

**Comment by javierarce** [comment]
After thinking it for a while, I'm not sure which solution is better.

In my opinion, locking a dataset is useful because prevents me from changing it by mistake. If I share a locked dataset with another person, it can make sense to apply the same restriction (this is what we have now). On the other hand, it could be a good idea to restrict the other user for making changes altogether (and thus removing the possibility of any change, accidental or not).

There's a third option (which I don't really like) which is to allow full editing to the users the dataset is shared with. I don't like this option because it removes the warning (other users won't be aware that I have locked the data).

We need to make a decision. I vote for the first option (which means we don't do anything, since it's the solution we already have), although option 2 is reasonable too.

@xavijam, @viddo, @saleiva… what do you think?

**Comment by saleiva** [comment]
solution #1 is fine

**Comment by javierarce** [comment]
Ok, thanks! The only change I'll make is to the text of the modal:

![screen shot 2015-06-15 at 17 41 12](https://cloud.githubusercontent.com/assets/4933/8163846/d216844a-1385-11e5-8628-2dd47715cd9f.png)
