### ISSUE TITLE
Can't load WMS basemap

### ISSUE THREAD

**Issue by danicarrion** [CartoDB/cartodb#4057]
I can't add this WMS basemap to a visualization:

http://api.maps.vic.gov.au/geowebcacheWM/service/wms

I can select the layer, but no basemap is loaded after that. I can see the basemap without problems in http://mapviewer.org/

**Comment by jsanz** [comment]
I can't add also this other WMS server as a basemap

http://maps.six.nsw.gov.au/arcgis/services/public/NSW_Imagery/MapServer/WMSServer

This one is not even recognised so I can't select a layer but it works without problems in QGIS.

Worth to note that the first one reported comes from a [GeoWebCache](http://docs.geoserver.org/stable/en/user/geowebcache/index.html) service and mine is an ArcGIS Server one so different implementations of the WMS standard.

cc. @viddo @javisantana

**Comment by viddo** [comment]
@jsanz that one works for me™, so perhaps is the circumstances you describe, I'm not familiar with that setup:
![screen shot 2015-08-24 at 16 08 39](https://cloud.githubusercontent.com/assets/978461/9443164/e16c6fd2-4a7f-11e5-8299-8eb5b2caae0c.png)

**Comment by viddo** [comment]
@danicarrion the URL provoks 503 errors on the WMS proxy, need to investigate further.

**Comment by jsanz** [comment]
@viddo thanks yeah, now it's working that Australia WMS, thanks for re-chekcing :pray:

**Comment by viddo** [comment]
@danicarrion so now it seems to work for the reported URL to: 
![screen shot 2015-08-27 at 12 53 06](https://cloud.githubusercontent.com/assets/978461/9518918/f34b1374-4cba-11e5-8098-3f8fcac76592.png) so it seems like the service is not returning a correct layer URL. 

The problem was that the mapproxy cached the first result (the internal IPs), so following requests were not going to work obviously. The solution was to remove the cached result and restart the service. While that solved this particular case it's possible that this happens again in the future, we'll continue the discussion in the reported issue [@jsanz created](https://github.com/omniscale/cartodb-wmsproxy/issues/1)

Re-open the issue if this still fails.

**Comment by danicarrion** [comment]
thanks!
