### ISSUE TITLE
Can't scroll table rows in a read-only dataset shared with you

### ISSUE THREAD

**Issue by mnquintana** [CartoDB/cartodb#4123]
Currently, you can't scroll tables rows in a read-only dataset shared with you - if you have write access though, then scrolling works as expected. This is quite an issue for us - we have groups we would like to share our datasets with completely within CartoDB, and that's currently not possible unless they only look at the map view.

Related to https://github.com/CartoDB/cartodb/issues/2906

**Comment by saleiva** [comment]
We should stop linking to the public page and link to the read-only dataset view. Assigning to @xavijam

**Comment by xavijam** [comment]
I've just checked it and I feel the problem could come from a backend bug. Seems like it redirects to the public dataset page and not to the table view.

If we check the url:
![screen shot 2015-07-08 at 12 10 54](https://cloud.githubusercontent.com/assets/132146/8568024/73142f3c-256a-11e5-8826-85448f01c4db.png)

But it goes to:
http://theteam.localhost.lan:3000/u/cartofante/tables/saleiva.shared_table/public/map?redirected=true

cc @CartoDB/backend

**Comment by Kartones** [comment]
This hasn't been touched since multiuser... See https://github.com/CartoDB/cartodb/blame/master/app/controllers/admin/visualizations_controller.rb#L52 (for the lazy: *Jul 23, 2014*)

In fact now with the oneclick is even better because you see the readonly table and if you click on "create map" you get your copy.

But anyway, if it is a backend bug has more than 1 year

**Comment by xavijam** [comment]
More reasons to fix it! :dancer:

**Comment by ethervoid** [comment]
After checking I have to say @Kartones is right, this was blocked for a reason. After change to open the editor in read only mode there are some considerations to take into account:

* You have the option to geocoding the table
* You can merge tables 
* We have to verify and test that the current user can't do owner actions.

We can take two sides:

* We can activate scrolling in the public visualization table (scrolling is the only required action)
* We can modify the editor to check for shared permissions and disable non-possible actions along with check for all possible scenarios to avoid security issues (updates, inserts, etc)

What do you think?

// @javisantana @xavijam @Kartones

**Comment by xavijam** [comment]
First, read only mode:

- 'Geocoding' option is disabled in read only mode.
- 'Merge datasets' option is disabled in read only mode.
- You can't "edit things" in read only mode, this is tested and working, for example, with "sync" datasets.

Then:
- Public dataset (not visualization) page has the scroll limitation by design, we will revisit the UI in the next iteration, but for the moment it will work as it is.

Opinion: we had this behaviour working in the past. Shared (read only) datasets could be visited through the private table view, and shared visualizations were visited through public view.

**Comment by Kartones** [comment]
Allowing a "Editor edit mode in readonly" was removed when building the MU because had issues. 

If you want it back is going to be a hell of FE changes and QA/testing to be 100% sure it doesn't behaves wrongly in the editor. We took the pragmatic/simple approach because "automatically disallows edition" (not having it :stuck_out_tongue: ), the alternative is a non-trivial editor work of having a edit in readonly mode. For the backend is only removing 5 lines of code and as much as flagging the edit as in "read mode". 

I don't see why just fixing the public view scroll is so bad, when you avoid code complexity (handling both edit and read modes inside the editor), is way less effort, the open in cartodb button is there so you can actually copy the table (inside the editor I am not even sure this will work), etc.

This can easily go out of scope for a "simple change", and if we decided in the past to go with the public map/table view for readonly-shared stuff was probably to avoid all this not-superficial problems.


That said, I'm not the one in charge, whatever approach is taken I'll help with, as always. Is just that I sincerely think avoiding a fix will trigger a cascade of potential issues in another area that now works fine.

**Comment by ethervoid** [comment]
Finally what should be done here?

**Comment by ethervoid** [comment]
After talk with @javisantana this should be done by frontend people activating the scroll in the public tables

**Comment by javisantana** [comment]
not sure if this makes sense for this milestone tho

**Comment by saleiva** [comment]
Nope. We are redesiggning the public view so... let's keep this closed for the time being
