### ISSUE TITLE
Missing support for plain background/background url layer at named map

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#4126]
@Kartones new definition:
Documentation for plain bg/image bg layers was missing at [windshaft](https://github.com/CartoDB/Windshaft/blob/0.44.1/doc/MapConfig-1.3.0.md), so was wrongly implemented as just an `http` layer with empty urlTemplate.
They use a different format and layer type instead of `http` (`plain` with a `color` property, and other field for background url). Implement them properly.

Old definition:
<hr>
for example, this: https://javi.cartodb.com/api/v1/map/static/named/tpl_7a99951e_aba7_11e3_b843_0e10bcd91c2b/300/300.png

steps:
- create a visualization with plain color baselayer
- add a cartodb layer
- request the static map

I guess it's because backend is not dealing properly with plain baselayers (take into account we have WMS layers too which can be translated to http ones)

**Comment by Kartones** [comment]
note to self:
- vis is not broken, `save_named_map` doesn't raise any error
- other vis with plain bgs work (just return a null urlTemplate)
- the error is coming from windshaft, so the issue is not a bad reading of layer types but somehow not storing the layer field inside the named map http layer.
