### ISSUE TITLE
Couple of bugs related with quota indicators

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4177]
![screen shot 2015-06-23 at 20 38 55](https://cloud.githubusercontent.com/assets/132149/8314160/eecc041c-19e7-11e5-9468-378f04be6a16.png)
![screen shot 2015-06-23 at 20 39 05](https://cloud.githubusercontent.com/assets/132149/8314161/eed0d154-19e7-11e5-9010-2db822521512.png)

- The bar on the dropbdown should be clickable and take the user to the account page
- Bar is colored different based on the place. The yellow is the correct color.

**Comment by xavijam** [comment]
Do we need to link the progress bar in the user settings dropdown? We already have the upgrade link (yo u don't see it under your account because you are not an organization admin).

![screen shot 2015-06-29 at 14 19 13](https://cloud.githubusercontent.com/assets/132146/8407727/ff5f0208-1e69-11e5-9d8e-cf0deae9a564.png)

**Comment by saleiva** [comment]
Make it all clickeable!

**Comment by xavijam** [comment]
Sure! :D
