### ISSUE TITLE
NoMethodError: undefined method `id' for nil:NilClass at visualizations#is_liked

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#4181]
cc @kartones @rafatower 

https://rollbar.com/vizzuality/CartoDB/items/8015/?item_page=0&#instances

```
NoMethodError: undefined method `id' for nil:NilClass
1
File "/home/ubuntu/www/production.cartodb.com/releases/20150624073318/app/controllers/carto/api/visualizations_controller.rb", line 68 in is_liked
... 6 non-project frames
8
File "/home/ubuntu/www/production.cartodb.com/releases/20150624073318/app/controllers/application_controller.rb", line 54 in wrap_in_profiler
... 67 non-project frames
```

It's because `current_viewer` is `nil` at `liked: @visualization.is_liked_by_user_id?(current_viewer.id)` .

**Comment by Kartones** [comment]
mm yep, was wrongly migrated [from old code](https://github.com/CartoDB/cartodb/commit/2c498ae57eafcb017851c5f2964efa0679cab361#diff-43e04d2a17aabf8ee19c1a3dc98d2f0bL343), because there can be no `current_user` for likes (think this appears at embeds, public_maps, etc. so it's common to not have opened sessions.

Can you handle it or do you want me to work on it?
