### ISSUE TITLE
EPSG:31258 is not correctly detected by ogr2ogr

### ISSUE THREAD

**Issue by danicarrion** [CartoDB/cartodb#4200]
Reported to GDAL here: http://trac.osgeo.org/gdal/ticket/6011

**Comment by rafatower** [comment]
I tried to import that file and despite the mentioned issue with SRID constraint not being set in ogr2ogr the file mentioned in the gdal ticket is flawlessly imported. Shall I close this ticket @danicarrion ?

**Comment by danicarrion** [comment]
Have you checked the projection is ok? I mean, the original problem was that the file seemed to be imported alright (no errors) but the geometries weren't reprojected into 4326 (they were assumed to be already in 4326), which meant the visualization was broken.

**Comment by rafatower** [comment]
I haven't, I just checked that it looked nice on the map ^_^

https://team.cartodb.com/u/rtorre/tables/tonnage

But there's something we've changed in cartodbfy process since you opened the ticket: we always reproject to 4326 and as long as the GEOMETRY has SRID it should go fine even if the table does not have the SRID constraint as part of its metadata.

https://github.com/CartoDB/cartodb-postgresql/blob/master/scripts-available/CDB_CartodbfyTable.sql#L1054-L1087

To some extent the ticket in gdal still makes sense. But being pragmatic, there's no issue per se in this repository and now it fits the bill when imported, end-to-end, so personally I'd close this ticket

**Comment by danicarrion** [comment]
makes sense, so go ahead and close it

thanks!
