### ISSUE TITLE
Detect and report invalid encoding imports if no rows created

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#4223]
In some scenarios, like https://github.com/CartoDB/cartodb/issues/3919, we are not giving to the user any feedback and just creating an empty table.

A way to handle some of this errors and properly notify is to check if ogr2ogr had errors with similar format to:
```
 has no equivalent in encoding "UTF8"
```
and if they do, and the resulting table has 0 rows (which can be interpreted as "everything failed"), we can return a new import error to inform that the encoding was wrong.

Text proposal:
```
Encoding error (xxxx)
The file you tried to import failed due to encoding issues. We recommend you to open it with a tool like [QGis](http://qgis.org/) and export in "UTF-8" format.
```

**Comment by saleiva** [comment]
The file you tried to import failed due to encoding issues. To fix this, force the encoding of your file using a text editor or a tool like [QGis](http://qgis.org/). You just need to export your files in "UTF-8" format.

**Comment by javisantana** [comment]
but if QGIS is able to load it, why don't we load it?

**Comment by Kartones** [comment]
Because QGis allows probably any encoding, our DB tables are UTF-8. Anyway @ethervoid is testing trying to cast when ogr2ogr gets called to try to do precisely this (or at least try to automatically convert).

**Comment by ethervoid** [comment]
I have one question: If while ogr2ogr its trying to import rows to `pg` detects errors in a few of the rows of the file, what is the policy to follow? we make the import fail completely or we skip that failures from the total rows and keep importing the right rows

**Comment by Kartones** [comment]
That was what the ticket was originally about: We let it continue (skip that row) if it finds an error reading a single line. The "trick" is that if resulting table has 0 rows all were invalid so then we should actually fail :stuck_out_tongue:

**Comment by ethervoid** [comment]
Related #4223

**Comment by ethervoid** [comment]
I've been searching about this issue this weeked and I've discovered some points about the import of `shp` files:

* The encoding detector either `chardet` (python) or `charlock_holmes` (ruby) doesn't work properly. One of the main problems is that it detect LATIN1 as UTF8 (primarily because `chardet` doesn't support detection of ISO-8859-1 a.k.a LATIN1).

* `chardet` is going to relase a new version with the Hungarian detector disabled because interfere with other detectos and return false positives

* `ogr2ogr` import to Postgresql is based on transactions, it use the attribute `-gt` as the number of rows per transactions. Per default is 20000 in the version 1.11.0. This leads to massive data loss when an encoding error arise in the postgresql import.

* I've been testing how to detect encoding of `shp` files properly but I couldn't find a proper solution. If one file works, other gives me failure and I'm only working with 3-4 files :S

**Possible Solutions**

Apart from implementing the solution given above (return error if the number of rows imported is 0) I'd like to share some improvements to this question and talk about it :)

* One of the firsts solutions is to measure the data loss we are having sending to `statsd` the percentge of error in the `shp` files data import (rows imported \ total rows)
* I'd send the type of file too, to measure how many `shp` files we are importing every day.

Given this two we could estimate how much time we should spend improving this.

* Now I'm going to try a possible fix converting `shp` files to `csv` files with UTF-8 encoding and then import to Postgresql. This will import all the rows but with some bad encoded rows. (For example QGis open files with bad encoding rows). This would expensive but could work
* The best solution but the most expensive is to introduce imports with warnings reporting to the user that the file was import but with errors. 
* Other solution is to create a huge transaction and fail with every error (I don't like this solution but I put here to take into account)

**Comment by Kartones** [comment]
About improvement ideas:
- If a CSV has invalid encoding/encoding issues, careful as the whole CSV import will break. I guess you mean export from SHP to CSV and in that process remove those wrong.

In any case importing data that is not full without notifying the user IMHO is wrong, we give the false appearance that all went ok and then there are missing rows. I suggested a while ago implementing post-import feedback too, to inform of "partial imports" or "imports finished but with errrors", because things are never just black or white, we sometimes cast/convert/skip stuff.

But 200% agreed on adding metrics to see how good or bad we do before trying to chagen a lot for then a small real world usage.

**Comment by juanignaciosl** [comment]
Converting SHP to CSV looks like a huge and dangerous overkill to me :-\ What about the "retry with another encoding" fallback? If it solves this case it can be enough and won't affect working imports.

**Comment by ethervoid** [comment]
That was a test to check if it's possible but it doesn't work properly neither.

There is one case where we can do fallback a WIN1252 file that fails and we try to use LATIN1, but even in that way we have encoding issues caused because WIN1252 is not equals to LATIN1 between chars 128-159 (http://www.i18nqa.com/debug/table-iso8859-1-vs-windows-1252.html)

**Comment by juanignaciosl** [comment]
Ok, dismissed then.
