### ISSUE TITLE
Error importing from gzipped url

### ISSUE THREAD

**Issue by jsanz** [CartoDB/cartodb#4254]
The importer fails when on the editor using a url of a gziped geojson. The trace on the logs are:

```
2015-06-30 17:37:16 UTC: Fetching datasource public_url metadata for item id https://URL_TO_THE_GZIPPED_GEOJSON.gz
2015-06-30 17:37:16 UTC: File will be downloaded from https://URL_TO_THE_GZIPPED_GEOJSON.gz
2015-06-30 17:37:17 UTC: Before importer run
2015-06-30 17:37:17 UTC: Starting import for /tmp/imports/20150630-29162-jhrr71/Campground.geojson.gz.tgz
```

Uploading it from a local file works so it's only affecting a task that come from urls.

**Comment by ztephm** [comment]
ref S/B 5801732

**Comment by javisantana** [comment]
what is the issue? is there any error?

it's weird because the file downloaded is gz but the extension is tgz

**Comment by jsanz** [comment]
The download url ends with `.gz`, you can download it and imports normally from my local file system.

But when you put that url on the importer, it seems it adds that `.tgz` and falis.

**Comment by Kartones** [comment]
then probably the Downloader importer class is not detecting the content-type header, or mismatching it for another, and adding that extension.

I changed that recently due to another user having issues. Can you please inspect the content-type returned and see if might mismatch with this? https://github.com/CartoDB/cartodb/blob/master/services/importer/lib/importer/downloader.rb#L82

**Comment by jsanz** [comment]
```
θ64° [jsanz:~/tmp] $ curl -I "http://url.tot.this/file.geojson.gz"
HTTP/1.1 200 OK
Content-Type: application/x-gzip
Content-Length: 53670
Connection: keep-alive
Date: Thu, 02 Jul 2015 13:22:22 GMT
Cache-Control: max-age=60, public
Last-Modified: Thu, 02 Jul 2015 13:11:25 GMT
ETag: "059fa369ecfc42268a064831d75e1d20"
Accept-Ranges: bytes
Server: AmazonS3
X-Cache: Miss from cloudfront
Via: 1.1 cc3cdd1309dd3b161a9cbde2b5afec87.cloudfront.net (CloudFront)
X-Amz-Cf-Id: tAF2wKUA-nyYGqLf9qhoToCcyIqTyFaHkoE2iiwjWlxXz376ApPZiQ==
```

**Comment by jsanz** [comment]
Hi we've found the source of the problem on this, `unp` is not being able to uncompress the file with that `.gz.tgz` filename end

```
θ61° [jsanz:~/downloads] $ unp Trailhead.geojson.gz.tgz 
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
Cannot create target Trailhead.geojson.gz.tgz: file already exists. Trying alternative targets...
Suggested target name: Trailhead.geojson.gz.tgz.unp
WARNING: There were errors while processing files!
```

**Comment by Kartones** [comment]
but you said it works locally no? when you download the file has also the same name? 
take into account that unp is called in both scenarios, local upload or url-based, but when coming from url-based if content-type comes and exists in the list I mentioned before but doesn't matches with extension, "correct extension" is added (for example to handle "download.php" files that only have content type).

That's the point that makes me unsure, if is an unsupported extension it should either fail in both cases or work always. That's why my guess is that is messing up given extension + content type when comes from URL.

**Comment by jsanz** [comment]
My tests

- Download the file (ended with `.gz`) and upload it to cartodb :white_check_mark: 
- Uncompress the file locally `unp file.gz` :white_check_mark: 
- Rename tha file appending `.tgz` and try `unp file.gz.tgz`:x:

Apparently the importer when it downloads the file from an url renames it appending `.tgz`at the end and then fails.

It's a problem with `unp`, I tried with another geojson file and it's the same. Add that `.tgz` extension to any gzipped file and it won't uncompress it.

**Comment by Kartones** [comment]
That's what I wanted to read ;) Then it confirms my theory, and probably the fix is just checking the header.

We recently had other user having similar issue with `tgz`, so maybe both `gz` and `tgz` share the same header, I haven't tried, would be interesting to research and act accordingly.

Thanks!

**Comment by ethervoid** [comment]
Please recheck @Kartones because there are changes. I've added unit tests to check differents Content-Types and I've refactorized the code to be more clear

**Comment by ztephm** [comment]
Thanks! FYI I notified S/B 5801732 it was fixed.
