### ISSUE TITLE
Lock icon not updating on privacy change

### ISSUE THREAD

**Issue by gfiorav** [CartoDB/cartodb#4312]
Inside a dataset view, the upper left lock icon doesn't change color when privacy settings are changed using the "edit" unless the page is refreshed or the dataset is reentered. The behavior is as excepted clicking on the lock icon directly instead of using the "edit" menu.

To reproduce the problem:

1. Go into any dataset
2. Use the "edit" menu and click on "Change privacy"
3. Change the privacy to another setting.
4. The lock on the upper left does not change color as it should.

**Comment by viddo** [comment]
This happens because the options menu is actually not using `master_vis` ("master visualization"), but the [`this.options.visualization`](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/table/table.js#L62) (current vis being edited), so we're not using the same model as is used in the [header](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/old_common/header.js#L190) (which uses `master_vis`).

It's been like this since [fixes update table when geocode, fix #1934](https://github.com/CartoDB/cartodb/commit/52eca2cfc8b90d27945d6ef6ac9b005d22aff0d9), looking at the code at that point in time I guess it made sense since the [`this.table`](https://github.com/CartoDB/cartodb/blob/52eca2cfc8b90d27945d6ef6ac9b005d22aff0d9/lib/assets/javascripts/cartodb/table/header/options_menu.js#L42) was derived from the given vis model (which is the actually [used model for the geocoding](https://github.com/CartoDB/cartodb/blob/52eca2cfc8b90d27945d6ef6ac9b005d22aff0d9/lib/assets/javascripts/cartodb/table/header/options_menu.js#L238-L241)). 

But since then things have changed, [now the table is set from the given dataLayer instead](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/table/header/options_menu.js#L44), so the [comment](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/old_common/header.js#L113-L114) is no longer valid.

AFAIK, the `master_vis` should be the correct model to use, so we should probably [change the model given to that](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/old_common/header.js#L113-L114), i.e.:
```
- // use the current visualization instead the master one
- model: this.options.visualization,
+ model: this.model, // master_vis
```
There are more stuff in the [`options_menu` view](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/table/header/options_menu.js) that's possibly not using the correct model (e.g. lock/unlock, duplicate, permissions) either.

@javisantana since you did the last change, can you confirm if my change proposal makes sense? Testing this locally seems to work fine, but want to be sure I have the correct mental model here.
