### ISSUE TITLE
Upgrade your account link is wrong on organizations

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4402]
it should be a enterprise-support@cartodb.com
Also it should be hidden for users that are not the admin.

**Comment by juanignaciosl** [comment]
1. Do you mean this link should be a mailto?

![screen shot 2015-07-13 at 09 25 13](https://cloud.githubusercontent.com/assets/932968/8644664/26a4f818-2941-11e5-8d5a-c73cf5a98b9d.png)

2. Where have you found an upgrade link for non-owners? I can't reproduce.

**Comment by saleiva** [comment]
This was @andrewxhill  or @namessanti. Guys can you provide some more info?

**Comment by andrewxhill** [comment]
adding @andrewbt to correct me if i'm wrong.
but i think this was for users within the organization. if they reached their quota they still got a link to the upgrade page as a notification, instead of an "email your admin", speaking of which,

https://github.com/CartoDB/cartodb/issues/4465

**Comment by juanignaciosl** [comment]
I see this message at import time, this should be improved but I think it's not what you mean.

![screen shot 2015-07-15 at 15 52 07](https://cloud.githubusercontent.com/assets/932968/8700007/ac453cc0-2b09-11e5-842e-9f7d41f84a93.png)

I've also seen that clicking your quota is a plan link (although it doesn't work) and should be disabled for org users.

![screen shot 2015-07-15 at 15 54 29](https://cloud.githubusercontent.com/assets/932968/8700026/cc4f5c30-2b09-11e5-8e7c-ca9e55d8a72b.png)

I'll wait for @andrewbt details on this to fix this details as well.

**Comment by andrewbt** [comment]
This is the upgrade your account link in #4227 . It goes to http://cartodb.com/account/umap-admin/upgrade, which an Enterprise user should never see because that page talks about the standard/personal plans.

This link should really just be a link to sales@cartodb.com or enterprise-support@cartodb.com , whichever is most appropriate (probably enterprise-support)

**Comment by juanignaciosl** [comment]
I've seen that link is in several places right now. After talking to @saleiva, instead of changing every upgrade link for the owner we'll link to organization owner plan page:

![screen shot 2015-07-16 at 16 13 58](https://cloud.githubusercontent.com/assets/932968/8725851/f0add908-2bd6-11e5-8c1b-3ec8b5f84c4c.png)

And this page will be redesigned by @josecruz (CartoDB/cartodb-central/issues/715) to support this use case of "I'm the owner of the organization and I want to upgrade something.

I'll continue with this after redesign.

**Comment by saleiva** [comment]
This will be redesigned so closing
