### ISSUE TITLE
Error after 20 imports through api of table with the same name

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#4586]
There's a user who is doing this every X minutes:
- Import file through Import API. Since the file has already been registered previously it's registered/renamed as filename_1, filename_2...
- Update original table (trunc + insert-select) with new values.
- Drop new table.

The problem with this is that since they don't enter the dashboard ghost table cleanup is not triggered so nonexisting tables are not unregistered and imports beyond 20 fail ([error](https://rollbar.com/vizzuality/CartoDB/items/426/occurrences/6646001684/)).

Possible solutions:
- Trigger ghost tables before importing through the API.
- Trigger ghost tables once on first renaming attempt.
- Trigger ghost tables on table drop or table creation.
... ?

@javisantana @Kartones

**Comment by Kartones** [comment]
I'd say none of them if we're going through an import.

Ghost tables register is fully async, so just triggering it won't guarantee we have "everything in order" before the import starts... and I'm really afraid of issues in the step when we're moving the data between schemas.

What we could actually do instead is, if the import fails due to too many renames (detecting this scenario, that is), then afterwards trigger the ghost tables. What do you think? That would also solve the issue no?

**Comment by juanignaciosl** [comment]
Well, I thought about being more explicit but then I forgot to write this: "trigger ghost tables _synchronously_, in the same job import is running". Job's already async, this is not a problem. I'm not so sure about this solution, but I prefer this to your proposal, since this way we avoid errors.

Anyway, something about this doesn't feel good to me, not sure what :-\

**Comment by Kartones** [comment]
The thing is that import itself should not know about rakes, ghost tables, etc. (and doesn't right now), that's why I was looking at an approach of "fail, then at an upper level fix".
We have already violated the knowledge part because the importer had to know about platform limits, some user data, etc. but if chasing your solution I'd make the link + import go in the resque job code, not inside the importer itself...

In any case, for me the real proper way of having ghost tables run is a daemon that visits active users and runs the ghost tables link check upon them... but how we detect properly active users? how we avoid Ruby OOMs? etc.

**Comment by javisantana** [comment]
Let's be clear, the right way to do thing is to enable ddl_triggers and ping cartodb api to register/unregister new tables on create/drop from sql api. 

Said that, the solution you propose about running ghost tables would work, but take into account is not the final solution.

cc @pramsey
