### ISSUE TITLE
Update mockups, add order

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4633]
- [x] Dashboard-1.5-responsive and dashboard-1.6 to be unified and updated to the latest production version. 
- [x] Public-map-dataset-2.3 check headers 
- [x] Create-map-1-7. Check headers, Get the map-in-cartodb scenarios to another file since it's not part of this app (should be in 04-Map-on-cartodb). Order the pages.
- [x] Configuration. That should be part of the multiuser settings mockups.
- [x] Multiuser. Update with the latest version that is on production. 
- [x] Merge tables. Should be part of the map editor mockups as a modal.
- [x] Upselling. Should be unified to the different mockups (dashboard, editor,... ) where there are these usecases.
- [x] Unified headers and footers. Merged to the other mockups.
- [x] New editor -> Take margins on layers widget within the Layer Design artboard to the others.
- [x] Update email templates with current states
- [x] Update headers

**Comment by josecruz** [comment]
`Dashboard-1.5-responsive` & `dashboard-1.6`unified. Created `dashboard-1.7` instead and renamed folder to `02-current-dashboard` 
Could you please review it? 
Alse, what should we do with the rest of folders inside `01-Dashboard`?

**Comment by josecruz** [comment]
Just cleaned up email templates sketch and folder. I was wondering if there's any list with the mails that are already in production (to replicate it in the sketch file). Also, are we going to use this kind of buttons on the emails?
<img width="206" alt="screen shot 2015-08-07 at 00 43 17" src="https://cloud.githubusercontent.com/assets/596509/9125872/5c631a10-3c9d-11e5-95f1-e25d42f6aa88.png">


/cc @matallo

**Comment by matallo** [comment]
there isn't but I can provide you one:

**cartodb:**

- map liked
- new_organization_user
- share_table
- share_visualization
- share_visualization
- unshare_visualization
- data_import_finished
- geocoding_finished

**cartodb-central:** (to be migrated to new templates)

users
- map_views_warning (deprecated)
- geocodings_warning
- over_geocodings
- over_map_views (deprecated)
- over_twitter_imports
- twitter_warning

actually I'm creting an issue to remove mapviews limitation

system
- account_change_notification
- alert_notification
- api_failure
- notification
- organization_overquota_notification
- overquota_notification

then we have tech metrics and business metrics reports

the rounded corners don't work on mobile because when action is too long it breaks in two rows (see attached

![buttons](https://cloud.githubusercontent.com/assets/36676/9130086/9122d1ea-3cdf-11e5-8c70-35bc8515bc37.png)

**Comment by josecruz** [comment]
Thanks @matallo!! Already updated with some things that were missed.

@saleiva which mails should we recreate?

**Comment by josecruz** [comment]
Okay, updated some of the emails @ethervoid sent to me. There are a few that he couldn't reproduce (warnings). 

Also, I'm still revising the upselling file, but just need a review to ensure.
