### ISSUE TITLE
infowindow links in iframe-embedded maps open new pages in iframe, not _parent

### ISSUE THREAD

**Issue by ohasselblad** [CartoDB/cartodb#4662]
Reported from user. Didn't have the issue first few months of the year, but did have the issue in the last three or so months. Maybe related to @viddo's work on xss sanitizing?

## How to recreate

1. Create a map with links to external pages in the infowindows
2. Embed map in a webpage using iframe code
3. Click on a link and it will open in the iframe window instead of the main browser window

Without realizing the previous behavior, I encountered the same problem at our [trainings repo](http://cartodb.github.io/training/) but solved it by putting `<base target="_parent" />` in the main html file. Source here: https://github.com/CartoDB/training/blob/gh-pages/workshops_map.html

**Comment by viddo** [comment]
Hmm, no this sounds like something else, the sanitizing changes should not have this kind.

Without having more context information about that particular user, in theory one could add that `target="_parent"` attr to the links manually. But for both solutions that would require the user to know this pesky detail related to iframes.

Either way, I'm closing this because this is not an issue we can solve in this context (this repo/cartodb editor). 

If we want to support links to [break out from the iframe](https://css-tricks.com/snippets/javascript/break-out-of-iframe/) it's something that would have to be solved by [CartoDB.js lib](https://github.com/CartoDB/cartodb.js/), so I suggest to create an issue there instead in that case.

Does that answer your questions?

**Comment by ohasselblad** [comment]
Thanks @viddo, moving there.

Got the links to original maps: They were [here](http://guides.newman.baruch.cuny.edu/nyc_data/nbhoods) but user changed page so that iframes are not there to avoid the issue. He made them click through to original maps instead.
