### ISSUE TITLE
Twitter user defined % limit not being sent correctly to imports API

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#4684]
### Description
It seems that many times (but not always), no matter what % you choose on the Twitter connector, it sends 80% of your remaining tweets as the maximum.
It seems to happen at least when you choose same day and just some hours of difference, but not sure if there's a correlation or just chance.

### How to reproduce
- Have a user with low Twitter quota, like 10k
- Ttwitter search, same day start/end, just a few hours timespan, 1 term
- select only 1% of remaining quota (so should be 100 tweets on first search, etc.)
- have Chrome developer tools open to see any call to `imports` API performing a `POST`

### Expected results
The POST contains 1% of remaining tweets, something like:
```
user_defined_limits: {twitter_credits_limit: 100}
```

### Actual results
Sometimes it contains 80% of the remaining quota (user had ~9k remaining tweets):
```
user_defined_limits: {twitter_credits_limit: 7761.6}
```

**Comment by fdansv** [comment]
It seems that the percentage slider is not updating the view's model on its own. All the other elements seem to update it fine, so as long as that slider isn't the last parameter to be touched (which is no good since **it is** the last parameter), it'll work fine, but otherwise the latest value will be sent -- usually the default one, 80%.
