### ISSUE TITLE
Recover source and license options in dataset metadata modal

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#4803]
Previously, besides description and tags, the parameters source and license were available:

![image](https://cloud.githubusercontent.com/assets/1730320/8983387/4fb52c00-36ca-11e5-95a4-a79af52797e0.png)

cc @viddo @saleiva 

edit after offline conversations:

Add three new fields:
- [x] source
  - free text input, markdown supported
- [x] attributions
  - free text input, markdown supported
- [x] license
  - [x] pass licenses from [server-side model](https://github.com/CartoDB/cartodb/blob/master/app/models/carto/licenses.rb) to frontend config (to be available on `cdb.config` JS obj)
  - [x] add dropdown w/ list from above

**Comment by ethervoid** [comment]
We should add attributions field too #4826

**Comment by saleiva** [comment]
source should support .md links as well as attributions.

**Comment by viddo** [comment]
@ethervoid @saleiva Looking at the old code/modals, the source and licence is [only visible](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/old_common/views/metadata_dialog_base.jst.ejs#L43-L55) if the [user account type is "internal"](https://github.com/CartoDB/cartodb/blob/bc18027b9918f78e558182589689746562c80d10/lib/assets/javascripts/cartodb/table/metadata_dialog.js#L122), does this still hold true or is that changing due to _new data-library feature_? 

Also, from a more UX perspective, _attributions_ I presume is what is displayed at the bottom of a map(?) instead of the default, but what about _source_ and _license_? I don't think it's very clear what/where this fields are intended for.

**Comment by saleiva** [comment]
Yes, we should  open to everybody.

Source and license will be shown on the public pages. The attributions should be on the attributions on the map, yeah.

**Comment by viddo** [comment]
> Yes, we should open to everybody.

Do you mean that these fields should always be editable then?

**Comment by saleiva** [comment]
Yes, sure. Is the user who defines these

**Comment by iriberri** [comment]
> The attributions should be on the attributions on the map, yeah.

Loving this. Right now people hack the legend to add more attributions to the map. :revolving_hearts:
