### ISSUE TITLE
Feature request: notify users when viz.json urls change

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#4873]
Please ref: s/b 6138113

User has a case where the urls from "Publish your map" page's CartoDB.js section have changed (they did not make changes themselves):

1st version: http://[clientname].cartodb.com/api/v2/viz/[number]/viz.json
2nd version: https://[clientname].cartodb.com/api/v2/viz/[number]/viz.json 
3rd version: https://[clientname].cartodb.com/u/[organization_user_name]/api/v2/viz/[number]/viz.json 

Sorry if I'm missing this in https://github.com/CartoDB/cartodb.js/blob/develop/NEWS, are users notified anywhere when these changes are made from our end? If not, user would like to request notification as a feature. Or were these due to an account setting (ie: change to organization user) vs. production changes? Thanks!

**Comment by ztephm** [comment]
also ref s/b 6183427

**Comment by juanignaciosl** [comment]
This is caused by the changes for CartoDB/cartodb#4360 (CartoDB/cartodb#4394). Those urls previously worked but were not correct. We keep backwards compatibility, and when we don`t (like when we removed some API support) we notify users and support team.

Since it was bugfixing it was not added to NEWS.md, but maybe it should've be for the sake of clarity, my bad.

**Comment by ztephm** [comment]
No problem thank you @juanignaciosl
