### ISSUE TITLE
"DB host or name not found in redis" when retrieving twitter card of dataset

### ISSUE THREAD

**Issue by matallo** [CartoDB/cartodb#4890]
http://team.cartodb.com/api/v1/map/static/named/tpl_37281282_1ffb_11e5_9bc9_0e8dde98a187/600/300.png

```
{
error: "DB host or name not found in redis (try CARTODB/script/restore_redis)"
}
```

**table**
https://team.cartodb.com/u/matallo/tables/most_expensive_paintings_in_the_world_last_research/public

**Comment by rochoa** [comment]
That URL is invalid.

It should be: http://matallo.cartodb.com/api/v1/map/static/named/tpl_37281282_1ffb_11e5_9bc9_0e8dde98a187/600/300.png

**Comment by matallo** [comment]
ooop, true dat, will reassign then

**Comment by Kartones** [comment]
uhmm, stack trace please? where did that incorrect url got generated?

because indeed it should be ORG.cartodb.com/u/USER/

**Comment by Kartones** [comment]
Ok, is coming from https://github.com/CartoDB/cartodb/blob/master/app/controllers/api/json/visualizations_controller.rb#L249 so researching the Helper to see what might have changed

**Comment by Kartones** [comment]
@matallo I'm going to need you here, because there are tests and code looks ok, so I need to know the exact flow to replicate the error.

My bet is that the request causing this error is malformed (doesn't has the `/u/:user`) and this propagates this format inside. Is a pity but to support subdomain **and** subdomainless is not easy to enforce this.

**Comment by matallo** [comment]
looks like a cache issue, as investigated with you :runner:

**Comment by Kartones** [comment]
yep, I'm giving a look around trying to reproduce it anyway

**Comment by Kartones** [comment]
Nah, cannot reproduce even playing with logging out, through organization public pages, etc. Looks like a stale cache that finally got invalidated

**Comment by matallo** [comment]
still happening, user like: fdansv, user liked: matallo

**Comment by Kartones** [comment]
Ok, found:
`https://team.cartodb.com/u/matallo` if I like from there they go to urls like `https://team.cartodb.com/api/v1/viz/2f9e3d76-2185-11e5-b81e-0e43f3deba5a/like`

Going to see if is a FE or BE issue

**Comment by Kartones** [comment]
Uhn, loading the page already throws quite some 404s because of the wrong urls:
![image](https://cloud.githubusercontent.com/assets/2085449/9110012/8199b360-3c3a-11e5-959d-df56bca58606.png)

**Comment by Kartones** [comment]
at https://github.com/CartoDB/cartodb/blob/master/app/views/admin/pages/shared/_like_button.html.erb#L1
`<a href="#/like" class="js-likes"`

Please, guys, no handcrafted URLs because we break this kind of things. I'll add the corresponding proper rails call but never handcraft urls without first at least asking backend, because this kind of things can happen (especially if sharing a template on different views)

**Comment by Kartones** [comment]
The ball is going to be back at frontend, because I changed the like urls to be like:
```
CartoDB.url(self, 'api_v1_visualizations_add_like', {id: vis.fetch(:id)}, vis.fetch(:owner))
```
And returning paths are nice:
```
http://myorg.localhost.lan:3000/u/myuser/api/v1/viz/4102c308-2a30-11e5-8393-080027b3784b/like
```

But then going to Chrome and inspecting, javascript must be doing something because I get this:
```
<a href="#/like" class="LikesIndicator is-likeable" data-vis-id="4102c308-2a30-11e5-8393-080027b3784b" data-likes-count="0"><i class="iconFont iconFont-Heart--fill LikesIndicator-icon "></i>
</a>
```
I guess that because the url is still `http://myorg.localhost.lan:3000/api/v1/viz/4102c308-2a30-11e5-8393-080027b3784b/like`
