### ISSUE TITLE
Design CTA over empty map on emtpy accounts

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#4893]
So we invite people to create their first map in a very easy way.

**Comment by josecruz** [comment]
Here's my first approach. The idea is to show some killer features in Cartodb here, but don't know if it's a very agressive hover (because all the information)

![dashboard - user private - onboarding zero case hover copy](https://cloud.githubusercontent.com/assets/596509/9198245/b83057d4-4032-11e5-8e4c-47dacaa72f53.png)

**Comment by saleiva** [comment]
looks promissing. Not sure about the recurrent buttons and about the bottom white bar...
also, the drag & drop feature gets kind of invisible... maybe we can reuse the animation on the dark overlay that appears the first time you enter to the dashboard?

**Comment by josecruz** [comment]
With the dark overlay you mean something like this?
![dashboard - user private - onboarding](https://cloud.githubusercontent.com/assets/596509/9202138/4a263644-4048-11e5-9c15-e886c4d0825f.png)

**Comment by saleiva** [comment]
But in producción we have an animation!

**Comment by josecruz** [comment]
Yeah but I thought that this interaction will be when you hover the map when not having any maps on the dashboard.

**Comment by saleiva** [comment]
But that doesnt mean we cannot be congruentes, right?

**Comment by josecruz** [comment]
Actually, that's not the current white down bar that we show when there's no maps created. Also updated the text to ceneter everything:

![dashboard - user private - onboarding zero case hover copy](https://cloud.githubusercontent.com/assets/596509/9222664/77d46680-40eb-11e5-9e26-b1dc3a7dd8f1.png)

**Comment by saleiva** [comment]
If we are going with something like that, I'd not show this up on hover but always.
If that's the case, we should do something with the recurrent button 'NEW MAP' and also hide the icons for ordering, since there are not applicable.

Not sure I like the aesthethics tho...

**Comment by josecruz** [comment]
Design after talked in person. Empty browser will be the current on-boarding overlay gif. Tried with 2 different background maps:

![dashboard - user private - onboarding zero case hover copy 3](https://cloud.githubusercontent.com/assets/596509/9302991/377202c0-44db-11e5-8b40-bee525a54256.png)
![dashboard - user private - onboarding zero case hover copy](https://cloud.githubusercontent.com/assets/596509/9302992/38f8f5e0-44db-11e5-8875-483999214d1b.png)

**Comment by saleiva** [comment]
I like the one that lets the map to be seen

**Comment by josecruz** [comment]
![dashboard - user private - onboarding zero case hover cop](https://cloud.githubusercontent.com/assets/596509/9304971/b88f595e-44ed-11e5-9e18-90a9c450a31b.png)

**Comment by josecruz** [comment]
After talk with saleiva he decided to delay the animation a few seconds after it ends so there will be no loop. This screen will be always visible when you have your map list empty.

Design file is `dashboard-1.9`

**Comment by xavijam** [comment]
cc @csobier

**Comment by csobier** [comment]
@xavijam Here are my suggested edits.  Feel free to implement what you agree upon.  
- Is there a reason why we are using Aloha? It does not seem very professional, not all of our clients are students.  Just curious.
- Omit what else the dashboard can do from this particular dialog, since it is meant to be task oriented (and animated, right?)
- Is there a way to fade in the second step after they have connected a dataset? Maybe this is not necessary, but just a thought. If that is possible, we can reword the dialog to say that it will guide you through the process of creating your first map.
- In general, keep button names consistent with how they actually appear in the UI.

"Hello, cdb!
Welcome to the CartoDB Editor. Create your first map in 30 seconds.

Drag your data file to your dashboard to connect a dataset. 
(button:) CREATE MAP"

(Also, I proactively created an issue for myself to wordsmith all the similar Tip dialogs. Maybe we can sync up a workflow and assign targeted milestones?  I will communicate offline so that we are not creating any extra noise on this issue)

**Comment by xavijam** [comment]
1) About Aloha thing, I agree :+1:.
2) Yeah, it is oriented to highlight "create new map" feature.
3) cc @josecruz 
4) For me ok cc @josecruz 

About the text: It is true that from now on we don't show the navigation bar, so nobody can see 'Likes' button. cc @josecruz

**Comment by josecruz** [comment]
Totally agree, thanks @csobier !
