### ISSUE TITLE
CartoDB on Google: Add ability to modify rate-limit for geocoding per user

### ISSUE THREAD

**Issue by andrewbt** [CartoDB/cartodb#5087]
CartoDB on Google Cloud Platform is currently rate-limiting geocoding requests to Google's geocoder at around 1 QPS. This limit is artificial, as the Google Maps for Work geocoder can support about 10 QPS or around 100,000 requests per day. GCP accounts could have up to 10x faster geocoding for large datasets if this is resolved, which is a great value-add.

@javisantana suggested rather than removing the rate limit entirely, we add an ability to modify this rate limit for GCP users (either superadmin, or for organization owners to modify it for their users? to be decided by you all).

**Comment by javisantana** [comment]
@andrewbt why they say that we are geocoding at 1QPS ?

**Comment by rafatower** [comment]
We do not throttle on our side unless we get a `OVER_QUERY_LIMIT` from Google:
https://github.com/CartoDB/cartodb/blob/master/services/table-geocoder/lib/gme/client.rb#L94-L96
https://developers.google.com/maps/documentation/business/articles/usage_limits

HTH

**Comment by javisantana** [comment]
one small detail here:

```
 # 0.5 * (1.5 ^ i) is an increased sleep time of 1.5x per iteration,
        # starting at 0.5s when retry_counter=0. The first retry will occur
        # at 1, so subtract that first.
        if retry_counter > 0
          delay_seconds = 0.5 * 1.5 ** (retry_counter - 1)
          sleep delay_seconds
        end
```

It's likely ``retry_counter`` turns 1 very soon since the first geocodings will be over 10QPS, so

````
>>> 0.5 * 1.5 ** 0
0.5
```

So the max QPS we are going to have in that case is 2 (1/0.5)

Could we start with a higher QPS limit, like 20QPS, then 10, 5, 2, 1 ?

**Comment by rafatower** [comment]
You're right. to a certain extent. If the server is fast enough, the retry will happen at the 11th request, that will get throttled with a `sleep 0.5, 0.75, 1.125, ...` until the `MAX_QPS` is honored.

Since the requests happen sequentially, the 12th request won't happen until 11th is fulfilled.

If you measure QPS between 10th and 11th request it will be true that it will be around 2 but in the limit, effective QPS will be very close to 10 (as I checked experimentally).

I can change the delay to be `0.1 * 1.5 ** (retry_counter - 1)`. Whereas that will give you 10 QPS between 10th and 11th request, it won't change much other than a bit more retries.

**Comment by rafatower** [comment]
I ran a small simulation and you're right, I'm gonna change it to be `delay_seconds = 0.1 * 1.5 ** (retry_counter - 1)`.
https://gist.github.com/rafatower/3547e86c5f2d0442a9d5
