### ISSUE TITLE
When an external_source has been used, can't be deleted

### ISSUE THREAD

**Issue by ethervoid** [CartoDB/cartodb#5097]
If a user has used an external_source to import a dataset, a row in `external_data_imports` is created. When we want to update the remote visualizations and external sources, if there are rows that isn't going to appear anymore we remove them but it they are linked by a row in `external_data_imports` its impossible to remove.

The best solution is to remove them logically

**Comment by ethervoid** [comment]
I think this will disappear with the data-library sync but we have migrate the old `external_data_imports` and create sync for them?

// @Kartones

**Comment by Kartones** [comment]
No, do not create any sync, no need to migrate. The idea is to leave "legacy data-library" imports as they were, and only new syncs will make dissapear items from the data-library.

So a logical deletion is nice because you just need to exclude them from [the remote filtering at VQB](https://github.com/CartoDB/cartodb/blob/master/app/queries/carto/visualization_query_builder.rb#L211)
