### ISSUE TITLE
Check if downgrades blocks sync tables of being synced

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#5239]
If I'm not wrong, I remember that each sync period checks if the feature of sync tables is enabled. For a user that has some active sync tables and downgrades to a plan without this feature, the next syncing periods used to fail due to this.

P.S.: I'm testing this directly, I'll add the results in 1 hour.

**Comment by iriberri** [comment]
I was just able to test it. The sync failed:

`Synced failed. Error code : Unauthorized.`

It's: https://vmg.cartodb.com/tables/world_teacher2_2 in case you want to check it deeper.

**Comment by Kartones** [comment]
Initial research: Indeed normal syncs start failing and end up disconnecting after X times if user downgrades.

I have to check what happens with data library ones as they were tested to work without sync tables but "Sync Now" button activates itself if it is due update (probably my mistake not disabling there also), but throws a 401 if you click it.

**Comment by Kartones** [comment]
@iriberri I've done a bugfix, but apart from that everything works as expected. Non-data library syncs will stop syncing and eventually fail (After X attempts) due to user no longer being authorized.

This has been always this way from what I see in the code, if we want to change it you should talk with @saleiva first as it is a feature change.
