### ISSUE TITLE
No data library

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#5272]
When i create a new account if i try create my first map the data library is empty

![image](https://cloud.githubusercontent.com/assets/1214201/9526254/895404ac-4ce8-11e5-9a23-af7264b92251.png)

@viddo @javisantana @juanignaciosl

**Comment by javisantana** [comment]
cc @ethervoid

**Comment by ethervoid** [comment]
Basically the problem is that now, because we are using the visualizations API, take more time to load. As @juanignaciosl suggest we should preload in the user creation

**Comment by viddo** [comment]
We did have [preload](https://github.com/CartoDB/cartodb/pull/2741#issuecomment-82510996) once, so that changed at some point then?

**Comment by viddo** [comment]
So after talking w/ @ethervoid offline and investigating a little more, it seems that the the loading was implemented for the dashboard listing, not for the creation modal. So would have to be adde there, or have the creation modal refactored to share listing with the dashboard to have the same behavior (would this be problematic, @xavijam?)

**Comment by ethervoid** [comment]
I've done tests with the preload screen and all works fine, if we have the preload screen I don't think we need to preload everything the common_data in the user creation. The main problem is that we need the controller to create the URL to call the visualizations API.

// @javisantana

**Comment by juanignaciosl** [comment]
We can safely add common data loading as a final step of user creation. It was there at the beginning of the feature. We disabled it because of a bug with some organizations, and later we kept only update on entering dashboard (since it covered both cases) but it can be added back. @ethervoid ping me if you need anything.

**Comment by xavijam** [comment]
@viddo I'd implement the loader for the data library in the create modal.

**Comment by ethervoid** [comment]
I think that we could test first adding the loader and test if the performance is good. If not, we could move the logic somewhere in the user creation process but we have to take into account two things for this:

* The user creation in box is triggered by central
* We need the user_id in box so we need to do this after the user creation because of the user_id FK

**Comment by juanignaciosl** [comment]
I've been talking with @ethervoid and we've realized that after the latest changes we can't just move loading to user creation, because in order to generate the URL we need a controller. So, in case we want data library to be loaded from the very beginning we need a new config parameter with the hardcoded url.

Data library loading was not an issue when it was only at datasets --> data library, because most of times it would be already loaded, but certainly with the modal listing it might be interesting preloading it, in spite of requiring a hardcoded url at configuration.

@javisantana , this looks like a product decision, maybe you are the one that could close the discussion if we've managed to explain the involved tradeoff. Preloading with hardcoded url, or loading spinner at  modal?

**Comment by piensaenpixel** [comment]
if you want my opinion + 1 to Preload

**Comment by javisantana** [comment]
> because in order to generate the URL we need a controller

the common data api url ?

**Comment by ethervoid** [comment]
Yes. Since we have to build the URL based on the configuration for common_data we use internal method dependent of controllers to extract the base url. If we want to preload the data-library for us, we need to hardcode the url where we are going to request the data-library.

We have to take into account that this option is going to increase the time to create the user becuase we have to wait until the data-library is loaded.

**Comment by javisantana** [comment]
You just need to have a proper configuration, I don't see anything wrong in having the full url in the config.

I don't fully understand why we don't have that precached on every rail instance, in other words, cache the request to the common data

**Comment by ethervoid** [comment]
That's way we added the `base_url` param to it, so we can use it to build the visualizations api url (request to get the data) and the sql api url (build the import url). We can use the base url but the `path` is build using the Rails methodology. In case we add a URL to the config, should be exclusively for our use and it seems a pretty rough to me. 

I haven't cached that request because the common-data user is arbitrary chose so when don't have option to invalidate that cache in the moment the user add or delete a dataset. We can execute a cron to invalidate that cache every hour / day / week or something like that.

Even preloading the data, we are going to need the preload screen in the modal because for example if a user enters and the load_common tasks is executing, the data library could be empty too.

**Comment by javisantana** [comment]
> I haven't cached that request because the common-data user is arbitrary chose so when don't have option to invalidate that cache in the moment the user add or delete a dataset.

Every X hours

>  Rails methodology

:__) we don't need to do a pretty big workaround to use the rails url generation, right?

> Even preloading the data, we are going to need the preload screen in the modal because for example if a user enters and the load_common tasks is executing, the data library could be empty too.

It's only important for the first time, common datasets are important for the onboarding because lot of users does not know what to do once they login, that's one of the reasons why it's there

**Comment by ethervoid** [comment]
So the answer is to preload in the user creation. Roger.

* I'll add a harcoded url to the config to be used by us in the sign up as a first fix.
* As a second task I'll add cache to that. If I'm right this goes to redis but I don't know if it fits in an existing database or I should create a new one. (I'd love to have an answer to this :dancer:)

**Comment by Kartones** [comment]
Are we talking about delaying user creation until it has common data inside?  That is **part** of the creation process, that's a post-process task... Show something like "we're populating your data library" and not let him/her enter that page until done, but that sounds bad...
For the onboarding is nice to preload data, for at least me that should be an async, after-creation triggered task because that's not critical for user creation, just for the editor. But is not my call.

Also I am against hardcoding urls in config... I've been fighting for months to only have URLs generated serverside from Rails's MVC, if we hardcode one now in the config... again we introduce manual points we must remember to change if the format changes. Not that it should, but already has once or twice with Multiuser. But well, if you change that please put a big comment above and in the app_config.yml.sample so we know if we change something in the future...

**Comment by ethervoid** [comment]
I was finally able to use the superadmin controller to generate the URL so one less thing to worry :dancer:

**Comment by ethervoid** [comment]
I've doing some tests, if we load the data-library as an async task in the user creation process, we could save time but we still need the preload screen but I'll take less time to show data. It's up to you guys, there is a PR with the fix in a sync way, if nothing is said about it, I'll merge next monday.
