### ISSUE TITLE
team user can't import data library dataset even with enough data storage space

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#5315]
@Kartones cc @iriberri 

Data library datasets are failing to import into @makella 's team account.
That account's using 0.0 of 500.0 MB with 157286400 Max import file size.

To replicate: try connecting Populated Places dataset from Data library

That account's import errors are mostly:
ERROR 1: ERROR: canceling statement due to statement timeout
(another error in same files is ERROR 1: PostgreSQL driver doesn't currently support database creation.)

Populated places is connecting fine into my team account, but when trying to import same dataset into her acct it's timing out over same internet connection.

**Comment by rafatower** [comment]
https://github.com/CartoDB/cartodb/issues/5009

**Comment by rafatower** [comment]
Fixed

**Comment by makella** [comment]
@Kartones @rafatower @ztephm thanks for the help! tested just now and datasets are uploading!

**Comment by makella** [comment]
I was able to upload one dataset today but it is giving me a time out error again.  Anything I can do to provide helpful information, let me know.

**Comment by iriberri** [comment]
Rafa made a fix but he needed to roll it back because it was causing other issues. I recommend you to follow this problem directly at #5009, so that we don't have so many open for the same cause. :-)

I guess you were able to import the files when the fix was in production, but then we needed to go back. I have increased the timeout of your account to try to minimise the effect of this problem.
