### ISSUE TITLE
Make data library easier to explore

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#5326]
By adding filtering by 0..n tags

**Comment by josecruz** [comment]
I made some different versions:

### Integrated with search:
I integrated with the search field due it is a type of search. But not that intuitive:
![dashboard - user private - base copy 2](https://cloud.githubusercontent.com/assets/596509/9738407/a58185fc-564b-11e5-83bd-0dcdd8f3ce6c.png)

![dashboard - user private - search input copy](https://cloud.githubusercontent.com/assets/596509/9738418/af420df0-564b-11e5-889e-f3932ae275fc.png)

----

### Icon near search:
Just because they're *similar* actions. Looks really weird.
![dashboard - user private - base copy](https://cloud.githubusercontent.com/assets/596509/9738497/15405422-564c-11e5-83c6-f4441d2c65b0.png)

---- 

### Replace Like Icon
Most liked one. Since we have a tab to classify the liked datasets. Also, on the datasets dashboard, it only show **your** likes, so I decided to delete the `order by likes` options from the filters and add the filter by option:

![dashboard - user private - base copy](https://cloud.githubusercontent.com/assets/596509/9738807/7ecf29a8-564d-11e5-9c72-8b149249fd59.png)

This option works nice on the modal as well:
![empty dashboard - connect dataset data library copy 4](https://cloud.githubusercontent.com/assets/596509/9738813/8362385c-564d-11e5-9acb-d018cb60a2ef.png)

----

**Comment by saleiva** [comment]
Just one quick comment until I can think on this further... why you should keep the ordering icons on the data library? Ordering here (other than alphabetic) doesn't make any sense IMO

**Comment by josecruz** [comment]
Well I think that would be weird to change the ordering icons depending on the tab you are because they're both on the same place.

**Comment by saleiva** [comment]
Why would you keep something that is not useful in an UI then?

**Comment by josecruz** [comment]
Okay so in the case of Data Library I would remove the **Filter by Activity** and **Order by Likes**

**Comment by saleiva** [comment]
How do you think people uses this page? Or better, how do you think people will like to use this screen?

**Comment by josecruz** [comment]
IMHO I think that ordering data library by likes doesn't makes much sense *right now*. So I replaced by filter option. 

I think it would make sense to add a classification of polygon dataset/points/lines or even a spatial filter, e.g: US datasets, Spain Datasets... But it would make the data library search very complex, what do you think?

**Comment by josecruz** [comment]
After yesterday's talk of remove the filtering buttons replacing it with a "filter by category" option:
![dashboard - user private - base copy](https://cloud.githubusercontent.com/assets/596509/9879873/7d0d6450-5bc9-11e5-9714-dc814c11d2e9.png)
![dashboard - user private - base copy 3](https://cloud.githubusercontent.com/assets/596509/9879878/80a73cee-5bc9-11e5-8ba1-3c4ab50ab7ff.png)
![empty dashboard - connect dataset data library copy 5](https://cloud.githubusercontent.com/assets/596509/9879881/84191f00-5bc9-11e5-9660-8beaec90627d.png)

Thoughts?

**Comment by saleiva** [comment]
I think the filter by label is not needed. by default it could say "All categories" and then when selected the category name. also the left separator shoulnd't be there, right?

**Comment by josecruz** [comment]
Yep, much better: 
![empty dashboard - connect dataset data library copy 5](https://cloud.githubusercontent.com/assets/596509/9905151/77694446-5c83-11e5-96a0-53ad05795722.png)

![dashboard - user private - base copy 3](https://cloud.githubusercontent.com/assets/596509/9905145/69e96832-5c83-11e5-8b91-2b8732707cdc.png)

**Comment by josecruz** [comment]
Last version:
![dashboard - user private - base copy 3](https://cloud.githubusercontent.com/assets/596509/10160332/130be76e-669d-11e5-98b9-4c6066045cc1.png)
![empty dashboard - connect dataset data library copy 5](https://cloud.githubusercontent.com/assets/596509/10160336/1694877e-669d-11e5-9973-4e3395b9d01e.png)

File is called `dashboard-1.9.sketch`

**Comment by xavijam** [comment]
We should add it to new data library page, shouldn't we? 
cc @matallo (_not for implementing in the first version_)
