### ISSUE TITLE
Add support for adding a batch of users to a group

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#5372]
E.g. https://projects.invisionapp.com/share/P43R5D79K#/screens/93103189

While individual requests are doable and would work for a small set, it has a lot of overhead if selecting all users on a (pagination) page. Instead, we should be able to do do a batch add, something on the lines of
`PUT /groups/123 { users: [1,2,3, …]}`

Task breakdown:
- [X] Support for batches at editor endpoints.
- [X] Support for batches at database endpoints.
  - Support for batches at database extension: CartoDB/cartodb-postgresql#136.

_Additional refactor_:
- [ ] Rename "members" to "users" at group presenter (json).

Depending on timing, first and second tasks will be developed in the same branch or not, in order to avoid blocking UI work.

**Comment by juanignaciosl** [comment]
After seeing the interface it looks like you need to _add_ multiple users (not _editing_ a group), so, since single user addition is `POST /groups/<group_id>/users/<user_id>`, I suggest multiple user addition to be `POST /groups/<group_id>/users [ <user_1_id>, <user_2_id> ]`. I think your suggestion fits better group _edition_. Let me know if this is worse for you.

**Comment by juanignaciosl** [comment]
@viddo you can take a look at the last commit (b3fd94a), including sample tests. I'll continue with this issue in this branch until you warn me you're needing it soon.

**Comment by viddo** [comment]
Looks reasonable to me, sure :+1: 

And :warning: I'll need it soon ;)

**Comment by juanignaciosl** [comment]
Merged into #4924.
