### ISSUE TITLE
Update attribution of map layers when the attribution of the "original" dataset is changed

### ISSUE THREAD

**Issue by alonsogarciapablo** [CartoDB/cartodb#5394]
By default, new layers get a default "CartoDB" attribution. Users have the ability to edit the metadata of datasets. In order for the editor to display the right attributions, we'd need to update the attribution of layers when the attribution of its corresponding dataset is changed :)

cc// @javisantana

**Comment by javisantana** [comment]
what should i do here?

**Comment by alonsogarciapablo** [comment]
You should assign it to some backend guy to implement it.

**Comment by Kartones** [comment]
I am checking this. While I'll keep forward with a backend solution, this is going to be a bit ugly, because `Layer` model is almost only a container of data sent by the frontend, so I have to be parsing JSONs and doing replaces.

But is just for the record, I also think the editor does too much logic so the solution is not to move this also to there (but instead in a far far rewrite Layer model to be decent)

**Comment by Kartones** [comment]
Code is ready (including a test) and already propagating changes so when you refresh the editor (or do another `/maps/xxxx/layers` call) you get the layers with updated attributions.

There seems to be some bug because despite having correct data UI only shows one attribution, but I'll left that to you @alonsogarciapablo:
![image](https://cloud.githubusercontent.com/assets/2085449/9736601/750f950c-5642-11e5-9812-a62cdf7a4d86.png)

**Comment by alonsogarciapablo** [comment]
Thanks! I will take a look!

**Comment by javisantana** [comment]
did you take a look @alonsogarciapablo ?

**Comment by alonsogarciapablo** [comment]
Indeed! This is fixed already! I forgot to close the issue!
