### ISSUE TITLE
Weird bounding box is being assigned to map when there's no data (again)

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#5400]
Some weeks ago I opened a similar issue reporting that we were centering the map in 0,0 and zoom 18 when the dataset didn't contain data. Hello Null Island! :palm_tree: 

In the last days I'm seeing a more weird thing, we're centering it in the North Pole, at zoom level = 18.

![image](https://cloud.githubusercontent.com/assets/1730320/9698499/7161791a-53b9-11e5-92b6-3ecb43ae6ab3.png)

And you have to zoom out until zoom 3 to actually see "the Earth" (my screenshot is at 2, though):

![image](https://cloud.githubusercontent.com/assets/1730320/9698508/b31c3ad4-53b9-11e5-9944-294c930854ce.png)

Importing [this CSV](https://gist.githubusercontent.com/iriberri/2ca0a2372db8c87f551d/raw/23455a3f50d8c4a7e2c1d87d6f978411a26374a6/sample.csv) for example makes it happen.

**Comment by Kartones** [comment]
@iriberri can you please provide another example with a proper polygon? Because I'd have to check but that CSV seems to be painting a polygon outside of the earth, or an invalid one. I placed a size 40 black border and there's no trace of it, and it is because `the_geom_webmercator` is null. `the_geom` is valid and there's a `wkb_geometry` geom... so it smells like another extension-related import bug :(

With a truly empty csv I get a valid view:
![image](https://cloud.githubusercontent.com/assets/2085449/9784157/ba7d5940-57a9-11e5-96cd-b0f971e5d705.png)

**Comment by Kartones** [comment]
closing for now, feel free to reopen if somethign happens, latest fixes should have solved the issue
