### ISSUE TITLE
Scroll Wheel Zoom Not Working 

### ISSUE THREAD

**Issue by ezys** [CartoDB/cartodb#5494]
On this (and other maps I've made) I have enabled "scroll wheel zoom"

https://davidmanthos.cartodb.com/viz/9e48164c-45da-11e5-bcf9-0e0c41326911/public_map

But scroll wheel zoom does not work for me either in Chrome or Safari.

**Comment by iriberri** [comment]
Hi @ezys,

In the public map sites, the scroll wheel zoom is disabled automatically in order to allow users to scroll in the page and not get stuck in the map zoom interaction.

You can check that the scroll wheel zoom is indeed working here: https://davidmanthos.cartodb.com/viz/9e48164c-45da-11e5-bcf9-0e0c41326911/embed_map

Hope this helps!

**Comment by ezys** [comment]
Ok, I see the difference, but it's a rather unclear extra step if someone thinks they are linking to the explorable map. 

In general, scroll wheel interaction is a tricky thing for any map that could live by itself  or be embedded in a website somewhere. Any chance you could create an option that scrolling zoom doesn't until someone clicks to "interact with the map". Something like this, perhaps?

http://stackoverflow.com/a/22567753

Just a suggestion. Thanks.
