### ISSUE TITLE
Improve error message when importing over the row limit

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#5502]
Right now it says there are too many rows, and that's it. I'd suggest to complete a bit more the error (in the modal and the email as well)

cc/ @ethervoid  can you paste the actual test to @csobier so we find a better one?

**Comment by ethervoid** [comment]
Here is the text https://github.com/CartoDB/cartodb/blob/master/lib/cartodb/import_error_codes.rb#L240

**Comment by csobier** [comment]
@ethervoid, see suggested error in quotes below.  Also, is there a known maximum number of rows allowed, or is this based on data size?  I can document this if it is a known restriction. Otherwise, what is the suggested workaround if their dataset has too many rows?

"This import cannot be completed, as you have exceeded the maxium number of table rows for your dataset."

**Comment by ethervoid** [comment]
The maximum number of rows is defined for every user (property `max_import_table_row_count`) with a default value of `500000`. This could be updated to a greater quantity, I suppose with a greater plan this quota should be increased

The maximum size of file is defined with other user property `max_import_file_size` with a limit of `157286400`

**Comment by csobier** [comment]
Oh, I see.  If it is related to their account, then perhaps update the error message as follows? (note spelling of "maximum" too), but the Pricing Plan page does not mention anything about import size restrictions?  If you do not want to mention this restriction, do not include the part about contacting Sales.

"You cannot import this dataset, as you have exceeded the maximum number of import rows allowed for your account. Please contact [Sales](mailto:sales@cartodb.com) if you have questions about importing a larger dataset with different account plans."

**Comment by ethervoid** [comment]
That phrase could lead to the error because the user could think that he could import more datasets, what about:

"You cannot import this dataset, the number of rows of excedes maximum number permitted by dataset for your account. Please contact Sales if you have questions about importing datasets of this kind with different account plans."

(Sorry for the mistakes :\)

**Comment by csobier** [comment]
Agreed, makes sense.  (I just tidied up the content to better describe your suggestion):

"You cannot import this dataset. The number of rows exceeds the maximum dataset quota permitted for your account. Please contact [Sales](mailto:sales@cartodb.com) if you have questions about importing this dataset."

**Comment by ethervoid** [comment]
Good for me :)
