### ISSUE TITLE
Can't edit fields when custom SQL query is applied

### ISSUE THREAD

**Issue by mnquintana** [CartoDB/cartodb#5511]
Refs https://github.com/CartoDB/cartodb/issues/4810

Steps to reproduce:

1. Open a dataset on which you have admin rights
1. Apply a custom SQL query / view
1. Double click on a value - the "edit" popup will appear with a text input
1. Try to focus / type in that input - nothing happens

**Comment by gfiorav** [comment]
@alonsogarciapablo @xavijam  Is this behaviour allowed? I'm asking because I saw the solution of ticket #4810 was that metadata is not editable during custom queries.

What about this case? Should a user be able to change values with a query applied?

**Comment by xavijam** [comment]
Yep, if a custom query is applied you can't edit the data. But if you want to filter your data (using filter module), you can edit the data, @alonsogarciapablo enabled some time ago.

**Comment by gfiorav** [comment]
@mnquintana like @xavijam explained, this behaviour is intended. 

Closing ticket!

**Comment by mnquintana** [comment]
So wait, I'm not sure I understand - why is this behavior intended? Granted, when I was doing this it was to do the same thing as a Filter but with a SQL query, but when applying a Filter you can still edit data. Why couldn't this also work with custom queries?

**Comment by xavijam** [comment]
Basically with the filter query we ensure that query belongs to the current dataset, so the JS behaviour we have for the table models will work as expected (in fact it is a POST to records endpoint). Imagine if you run a query requesting data from several tables, in that case our table model doesn't know how to run an update because it doesn't know which are the table, that's the reason why we can't enable the edition over the results.
Another example would be related with security. If you are in an organization, and you request data of a table from another user where you have readonly limits, you couldn't run any update over it.

**Comment by mnquintana** [comment]
Ah okay, thanks for the update @xavijam! In that case, rather than preventing edits in all cases, what do you think about allowing edits only if the custom query belongs to the current dataset (like with filters), and preventing it in all other cases?
