### ISSUE TITLE
Export Image Button not appearing on some maps

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#5600]
Ref S/B 6672359 (ping for assignment @saleiva )

Expected: 
When user is in Map View "Export Image" button is available at top left of page. When they click it, they can size export area as needed & then click "Export" button to get .png.

Happening:
"Export Image" button is not available in all maps. In ones it is available for, the Export button from draggable interface screen is clickable but no .png is exported. Keeping user info private here but see screenshots attached to last reply in ticket for map names.

**Comment by danicarrion** [comment]
@xavijam this might be for your team I guess?

**Comment by xavijam** [comment]
We decided to change that because we wanted to show the overlays from the visualization, thing that we can't do with the static API (only basic image). But in any case we have planed for this milestone, provide the possibility to export PNG, JPG or the current base 64.
https://github.com/CartoDB/cartodb/issues/5162

**Comment by ztephm** [comment]
FYI behavior isn't consistent for all maps in their account though. Arg. Prov. Prot. A. (sorry, this is map title abbreviation b/c keeping their data private b/c public issue) map has Export button, EU GHG doesn't.

**Comment by xavijam** [comment]
So:
- using GMaps provider, export option is not enabled.
- using Leaflet provider, export options is enabled.
