### ISSUE TITLE
Add users to a new group (w/o members) directly from group view

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#5654]
<img width="1078" alt="screen shot 2015-09-22 at 11 57 43" src="https://cloud.githubusercontent.com/assets/132146/10015554/44140f48-6121-11e5-95c5-d43a5677775d.png">

cc @viddo

**Comment by viddo** [comment]
It's already designed: https://projects.invisionapp.com/share/P43R5D79K#/screens/93103194 
Supposed to show the search-and-add-users inline if there are no members in group yet. I took the shortcut of opening the modal for now, since implementing this would require more work in terms of refactoring the styles (e.g. `.Filters`) to not be tied to the dialogs
