### ISSUE TITLE
Different numbers of dataset

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#5669]
1 public dataset
![image](https://cloud.githubusercontent.com/assets/1214201/10019006/111b8020-613b-11e5-8111-a244f410b930.png)

In the detail view appears (2 private datasets)
- http://tecnilogica.cartodb.com/viz/56e702fe-4693-11e5-8f79-0e853d047bba/public_map

**Comment by ethervoid** [comment]
Right now we have the name of the datasets used but we don't store duplicates about it.

As a solution I could add a 'used_datasets_count' that is calculated with the number of carto and torque layers in that map (I think that's how the number is currently calculated)

// @Kartones @juanignaciosl

**Comment by ethervoid** [comment]
One thing we should change is `public dataset` for `dataset or datasets`. In explore API we don't know the type of privacy the dataset has

**Comment by Kartones** [comment]
I'd just reuse whatever logic appears on the public_map corresponding section (regarding the number). If it allows duplicates then just use allow them too to be consistent.

And yes, as that's a summarized view I'd remove the "privacy" because what happens if there is a mix of public and privacte datasets, the literal expands? (and if you say there is no privacy of them...)

**Comment by juanignaciosl** [comment]
:+1: for Kartones, since there's currently that kind inforformation I wouldn't add another counter and stick to any of existing. IMHO, I'd display the number of public datasets, a user don't mind about datasets he can't reach I guess. @ethervoid I don't know current Explore API structure, but in the early days it was said that it should only contain public information, so datasets should be (implicitly) public.

**Comment by ethervoid** [comment]
Right know we are showing the table names public and private until we change and put the public view as the public api and the current api as private. (This depends of the mapviews decision, once  we      have that we could create the public view and make the change of permissions) 

The name of the tables comes from the layer options where I can't know the privacy level, and we can't go for it because it would connect to the users databases.

What I'm going to do is to get the number of carto_and_torque layers and put as dataset number for consistency

**Comment by xavijam** [comment]
Yep :tada:
