### ISSUE TITLE
Bug trying to change users permission

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#5676]
### STR:
- Having a user within an organization and belonging to a group.
- Open sharing options from a dataset.
- If you try to change the permissions over a group, it works weird.
   - Disabling WRITE permission, group members still have write permissions.
   - And if we try to remove READ permission, it disables both READ and WRITE checks.

![groups-bug](https://cloud.githubusercontent.com/assets/132146/10022762/bb4319ce-614e-11e5-90cb-a86a20d6a74d.gif)

Found by @urbanphes

**Comment by viddo** [comment]
Unfortunately those are not bugs but side-effects due to how the ACL works, more specifically:

> Disabling WRITE permission, group members still have write permissions.

That's because the permissions are inherited from the organization in that case, the permission system don't support exceptions/black-listing of individual items.

> And if we try to remove READ permission, it disables both READ and WRITE checks.

That's also how the permissions currently works (write implies read access).

Now knowing :point_up: , what do you suggest to change?

**Comment by viddo** [comment]
From talk offline; there seems to be a bug with revoking write access however, should show the inherited access (from organization) instead of un-toggled state. Will investigate…

**Comment by xavijam** [comment]
:+1:

**Comment by viddo** [comment]
Solved in #5702
