### ISSUE TITLE
Weird bg in "login with google" button

### ISSUE THREAD

**Issue by piensaenpixel** [CartoDB/cartodb#5683]
![image](https://cloud.githubusercontent.com/assets/1214201/10026309/5475baf4-6161-11e5-83af-5a15f45bcf23.png)

**Comment by xavijam** [comment]
Do you know @juanignaciosl why it is appearing with that dark background?

**Comment by juanignaciosl** [comment]
Yep, @saleiva request at #4397. We didn't change "Login with Google" to "Login with ORG_NAME" because we can't actually distinguish between Google Apps or not, but now there's whitelisting maybe we could have a second thought.

**Comment by piensaenpixel** [comment]
IMO if we can't change the button text, the background should be red, the majority of cases of "Login with Google" are red.

**Comment by xavijam** [comment]
I agree with @piensaenpixel.

**Comment by juanignaciosl** [comment]
We can change it to the organization name. I have some concerns about organization name not matching email domain, but maybe I'm just overthinking.

**Comment by xavijam** [comment]
We are discussing about the background color of the button, not the text, right @piensaenpixel ?

**Comment by piensaenpixel** [comment]
right @xavijam

**Comment by juanignaciosl** [comment]
@piensaenpixel said "if we can't change the button text, the background should be red", so he was discussing both.

I won't discuss design decisions, I just wanted you to know this is not "weird" but on purpose for weeks and requested by @saleiva. In fact making it was not trivial but hacky since it's rendered in Central. Just decide how it should be and I'll change it if I should.

**Comment by xavijam** [comment]
Closed because it is red again :+1:.
