### ISSUE TITLE
Australian bureau of statistic files cannot be imported by URL

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#5704]
Example: 

http://www.abs.gov.au/ausstats/subscriber.nsf/log?openagent&1259030001_MB_2011_ASGC_NSW_csv.zip&1259.0.30.001&Data%20Cubes&2787F2FFF3F6E607CA2578CC001268ED&0&July%202011&05.10.2011&Latest

This comes from this big library: 

http://www.abs.gov.au/AUSSTATS/abs@.nsf/DetailsPage/1259.0.30.001July%202011?OpenDocument

CartoDB is downloading a "log" file and throwing a `Unable to open datasource `/tmp/imports/20150923-19668-azep6v/log' with the following drivers.` error.

**Comment by iriberri** [comment]
The HEAD request to the file URLs returns a valid `Content-Type → application/x-zip`

**Comment by gfiorav** [comment]
I found a weak spot in the naming convention for the downloader that is causing this error. The problem is that for this particular request:

`URL: http://www.abs.gov.au/ausstats/subscriber.nsf/log?openagent&1259030001_MB_2011_ASGC_NSW_csv.zip&1259.0.30.001&Data%20Cubes&2787F2FFF3F6E607CA2578CC001268ED&0&July%202011&05.10.2011&Latest`

No filename is specified in the HTTP headers so the downloader tries to infer it from the url. [The code for that inference is]():

```ruby
def name_in(url)
  url.split('/').last.split('?').first
end
```

In this case the result is `log`. Having such a name, without an extension, makes the importer think this is a single file download when it's really a zip. Hence, `ogr2ogr` is trying to work with a binary file (the zip itself). I have tested that manually renaming it to `whatever.zip` in runtime with the debugger yields a successful import.

I'm still deciding on the best approach to over come this.
