### ISSUE TITLE
No info on first step of "show details" view for a failed import

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#5722]
![screen shot 2015-09-23 at 17 55 10](https://cloud.githubusercontent.com/assets/978461/10050404/6b58e5dc-621c-11e5-866f-e8245ac621a1.png)

e.g. when trying to add layer from URL https://github.com/juanignaciosl/test-data-repository/blob/master/many_characters_%C3%A1%C3%81%C3%B1%C3%91%C3%A7%C3%87%C3%A0%C3%80.csv

The thing is that the returned 200 response contains some general info but both error data points are empty:
```
error_code: null
get_error_text: null
```

But on the other hand, the [background_polling/models/imports_model](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb/common/background_polling/models/imports_model.js#L110-L128) don't return sufficient data to display any meaningful information in the error_details_view in the first place. 

cc @juanignaciosl shouldn't we provide some more meaningful error information from backend?

**Comment by juanignaciosl** [comment]
I don't know the precise details of how frontend takes backend error information, but I know that everytime first line is empty it's been caused by an unknown situation, so this problem has two actions we should take:
- We should display a generic error message at *1*, really generic ("An unknown error has happened") or something. I don't know if you prefer hardcoding this text in front or back, but it's actually that not handled error scenario.
- We should analyse what the specific problem with this specific file is and fix it so it can be imported or display a meaningful message. In fact I opened #5716 yesterday because of that.

**Comment by xavijam** [comment]
Definitely frontend should show a generic/standard error.

**Comment by viddo** [comment]
A fallback value in case of error is not available then :+1:
