### ISSUE TITLE
Sharing a private map with private data with a group doesn't display data

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#5728]
1.- User A shares a private map with private data with group G.
2.- User B, belonging group G can open the map but data doesn't appear. No error either.

**Comment by juanignaciosl** [comment]
This seems currently broken for organization users as well. I've tried to open a private map with private data shared with the organization. This is the request:

```
https://mariodefrutos.cartodb.com/api/v1/map/named/<template id>/jsonp?stat_tag=<stat_tag>&config=%7B%22layer0%22%3A1%7D&callback=_cdbc_910841071_1
````

 and it triggers the same error than current (missing) group sharing map features:

```
errors: ["Error: Unauthorized template instanciation"]
```

I'll fix this within this feature as well, since it overlaps.

cc @Kartones @xavijam @javisantana

**Comment by Kartones** [comment]
Check https://github.com/CartoDB/cartodb/blob/master/app/models/permission.rb#L363 there is no logic to do anything with Visualizations. Based on my memory, this is because viz permissions are only checked via ruby and the `Permission` model, so the visualization itself should be able to be shared.

I'm almost 100% sure the issue relies on the data (on having at least 1 data layer private) and or other thing other than viz privacy "per se". Will add more info

**Comment by juanignaciosl** [comment]
Actually fixed after fixing existing issues.
