### ISSUE TITLE
n/a

### ISSUE THREAD

**Issue by santisaez** [CartoDB/cartodb#5784]
n/a

**Comment by Kartones** [comment]
Timeout is set by default to the following, according to [AWS doc](http://docs.aws.amazon.com/AWSRubySDK/latest/AWS.html#config-class_method):
```
:http_idle_timeout (Integer) — default: 60 — 
The number of seconds a persistent connection is allowed to sit idle before it should no longer be used.
:http_open_timeout (Integer) — default: 15 — 
The number of seconds before the :http_handler should timeout while trying to open a new HTTP session.
:http_read_timeout (Integer) — default: 60 — 
The number of seconds before the :http_handler should timeout while waiting for a HTTP response.
```
(and there are no more)

**Comment by Kartones** [comment]
Branch: `5784-check-S3-timeouts-and-https`

**Comment by Kartones** [comment]
After some research, S3 by default [always uses HTTP](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html) for working with buckets internally.

In order to setup HTTPS for internal traffic (remember, not the urls served to the resques, those are already HTTPS),  seems that you need to setup [an ssl ca bundle](http://docs.aws.amazon.com/sdkforruby/api/Aws/S3/Client.html), or store or something similar so that the `bucket_name` (e.g. `my.cartodb.imports`) is called using https and not http.

There is no straightforward way of just saying "hey, I want https here".

So for internal https calls we'll need an SSL certificate for staging and other for production, as for sure **one per bucket is required**.

So... your call @santisaez, if you think is worth to have the internal traffic this safe, setup the keys and bring back to me the issue so I can setup it and do some tests to confirm.

**Comment by Kartones** [comment]
BTW, the other commit shouldn't do much as only makes explicit some config values for timeouts and SSL on download urls that were in theory already there...

**Comment by santisaez** [comment]
![ataud](https://user-images.githubusercontent.com/223956/81411781-25b9ee80-9143-11ea-925d-f9397dd0508d.gif)
