### ISSUE TITLE
Stuck state of imports can cause loop of exceptions

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#5796]
See history of https://rollbar.com/vizzuality/CartoDB/items/1128/ for how the same imports were causing dozens of entries per minute, instead of reporting one and dying.

After checking, there were 29 stuck imports (causing 14K error entries), just DataImports with state 'stuck'.

This usually happens due to a job consuming too much memory and Monit killing it, but seems that migration of queues servers caused some to be set at that state, and instead of dying they kept running over and over.

/cc @azamorano @santisaez

**Comment by rafatower** [comment]
Note to myself: somebody should look into this at least to get a better idea of what happened.

Also a review of importer exception handling can be worth the effort.

**Comment by iriberri** [comment]
This is still happening. There are peaks of these errors from time to time. Last ones were on Aug 31, Sept 1 -- and actually, during those days I was reproducing a timeout error for a user.

**Comment by iriberri** [comment]
Okay. I'd say this is a "frontend" issue. If the dashboard is opened, the frontend is polling the Import status all the time. Basically, the #show method for an import gets [here](https://github.com/CartoDB/cartodb/blob/ebfb0e62bfdb6bd941408b4d2f0826b3195318fb/app/services/carto/data_imports_service.rb#L29-L38), and the `mark_as_failed_if_stuck` method raises an exception to Rollbar: https://github.com/CartoDB/cartodb/blob/f8c33235c974a49bc70b8cc0a393d79edcf25379/app/models/data_import.rb#L254-L268

So this means that there's a ton of exceptions for each import just because the frontend is requesting the info, not because a loop in the backend. I have been able to reproduce the issue with my own account leaving the dashboard opened.

I'd say that if an import goes into this state, it means that it's no longer working anymore: https://github.com/CartoDB/cartodb/blob/ebfb0e62bfdb6bd941408b4d2f0826b3195318fb/app/services/carto/data_imports_service.rb#L148-L150 mostly because of:

```ruby
    def running_import_ids
      Resque::Worker.all.map { |worker| worker.job["payload"]["args"].first["job_id"] rescue nil }.compact
    end
````

**Comment by iriberri** [comment]
I opened a front issue to stop polling the import endpoint in this scenario. No back changes required.
