### ISSUE TITLE
JS error: `cdb.admin.forms` is undefined

### ISSUE THREAD

**Issue by Kartones** [CartoDB/cartodb#5860]
In production, file `wizard.js` is throwing me an error upon creating a new map with two datasets (haven't checked if depends on the layers data, one had points the otther world countries polygons).

## How to reproduce 
(having `stop on exceptions` active on Google Chrome dev tools)
- Go to `/maps` page
- Click on `Create new map`
- Select 2 datasets (I selected one with polygons, other with points)
- Click on `Create map`

## Expected behaviour
- Map loads without JS errors

## Actual behaviour
- Map loads but JS error appears.

Offending lines are:
```
  defaultFor: function(type) {
    var form_data = cdb.admin.forms.get(type)[this.table.geomColumnTypes()[0] || 'point'];
    return form_data;
  },
```
And the error is that `cdb.admin.forms` is undefined, causing:
```
Uncaught TypeError: Cannot read property 'get' of undefined
```

**Comment by xavijam** [comment]
When a map (visualization) model is created, there are other internal models within it that need to be created. Some of those internal models need to make server requests in order to know their state.
But when a map is created and the page redirects the user to the map view, those requests are aborted due to the browser redirection, but they don't collide with the map process.
It happens a lot when you send a request but it is stopped because you change the page.

**Comment by xavijam** [comment]
Closing since there will not be a solution for now.
