### ISSUE TITLE
spec/integrations/common_data_integration.rb (Test Parallelization)

### ISSUE THREAD

**Issue by jesusvazquez** [CartoDB/cartodb#5907]
```
  should import correctly Common Data datasets (FAILED - 1)

Failures:

  1) CommonData should import correctly Common Data datasets
     Failure/Error: @common_data = CommonData.new
     ArgumentError:
       wrong number of arguments (0 for 1)
     # ./app/models/common_data.rb:12:in `initialize'
     # ./spec/integrations/common_data_integration.rb:6:in `new'
     # ./spec/integrations/common_data_integration.rb:6:in `block (2 levels) in <top (required)>'
```

**Comment by rafatower** [comment]
@gfiorav can you please take a quick look at it when you have a chance and give a "guestimate" of how long this can take to get fixed?

**Comment by gfiorav** [comment]
@rafatower 

I was a bit confused as the test is obviously broken since @ethervoid `CommonData` modifications came into effect on the 20th of August but it had never actually failed until last week.

Speaking to @jesusvazquez, it has become apparent that a misconfiguration in the `Makefile` for test resulted in this test never being executed.

@ethervoid fixed all tests back in the day, but since this one wasn't executing and therefore did not fail, he didn't see it.

This test needs some fixes:
+ The file name should include a `_spec` suffix
+ A url should be provider to the `CommonData` constructor.

I will take care of both of those things and PR.

**Comment by gfiorav** [comment]
Ok so the problem is more complex than what it seemed at first.

The spirit of this test set is to check that common-data can be imported, so stubbing the API with a hardcoded JSON won't prove anything.

I'll wait until @ethervoid comes back to discuss the nature of these tests since I suspect no easy solution is available (i.e, we have to generate the 'common-data' user inside the test db).

**Comment by jesusvazquez** [comment]
Okey, since it's already excluded from the main spec blocks, I'm going to add the tag "# Pending" to exclude it from the parallel execution.

**Comment by gfiorav** [comment]
@jesusvazquez 

Just a recap:

These test were made when Common Data was an external source, that's why they're in a folder called `integrations`. Now, Common Data is just a user whose datasets we use, so it no longer makes sense to have these tests here. I'll remove them and when we make our end-to-end tests we will move them there.

Thanks, PR in a few minutes.

**Comment by gfiorav** [comment]
These test will be end-to-end [in the future](https://github.com/CartoDB/cartodb/issues/6029).
