### ISSUE TITLE
Private Dataset Shared as Read-Only to Users Within Org Not Downloadable

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/cartodb#6020]
S/B 7071919

## Context
Can't download a private dataset if shared to me by another user in an organization and marked "read-only"

## Process
1) Select a private dataset to share
2) Click on the lock icon and select share to users within org
3) Select the user to share with, toggle on "read" only permissions
4) Save settings

## Expected Result
User to whom the private, read-only dataset was shared with should be able to download the dataset for user in her own map, but not be able to change the original dataset

## Current Result
User cannot download the dataset or create a map with it

**Comment by Kartones** [comment]
This issue will get solved when https://github.com/CartoDB/cartodb/issues/6002 is finished, as we're enabling a read-only view of the editor instead of redirecting to the public map.

Current error is a missing `api_key` on the download url/link, which we cannot add because as we're at a 'public_map' it would get cached and pose a security bug.

So better to just wait to the new "readonly view" where you can export and click "visualize" and build maps with readonly shared datasets.

**Comment by juanignaciosl** [comment]
Bump (as this' been reported again).

**Comment by michellechandra** [comment]
S/B: 9695778

**Comment by xavijam** [comment]
@javitonino, https://github.com/CartoDB/cartodb/issues/6002 should fix this one too.

**Comment by javitonino** [comment]
Fixed with #9519. The downloaded file name is not very good though -> #9529
