### ISSUE TITLE
"X" icon does not look good - Infowindow

### ISSUE THREAD

**Issue by urbanphes** [CartoDB/cartodb#6113]
<img width="337" alt="captura de pantalla 2015-11-10 a las 18 49 09" src="https://cloud.githubusercontent.com/assets/14546701/11070470/271e19ce-87dc-11e5-9004-94dfede689f1.png">

**Comment by xavijam** [comment]
Under which browser? I guess there was any zoom level applied because it is properly styled right now:

Chrome:
<img width="390" alt="screen shot 2015-12-01 at 12 03 44" src="https://cloud.githubusercontent.com/assets/132146/11499096/e00ec724-9823-11e5-8ca9-d5923c4ec220.png">

Firefox: 
<img width="390" alt="screen shot 2015-12-01 at 12 03 44" src="https://cloud.githubusercontent.com/assets/132146/11499091/d858a144-9823-11e5-878b-e41fd7fcc811.png">
