### ISSUE TITLE
Strings starting with E & containing numbers import as "0" numbers

### ISSUE THREAD

**Issue by ztephm** [CartoDB/cartodb#6224]
@rafatower

S/B 6649574

A user is importing a dataset with a column containing long number sequences prepended with "E". It imports as number-type column instead of string. All of the "E...." values become 0.

## Context

User is importing an .xls but it also happened in my test CSV. Is this related to "E" being used in (scientific notation?)[https://en.wikipedia.org/wiki/Scientific_notation#E_notation]

## Process

1. Create a one-column CSV like this:
test_string
E00000012

2. Import with type guessing box checked

## Expected result

test_string column will import as a string type.

## Current result

test_string column imports as a number, and instead of "E00000012" the value is 0.

**Comment by rafatower** [comment]
there's a workaround: do not use type guessing.

**Comment by rafatower** [comment]
Actually that's incorrect notation. `E0000012` is not a number in most languages. Usually the correct one is `<number>[E|e]<number>`. E.g: `1e12`, `1E12`.

**Comment by rafatower** [comment]
OTOH a number like `1e-12` can be rounded up to `0.0` for representation, which doesn't mean it is actually 0.

**Comment by rafatower** [comment]
Taking it to the letter, it can be considered a bug or not. Depending on the language `E0000012` can be:
- considered valid e-notation, with the mantissa equal to zero and therefore `E0000012 = 0e12 = 0` which is correct
- considered invalid and therefore not a number (defaulting to string).

It needs to be fixed in gdal, but I'm considering this low priority as there's a workaround and arguably this is a bug.

There are several workarounds:
- do not use `E` as the prefix
- quote the values and use `quote_fields_guessing = false`. See http://docs.cartodb.com/cartodb-platform/import-api/standard-tables/
- do not use guessing at all.

**Comment by ztephm** [comment]
Thanks @rafatower we told client about workaround so not high priority for them.
