### ISSUE TITLE
Infowindow "change title labels" issue (updated Chrome in Windows 7)

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#6285]
Chrome version: 47.0.2526.80
SO: Windows 7 (from ModernIE)

In the infowindows tab, when clicking over the "change title labels", Chrome over IE is not showing the textboxes for editing the titles, as it does appropriately in Chrome over OS X. Therefore titles cannot be edited this way.

I have not seen any error in the console, besides a bunch of HTTPS warnings. I have recorded a video showing the process, so that you can see the behaviour (with dev tools open for you to check any possible message) [here](https://dl.dropboxusercontent.com/u/2879308/video-titles.mov). 

- 7594335

**Comment by ztephm** [comment]
S/B 8672102 also can't roll over the infowindow panel's A/ button consistently in Chrome 50.0.2661.75 on Windows 8.1.

We tested in VirtualBox & saw that interactive area is there but very small. Maybe only non-transparent areas of the A/ graphic are clickable?

**Comment by MariaCheca** [comment]
Hi! I've found the problem here: as an exceptional case, the tooltip of that link has a line break because due to its relative position from the link tag, it has not enough space to display the text in one line. So **the tooltip is over the link and it cannot be clicked**.

As it's not possible to give width properties to the tooltip element, I would modify the text to make it short and fittable.

**Comment by xavijam** [comment]
Could you attach a gif or an image?

**Comment by MariaCheca** [comment]
Sure! I just added a .gif in my explanation comment.

**Comment by xavijam** [comment]
Let's try with a 'Edit title labels', and if it doesn't work, 'Change titles'.

**Comment by MariaCheca** [comment]
'Edit title labels' works ok there, I'll send the PR asap. Thanks!

**Comment by ztephm** [comment]
Thanks guys! Notifying S/B 7594335 8672102
