### ISSUE TITLE
Organization Quota and User Quota mismatch

### ISSUE THREAD

**Issue by jqnatividad** [CartoDB/cartodb#6356]
With a new organization account with 5GB, I created a new user.

The UI says that the user had 100MB quota allocation.

But when I created an additional user, I wasn't allowed to proceed since it said I exhausted my quota.

I gather its not 100MB, but 100%, right?  There are several typos in the error messages too.

![new_ontodia_user___cartodb](https://cloud.githubusercontent.com/assets/1980690/12122249/d4f51254-b3a7-11e5-9b6d-94bafa0ea413.jpg)

**Comment by jqnatividad** [comment]
Ah OK.  The org account by default has 100% allocated to it upon creation.  Thanks for the clarification Mica!  What led me to the false report was that it incidentally had 100MB left when I created the additional user.

Still, the faulty error messages still deserve investigation.

**Comment by iriberri** [comment]
Hi @jqnatividad, that error appears because of the %NaN quota percentage choosen. If there's no quota left, the new user would have "X quota / 0 quota left", which is Not a Number. When setting a user with an invalid quota number, then the red error bar above appears.

Perhaps it could be useful to even block user creation if the system detects no quota left at all.

**Comment by MariaCheca** [comment]
Old UI. This problem is no longer happening.
