### ISSUE TITLE
Vizjson including widgets

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#6428]
- [X] Add widgets to the vizjson.
- [X] ~~Check whether editor that doesn't support widgets destroys them~~. Not needed because of v3 vizjson versioning.

**Comment by juanignaciosl** [comment]
I just committed a first attempt, take a look: 8c5c775500272117494e628e55d15c2156b26eb9. Focus on `vizjson3_presenter.rb` and `widget_presenter.rb`: a new `'widgets'` array is added at the root of the vizjson. Widget structure (`title` was added in 8c5c775500272117494e628e55d15c2156b26eb9):

```
{
           type: @widget.type,
           title: @widget.title,
           order: @widget.order,
           options: @widget.options_json
}
```

Note:
- Vizjson assumes that `options` contains `layerId`, which is not his concern.
- Title is optional, could be `null`.
- It includes `order` because since it`s a flat list containing all layers widgets you'll need it to sort it properly.

cc @viddo @alonsogarciapablo @acanimal @xavijam

**Comment by acanimal** [comment]
Looks fine for me. 

My concern is about where to place the widgets info and the format for the new vizjson file. So I put my comment here so we can discus.

From backend point of view I think it has sense think a layer contains some widgets. In addition, as @juanignaciosl suggested in chat, when you remove a layer all their widgets must be removed too.

From deep-insight and cartodb.js implementation this is not the same. The flow is: Editor ---(uses)--> DI ---(uses)---> cartodb.js The trouble is:

- Widgets are a concept implemented in DI.
- Cartodb.js don't know about widgets they only know about something called `dataviews`, which is a kind of data provider widgets uses to get data. *Sidenote: I don't spent time thinking on this but it is weird for my having a class on cartodb.js that it is only used by classes on DI. Don't would be better to move dataviews to DI?*

With previous in mind, in addition to the editor use case, where user adds layer, widgets, configure them, etc we have the *visualization uses cases", where user can share a visualisation created in the editor. In this case I found two scennarios:

1- "Deep insights" visualization: Given a vizjson a dashboard must be created: blue menu bar, maps, layers and widgets. Almost the same as in the editor.
2- "cartodb.js" visualization: given a vizjson a typical cartodb.js visualization must be created (simply the map, tools, etc No widgets neither blue.menu-bar), here tags in the vizjson, like `widgets, must be ignored because they will not shown.

**Comment by viddo** [comment]
Looks legit to me.

@acanimal widget persistence structure do not necessarily need to be 1-to-1 as how things are setup on the frontend, since the widget concept have slightly different lifecycle depending on what context we're talking about. @juanignaciosl and I conversed on this topic yesterday. 

I think it makes sense to delete related widgets when a layer is deleted (server-side), the only detail we have to take into account on the frontend is to just remove the models from a collection instead of deleting them explicitly (i.e. no `widgetModel.destroy()` are necessary).

**Comment by juanignaciosl** [comment]
@viddo the actual interaction for widget adding/removing is yet to be decided. Currently you should do it with the Widget API, which I guess is translated on create/update/destroy method calls on your side. Take into account that the widget collection is inside the vizjson, but you don't `PUT` it.

**Comment by alonsogarciapablo** [comment]
Why is `layerId` being included as an option? All widgets will have a `layerId` so I would personally move it out of the `options` attribute...

**Comment by juanignaciosl** [comment]
That was the structure I was given. I _think_ that's because layers are conceptually related to dataviews, not to widgets.

**Comment by alonsogarciapablo** [comment]
I think we agreed on something like:

```
{
  "type": "formula",
  "title": "Min population",
  "layerId": "4d82e8df-f21b-4225-b776-61b1bdffde6c",
  "options": {
    "column": "pop_max",
    "operation": "min"
  }
}
```

I personally think it totally makes sense because `layerId` is something common to all types of widgets (editor doesn't know anything about dataviews). Also, isn't that [how we're storing it in the DB](https://github.com/CartoDB/cartodb/compare/6428-Vizjson_including_widgets#diff-1979633456f9851f60bf03d02e704835R7)?.

**Comment by juanignaciosl** [comment]
Not a problem on my side as I said, I think the example I'm using is outdated.

**Comment by alonsogarciapablo** [comment]
:+1:

**Comment by juanignaciosl** [comment]
Added `layerId`, with `order` as well, so final structure is this:

```
{
  "type": "formula",
  "title": "Min population",
  "order": 1,
  "layerId": "4d82e8df-f21b-4225-b776-61b1bdffde6c",
  "options": {
    "column": "pop_max",
    "operation": "min"
  }
}
```

**Comment by alonsogarciapablo** [comment]
:+1: Thanks @juanignaciosl!
