### ISSUE TITLE
Problems with adding/removing columns

### ISSUE THREAD

**Issue by jsanz** [CartoDB/cartodb#6492]
Something wrong is happening between the editor and the SQL API when the user creates a new column or removes it. When adding a new column it doesn't appear (but checking directly with the SQL API the column is there) and a force reload is needed to get the new column at the editor.

On the other hand when the user removes the column an error is thrown at the editor and again, a force reload is needed to get the correct table schema and all. 

I've experienced this behavior this morning and just seen @piensaenpixel  having the same issue.

**Comment by xavijam** [comment]
@juanignaciosl @gfiorav here we go!

**Comment by gfiorav** [comment]
Apparently the SQL-API has been returning a `Last-Modified` header recently. The browser uses this information to decide on its own not to request a given page again (skipping varnish).

@rochoa can give some insight on the solution for this :smile:

**Comment by rochoa** [comment]
It's more a client side issue with last-modified and if-modified-since headers. Although varnish/api-sql are returning a fresh result the client is reusing the result as the new last-modified header is the same.

We will release a new SQL API version that will skip cached last modified result for authenticated requests until we find a general solution for all cases.

**Comment by xavijam** [comment]
Great, thanks @rochoa.

**Comment by gfiorav** [comment]
Thanks, @rochoa !

**Comment by xavijam** [comment]
The bug is reproducible under Chrome and Safari, but Firefox is working properly.
Also the problem can be found adding new rows.

**Comment by gfiorav** [comment]
Probably has to do with how different browser manage cache. I think the fix that @rochoa proposes should have us in the clear for all cases (rows, columns, etc). We'll see!

**Comment by michellechandra** [comment]
S/B 8026890

**Comment by zenitraM** [comment]
To solve this properly, the editor could invoke the [CDB_TableMetadataTouch SQL function](https://github.com/CartoDB/cartodb-postgresql/blob/master/scripts-available/CDB_TableMetadata.sql#L123) on the table instead of purging Varnish, which will both purge Varnish (either using Varnish or any other invalidation method set as a trigger on CDB_Tablemetadata) and bump the last_modified date on cdb_tablemetadata table (which will return a proper `Last-Modified` and might also help to avoid some other edge cases with cached tiles).

**Comment by gfiorav** [comment]
Genius! 

Let's try this tomorrow :)

**Comment by rochoa** [comment]
SQL API is no longer using the internal cache to return the last modified, but as @zenitraM pointed out we still need to invoke cdb_tablemetadatatouch so last update time gets updated and SQL API can retrieve that value for the last modified header.
