### ISSUE TITLE
Provide map ID for (client-side) data model

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#6499]
The (client-side) `MapModel` need the id to generate the appropriate URL base, e.g.:
`http://localhost.lan:3000/user/pepe/maps/abc-123/layers/…`

Right now [it's hardcoded](https://github.com/CartoDB/cartodb/commit/a08b86d67692e744cd71739a10b41b669573895b#diff-d27b00749653f54e193fd10402d14d8dR58) while WIP.

From what we understand it's something that should only be provided to the client-side of the editor, perhaps it's not to pass it through some serialized model like we're doing for [vizJSON and userData](https://github.com/CartoDB/cartodb/commit/a08b86d67692e744cd71739a10b41b669573895b#diff-e689b35dd9493bc346dbad25c9991ca6R7)?

cc @xavijam

**Comment by xavijam** [comment]
Could we get rid of it from the widgets api perspective?

**Comment by juanignaciosl** [comment]
[`map_id` is already _presented_ for the visualization at the editor](https://github.com/CartoDB/cartodb/blob/master/app/controllers/carto/api/visualization_presenter.rb#L39), so I guess you need it in the vizjson, isn't 't? @viddo, if you confirm this I'll add it as a first level attribute at the vizjson.

I guess @xavijam means don't adding it to the widgets api request/response payload, which I agree as long as you don't need it (I don't think you need it, since it's only used at the editor and you already have `map_id` there).

**Comment by xavijam** [comment]
We can't show the ```map_id``` in the viz.json due to the fact that it doesn't have to be public.

**Comment by viddo** [comment]
No, we don't need it in the vizJSON, or in any request/response payload. We only need it to construct the rest API endpoint as expected.

**Comment by juanignaciosl** [comment]
Then you already have it, isn't it? Check the source code of the editor page, it's loaded at `vis_data`.

**Comment by viddo** [comment]
Yes, I'll ping you once we have the PR ready (ETA tomorrow Tue), thx! :kiss:
