### ISSUE TITLE
"See all formats" is linked to the wrong URL 

### ISSUE THREAD

**Issue by arianaescobar** [CartoDB/cartodb#6539]
It should be http://docs.cartodb.com/cartodb-editor/datasets/#supported-file-formats instead of the current http://docs.cartodb.com/cartodb-editor.html#supported-file-formats

**Comment by arianaescobar** [comment]
There may be more broken links...

**Comment by javisantana** [comment]
where?

**Comment by arianaescobar** [comment]
oops sorry, here:

![screenshot_2016-02-09_14_56_01](https://cloud.githubusercontent.com/assets/16247628/12918086/763953ae-cf3d-11e5-909f-a72c08042365.png)

**Comment by ernesmb** [comment]
# steps to reproduce
- In the dashboard click on NEW MAP and select 'Connect Dataset'. 
- Clicking on 'see all formats' (image above) redirects to Editor Docs

# expected behavior
- The link should lead to: http://docs.cartodb.com/cartodb-editor/datasets/#supported-file-formats

# current behavior
- The link is now pointing to: http://docs.cartodb.com/cartodb-editor.html#supported-file-formats

**Comment by matallo** [comment]
the link has changed again, it should be:
https://carto.com/docs/carto-engine/import-api/importing-geospatial-data/#supported-geospatial-data-formats
