### ISSUE TITLE
Return proper table names on vizJSON and visualization data

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#6553]
We need a way of mapping layers <-> tables.  The table names are the ids, but for some reason both the visualization model and the vizJSON data contains `"".""` as table name:
![screen shot 2016-02-10 at 11 28 45](https://cloud.githubusercontent.com/assets/978461/12944802/cc1be690-cfe9-11e5-9e4c-be21499fbad6.png)
![screen shot 2016-02-10 at 11 29 07](https://cloud.githubusercontent.com/assets/978461/12944803/ccea0868-cfe9-11e5-8b3d-6c72b5cfea64.png)

**Comment by juanignaciosl** [comment]
Uhm. The problem is that "table_name" is inside `options`, and is sent _by_ the editor for torque layers. If you actually need some kind of layer <-> tables mapping we might try something else, backend-supported, instead of reusing that attribute.

Proposal: adding at vizjson v3, to `layer`, a `table_names` first-level attribute containing an array of the table names.

Summon @javisantana wisdom on this.

PS: maybe a brief summary about the need for that might be useful.

**Comment by viddo** [comment]
Yes, you're right, we figured it out.

**Comment by juanignaciosl** [comment]
Uhm, how have you overcome this?

**Comment by viddo** [comment]
We looked how things were setup on old editor.

Although, I'd say that the `table_name` is obviously wrong still, so feel free to reopen, but I'd guess it's not a prio to fix that atm.
