### ISSUE TITLE
Table Schema Changes when GeoJSON Response is Empty

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/cartodb#6651]
S/B 7251411
@iriberri 

### Context
If a user creates a sync table using a GeoJSON and the GeoJSON response when synced is empty, the schema of the table changes. If the table is being used with a SQL query in a map, and columns no longer exist, the map is broken.

### Process
Create a sync table from GeoJSON file hosted online. 
Empty the GeoJSON file:
```
{
"type": "FeatureCollection",
"features": [
{}
]
}
```
With an empty GeoJSON, there is no schema information. The updated table will be empty with only two columns (cartodb_id and the_geom).

### Expected Result
The updated table should retain the same schema as previously.

###  Current Result
Empty sync table with two columns (cartodb_id and the_geom)

**Comment by iriberri** [comment]
This issue is a duplicated from https://github.com/CartoDB/cartodb/issues/5131.

The "expected result" is not a current functionality of CartoDB, which is targeted in the issue #5131.

**Comment by jsanz** [comment]
I don't think it's duplicated, this is a different situation (or it should be at least). 

If instead of using GeoJSON the user syncs a shapefile and it's empty, the sync doesn't break because a shapefile has always a schema so the table would be simply empty.

GeoJSON doesn't explicit any schema, but  I don't think we should stop the sync (the solution addressed at #5131) but create an empty table with the same schema of the previous sync.

@iriberri what do you think?

**Comment by iriberri** [comment]
In #5131 we still don't really have the way to go. If you see the history of the issue, the first idea was to disconnect it. After some discussion (outside the thread), we thought that disconnecting would be too much, so we started thinking about just stopping it until there's a valid schema in a next sync.

If you have ideas about scenarios that we would have to take into account when the schema doesn't match between syncs, I encourage you to continue the discussion in the other thread (i.e. set a table with the old schema but no contents, instead of maintaining the old data until the schema is compatible again). I don't think that setting different behaviours with respect to the type of the file that is being uploaded is something we want to do.

**Comment by jsanz** [comment]
Oh well if the sync resumes then that's a different story, didn't knew
that, I thought when they stop user needs to resume it manually. I wasn't
referring to have different behaviors by file type quite the contrary.

Thanks for the detailed answer @iriberri !!

On Thu, Feb 25, 2016 at 5:03 PM, Carla <notifications@github.com> wrote:

> In #5131 <https://github.com/CartoDB/cartodb/issues/5131> we still don't
> really have the way to go. If you see the history of the issue, the first
> idea was to disconnect it. After some discussion (outside the thread), we
> thought that disconnecting would be too much, so we started thinking about
> just stopping it until there's a valid schema in a next sync.
>
> If you have ideas about scenarios that we would have to take into account
> when the schema doesn't match between syncs, I encourage you to continue
> the discussion in the other thread (i.e. set a table with the old schema
> but no contents, instead of maintaining the old data until the schema is
> compatible again). I don't think that setting different behaviours with
> respect to the type of the file that is being uploaded is something we want
> to do.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/6651#issuecomment-188854096>.
>



-- 
Jorge Sanz
Solutions Engineer
CartoDB · Map Your World's Data
