### ISSUE TITLE
Geocoding: Unable to return admin region polygons for any country with regional ADM1 boundaries

### ISSUE THREAD

**Issue by gtallen1187** [CartoDB/cartodb#6750]
Tested and confirmed with both Italy and Spain, but it looks as though the geocoder is currently unable to return boundaries for any country with regional admin1 polygons in [**this list**](https://github.com/CartoDB/data-services/blob/master/geocoder/admin1/sql/build_admin1_synonyms.sql#L17).

Steps to Reproduce:

1. Create an empty table in your account.
2. create two rows, and populate the `name` column for each row with any italian region name (list [here](https://en.wikipedia.org/wiki/Regions_of_Italy))

  > ![italy_regions](https://cloud.githubusercontent.com/assets/4712768/13467968/8e5e4a6a-e06e-11e5-9b97-ec20b0f1ddf8.png)

3. Geocode by Admin Region, use the `name` column for your regions, and type in `italy` as the country name.

  > 
![italy_regions_geocoding](https://cloud.githubusercontent.com/assets/4712768/13468002/b234ccfc-e06e-11e5-9da0-df31243acf25.png)

This will return an error.

**Comment by iriberri** [comment]
First, thank you for opening the issue! I have been handling geocoder data but haven't noticed about this issue before, so sorry for the delay.

For some countries CartoDB is geocoding admin2 but not admin1, due to the source geometries that we are using which are mixing up the categories.

In this case, this is the coverage for the administrative regions data for Italy:

![image](https://cloud.githubusercontent.com/assets/1730320/14213675/9645d9ea-f839-11e5-9603-e22a3f6d81bd.png)

We typically manage the geocoding data issues in our `CartoDB/data-services` repo, and this specific problem will be covered here (even though the title would not be the most appropriate in this scenario, check the description): https://github.com/CartoDB/data-services/issues/199

**Comment by iriberri** [comment]
By the way, Spain admin1 and admin2 should be both working, as I manually saved them in the database. If you have found any synonym that wasn't properly geocoded don't hesitate to open an issue in the repo!
