### ISSUE TITLE
Custom basemaps using http don't work in public maps

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#6965]
When using a custom basemap over http (e.g: `http://tile.stamen.com/watercolor/{z}/{x}/{y}.jpg`), it works in the editor but fails to load in the public map view. It seems that the public view is trying to load the basemap over https, even though the vizjson specifies the HTTP url.

@xavijam has been looking at this.

**Comment by xavijam** [comment]
There is a function in CartoDB.js that transforms some URLs to https, that stamen one is included :joy:.
https://github.com/CartoDB/cartodb.js/blob/2983b2fdcef914afdb1f4fdae173471143930452/src/vis/layers.js#L11

As @javisantana pointed me, we did that in order to prevent problems visualizing maps with https.
Let me close it!

**Comment by javitonino** [comment]
Perfect then, just went over the smoke tests results and didn't want to lose track of this.

**Comment by xavijam** [comment]
Really appreciated man :heart:
