### ISSUE TITLE
raster design mixes rendering and analysis

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#7120]
When we import a raster we generate a series of overviews for rendering, that's fine, the problem is we don't keep the original raster.

If you want to do any analysis you'd need to use the last overview. That overview is calculated sampling the original file so the results might not be the right ones.

The proposals is:

- keep original table to be used with SQL API
- generate overviews and use them from the tiles (as it's being done right now)

@rafatower

**Comment by javisantana** [comment]
regarding the problem, if we keep the original raster for analysis we could avoid the 3857 transformation, it only makes sense for rendering and that table is not being used for that.

What do you think @rafatower

**Comment by rafatower** [comment]
I was looking into mapnik pgraster plugin and I think we can keep the generation of the overviews provided we generate an overview with `overview.scale <= raster.scale` so that overviews are always used from the tiler and then import the original raster without any transformation but the cropping in tiles.

https://github.com/CartoDB/mapnik/blob/8cf77fa91467e31b6250861bfa0f23f9d622e055/plugins/input/pgraster/pgraster_datasource.cpp#L880-L914

The first iteration for this solution can be kind of a hack but should work without too much hassle. A second iteration might imply touching mapnik and `raster2pgsql` (within postgis package)

**Comment by rafatower** [comment]
So the code referenced above needs to be changed in mapnik in order to  use the highest resolution overview by default instead of the base table. Probably this also needs to be changed in raster2pgsql if we want it to generate overviews properly in one go: https://github.com/CartoDB/postgis/blob/48adac11f09a963cbbb85f01e060b162dda88ca9/raster/loader/raster2pgsql.h#L58

but I'll try to minimize changes outside cartodb in order to test everything ASAP.

**Comment by rafatower** [comment]
https://github.com/mapnik/mapnik/pull/3424

**Comment by rafatower** [comment]
Solved in the following PR's:

https://github.com/CartoDB/mapnik/pull/15
https://github.com/CartoDB/cartodb/pull/7282
https://github.com/CartoDB/Windshaft/pull/482
