### ISSUE TITLE
implement publishing snapshots (Mapcaps)

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#7379]
cc @saleiva @xavijam

**Comment by gfiorav** [comment]
On May 12 2016, at 2:07 pm, Juan Ignacio Sánchez Lara
&lt;notifications@github.com&gt; wrote:  

> Assigned [#7379](https://github.com/CartoDB/cartodb/issues/7379) to
[@gfiorav](https://github.com/gfiorav).

>

> —  
You are receiving this because you were mentioned.  
Reply to this email directly or [view it on GitHub](https://github.com/CartoDB
/cartodb/issues/7379#event-658488898)![](https://github.com/notifications/beac
on/AEBvauhc72KTOA1p_81Iv-I5MO8BTbZYks5qAxgHgaJpZM4IcVDW.gif)

**Comment by gfiorav** [comment]
Deployed via https://github.com/CartoDB/cartodb/pull/8024
