### ISSUE TITLE
Generate style_properties on the fly based on wizard_properties

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/cartodb#7391]
When a vizjson or named map of a layer without `style_properties` is generated, that option should be generated on the fly based on `wizard_properties` and the mapping at #7316. It will have a `autogenerated: true` property indicating that this is transient. This way we can distinguish whether it should be persisted/overriden or not.

cc @javisantana @xavijam

**Comment by juanignaciosl** [comment]
@xavijam, @alonsogarciapablo, @javisantana  after some checking I think that `wizard_properties` attribute is not used at vizjson or named map. Will `style_properties` be needed? Otherwise I'll only do this transformation at the (private) editor page.

**Comment by xavijam** [comment]
Yes, it is only used for the private editor.

**Comment by javisantana** [comment]
to give you some context. `wizard_propierties` is just a proxy from the UI to the rendering attributes (`sql`,  `cartocss` and some others), that's why we don't send it in the viz.json

We though about sending it so cartodb.js could do all the stuff (calculate style and legends) but we took turbocarto way
