### ISSUE TITLE
Windows 10 CSV Import Error - Unsupported File Format

### ISSUE THREAD

**Issue by michellechandra** [CartoDB/cartodb#7401]
@iriberri 

S/B - 8926604

## Context
Importing CSV file when using a Windows 10 machine on any browser causes an Unsupported File Format error. 

## Process
Log in to CartoDB Editor using Windows 10 machine on any browser
Attempt to import a CSV file by dragging / dropping or browsing for the file
Unsupported file format error will occur 

## Expected Result
CSV should import without error. The CSV is clean and uploads properly to CartoDB using a Mac OS with the latest version of Chrome.

## Current Result
Unable to import CSV file using Windows 10, but Excel file imports fine

**Comment by iriberri** [comment]
This failure is not due to the OS from which the file is imported (which is transparent for the Import API) but to the uppercase extension of the file. Please see https://github.com/CartoDB/cartodb/issues/7320, which I detected last week.

It was working with the Chrome over OSX because in the download, Chrome detects the .CSV extension and saves the file as .csv.

Please, don't forget to provide import log traces in the reports. :-)
