### ISSUE TITLE
[WIDGETS] Input layer is missing from widget configuration panel

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7504]
Remember that this is important to plug the widget to an analysis node or to a result. Right now they are plugged always to the dataset AFAIK. 

Also I think that we should always plug the widgets to the layer and not to the dataset of the layer by default since we will have the filter analysis for filtering the original dataset. What do you think @xavijam @javisantana @rochoa?

**Comment by rochoa** [comment]
AFAIK the first analysis you plug into a layer is using the layer's dataset instead of the SQL, once it starts using the layer's SQL everything will work as you expect.

And about applying the widget to the layer I think is just a matter of selecting the top node by default instead of the lower one:

![top-vs-low](https://cloud.githubusercontent.com/assets/45346/15533051/07b86b08-2263-11e6-93da-4b20b0def555.png)

**Comment by javisantana** [comment]
I will push for this as soon as we can since this opens one important performance and usability issue. When we start to attach widgets to the source node (by default is the layer but at some point we'll need to filter the source) we'll be raising analysis from the embed and that opens the pandorax box.

**Comment by rochoa** [comment]
Actually the current situation is like that, the widgets are attached to the source node by default 😈 .

**Comment by saleiva** [comment]
This requires also to add that selector to the editing UI

**Comment by xavijam** [comment]
Already done -> https://github.com/CartoDB/cartodb/pull/7529 :)
