### ISSUE TITLE
Expose Maps API error requests to the builder

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#7574]
Basically we need to know when a request to the Maps API failed.
It would be great if we could have:

- The reason of the error (`column whatever is not present`).
- Which is the affected component (layer id, widget id, whatever...).

cc @rochoa @viddo @javisantana and @nobuti (he will be using it in the main loader).

**Comment by alonsogarciapablo** [comment]
I've been looking into this and talked with @xavijam about it (thanks for the insights) and here's some context/planning.

## Scenarios

1. Map instantiation fails due to one or multiple of the following errors.
  1.1. Some layer related stuff is wrong (eg: cartocss).
  1.2. Some analysis related stuff is wrong (eg: column doesn't exist).
  1.3. Some dataview related stuff is wrong (eg: type of column is wrong).
2. Map instantiation fails due to an unknown error.

## The Maps API

When there's a known error (1) the Maps API will return something like:

```
{
  error: [ ... ],
  errors_with_context: [
    {
      type: 'analysis',
      context: {
        index: 0,
        id: '1234567890',
        type, 'buffer'
      },
      message: 'Analysis requires authentication with API key: permission denied.'
    }
  ]
}
```

Given that we manage 3 type of objects (layers, dataviews, and analyses) in CartoDB.js/editor/Maps API, it would be nice if the Maps API could categorise errors in one of these 3 types (@rochoa @dgaubert  what do you think ☝️ ).

When an unknown error happens (2), Maps API returns:

```
{
  errors: [ ... ],
  errors_with_context: [
    { 
      type: 'unknown',
      message: 'THE INTERNETS ARE ARE BROKEN',
      context: 'unknown'
    }
  ]
}
```

## CartoDB.js

Maps instantiation errors will be exposed through:

1. `vis` model
2. `layer` models.
3. `dataview` models.
4. `analysis` models.

Let's say, for example, CartoDB.js tries to instantiate a map with a layer whose CartoCSS is not right:

- The `vis` object will trigger an `error` event with a message like `There're some issues with this map`.
- The `layer` object will trigger an `error` event with a message like `CartoCSS is not valid: marker-fill: #;`

Not sure if it would be helpful but perhaps we could categorise errors and append a prefix to the message. Like: `TurboCartoCSSError: Syntax error. Line 11: Invalid code: marker-fill: #;` (@xavijam @nobuti @viddo would this help?)

Since all these objects are Backbone Models, we can just use Backbone Events for now.

Feedback welcome, thanks!

**Comment by viddo** [comment]
First, thx for writing this summary, very helpful! I currently lack info of where/how will the error feedback be displayed to the end-user though (i.e. what's the use-case that motivates the context-specific errors)? Without that I feel it's a bit hard to give more specific feedback. 
I'll comment on what I can meanwhile:

> Not sure if it would be helpful but perhaps we could categorise errors and append a prefix to the message. 

Prefix with what/how? Can you elaborate a little more what you have in mind?

> `errors_with_context: [{ message: 'something', …`

I assume this `message` is intended for developer convenience, right? I think it would be helpful to have some system of error codes, to be able to produce suitable (translated etc.) error feedback in the UI.

> Maps instantiation errors will be exposed through: vis model, layer models, …

E.g. Perhaps it would make sense to also expose all errors through a single channel? Not as a replacement but in addition to what you propose. Having to keep track of all individual objects where errors might happen can be a bit tedious. (Again, depends on the use-cases)

**Comment by alonsogarciapablo** [comment]
> where/how will the error feedback be displayed to the end-user though

If something is wrong with a layer, analysis, dataview, the "object" in the UI will expose the error. Examples:

![screen shot 2016-06-22 at 11 36 13](https://cloud.githubusercontent.com/assets/390398/16261935/d2ef66a8-386d-11e6-9fa1-a5dbde5419dc.png)
![screen shot 2016-06-22 at 11 36 43](https://cloud.githubusercontent.com/assets/390398/16261936/d2f4cc60-386d-11e6-9f10-8b6e68296bb3.png)

Other unknown errors will be displayed in the "global" Notifier.

> Prefix with what/how? Can you elaborate a little more what you have in mind?

I was thinking if a message like `TurboCartoCSSError: Syntax error. Line 11: Invalid code: marker-fill: #;` would make things easier (prefix would be TurboCartoCSSError here). Just so that there's a way to know what type of error it is. Perhaps 👇  makes more sense.

>  I think it would be helpful to have some system of error codes

I like the idea! Specially since we'll want to translate the UI at some point. cc: @dgaubert @rochoa 

>  Perhaps it would make sense to also expose all errors through a single channel?

IMO, since there's a 1:1 mapping between models in the editor and CartoDB.js we should be good for now with errors triggered by each object...

**Comment by viddo** [comment]
thx for clarifications, agree with your comments 👍

**Comment by rochoa** [comment]
> Given that we manage 3 type of objects (layers, dataviews, and analyses) in CartoDB.js/editor/Maps API, it would be nice if the Maps API could categorise errors in one of these 3 types: `type: 'layer'`, `type: 'analysis'`, and `type: 'dataview'` (:point_left: @rochoa @dgaubert  what do you think? ).

I'm OK with that proposal, although there will be situations where it's hard to decide whether is one type or another. What happens when the error could be either an analysis error or a layer error? 😛  A layer source pointing to a non-existent analysis node id: is it a layer error or an analysis error?

**Comment by alonsogarciapablo** [comment]
> I'm OK with that proposal, although there will be situations where it's hard to decide whether is one type or another. What happens when the error could be either an analysis error or a layer error? 😛 A layer source pointing to a non-existent analysis node id: is it a layer error or an analysis error?

Layer error IMO: It's the layer the one that is pointing to something that doesn't exist.

**Comment by alonsogarciapablo** [comment]
The "final" version of errors with context has been implemented in: https://github.com/CartoDB/Windshaft-cartodb/pull/525

**Comment by alonsogarciapablo** [comment]
Implemented in https://github.com/CartoDB/cartodb.js/pull/1324.
