### ISSUE TITLE
Link ghost tables on import API run

### ISSUE THREAD

**Issue by talos** [CartoDB/cartodb#7718]
Non unlinked tables have become a big problem with programmatic imports.  It shouldn't add any appreciable overhead to link ghost tables after an import API run, instead of just when the dashboard is loaded.

@gfiorav

**Comment by ramiroaznar** [comment]
@gfiorav @juanignaciosl is this issue still happening?

**Comment by juanignaciosl** [comment]
This ~"issue"~ is still happening, because Import API is not related at all with ghost tables. It's not a matter of performance, it's just that we shouldn't do it. Import API links imported tables, and shouldn't worry about other existing tables.

We could consider a programmatic way to trigger ghost tables, but importing any dataset shouldn't have this effect.
