### ISSUE TITLE
Add SQL editor for data panel

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#7759]
- [x] Add switcher between data content or sql panel.
- [x] Add SQL editor.
- [x] Add SQL parser
- [x] Don't let edit SQL if an analysis is applied.
- [ ] ~~Add data panel with new stats~~ (cc @fdansv). #7815
- [ ] ~~Retro compatibility between layer sql and query schema model query.~~ #7843

**Comment by nobuti** [comment]
Current status:

![sql](https://cloud.githubusercontent.com/assets/1366843/15971230/7038e9c8-2f38-11e6-9211-cd1dc537f9f8.gif)

The views (mostly placeholders), the toggle and the sql editor are there. We are showing errors from sql but we can't show the error's line number, because the parser is not able to provide it. So, we are getting rid of it in the sql editor for now.

@xavijam I need some clarification about when an analysis is applied, and all the stats from @fdansv to render them properly.

**Comment by xavijam** [comment]
Looks great :). Let's talk about analysis and so on on monday and then with @fdansv about the data integration ok?

**Comment by nobuti** [comment]
No te preocupes ™️
