### ISSUE TITLE
Open the popup components on the top of the fields when no space at the bottom

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7786]
So we avoid this
![screen shot 2016-06-13 at 19 36 36](https://cloud.githubusercontent.com/assets/132149/16017017/40d946ce-319e-11e6-8fc9-7d1a9ea31f5f.png)

**Comment by saleiva** [comment]
Remember this was initiated by @piensaenpixel and @MariaCheca I think

**Comment by matallo** [comment]
I've already started come work on this, but there are some cases where the dialog is high enough that the dialog header is overlapped by the tab bar (see attached) how can we solve this?

![screen shot 2017-02-03 at 12 01 58](https://cloud.githubusercontent.com/assets/36676/22589145/16f5e1c2-ea09-11e6-926a-6f6710698f03.png)

not easily fixed with a change in the z-index

/cc @CartoDB/design

**Comment by xavijam** [comment]
Yes, that's one of the stoppers we found with the first try of this tickets. And try with a polygons layer, where there is no aggregation block, please.

**Comment by arianaescobar** [comment]
Can't we make it appear on top of the tab bar?

**Comment by xavijam** [comment]
No (right now), because the component belongs to the form. We took that decision because when you scroll you want to have the component there, not floating and being disappear when that action happens. Said that, custom scroll is another component, and form doesn't know anything about it, so the communication with it would be really difficult in case we want to implement the "floating" popup...

**Comment by matallo** [comment]
Indeed, not an easy workaround unless we pass the reference of the
_parent_all the way down or access the parent directly from the component
which is not desirable at all.

**Comment by saleiva** [comment]
We might need to find a way to do what @arianaescobar says... That's how this components should work. If not, we will keep having issues all the time :(

**Comment by xavijam** [comment]
If we want the component to be floating (over other components), we will need:

- Scroll component should notify/trigger in any way, when user is scrolling.
- Form (yes, Backbone.Forms) should be warned when user has scrolled in a parent view.
- Form should close all "floating" components opened if user has scrolled.
- Make all desired form components with dropdown flotable (please, with a custom attribute, let's not make it by default because those components are used everywhere).

... those are my thoughts.

**Comment by xavijam** [comment]
Adding @nobuti to the loop, because he knows about scroll component and has played with Backbone.Forms.

**Comment by nobuti** [comment]
I agree, there is no easy workaround for this. We can append the popup to the body, keeping the reference to the input to translate the right position in terms of the viewport. The hardest part is to get the popup to respond to the scroll when it's open because obviously, they are not going to be under the same context anymore.

**Comment by nobuti** [comment]
Picking this

**Comment by nobuti** [comment]
@arianaescobar @saleiva making the popup to open on top of everything will not work on every case. What should happen when the field that throws the popups disappears behind the scroll area? See the screencast below and imagine it opens on top.

![popup](https://cloud.githubusercontent.com/assets/1366843/22927031/7e06b482-f2af-11e6-90f8-205eae69ee31.gif)

In that scenario, should we close the popup? should we close the popup once the user does scroll?

**Comment by arianaescobar** [comment]
I keep thinking that dropdowns should work like tooltips, appearing on top of everything, and not bounded to that scrollable area. In that scenario, the dropdown would open on top of its field, and it would probably cover part of the header and when you scroll, it would disappear.

**Comment by josecruz** [comment]
I agree on what @arianaescobar says but I would lock the back form scroll when having opened a dropdown so we avoid the dropdown to be closed by mistake scrolling outside it.

**Comment by arianaescobar** [comment]
that's a great idea

**Comment by piensaenpixel** [comment]
+1 but.. IMO i'd leave the scroll locked for a second iteration

**Comment by nobuti** [comment]
Ready for CR.

**Comment by ivanmalagon** [comment]
Deployed to produ.

:man_dancing:
