### ISSUE TITLE
Some endpoints are extremely slow

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#7839]
Hard to reproduce since it's not happening always, but looks like some endpoints are very slow.
Attaching one when trying to add a widget

![screen shot 2016-06-14 at 13 46 59](https://cloud.githubusercontent.com/assets/132149/16041618/b70882fe-3236-11e6-997f-57a6d2a26230.png)
![screen shot 2016-06-14 at 13 47 11](https://cloud.githubusercontent.com/assets/132149/16041619/b7139fe0-3236-11e6-91c6-129f7711ae74.png)

cc/ @javisantana

**Comment by juanignaciosl** [comment]
@saleiva ok, we'll take a look. If it happens with other endpoints please let us know.

**Comment by javisantana** [comment]
probably related to index creation @javitonino ?

**Comment by juanignaciosl** [comment]
We've already talked about that, but [index creation is enqueued](https://rollbar.com/vizzuality/CartoDB/items/18797/?item_page=0&#instances), it can't affect. We're getting some slow (>40s) updates on some tables, including `widgets`, we should research that.

**Comment by saleiva** [comment]
With styles it also happens

2016-06-14 14:15 GMT+02:00 Juan Ignacio Sánchez Lara <
notifications@github.com>:

> @saleiva <https://github.com/saleiva> ok, we'll take a look. If it
> happens with other endpoints please let us know.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CartoDB/cartodb/issues/7839#issuecomment-225862944>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIENSAKFHTFKch_rwBtxhYkPUCge-7Uks5qLptngaJpZM4I1PFV>
> .
>



-- 
Sergio Alvarez Leiva

**Comment by juanignaciosl** [comment]
Ok, thanks, we're pretty sure that it's related to database random slowness.

**Comment by javitonino** [comment]
After looking at logs until my eyes bled, I'm pretty sure this is related to named maps updates, with some aggravating factors. I have seen named maps updates to take up to 45 seconds without apparent reason, and we do these updates synchronously from the UI worker, so this is what delays the update. The new named map implementation has a 5 second timeout, which should help with that, but maybe at the cost of losing updates.

Additionally, we update the named maps and invalidate caches inside the DB transaction, so if a worker gets stuck on a named map update, the row gets exclusively locked for all competing transactions and everything crawls to a halt. That's why we are seeing long query times as well.

Finally, some UI operations launch a lot of requests. The biggest offender I found is widget reordering, which launches two request for each widget (one for the widget, one for the layer). If any of the requests get stuck updating named maps, we block all other until that finishes.

Proposed actions, to discuss:
 - Investigate slow named maps updates in the tiler @rochoa 
 - Extract costly operations outside of the DB transaction. This should be slightly better with the named maps refactor, which updates named maps after commit.
 - Reduce number of calls to named maps api #6901
 - Batch operations from the UI: @xavijam
   - We have a batch update endpoint for layers, we should do the same for widgets. This way, layer reordering should just call a batch update for widgets and another for layers (2 requests instead of 2n)
   - Delayed updates when changing slider values may also be a good idea if it is easy to implement.

**Comment by rochoa** [comment]
I will try to investigate why those endpoints get stuck sometimes, as they should be really fast operations, doing some validations and interacting just with redis server.

One idea we discussed some time ago was to change the semantics of named maps rest service, so PUT endpoint could accept updates and new items, that way we would remove half of the requests from the editor: IIRC we do a GET to know if the named map already exists and then a POST or PUT based on existence.

**Comment by xavijam** [comment]
cc @gfiorav

**Comment by javitonino** [comment]
We merged some changes to reduce the number of named maps calls and execute them after the transaction. This appears to be helping a bit, we still have a slow update from time to time, but not the same peaks we had before.

**Comment by javitonino** [comment]
Closing since this doesn't seem to be an issue anymore since we updated redis timeouts.
