### ISSUE TITLE
Analyses colors are not correct

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#7855]
![screen shot 2016-06-15 at 11 05 16](https://cloud.githubusercontent.com/assets/132146/16074074/1f3a8bd0-32e9-11e6-9e01-5506b9e6a066.png)

**Comment by alonsogarciapablo** [comment]
@viddo were you planning to do this?

**Comment by viddo** [comment]
I figured I'd do it eventually, but first I want to finish the layer creation. If you don't have anything else to work on you could start on it.
But either way I'd most likely need to change some things in my current WIP (the layer-creation-from-node), since some logic related to how the nodes are rendered have changed.
