### ISSUE TITLE
The visualization is not updated if you save the SQL custom when the map is new

### ISSUE THREAD

**Issue by nobuti** [CartoDB/cartodb#7875]
Steps to reproduce:

- Create a new map
- Go to the SQL editor and change the default query to a custom one
- CMD + S (nothing happens but all it's saved).
- F5
- Repeat steps 2 and 3 and see that the map is updated to show the result properly

As @viddo says, the problem is most likely that when reloaded the analysis is given to `cdb` through the vizjson, so the node and query exists, while when “fresh” `cdb` discards the node/query changes. If you compare the `map?stat` requests there’s no analyses on a fresh map, until a non-source node is created
but once reloaded it includes the analysis.

**Comment by xavijam** [comment]
In my opinion this is an important bug, because we can't apply new queries, and also, after a deep check, we are making more requests than needed.

**Comment by xavijam** [comment]
cc @CartoDB/frontend

**Comment by alonsogarciapablo** [comment]
Ok, here's what's happening... When the map is created, the map is created in CartoDB.js through [`deepInsights.createDashboard`](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb3/editor.js#L72), using the data that is present in `window.vizJSON` (right after the redirection). The vizjson contains the following information about the "data" layer:

```
{
  "id": "9f5359e7-e4b6-46b6-8eef-801bac7bfc70",
  "type": "CartoDB",
  "infowindow": { ... },
  "tooltip": { ... },
  "legend": null,
  "order": 1,
  "visible": true,
  "options": {
    "layer_name": "paradas_metro_madrid_1",
    "cartocss": "#paradas_metro_madrid_1 { ... }",
    "cartocss_version": "2.1.1",
    "interactivity": "cartodb_id",
    "sql": "select * from paradas_metro_madrid_1"
  }
}
```

As you can see, there's no `source` option for this layer, so CartoDB.js doesn't know that it's connected to the analysis node whose SQL we're changing. When the map is reloaded, the vizJSON does include the `source` option for this layer, and everything starts working fine...

**Comment by alonsogarciapablo** [comment]
The editor initially sets the `source` attribute for the layerDefinitionModel [here](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb3/data/layer-definitions-collection.js#L124) and since this attribute doesn't change when we update the SQL of a layer (it shouldn't change), the `source` [is never propagated](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb3/deep-insights-integrations.js#L171) to CartoDB.js.

**Comment by viddo** [comment]
Before the node is saved [there's an explicit layer-save being done](https://github.com/CartoDB/cartodb/blame/fix-layer-drag-size/lib/assets/javascripts/cartodb3/editor/layers/layer-content-views/data/data-view.js#L104-L105), which should create an analysis so the node exists, but I guess the source is not updated since it's not changed since the [layer was created](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb3/data/layer-definitions-collection.js#L123-L138). Perhaps we should move that "up", to be applied on the vizjson so the data between editor/cdb is consistent? Or do you have any other idea how to get around this?

**Comment by alonsogarciapablo** [comment]
As discussed offline I'll change the integration between CartoDB and CartoDB.js so that, when a layer definition changes in CartoDB, the source of the layer in CartoDB.js is set/updated if the layer didn't have one.
