### ISSUE TITLE
Analysis workflow view is not scrollable, so hides some analyses

### ISSUE THREAD

**Issue by viddo** [CartoDB/cartodb#7880]
![screen shot 2016-06-16 at 12 06 52](https://cloud.githubusercontent.com/assets/978461/16113080/da634d12-33ba-11e6-80d4-a96fac403d61.png)

A3 and A2 in the screenshot, so they can't be accessed from this view.

**Comment by piensaenpixel** [comment]
cc @xavijam we should add scroll here :(

**Comment by xavijam** [comment]
Why not passing them to the next line?, Anyway, whatever you decide @CartoDB/design team is ok.

**Comment by javisantana** [comment]
I think that should be fixed doing some kind of merging, the reasons are:

- If you have that amount of analysis means you are doing some operations that can be merged and seen as just one
- it give api room for optimization since we remove a lot of temporal tables in the middle (hopefully)
- With that amount of analysis you feel missing when, for example, add a widget

As an early feedback, we should name the analysis by the analysis name and not just a letter when you are not seeing the layer list

cc @saleiva @urbanphes

**Comment by javisantana** [comment]
(of course not for 7/7)

**Comment by piensaenpixel** [comment]
@xavijam not very easy because we should draw the line, between the last one of the first line and the first one of the second line...

**Comment by urbanphes** [comment]
![image](https://cloud.githubusercontent.com/assets/14546701/16144632/9bdc8328-3474-11e6-910f-6a76566b040d.png)

This could be a solution. You can view your analysis always.

**Comment by piensaenpixel** [comment]
For me, that's very strange how you read, but let me check

**Comment by matallo** [comment]
strange to me, too

I'd rather left-to-right-top-to-bottom

**Comment by urbanphes** [comment]
but...

How do they connected analysis ends?

**Comment by urbanphes** [comment]
@piensaenpixel this is the solution, a carrousel

![image](https://cloud.githubusercontent.com/assets/14546701/16148260/babdb398-3488-11e6-9586-310faed032f6.png)
