### ISSUE TITLE
If denominator is optional, we should add a checkbox to activate/deactivate it

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8018]
like we do in the style panel with the animated options for example.

**Comment by inigomedina** [comment]
I'm closing this issue because it has been inactive for a long time. This probably means that it is not reproducible or it has been fixed in a newer version. If it's an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue.

Thank you!
