### ISSUE TITLE
Buffer analysis should work on lines layers

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8075]

**Comment by viddo** [comment]
It already does: https://github.com/CartoDB/camshaft/blob/master/reference/versions/0.17.0/reference.json#L38

The problem is that it's not possible to create a buffer from the modal anymore since it was removed recently (#7965), the remaining area-of-influence option only [supports points](https://github.com/CartoDB/camshaft/blob/master/reference/versions/0.17.0/reference.json#L246). cc @javisantana

**Comment by saleiva** [comment]
So we should change it on the AOI

**Comment by viddo** [comment]
Change it so the option is the buffer would solve it.

**Comment by saleiva** [comment]
Who should assign this to me?

**Comment by viddo** [comment]
I can take it and get to it _eventually_, unless someone else picks it up before me
