### ISSUE TITLE
Name shown in the layer list for some analysis is wrong

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8317]
- [ ] Link to layer analysis.
- [ ] Cluster.

STR, add analysis to the layer, and go to the layer list.

**Comment by viddo** [comment]
Shouldn't the titles used in the layers list match the ones shown in the add-analysis modal? It's a bit weird to only read "Cluster" in the layers list and not know if it's a kmeans or moran.

![screen shot 2016-07-01 at 11 34 02](https://cloud.githubusercontent.com/assets/978461/16517827/c5fe911c-3f7f-11e6-8116-ae22a575a318.png)

**Comment by saleiva** [comment]
but that was the object of this ticket right? I might be getting it wrong

**Comment by viddo** [comment]
The issue didn't have much information, but I thought it was about the layers list (since that was the only thing mentioned).

Either way, if you compare the [tokens for layers list](https://github.com/CartoDB/cartodb/blob/master/lib/assets/locale/en.json#L19-L29) vs. [options modal](https://github.com/CartoDB/cartodb/blob/master/lib/assets/locale/en.json#L314-L347) you can see the differences/inconsistencies, it would help to know which ones are correct, and if they should be consistent or not in the two locations.

**Comment by saleiva** [comment]
Ok, I'll prepare the list for you

**Comment by viddo** [comment]
Bump, are there still literals that should be fixed finally or were they finally resolved in other issues/PRs?
