### ISSUE TITLE
Explain Moran Tool 

### ISSUE THREAD

**Issue by cartodave** [CartoDB/cartodb#8343]
![enhancement](https://cloud.githubusercontent.com/assets/15348234/16465711/5d41a282-3dfd-11e6-9f90-028a38b3f95f.JPG)
For Moran's tool. Make the 'numerator' and 'denominator' more clear in the context of the analysis: 

example: Numerator = 'variable of interest' denominator = 'weight' or similar....

**Comment by saleiva** [comment]
hey @ohasselblad could you provide us some text and short explanation about every parameter of this?

**Comment by xavijam** [comment]
We could add them as help tooltips.

**Comment by javisantana** [comment]
here we have an explanation https://github.com/CartoDB/crankshaft/blob/develop/doc/02_moran.md#arguments

```
```

**Comment by ohasselblad** [comment]
I'd change

* numerator -> `input variable` (`variable of interest` is good, too)
* denominator -> `normalization (optional)` 
* `neighbours` should lose the `u`? I see more American English spellings than British English spellings in our product.

For tooltips, 

* `input variable`: "The input variable is used for calculating statistically significant spatial clusters and outliers."
* `denominator`: "This optional parameter is used for forming a rate with the input variable. E.g., total population if the input variable is total of sub-population."
* `significance`: "The statistical significance of the spatial cluster our outlier core. Smaller numbers are more significant. Significance is a metric on the probability that the cluster or outlier pattern is due to a random process."
* `neighbors`: "The number of spatial neighbors for comparison of any geometry."

**Comment by saleiva** [comment]
That content looks great @ohasselblad. BTW, normalization or denominator finally?

**Comment by ohasselblad** [comment]
argh, tough one. Let's go with 'denominator'.

**Comment by saleiva** [comment]
@andrewxhill can you take care of this then?

**Comment by andrewxhill** [comment]
https://github.com/CartoDB/cartodb/pull/8573/commits/769440182f971234558d96ade15a85b612910bc4
