### ISSUE TITLE
When an analysis is loading, widgets should show the loading bar as well

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8365]
_edit: //@viddo_

TODOs:
- [ ] await https://github.com/CartoDB/cartodb.js/pull/1356 to be merged
- [ ] update internal deps

**Comment by saleiva** [comment]
Hey @viddo @xavijam just noticed that we might need to prioritize this since a map with widgets and analysis is on the new homepage and the feeling is pretty bad.

maybe @alonsogarciapablo or @fdansv could help?

**Comment by viddo** [comment]
[Feel free to prioritize it among the other stuff I have pending](https://github.com/CartoDB/cartodb#boards?repos=4909355,4871551,47708079&milestone=Vamosnenos%20-%20editor%203-2016-07-07&assignee=viddo). I want to close all the _in progress_ things before I start on something new, I'll get to it eventually unless someone else takes over the ownership of it.

**Comment by saleiva** [comment]
ok, cool

**Comment by viddo** [comment]
reassigning to @rochoa will investigate it, he thinks it's related to a response from the maps API 😚

**Comment by rochoa** [comment]
Reassigning it back to @viddo. Backend responses were getting widgets to error state, but now that backend responses don't fail the loading progress bar is not showing although the widgets are in loading state and eventually the load the results.

**Comment by viddo** [comment]
Findings so far seems like the underlying dataviews aren't aware of analysis so that would have to be updated on cartodb.js (and then having the dependency bumped here) to solve this.

Also awaiting https://github.com/CartoDB/cartodb.js/pull/1356 since it contains a fix to the dataview to be we aware of its data source. Will create an issue on that repo to fix this.

**Comment by viddo** [comment]
Reassigning to @alonsogarciapablo since I won't have time to finish this before leaving for vacation, sorry about that. :(
On the good side, tho, the awaiting PR in cdb.js is done and I've tested locally and it seems to work as it should now, so once that is reviewed & merged it should just be a matter of updating the internal deps over here. cc @xavijam
