### ISSUE TITLE
Analysis layers don't hold styling when dragged to new layer

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#8382]
Walking through the Store Locator workflow, it would be nice if as much as the layer holds its **analysis** from previous steps that it also holds its **styling**.

Examples: 
- steps 4 and 9 are very repetitive (lots of button clicking and steps to go through twice)
- the styling done at step 6 is lost again by step 11 -- to get it back, you have to do the (bivariate) styling again 

By step 9 you've styled the kmeans/customer points **twice** but probably have a map that looks something like this:
![screen shot 2016-06-30 at 4 50 45 pm](https://cloud.githubusercontent.com/assets/1566273/16492651/d0b5a278-3ee2-11e6-8d29-307ea50d88ea.png)

But after step 11, the styling work is gone:
![screen shot 2016-06-30 at 5 14 47 pm](https://cloud.githubusercontent.com/assets/1566273/16493582/536c6a14-3ee6-11e6-804c-993353f2e9dc.png)

Just an example of what is going to happen every time a layer is pulled out to run another analysis. If the analysis is inherited, can't the styling be as well?
# SMOKE_AN09

**Comment by viddo** [comment]
>  If the analysis is inherited, can't the styling be as well?

ATM the styles are stored on the _layer_, not the _analysis node_, so when the analysis changes (adding, removing, dragging to a new layer…) the styles are reset. 

I've also noticed this behavior and think what you suggest makes sense and is more intuitive. But it require some non-trivial changes to how layers<->analysis<->styles are setup/persisted.

**Comment by saleiva** [comment]
+1 to @makella's suggestion and also +1 to @viddo let's try to fix this but not before the release date :(

**Comment by javisantana** [comment]
Technical description of this:

Basically we only keep style (and other properties) information for the layers. Each layer points to an analysis node so when the that node changes (because we add an analysis for example) we lose the information.

In order to do what @makella proposes we need to implement a new feature to keep layer state per node.

**Comment by viddo** [comment]
Based on the what we have/know so far, I can only see two hard requirements:
- Be able to associate a set of styles with a particular node
  - Considering styles are something that is related to _how_ some _data_ should be visualized, I think we should maintain the current way dependencies are setup, i.e. layers/styles knows about analysis but not the other way around.
- Allow multiple styles to be associated with each node
  - e.g. there can exit a single node a0 which have multiple layers A and B depending on it, each with their own set of preferences of to visualize the output.

Btw, wouldn't it make sense to also treat pop-ups in the same way then (same rules as above)?

I think the easiest approach would be store a collection of styles on the layer, instead of a single model which is the case now.

**Comment by saleiva** [comment]
pop-ups in the same way +1

**Comment by xavijam** [comment]
Branch: 8382-styles-per-node

**Comment by viddo** [comment]
💪 👏

**Comment by saleiva** [comment]
ha!
