### ISSUE TITLE
Aggregation by administrative region doesn't seem to work

### ISSUE THREAD

**Issue by fernando-carto** [CartoDB/cartodb#8543]
After watching the video on styling (great new capabilities by the way), I wanted to do an aggregation by country on a twitter map but it doesn't seem to work.

As per the attachments, when I switch from "squares aggregation" (OK) to "administrative region" aggregation (KO) I get the same result.

Thanks

![captura de pantalla 2016-07-06 a las 10 49 42](https://cloud.githubusercontent.com/assets/19906145/16612551/d6ea76c6-4367-11e6-9e26-00787a690790.png)
![captura de pantalla 2016-07-06 a las 10 49 31](https://cloud.githubusercontent.com/assets/19906145/16612552/d6f6b7ba-4367-11e6-83fc-8e3ccb782544.png)

**Comment by saleiva** [comment]
Well, it works to me.
Can you check in the developer console if the API is failing?

**Comment by fernando-carto** [comment]
{errors: ["permission denied for relation agg_admin0"], errors_with_context: [,…]}
errors
:
["permission denied for relation agg_admin0"]
0
:
"permission denied for relation agg_admin0"
errors_with_context
:
[,…]

**Comment by javisantana** [comment]
cc @rafatower 

looks like permissions are not properly set.

In the other side any user with editor enabled should have these tables linked

**Comment by rafatower** [comment]
@jgoizueta 

The current code to set the tables and perms: https://github.com/CartoDB/cartodb/blob/049e99f1e12e65c4b49442aa3d7bd7ddda8ea328/app/models/user/db_service.rb#L1195-L1214

The rake used at the time to trigger that operation:
https://github.com/CartoDB/cartodb/blob/049e99f1e12e65c4b49442aa3d7bd7ddda8ea328/lib/tasks/db_maintenance.rake#L1272-L1296

So there are two things to do:
- [ ] fix it for current users with the new builder activated. We can consider using `publicuser` instead of the user's role for that BTW.
- [ ] make sure it is done for users with the builder activated. I'm not sure how to do that or what's the best approach. My guess is that we can just create all the FDW stuff in all databases regardless of having the builder activated or not (a connection will only be established when using the fdw table)

**Comment by jgoizueta** [comment]
Using `publicuser` would be useful to activate all users of an organization (present or future) but isn't any advantage for non-org users.

**Comment by jgoizueta** [comment]
I also think we should have the aggregation FDW configured for all users: it shouldn't have any cost and it saves us from having to configure/remove them when the builder (`editor-3` feature flag) changes for a user.

**Comment by jgoizueta** [comment]
The users that need this at the moment is those having the `editor-3` feature flag, regardless of the `builder_enabled` attribute, right?

**Comment by jgoizueta** [comment]
This task has been manually exectued in all clouds: https://github.com/CartoDB/cartodb/commit/2c57222bbaa14ee096113e7d29a66f25d97282ba
So now all users with access to the new builder should have the aggregation tables configured.

**Comment by fernando-carto** [comment]
Thanks guys. It's working great with me!!
