### ISSUE TITLE
Shared map breaks when disabling/enabling logo option

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#8674]
The shared map view breaks when the owner disable/enable the CARTO logo option. 

#### User 1
- Create a map
- Edit sharing options and give read permission to someone in the organization

#### User 2
- Open shared map

----

#### User 1
- Disable the logo from map options

#### User 2
- Refresh shared map view ---> The map should load correctly, without logo

----

#### User 1
- Enable the logo from map options

#### User 2
- Refresh shared map view ---> The map **does not work** 

----

The console shows this error: 

![screen shot 2016-07-07 at 10 57 27](https://cloud.githubusercontent.com/assets/10940006/16662295/10653b9c-4477-11e6-8ae3-f53380a21849.png)

**Comment by nobuti** [comment]
@ernesmb one question, you are "edit sharing options and give read permission to someone in the organization" using the old editor, right?

**Comment by ernesmb** [comment]
hey @nobuti, sorry I didn't specify it in the issue, but I meant the Builder. 

The first time we noticed it was happening with the Builder, but the map had been created with the Editor.

Later on, we tested and reproduced it again with a map made with the Builder from scratch. It also happened with one of the Smoke Tests maps, made with the Builder.

@oriolbx can give you more info about it :)

**Comment by nobuti** [comment]
Reproduced. After fetching the template definition this is what I've got:
```
{"errors":["Only authenticated users can get template maps"],"errors_with_context":[{"type":"unknown","message":"Only authenticated users can get template maps","http_status":403}]}
```

Does it ring your bell @gfiorav @javitonino?

**Comment by javitonino** [comment]
Taking over @nobuti as this seems awfully related to auth_tokens

**Comment by javitonino** [comment]
Giving it back to @nobuti as it is actually a problem with the logo proper. More detailed steps to reproduce, no need to even share it:
 1. Create map with builder
 2. Disable and enabled the logo (this creates an overlay)
 3. Go to the public view, e.g.: `/viz/188be73c-5ee2-11e6-b3f7-dc4a3eeb0148/public_map`

Error: `TypeError: o.options is null`

I think the overlay is missing an `options` value. Maybe an empty hash instead of `null` fixes it.

**Comment by xavijam** [comment]
Hey @javitonino, but the problem that @ernesmb mentioned was related with the Builder, not with the editor.

**Comment by javitonino** [comment]
The problem is that the overlays created by the builder (with the map options) are not compatible with the old embed/public view and make it crash, because the `options` field is set to nil. It works fine in the builder embed.

Although we are not keeping backwards compatibility, this is a very easy fix (set `options = {}`) and avoids an error in the public view (which we are still linking to), so I think it is worth it.
