### ISSUE TITLE
Lack of information when an anlaysis fail

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8691]
Error on the notifier should explain a bit about the error and red point on analysis and layer list should show the error on hover.

cc/ @urbanphes not sure the design will support real errors :(

**Comment by alonsogarciapablo** [comment]
@saleiva We should be showing the error messages coming from the Maps API. Here is an example:

<img width="406" alt="screen shot 2016-07-08 at 11 56 28" src="https://cloud.githubusercontent.com/assets/390398/16684038/12e912a8-4503-11e6-9cc4-95a2cd6eada7.png">

Can you please share the steps to reproduce so that I can take a look? Thx!

**Comment by saleiva** [comment]
You just need to add an Area of Influence analysis by time walking for example.
This might be related to https://github.com/CartoDB/cartodb/issues/8683

**Comment by javisantana** [comment]
hey, talking about server side errors:

- There are two kind of errors: 1) the ones because a wrong input (10%) and 2) the ones related the application not working properly (90%)

- for 1) we should NOT show the output from maps api. Most of the times the output is not enough for the user to guess what's going on and what they should change.

- for 2) we should say to the user what to do. A reload usually fixes the problem but not sure what is the best thing to say to the user ("contact us"?, "try in a few moments")

- When we design a analysis we should design all the error states (for example, trying to run a moran with 3 points using 5 neighbors should give an error), quotas, timeouts or "too many points for this analysis"

**Comment by alonsogarciapablo** [comment]
Perfect. I was able to reproduce it now.

The Maps API is returning the following payload:

```
{
  "layergroupid": "64cb00f4212d85f780f6e3b2127e2018:1467972346205",
  "metadata": {
    "layers": [
      {
        "type": "mapnik",
        ...
      }
    ],
    "dataviews": {},
    "analyses": [
      {
        "nodes": {
          "a1": {
            "status": "failed",
            "url": {
              "http": "http://ashbu.cartocdn.com/pabloalonso/api/v1/map/64cb00f4212d85f780f6e3b2127e2018:1467972346205/analysis/node/041f06928a3afa0e31f51d572efc396679931b47",
              "https": "https://cartocdn-ashbu.global.ssl.fastly.net/pabloalonso/api/v1/map/64cb00f4212d85f780f6e3b2127e2018:1467972346205/analysis/node/041f06928a3afa0e31f51d572efc396679931b47"
            },
            "query": "select * from analysis_112d4fc091_041f06928a3afa0e31f51d572efc396679931b47"
          },
          "a0": {
            "status": "ready",
            "url": {
              "http": "http://ashbu.cartocdn.com/pabloalonso/api/v1/map/64cb00f4212d85f780f6e3b2127e2018:1467972346205/analysis/node/a9427cf59829364ef5acb263a8fb6506f5bd0e04",
              "https": "https://cartocdn-ashbu.global.ssl.fastly.net/pabloalonso/api/v1/map/64cb00f4212d85f780f6e3b2127e2018:1467972346205/analysis/node/a9427cf59829364ef5acb263a8fb6506f5bd0e04"
            },
            "query": "SELECT * FROM twitter_t3chfest_reduced"
          }
        }
      }
    ]
  },
  "cdn_url": {
    "http": "ashbu.cartocdn.com",
    "https": "cartocdn-ashbu.global.ssl.fastly.net"
  },
  "last_updated": "2016-07-08T10:05:46.205Z"
}
```

Notice that we don't have info about the error. I'm not sure why the Maps API is returning the "success" response as if the map was created successfully instead of the "error" response with all the info about what went wrong 👈  @rochoa can give us some light here!

**Comment by rochoa** [comment]
This is another of the big discussions: having a failed analysis doesn't necessarily mean the whole map should fail, or maybe yes, I don't know. Probably we want to tell the user what the error is, but if we fail the entire request that means we won't be able to render anything.

The response is missing the error message. That problem will be addressed at https://github.com/CartoDB/Windshaft-cartodb/issues/551.

**Comment by urbanphes** [comment]
@saleiva we have this
<br>
![01 layers - 06-02 analysis - case 1](https://cloud.githubusercontent.com/assets/14546701/16757316/62c57072-480b-11e6-9374-32d8cb7c1fa1.png)
<br>

... and on the notification center we can support more than 2 lines.
(an example)<br>
![image](https://cloud.githubusercontent.com/assets/14546701/16757471/92651070-480c-11e6-918d-e7162814d513.png)

**Comment by saleiva** [comment]
But thats before applying, right?

**Comment by urbanphes** [comment]
Not, it's after applying

**Comment by saleiva** [comment]
Not sure we should use the same language after than before. Think that some
analysis vould last minutes.

**Comment by urbanphes** [comment]
but ... can we have an error before applying an analysis?

**Comment by javisantana** [comment]
what about notices, sometimes an analysis can half fail (for example, geocode half of the columns). Should we have that?

**Comment by saleiva** [comment]
I'd say, "refresh the page and try again. If the error persist, please contact us"
