### ISSUE TITLE
Layer stats are sometimes missing

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#8714]

**Comment by javisantana** [comment]
the problem is layers are not always tables and we can't get the stats for a sql query. We need to find a way to workarond that problem from the UI point of view as we can't get stats for all of them.

We shoudl also evaluate the performance implications of doing "vacuum analyze" in order to have table stats.

We could try to do tablesamples over the tables in the sql queries but even that it could return misleading stats

**Comment by saleiva** [comment]
In some cases all columns appear empty even if the dataset was already imported a few days ago.

**Comment by javisantana** [comment]
could you report some of them, it's likely a bug in how we use the postres stats

**Comment by saleiva** [comment]
![screen shot 2016-07-11 at 10 38 33](https://cloud.githubusercontent.com/assets/132149/16724574/aceb3f00-4753-11e6-8fa0-0862ec6abf73.png)

in https://team.carto.com/u/saleiva/builder/4c60c488-4227-11e6-b608-0e3ff518bd15 for example

**Comment by nobuti** [comment]
This request `api/v2/sql?cachebust=1468389823192&api_key=7e3e0f4a49006a19bf5fef4893b444017af01dd5&q=select+*+from+(with+a+as+(select+reltuples+from+pg_class+where+relname+%3D+%27traffic_control_officer%27)%2C+b+as+(select+*+from+pg_stats+where+tablename+%3D+%27traffic_control_officer%27)+select+*+from+a%2Cb)+__wrapped&sort_order=asc&rows_per_page=40&page=0` returns an empty row array, so the stat generation fails. I'll keep digging.

**Comment by piensaenpixel** [comment]
I can't reproduce it.
