### ISSUE TITLE
custom sql does not work on torque layers

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#8753]
1) add a torque layer and apply a sql query
2) reload, torque does not work

the problem is vizjson generation does not include the "source: 'X0'" where the sql is set

**Comment by juanignaciosl** [comment]
Params are being dropped because it's a named map, so it's ok. The problem is that analyses are duplicated. If you check the vizjson it's duplicated, and if you check the named map template you'll see it duplicated as well. The problem is, I think, that it's rendering the first one. Could you confirm this for your case? I've been able to reproduce it consistently, but we might be speaking about different issues.

This is the actual bug: #8690. I'll follow the discussion there in order to consider adding more checks at backend.

**Comment by javisantana** [comment]
one important thing, when I wrote viz.json i meant "editor viz.json", the viz.json that is being using inside the editor

There is no duplication for me

**Comment by juanignaciosl** [comment]
Ok, @javisantana gave me a little more detail. Long story short, the public vizjson doesn't contain the analysis source, only the old sql. Sorry about the confusion, but I couldn't replicate that!
