### ISSUE TITLE
Write on boarding text for "Join columns from 2nd layer" analysis

### ISSUE THREAD

**Issue by javierarce** [CartoDB/cartodb#9023]

**Comment by ohasselblad** [comment]
Listing out the columns seemed a little tedious since presumably the user is aware of the columns they chose. Happy to update if you'd like them to be added. Sample inputs screen-capped at bottom.

```
{Join columns from 2nd layer} has finished.

{New columns have} been included with your original data {based on the columns chosen for the input}.

{This analysis performed a columnar JOIN in order to get columns from two different tables.}

{Read more in [documentation](https://carto.com/academy/courses/sql-postgis/joining-data/)}

```

<img width="326" alt="screen shot 2016-07-22 at 08 23 54" src="https://cloud.githubusercontent.com/assets/1041056/17057051/aba16a30-4fe5-11e6-965d-e528368e10cb.png">
