### ISSUE TITLE
Popups doesn't work on embed

### ISSUE THREAD

**Issue by urbanphes** [CartoDB/cartodb#9111]
I have this map 
https://team.carto.com/u/urbanphes/builder/7fa7221a-500f-11e6-90cf-0ef7f98ade21/embed

with pop-ups in polygons and points

Builder (Polygons):
![image](https://cloud.githubusercontent.com/assets/14546701/17133282/bb41e8e6-5325-11e6-9d82-21a52e9e9f09.png)

Embed (Polygons):
![image](https://cloud.githubusercontent.com/assets/14546701/17133261/ae4ed432-5325-11e6-8f90-2833bf72b9b8.png)

Builder (Points):
![image](https://cloud.githubusercontent.com/assets/14546701/17133300/d0b35d4a-5325-11e6-8a96-4dddbc470e6b.png)

Embed (Points):
![image](https://cloud.githubusercontent.com/assets/14546701/17133336/e2d8717c-5325-11e6-9a29-cd4007e253c3.png)

cc/ @saleiva

**Comment by xavijam** [comment]
Looks like a problem that fields are not exposed in the interactivity.

**Comment by alonsogarciapablo** [comment]
Maps API is returning the following error when trying to retrieve some attributes for a feature:

`"Layer 1 has no exposed attributes"`

I checked the named map template for this map and it looks like:
```
{
  "template": {
    "auth": {
      "method": "open"
    },
    "name": "tpl_7fa7221a_500f_11e6_90cf_0ef7f98ade21",
    "version": "0.0.1",
    "placeholders": {
      "layer0": {
        "type": "number",
        "default": 1
      },
      "layer1": {
        "type": "number",
        "default": 1
      }
    },
    "layergroup": {
      "version": "1.5.0",
      "layers": [
        {
          "type": "http",
          "options": {
            "urlTemplate": "http://{s}.basemaps.cartocdn.com/light_nolabels/{z}/{x}/{y}.png",
            "subdomains": "abcd"
          }
        },
        {
          "type": "http",
          "options": {
            "urlTemplate": "http://{s}.basemaps.cartocdn.com/light_only_labels/{z}/{x}/{y}.png",
            "subdomains": "abcd"
          }
        },
        {
          "type": "cartodb",
          "options": {
            "id": "bdd4721d-a39d-4a7f-8b45-117d170e43fb",
            "cartocss": "#layer {\n  polygon-fill: ramp([count_vals_density], (#ecda9a, #efc47e, #f3ad6a, #f7945d, #f97b57, #f66356, #ee4d5a), quantiles);\n  line-width: 0.5;\n  line-color: #ffffff;\n  line-opacity: 1;\n  polygon-comp-op: src-over;\n}",
            "cartocss_version": "2.1.1",
            "source": {
              "id": "b1"
            },
            "attributes": {
              "id": "cartodb_id",
              "columns": [
                "totalpop"
              ]
            },
            "interactivity": "cartodb_id",
            "sql_wrap": null
          }
        },
        {
          "type": "cartodb",
          "options": {
            "id": "3b707fe1-7443-422e-9693-ab6d6bce3e7e",
            "cartocss": "#layer {\n  marker-width: 4;\n  marker-fill: #515151;\n  marker-fill-opacity: 0.9;\n  marker-allow-overlap: true;\n  marker-line-width: 0;\n  marker-line-color: #d7d7d7;\n  marker-line-opacity: 1;\n}",
            "cartocss_version": "2.1.1",
            "source": {
              "id": "a1"
            },
            "attributes": {
              "id": "cartodb_id",
              "columns": [
                "offense"
              ]
            },
            "interactivity": "cartodb_id",
            "sql_wrap": null
          }
        },
        {
          "type": "http",
          "options": {
            "urlTemplate": "http://{s}.basemaps.cartocdn.com/light_only_labels/{z}/{x}/{y}.png",
            "subdomains": "abcd"
          }
        }
      ],
      "stat_tag": "7fa7221a-500f-11e6-90cf-0ef7f98ade21",
      "dataviews": {
        ...
      },
      "analyses": [
        ...
      ]
    },
    "view": { ... }
  }
}
```

I think the problem is that this template has two "http" layers at the bottom in the template (basemap and labels) and that screws everything up with the indexes. **cdb.js only expects named maps templates to only have one `http` layer at the bottom**, so it's asking for attributes of layer #1, but attributes are exposed in layer #2 (first "cartodb" layer in the template...).

Not sure why/how we could have arrived to this state of things... AFAIK the backend mainly persists whatever the Frontend sends, right @juanignaciosl? So, probably the frontend sent this extra layer (cc: @matallo)?

We probably can handle this in cdb.js, but I also think we should enforce this kind of situations both in the front and backend (eg: a map with a labels layer which is not "on top")...

**Comment by xavijam** [comment]
Yeah, it was an inconsistency state with basemaps, there were two labels layers. I'll be working on that with @matallo. Thanks @alonsogarciapablo.
@urbanphes, your map is working again.

**Comment by juanignaciosl** [comment]
Yes, backend (should not) makes no changes to layer ordering.
