### ISSUE TITLE
Widget stop working when dragging a node outside of the layer

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9127]
STR

1. Create a points layer
2. Add a category widget to a column.
3. Add a sample analysis to the layer.
4. Add a Spatial Cluster analysis to the layer.
5. Add a Centroid analysis categorized by cluster_no.
6. Go to the layer list and drag the top node outside.
7. Click on autostyle on the widget you added at the beginning.
8. **It fails**. It says that the column selected previously doesn't exist. Looks like it is pointing to the wrong node.

If you add the widget back again, pointing to the original node it works.

**Comment by saleiva** [comment]
@xavijam, can we prioritize this to the next sprint?

**Comment by xavijam** [comment]
Ok, let me check mine and I'll include it in the priority list

**Comment by xavijam** [comment]
I've checking the definition that we send to the maps api and it looks correct. In fact, if you unselect the autostyling and move the map, widget is updated correctly and works great (even filtering for any of those items).

![widget-bug](https://cloud.githubusercontent.com/assets/132146/17241481/2adcb2d2-5572-11e6-8697-91f8e4f3cc47.gif)

I can't say 100% sure where the problem is, but I'll take a look with @rochoa or @dgaubert as soon as possible.

**Comment by rochoa** [comment]
Following the STR described by @saleiva the Map instantiation fails because the auto-style is being sent for the clusters layer, and not for the one with the original data, that's the one we linked the widget to.

**Comment by xavijam** [comment]
Working properly thanks to this PR 💃  \o/.
https://github.com/CartoDB/cartodb/pull/10114
