### ISSUE TITLE
Error connecting Google Drive

### ISSUE THREAD

**Issue by urbanphes** [CartoDB/cartodb#9147]
When I try to connect with Google Drive this error appears

![image](https://cloud.githubusercontent.com/assets/14546701/17181901/075a85c4-5422-11e6-9366-9c45c49303a3.png)

cc/ @saleiva

**Comment by iriberri** [comment]
I just saw this issue randomly. The error is due to your Google account being already linked in other CARTO account. You'd need to go into your Google account security settings and revoke the current permissions to the CARTO app, then just try again as the old permissions should no longer be affecting your new connection.

**Comment by xavijam** [comment]
Removing Builder milestone, it doesn't belong to the new Builder. 💋
