### ISSUE TITLE
If you create a map (with several layers), and then hide any of them, map fails

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#9179]
## STR

- Create a map with several layers (try [this](http://withoutbaggage.com/gps/cycling-vietnam-without-baggage.gpx)).
- Once in the map, with 3 layers, try to hide one of them.
- Map fails due to source X0 doesn't exist.

In my opinion, this is another clue that we need to create and store the source analysis from the beginning in the backend when a new map is created, with that we would avoid all the hacks we are doing in the frontend side and more bugs that will appear.

PS: styling also fails at the first time you try.

@CartoDB/backend @CartoDB/frontend

**Comment by javitonino** [comment]
The best place to do this would be at visualization creation time (api controller for create). However, that one is common for builder and editor, and creating analyses there would show the warning that this map is too new to be opened in the editor. Maybe we can check here if the builder is enabled (both by feature flag and the account settings?).

The only place I can think of to do this in backend, only for the builder, is when opening the builder, checking if there are analyses, and creating them, but I'm not a fan of doing write operations on a show controller.

**Comment by javitonino** [comment]
Just ran into a variant of this issue (trying to style a newly created map with a single layer also fails).

**Comment by matallo** [comment]
newcomer here, but

> I'm not a fan of doing write operations on a show controller.

neither I am

**Comment by juanignaciosl** [comment]
👍  to the first comment, let's don't do it at `show`. It it were done at front it should be also based on that flag too. Doing it at backend on creation time seems more appropriate than in front, as visualization creation is mostly made at back. What do you think?

**Comment by viddo** [comment]
Is the plan to migrate all existing viz too then? Because this would also happen for any old/existing viz (with multiple layers) that are opened in the builder.

**Comment by juanignaciosl** [comment]
@viddo I wouldn't do it, mainly because it implies layer options JSON parsing. Not impossible, but not the kind of things that I'd want to automate.

**Comment by xavijam** [comment]
Agree with @juanignaciosl, only with the new ones.

**Comment by viddo** [comment]
Then we would still need the fallbacks on the frontend side either way.

Nevertheless, reproducing this issue, the frontend is actually doing what it's supposed to do (persisting the analysis for the relevant layer), the error is thrown in cartodb.js on reloading the map, see stack trace:
![screen shot 2016-08-01 at 12 23 44](https://cloud.githubusercontent.com/assets/978461/17291239/101b3c52-57e3-11e6-8623-0427aaa6a416.png)
AFAIK the source nodes should be created ad-hoc/as-needed in that context if they're not existing already, so not sure this is a necessarily a problem to solve in the builder. @alonsogarciapablo what do you think?

**Comment by xavijam** [comment]
Oh, if it is a CartoDB.js problem let's review it @alonsogarciapablo, but in any case I like the prevention with the backend change too.

**Comment by alonsogarciapablo** [comment]
Taking a look!

**Comment by alonsogarciapablo** [comment]
Ok, here's what I found out. Imagine a map that is created from a single dataset. Right after is loaded, here's the state of things:

- On the Builder side:

```
> layerDefinitionsCollection.pluck('source')
[undefined, "a0", undefined]
> analysisDefinitionsCollection.pluck('node_id')
[]
> analysisDefinitionNodesCollection.pluck('id')
["a0"]
```
- On the cdb.js side:

```
> vis._layersCollection.pluck('source')
[undefined, undefined, undefined]
> vis._analysisCollection.pluck('id')
[]
```

In summary, The Builder has "created" the "a0" node, which is the source of the layer. cdb.js, on the other hand, still knows nothing about this, and still works with `sql`...

When we try to hide the layer, the `visible` attr of the layer definition model is changed, and that change needs to be "propagated" to cdb.js. This happens [here](https://github.com/CartoDB/cartodb/blob/da9180e638e5129831eff86f82a17c9913c452f2/lib/assets/javascripts/cartodb3/deep-insights-integrations.js#L251-L254). And/but, we're not only updating the `visible` attr, but we're also setting the `source` of the layer to `a0` (see lines 251 and 252)... At this point, cdb.js still knows nothing about `a0` (`vis.analysis.analyse(...)` hasn't been called yet) and so, when it tries to instantiate the map with the hidden layer, it throws an exception saying that "a0" doesn't exist... 

So, basically, this is the error that happens when you change the source of a layer to an inexistent analysis, which I think makes sense from the POV of cdb.js... To fix this, we'd need to make sure `vis.analysis.analyse(...)` before running that `layer.update({visible: false, source: "a0"})`...

**Comment by xavijam** [comment]
Exactly, that's why we'd like to implement the backend solution, adding layer sources from the beginning, avoiding guessing(s) or unstable situations.

**Comment by javitonino** [comment]
We only discussed the solution for new visualizations. Don't we have the same problems from existing ones migrated from the editor?

**Comment by xavijam** [comment]
Yeah, you are right, we will need to do the same "trick" for visualizations migrated from old editor.
