### ISSUE TITLE
"Migrate" estimation_for API endpoint to the new builder

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#9231]
So, we used to use this `estimation_for` endpoint in the geocoding modal in order to know how many credits could use a geocoding by street address (basically it was used as info for the user).

Bad thing is we can't keep using this way because we are not running geocoding against datasets, we can run it against any "analysis" or query, so it is likely we need to re-implement this endpoint.

What do you think @CartoDB/dataservices ?
cc @saleiva

**Comment by rafatower** [comment]
Basically what it does is to count rows and multiply by a factor:

https://github.com/CartoDB/cartodb/blob/d37f67f045a22fa017172d8981a246aed1531062/app/controllers/carto/api/geocodings_controller.rb#L39

I'd say we just don't need that for geocodings but for any other service. Also it would be nice to tell users even for free services ("free because we love you").

Also it seems like the estimation shall be applied on the analysis. @rochoa from analysis side, is it ok to have an estimation on a raw table or shall we use a different approach?

**Comment by xavijam** [comment]
Agree, it should not only be valid for geocoding, title changed.

**Comment by saleiva** [comment]
@rafatower to update this issue ASAP.
