### ISSUE TITLE
Default styling is not being applied under some cirumstances

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9339]
STR

Import the following KML on the datasets view.
Select the two layers with georeferenced data, and create a map with those.
Default styles are the old orange ones instead of the new ones 

[Unofficial Pokémon Go Map  San Francisco Bay Area.kml.zip](https://github.com/CartoDB/cartodb/files/406606/Unofficial.Pokemon.Go.Map.San.Francisco.Bay.Area.kml.zip)

**Comment by xavijam** [comment]
["New" cartography styles](https://github.com/CartoDB/cartodb/blob/master/lib/assets/javascripts/cartodb3/data/default-cartography.json) is something we use only for the style forms, not providing the CartoCSS (because generation is done there). Bad thing is, we don't have that kind of logic in the backend, it only checks wizards_properties in the migration to the builder but not so much. It is likely I'm wrong, so let me summon @javisantana and @juanignaciosl.

**Comment by saleiva** [comment]
this is happening always that you import a dataset. Any tyme you add a point layer, its styled with the old defaults instead of the new ones.

**Comment by xavijam** [comment]
I'm right now with this ticket, PR in some minutes.
