### ISSUE TITLE
Create a "metrics" proxy endpoint

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#9464]
It should be used by the Frontend in order to send any kind of metric. Something like:

` /api/v1/metrics/`
```js
{
  type: 'add-layer',
  params: {
    value: 'table_1',
    user_id: 'xxxx-xxxx-xxxx-xxxx',
    vis_id: 'xxxx-xxxx-xxxx-xxxx'
  }
}
```

It would need changes in frontend in order to send those events, but piece of cake.

cc @juanignaciosl @javitonino

**Comment by juanignaciosl** [comment]
No `value`, please. Always meaningful keys. In this case, `table_name` or `layer_name`, who knows ;-)

Also, probably unrelated with my previous comment, as @gfiorav proposed, let's solve with ids as much as possible, letting backend decide what to send.

**Comment by xavijam** [comment]
Whatever! :)

**Comment by gfiorav** [comment]
Do we have freedom to choose the names we want? If so, I'd probably snake case them to fit the backend classnames and then we'd be able to do a super efficient no-map solution of 

```ruby
event_name.constantize.new(payload).report
```

(@juanignaciosl might be having a heart attack)

**Comment by xavijam** [comment]
Whatever we decide is ok :kiss:

**Comment by juanignaciosl** [comment]
That's not such a bad idea indeed. [constantize](http://apidock.com/rails/String/constantize) is safe (it will fail if `params[:name]` doesn't match anything), so there's no security risk. And I can't foresee any security concern at `new(params[:payload])` either, so that seems quite comfortable. Dynamic instantiation of clases is one of the few actual advantages/shortcuts of ~~crappy~~ dynamic languages, so go for it!

I'm becoming more open-minded, I guess :D

**Comment by gfiorav** [comment]
Closed via https://github.com/CartoDB/cartodb/pull/9521
