### ISSUE TITLE
give warning for .carto downloads if datasets are private

### ISSUE THREAD

**Issue by andy-esch** [CartoDB/cartodb#9482]
Export of .carto files works even if the datasets are set to private, which causes confusion about the contents of the file once it is downloaded. There should be a warning and an on boarding screen about the contents of the file before a user downloads it.

**Comment by ztephm** [comment]
Also if a .carto file is made from private datasets/private map but it is imported to a Free account, those datasets and map become public.

cc @csobier b/c of first Importing Rules bullet [here](https://carto.com/docs/carto-builder/managing-your-map/#exportingimporting-carto-files)

**Comment by saleiva** [comment]
yes @ztephm. The owner of the data can always export it, but we can't/shouldn't control how it gets imported since it is an open format (you can always unzip the file and will get all stuff there)

**Comment by ohasselblad** [comment]
I should have said above... My main reason for filing this ticket is that if a user with only public permissions tries to download a .carto file from another user, but the datasets are set to private, the user _will_ be able to download the file but it will not have the data for the private tables. This is the confusing part to me and deserving of more explanation from the interface.

**Comment by csobier** [comment]
I clarified some of the exporting/importing rules in the docs for now. (Also, see the Slack #Builder channel discussion from today. There are plans to improve this functionality in the future, but not anytime soon.  Let me know if there is anything I can do.)

**Comment by ztephm** [comment]
Hiya @ohasselblad  @csobier - Maybe behavior changed recently but I was able to see and use data from the private-dataset 'With link' Builder map .carto files when I imported it to my Free (Editor) account:

1. I exported the .carto file from within Builder by clicking the vertical ellipses next to map name & then Export map. 
2. I imported that to Free account by dragging/dropping .carto file over Maps page.

I was also able to see/use private dataset when I exported a .carto file from [public map link](https://team.carto.com/u/stephaniemongon/viz/1995f784-6884-11e6-9130-0e233c30368f/public), then drag/dropped that into my Free account

Here's my test:
Builder 'With Link' map using private dataset: https://team.carto.com/u/stephaniemongon/builder/1995f784-6884-11e6-9130-0e233c30368f/embed

.carto file:
[cartozip.zip](https://github.com/CartoDB/cartodb/files/435055/cartozip.zip)

Free account Editor map using previously private datasets:
https://ztephm.carto.com/viz/3a261818-ce77-459c-857b-4558214cf055/public_map

**Comment by csobier** [comment]
Were you the map owner @ztephm? I think the difference is if you are the map owner, or a map viewer.

The privacy settings are only enforced when you are creating the .carto file so if you are the map owner, you can view private data in the Builder, thus that data is exported as part of the .carto file. 
- I suppose you can download the map as a .carto file from your Public Profile page, as a map viewer instead?  (To enforce the privacy of layers, I'm not sure though, I would have to test this)

Note: Once a .carto file is created, the privacy settings no longer apply and anyone with access to that .carto file will be able to see the layers and data contained in the file.

Let me know if I"m wrong on any fronts.

**Comment by ztephm** [comment]
When I downloaded from the public link I was map viewer, & was also logged into my non-team Free account.

I'm able to import that .carto file to Free account, have the datasets show up as public, and do things like make SQL queries/change styles to it.

**Comment by saleiva** [comment]
mentioning @gfiorav here

**Comment by gfiorav** [comment]
Let me sum up how this works from conversations with @csobier and the builder team:

Right now, when you're logged in and click "Export map" from the builder or public map pages, all datasets contained in that map **and that you have access to** are exported. Those datasets can be private, it doesn't matter as long as you can access them (your's or shared with you). Once they're in the .carto file, they're just like any other file out there: privacy doesn't exist out of CARTO.

When you import them, they're no different from any regular .csv file: they'll be imported as private by default if you have private tables enabled or public otherwise. The resulting data is yours and lives in your account. As a consequence, you can edit it to your pleasing. This, of course, is not modifying the original data in the owner's account. Again: this is now your data and lives in your dataset, just the same as importing any other file.

The owner of the data should be aware that all datasets accessible to her/him are exported in the .carto file and she/he is responsible for not distributing them. Any other claim would be the same as expecting to export a private dataset to a .csv file, into a thumb drive, and having it magically not import into any CARTO account expect the original owner's! We can't do that! No-one cans 😁 


So, 2 notes:
1. If the owner exports his own map, all private datasets are exported. A current workaround until we implement the dataset selector is to access the public page of the map in incognito (not logged in) and export it from there.
2. Under **no** circumstance do we ever export any private dataset to a user not entitled to see it. It's important we make this clear.

That being said and out of the way: I do think that some users looking to share their maps via .carto file do expect only public datasets to be exported (our docs can be confusing regarding that). We should show a warning and update the docs. **However, what the user probably wants is for the resulting export to look like our embeds: private datasets are not accessible but layers consuming from them are shown.** This, again, is imposible to achieve. If the dataset is not there, we can't show the layer. .carto is a standalone solution, unlike our cloud where we can privately consume data without giving it away.

**Comment by josecruz** [comment]
Thank you for clarifying it out @gfiorav! This also may help for understanding.

Okay so the workflow will be this:

## Having Private datasets on the Builder
![-56 - export map builder warn](https://cloud.githubusercontent.com/assets/596509/17976211/c9b7ec98-6aec-11e6-837f-f35c3084473e.png)


## Having Private Datasets on public page
![56 - export map - warn](https://cloud.githubusercontent.com/assets/596509/17976225/d8cf563a-6aec-11e6-951b-8b920749ba97.png)

## Having public datasets:
![56 - export map](https://cloud.githubusercontent.com/assets/596509/17998525/371f22c8-6b75-11e6-9345-e52aa4a7aa49.png)

**Comment by ramiroaznar** [comment]
Related to #8014
