### ISSUE TITLE
Fields of type date on JOIN analysis

### ISSUE THREAD

**Issue by jsanz** [CartoDB/cartodb#9501]
### Steps to reproduce
- Create a map with a dataset with fields of type `date` (a twitter import for example)
- Add a new join analysis with any other table

![2016-08-22_14 45 41_selection](https://cloud.githubusercontent.com/assets/188264/17855123/2a641eb8-6877-11e6-9eb7-abb0498bb9e7.png)
### Expected result
- Date fields should appear with the rest of the dataset fields
### Current result
- Date fields are not available

![2016-08-22_14 41 45_selection](https://cloud.githubusercontent.com/assets/188264/17855027/9df04592-6876-11e6-92d1-d9a5a16091da.png)

Attaching a sample exported map: 
[test_join_date_fields map (on 2016-08-22 at 12.42.40).carto.zip](https://github.com/CartoDB/cartodb/files/430120/test_join_date_fields.map.on.2016-08-22.at.12.42.40.carto.zip)

**Comment by saleiva** [comment]
Again this is something that never got implemented, but that was there since the beginning

For the by value dropdown
![screen shot 2016-08-22 at 16 47 02](https://cloud.githubusercontent.com/assets/132149/17858964/0ce11a60-6888-11e6-8833-99e4912e4182.png)

For the other places
![screen shot 2016-08-22 at 16 46 12](https://cloud.githubusercontent.com/assets/132149/17858976/1a64fd64-6888-11e6-9407-9ff6f41fccf0.png)

**Comment by ramiroaznar** [comment]
Hey @xavijam, this is still happening. I do not get what @saleiva closed it.

**Comment by saleiva** [comment]
wait, this looks wrong. That comment has nothing to do with the ticket... :/

**Comment by xavijam** [comment]
Yeah, that comment is for other thing, but it doesn't mind man 💋 .

**Comment by xavijam** [comment]
BTW, "hotfix" deployed, now evaluating why we don't offer any kind of column type within the analysis.

**Comment by javitonino** [comment]
Forgot to close it, but this is deployed.
