### ISSUE TITLE
Provide the number of organization users in the dataset and builder pages

### ISSUE THREAD

**Issue by xavijam** [CartoDB/cartodb#9525]
In order to avoid an unnecessary request to `users` endpoint.
Changes in frontend and backend, I feel. 💋

**Comment by javitonino** [comment]
@nobuti What exactly do we need here? Just a single integer with the number of users the vis has been shared with (including though groups and/or the whole org)?

**Comment by nobuti** [comment]
@javitonino Right now, we are making a call to `api/v1/organization/3c7255dd-1eae-4ec8-b8e8-0698248070c6/users` in order to get the `total_user_entries`. I guess that data will be enough, because even we are holding the entire structure, we are using only that data.

**Comment by javitonino** [comment]
I was experimenting a bit with this and groups. We are also doing a request per group to get the number of users (get the user list and remove duplicates).

What about going an step further and giving you the number of users the visualization is shared with, all aggregated. This way you don't have to request the groups when loading the builder (I think). But this may complicate things too much when changing the permissions, as you may have to request the groups there in order to keep the count current. 

As you know how hard could it be to implement, do you think it might be worth it? Anyway, doing the easy part (what is describe in this ticket) for now.

**Comment by nobuti** [comment]
I think it would be great, at least we can defer the request until the permission changes. But as you said, we can do it in another issue I think.
