### ISSUE TITLE
Shared permissions seem to be lost every time dataset changes

### ISSUE THREAD

**Issue by jmartinter** [CartoDB/cartodb#9527]
I've created a dataset by importing a csv file from dropbox. The dataset is configured to be sync'ed every hour. I'm read-only sharing the dataset with other account (user2) in same org so it can be accessed by something similar to:
```
https://user2.carto.com/api/v2/sql?api_key=xxxxxxxx&q=SELECT%20*%20FROM%20%22user1%22.bug_test
```
Problem is every time the dataset changes (new data is added), then the query returns this error:
```
{"error":["permission denied for relation bug_test"]}
```
Reactivating share permissions removes the error... until next update : (

Let me know when working on it so I can provide you real usernames and api key to reproduce the issue.

**Comment by javitonino** [comment]
cc @iriberri 

We tracked the problem to the sync process around here: https://github.com/CartoDB/cartodb/blob/9555-oauth_pixel_perfect/app/models/synchronization/adapter.rb#L30

`copy_privileges` works and does the right thing, but `cartodbfy` wipes the permissions, exactly in the SQL call `SELECT cartodb.CDB_CartodbfyTable('#{schema_name}'::TEXT,'#{qualified_table_name}'::REGCLASS);`

Maybe we can copy the privileges after cartodbfycation? Or we can check exactly what in the cartodbfy function is wiping the permissions (and why).

**Comment by iriberri** [comment]
Ohhhh. CartoDBfication does create a new physical table in some scenarios were it's better to basically recreate the table to cdbfy'it (if you're interested, you can check [this](https://github.com/CartoDB/cartodb-postgresql/blob/9ee3125913c85f5cb0d13617e079c937e729068f/scripts-available/CDB_CartodbfyTable.sql#L375-L378)). That's the problem.

It looks like just moving the `copy_privileges` line as you say will work (as far as we use the correct schemas in the params, because now both tables will live in the user schema and the new one will no longer be in `cdb_importer`).

If you want, I can take care of it, or you can go ahead with moving the lines if you want. 

The good thing is that it's already broken so we can't break it more whatever we do :sweat_smile:
