### ISSUE TITLE
When dragging a node to create a new layer, you need to change any style parameter in order to make the layer visibile

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9543]
I think this has been introduced with the last fix

**Comment by xavijam** [comment]
I haven't been able to reproduce it, but It is likely I'm doing simple, my steps:

### STR
- Create a map with a layer of points.
- Add a AOI analysis on top of that layer.
- Drag out that AOI analysis in order to create a new layer below the previous one.
- Both layers are rendered correctly.

Yours?

**Comment by xavijam** [comment]
No news, good news. Let me close it, and if it appears again, let's reopen or create a new one :kiss:
