### ISSUE TITLE
Torque layers do not work with basemaps with labels on top

### ISSUE THREAD

**Issue by javitonino** [CartoDB/cartodb#9548]
1. Create a map with an animated torque layer
2. Select a basemap with labels on top (positron, dark matter, toner...)
3. Load map in embed. Only first frame of the animation is displayed. Timeline doesn't work.
4. Change to a basemap with labels below
5. Refresh embed, it works fine.

cc @xavijam

**Comment by xavijam** [comment]
Looks like a problem with the index of the layers.

**Comment by xavijam** [comment]
cc @rochoa

**Comment by alonsogarciapablo** [comment]
Looked a bit into this. I was able to reproduce it and it's only failing when the dataset is private.

It looks like Torque is still doing an internal request to the Maps API, which fails when the dataset is private:

![screen shot 2016-09-23 at 17 15 51](https://cloud.githubusercontent.com/assets/390398/18791033/6f2cf792-81b1-11e6-8fb8-af4fc6e1452a.png)

First request is triggered by CartoDB.js and it's creating an instance of the named map:

`https://pabloalonso.carto.com/api/v1/map/named/tpl_4abb318c_819b_11e6_984c_0ecd1babdde5/jsonp?config=...`

Second request, on the other hand, is hitting the endpoint to create/instantiate anonymous maps:

`https://pabloalonso.carto.com/api/v1/map?config=...`

**Comment by alonsogarciapablo** [comment]
The problem is that we're not initialising the `named_map` attribute of the torque layer model correctly [here](https://github.com/CartoDB/cartodb.js/blob/v4/src/geo/torque-layer-view-base.js#L32). That is then used [here](https://github.com/CartoDB/torque/blob/31a81e760b249e76b159c9966c219ae570f9acb3/lib/torque/provider/windshaft.js#L419-L441) to determine if the map should be instantiated via anonymous or named maps...

**Comment by alonsogarciapablo** [comment]
Other properties like `auth_token` and `api_key` might also be `undefined`.

**Comment by alonsogarciapablo** [comment]
cc: @rochoa
