### ISSUE TITLE
error editing cells in dataset with polygon geometries

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/cartodb#9592]
When a cell of a dataset is edited by doing double click (or choosing the "Edit this cell" option), CARTO returns a http 400 bad request error and a message indicating that it can't edit the cell because the geometry of the row is invalid.

![screen shot 2016-08-29 at 12 41 21](https://cloud.githubusercontent.com/assets/11177693/18049480/d558471a-6de8-11e6-866d-abab3b0fe7c9.png)

I've tried to edit the cells of the world borders dataset and barris de barcelona dataset (both from the data library). I can create maps form both datasets and the geometries are correctly rendered.

![screen shot 2016-08-29 at 12 42 30](https://cloud.githubusercontent.com/assets/11177693/18049503/f6e24ba6-6de8-11e6-810f-109a4ad803a4.png)

This doesn't happen with datasets that have point geometries.

**Comment by gfiorav** [comment]
Ok, the issue only happens in the builder. `the_geom` on the row update is being sent as "MULTIPOLYGON" literal string, rather than the actual geom definition. I'm giving this all the priority.

Since it's most probably an issue with the dateset front code, I'm looking for a front engineer who can take care of it.

**Comment by gfiorav** [comment]
@nobuti could you take a look and confirm this is the case?

**Comment by nobuti** [comment]
@gfiorav @oriolbx on it

**Comment by gfiorav** [comment]
We found there is a call missing in the new code for the builder and the full geometries are not fetched. It works for points since these are fetched during instantiation ie `.... CASE WHEN GeometryType(the_geom) = 'POINT' THEN ST_AsGeoJSON(the_geom,8) WHEN (the_geom IS NULL) THEN NULL ELSE GeometryType(the_geom) ...`

Buti is on it!
