### ISSUE TITLE
Logging in Syncs is generating escaped & single-line huge logs in some specific scenarios

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#9615]
**STR**:

* Create a sync
* Let it sync one without data updates (probably not needed)
* Let it sync now with data updates successfully
* Break the file (add some nasty HTML+JS instead of your CSV)-> UnsupportedFileError
* Fix the file and let it sync
* Break the file -> UnsupportedError

Due to the fact that the exceptions raised in loader.rb are using the whole log as exception message, the log keeps growing and growing. Also, some incorrect line feed characters are provoking the backslashes to be escaped and the log to be a single line, which ends up blocking the sync as the log ends up being impossible to edit due to its size.

**Comment by iriberri** [comment]
To start with, we found a probably unrelated bug here: https://github.com/CartoDB/cartodb/blob/62bfd6b1149ed861848d65c065d6754ef93e75fb/services/importer/lib/importer/job.rb#L37

Append method parameters are disordered. Check: https://github.com/CartoDB/cartodb/commit/d42e9079298fed18caeca6861d06572676b2c2ce#diff-048d440a8838cbe46765a9504863c889

**Comment by jgoizueta** [comment]
We have several places in which we're using `'\n'` instead of `"\n"`. The first is a slash followed by an "n", not an end-of-line.

* https://github.com/CartoDB/cartodb/blob/f8c33235c974a49bc70b8cc0a393d79edcf25379/app/models/log.rb
* https://github.com/CartoDB/cartodb/blob/f8c33235c974a49bc70b8cc0a393d79edcf25379/app/models/synchronization/member.rb#L204
* https://github.com/CartoDB/cartodb/blob/f8c33235c974a49bc70b8cc0a393d79edcf25379/services/geocoder/lib/hires_geocoder.rb#L107
* https://github.com/CartoDB/cartodb/blob/f8c33235c974a49bc70b8cc0a393d79edcf25379/services/geocoder/lib/hires_geocoder.rb#L134

**Comment by jgoizueta** [comment]
This is also unrelated to the error, but this is causing out of order lines in long logs:

https://github.com/CartoDB/cartodb/blob/master/app/models/log.rb#L163

We should replace that line by:

```
(@fixed_entries_half + @circular_entries_half[@circular_index..-1] + @circular_entries_half[0...@circular_index]).join('')
```

To keep the correct order of the lines in the circular buffer.

**Comment by jgoizueta** [comment]
Finally I've found what created the log explosion with multiply-escaped backslahses.

The log recursion due to the Exceptions with job.logger mentioned above is not good, but is not the cause of he backslash proliferation. 

We have another log-recursion [here](https://github.com/CartoDB/cartodb/blob/1b6dac2daf2810d43904653d6558a1d3ef52de34/app/models/synchronization/adapter.rb#L26) where `Synchronization::Adapter#run` generates exceptions which include the `Results` array in its message.

Arrays such as the results array are converted to text (`to_s`)  using  `inspect` for each of their elements. Now `Result#inspect` calls `inspect` on all the instance variables, and  `Result` includes a copy of the full log in its `@log_trace` instance variable.

So each time a synchronization error occurs, the previous log is resinserted in a single line via `String#inspect` (showing the contents of `@log_trace` for a `Result`) and the escaping done by inspect accumulates.

Since each *inspected* copy of the log goes into a single line, the `Log` mechanism which limits the maximum number of log lines (using a circular buffer) has no effect here to limit exponential grow in size of the log.

We can avoid the problem by defining a `Result#inspect` method that doesn't show `@log_trace`.
