### ISSUE TITLE
Don't create the the_geom column until georeferencing the data.

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9659]
We should analyze the impact of this, but is has come in a conversation with a potential client

**Comment by rafatower** [comment]
This is done as part of the cartodbfy process at the very beginning, it's been our standard since almost forever. Changing it has a great impact: import process, cartodb postgresql extension, builder and analysis/tiler.

What's the client pursuing with that change? do they find it bothering? is it a performance concern? maybe it is just enough not showing it in the editor if it just contains NULL's.
