### ISSUE TITLE
drop ghost tables code and move to a callback based architecture

### ISSUE THREAD

**Issue by javisantana** [CartoDB/cartodb#9669]
Let's remove the guessing code from rails and move to a callback based architecture from cartodb-postgres extension

**Comment by javisantana** [comment]
cc @gfiorav @juanignaciosl

**Comment by juanignaciosl** [comment]
@javisantana there is (at least) one use case that is harder to handle from the extension: deletion + recreation. There are some users that have scripted the deletion of table and, just afterwards, its recreation. Current ghost tables behaviour doesn't delete the visualizations, but a callback based one might do.

**Comment by javisantana** [comment]
I understand that but that behavior could fail with current ghost tables as well, right?

My point is, the behavior should be consistent, if someones removes a table it must remove everything using it. If someone just wants to replace table contents, they should replace them (not drop and recreate the table)

**Comment by gfiorav** [comment]
@javisantana Current code for ghost tables detected drop + create.

Like I said: we can't blame the ghost table manager for flow errors. It would be like blaming CARTO for a Rails issue. This solution has proven stable for sometime as well. 

For the record, what happened today is:

1. Rename was cut in half (in between deploys) and vis was broken.
2. Ghost table manager realised the discrepancy and tried renaming the table visualization to match the physical table name.
3. Since vis was broken, rename failed.
4. Ghost table manager removed it as it couldn't be fixed, and the relinked it again.

**Comment by gfiorav** [comment]
@javisantana @juanignaciosl 

Maybe the real deal here is to actually rethink how we store metadata. Imagine a dataset dashboard that would just show whatever is in your db. Then metadata can be stored elsewhere and discarded if physical table disappears.

The current modeling of a dataset is kind of artificial, and that requires a "Ghost table manager" to make sure everything is synced.

**Comment by javisantana** [comment]
@gfiorav we tried to to that in the past and it's what i'm proposing here: have a real sync between database and metadata.

Nothing is being blamed, ghost tables is working but it has some issues due it's an async process.

**Comment by gfiorav** [comment]
> we tried to to that in the past and it's what i'm proposing here: have a real sync between database and metadata.

Ah! Didn't understand this was what you propose, I though it was using callbacks (not sold it would solve anything since a callback can fail and is asynchronous (race conditions).

> ghost tables is working but it has some issues due it's an async process.

Yes but it's concurrent! I uses mutex like structures so it's serial per user (we made the `Carto::Bolt` using the redlock algorithm, redis and atomic operations https://github.com/CartoDB/cartodb/blob/master/lib/carto/bolt.rb).

> Nothing is being blamed 

Of course 😄  I'm just pointing out it might not be such a bad solution after all. It's concurrent and has proven stable.

**Comment by gfiorav** [comment]
Hey, @juanignaciosl and I have been speaking about this and some conclusions were driven:

+ Callback require hacking the SQL API which might not be ideal.
+ We can move metadata to vis and remove the concept of User Table, but it's vertical to the builder and will take a lot of time.
+ The current implementation is "good enough", but we tend to hate it because it exposes other issues (rename fails -> a map is lost vs a map is unusable).

IMHO:

Our implementation is "Good enough" really and the other alternatives, albeit more beautiful, require a lot of time and deep transformation: for callbacks, the bigger change is in the SQL API. For dropping user table concept, the it's the Builder.

Non of this should stop us at a philosophical level (let's do the best we can and never settle for middle solutions) but deciding we should spend 3 weeks (worst case I guess) on either of these is more of an administration decision than a technical one.

Let us know @javisantana 😄

**Comment by javisantana** [comment]
Let me clarify things here:

- when I say callbacks I mean database http hooks as we do when user groups. If we need to spend time on that, let's spend it, don't be affraid :)
- the way ghost tables work is limiting for us, we should be able to control which tables are registered and be kind of transactional if we need it. For example, should a conector table be shown in the UI? maybe no, we should be able to control those things but the current implementation does not allow that

**Comment by gfiorav** [comment]
> when I say callbacks I mean database http hooks as we do when user groups

Looking into that :)

> the way ghost tables work is limiting for us, we should be able to control which tables are registered and be kind of transactional if we need it

What do you mean with transactional? It's concurrent right now: 1 process per user at a time (redlock algorithm)

**Comment by javisantana** [comment]
> What do you mean with transactional? It's concurrent right now: 1 process per user at a time (redlock algorithm)

If I do a "select cdb_cartodbfytable(...)" and the table can't be registered in metadata database it should fail
