### ISSUE TITLE
CartoDB login loads 10 sec later

### ISSUE THREAD

**Issue by icetorm** [CartoDB/cartodb#9696]
Hi everyone, 
I installed CARTO in ubuntu 12.04 and it works smoothly with some tweaks that i made. However when i load  http://localhost:3000/login the background load instantly but the login takes 10 seconds to load everytime.

Thanks. Your help will be really appreciated.

**Comment by iriberri** [comment]
This is happening because of the Google Plus login option. In order to avoid it, you might want to comment or remove the  `google_plus` line inside `oauth` in your `app_config.yml` file. Explicitly, these ones [here](https://github.com/CartoDB/cartodb/blob/47e653514133c241a5e630a85484fe21a697e773/config/app_config.yml.sample#L299-L302):

```yml
    #google_plus:
      #client_id: ''
      #cookie_policy: 'single_host_origin'
      #cookie_policy: 'https://cartodb-staging.com'
```

**Comment by icetorm** [comment]
Thanks @iriberri , my problem is solved.

**Comment by iriberri** [comment]
That's great @icetorm! By the way, I'm going to comment those lines in the sample app config probably, as it won't work unless configured anyway.
