### ISSUE TITLE
List of Feature flags

### ISSUE THREAD

**Issue by hhryw** [CartoDB/cartodb#9744]
Hi, 

How I can get a list of all Feature_Flag names like for example "builder_Enabled" or "disabled_cartodb_logo"?

bundle exec rake cartodb:features:enable_feature_for_all_users[**<feature_flag_name>**]

Any idea??? Thanks

**Comment by iriberri** [comment]
Hi @hhryw, these are the feature flags currently used throughout the CARTO project:

````
'editor-3'
'visualizations_backup'
'ghost_tables'
'new_geocoder_quota'
'profiler'
'carto-connectors'
'explore_site'
'instagram_import'
'templated_workflows'
'mailchimp_import'
'create_overviews'
'disabled_cartodb_logo'
'intercom'
```

In order to use them in your local installation, you can follow the Feature Flags guide at our docs, which I guess you know already: http://cartodb.readthedocs.io/en/latest/operations/change_feature_flags.html

Hope this helps!

**Comment by hhryw** [comment]
Hi @iriberri ,

That is what I needed.

Thank very much again!!!! :)

**Comment by jjmata** [comment]
Wonderful, @iriberri!  Is there a way to generate that listing without having to bug you fine Carto people?  I've tried my luck at grepping and Github searching, to no avail ...

**Comment by jjmata** [comment]
I mean, a fresh schema post migrations running would lead you to believe that this is what you're dealing with:  😮 

  * `new_public_dashboard`
  * `new_dashboard`
  * `new_public_dashboard_global`
