### ISSUE TITLE
Import API: Option to overwrite existing table/do not append _1, _2, etc.

### ISSUE THREAD

**Issue by talos** [CartoDB/cartodb#9776]
Currently the [Import API](https://carto.com/docs/carto-engine/import-api/standard-tables/) does not provide any switch for the automatic renaming.  In certain cases, it actually is desirable to overwrite an existing table.  I think it should be an option, whether officially supported or use-at-your-own-risk.

Additionally, because there is no clear programmatic way to clear out the "ghost" tables that can make it impossible to name something the same as a deleted table, implementing this could avoid some support overhead.

**Comment by iriberri** [comment]
(Just sharing some thoughts here 😄)

Right now the "overwrite" mode could be accomplished with a Sync table, but I understand it has some limitations (it needs to be online, and if you're using GDrive or Dropbox, it needs to be the same file that you initially uploaded, as any other file with the same name would have a different identifier for those services).

We have an issue opened for a while about blocking/pausing Sync Tables when the schema of a table changes, specially if columns are lost / types have changed, because that could break the maps of the user. My first thought about the feature you propose is that, as you say, it has a lot of "use-at-your-own-risk" :)

I'm also aware that there are plans to improve the Ghost Tables scenario. Right now, these are triggered whenever you access to your dashboard. If you're a user of the Engine then the scenario you mention occurs: you won't get a table with the same name even if you drop your old table because we still have the metadata for your old table.

I'm curious about the specific use case you have. Could you elaborate further? Would Sync Tables be of any use in your case?

The related issues I mentioned:
* Ghost tables: https://github.com/CartoDB/cartodb/issues/9669
* "Pause" syncs: https://github.com/CartoDB/cartodb/issues/5131

**Comment by talos** [comment]
Happy to elaborate further!

My use case is programmatic access of the Import API to the observatory.carto.com account to allow for testing of Observatory data in CARTO.  This frequently involves replacing a table that's already there, most often for the metadata tables (`obs_column`, `obs_table`, `obs_tag`, etc.)

Since there is no officially supported drop table feature, I mimic the `DELETE` request made in the browser to eliminate the visualization, then drop the table.

Code for the import is here: https://github.com/CartoDB/bigmetadata/blob/master/tasks/util.py#L744
Code for removing the existing table & its associated visualization is here: https://github.com/CartoDB/bigmetadata/blob/master/tasks/util.py#L292

What ends up happening about 50% of the time is that at least one of those tables, even though its visualization is dropped and its table eliminated, is still uploaded as `_1`, `_2`, etc.  The only semi-reliable way I've found to get around this is to actually reload the `/dashboard/datasets` page by opening up a browser and reloading it.  I was informed by someone (I forget who) that this would trigger an update of the metadata for the user, essentially removing the table that for some reason was still hanging out and screwing up the naming (which I may have erroneously called a "ghost table").

Please let me know if you need any more info!

**Comment by iriberri** [comment]
We talked a bit about this later, no big conclusions though :)

Are you editing the schema of obs_column/table/tag? If you're just editing the contents I think it would be useful for you to set up a Sync Table. You can for example set the Sync interval to 1 month and then, when you update the data, just force the "sync now" (you can do this programatically! The big interval is so that sync doesn't run when you don't really want and you want to sync it but the automatic sync happened less than 15min ago).

Besides dropping the visualization itself by mimic'ing the builder, take into account that Tables are also registered even though you drop them, so this would not work until the table is unregistered too.

I definitely see your point with this info, thanks for sharing!

**Comment by talos** [comment]
The schema of obs_column/table/tag changes rarely enough that I can do some special work when it does.

To use sync tables and take advantage of "Sync Now", I would just need to host the CSV at some publicly accessible address? That's definitely an option.

**Comment by iriberri** [comment]
Yep!

Or even your own dropbox/gdrive account I guess. You could set the Sync by using the Builder (because you'd need to authenticate the first time) and I'd say you should be able to trigger the synchronizations programatically as for any other sync.
