### ISSUE TITLE
Dataset sharing errors

### ISSUE THREAD

**Issue by erodespons** [CartoDB/cartodb#9779]
Description:

Christophe shared a dataset with me.

I got the email from CARTO with the notification.
![screenshot 2016-09-15 18 49 57](https://cloud.githubusercontent.com/assets/7283363/18558969/6b1547c8-7b75-11e6-8c1d-069f0a5bf2f3.png)

When I open the link the dataset doesn't load:

![screenshot 2016-09-15 18 49 22](https://cloud.githubusercontent.com/assets/7283363/18559030/ba0c1578-7b75-11e6-9a1e-97792c080f86.png)

When I try to download it doesn't work (I have read only access):

![screenshot 2016-09-15 18 49 31](https://cloud.githubusercontent.com/assets/7283363/18559043/cbeed05a-7b75-11e6-925d-ce9b6c267c18.png)

It is surprising that you can see the query to the database but nice for those who understand SQL.

**Comment by ramiroaznar** [comment]
### STR

* Share a private dataset with someone from your organization.
* Open the dataset from the link of the notification email or from the Builder.
* As shown in the screenshot above the table does not show up.  The query keeps running.
* This is caused because **the Builder (in the Editor works fine) is not getting the schema**. The query should be like this `ccaron.macdorestaurantssansbla_1` instead of `macdorestaurantssansbla_1`. A temporal workaround would be applying the following query on the SQL console:

```SQL
SELECT * FROM ccaron.macdorestaurantssansbla_1
```

And duplicate a dataset from query.

cc @ernesmb

**Comment by xavijam** [comment]
Shared dataset problems hitting us again, @nobuti @javitonino @gfiorav.

**Comment by javitonino** [comment]
I feel this is more frontend job. The issue is opening any dataset from another user. The backend here just presents the dataset as is. This is with the default query, so I think it is a problem with the frontend not adding the username to the generated default query (the backend is not passing any query I can see).

**Comment by ernesmb** [comment]
cc/ @CartoDB/support for awareness

**Comment by xavijam** [comment]
So, my opinion is, when a dataset is shared, we should change change the sql adding the username before the table name.

**Comment by javitonino** [comment]
Two cases here:
 - The dataset already has a custom query, rewriting it might be the better (only?) solution. However I'm not too fond of rewriting it on a privacy change, as the process is not perfect and may break the query. Still, I haven't got any better ideas, so we may have to do this.
 - In the case where there is no query (only `table_name`), we can do something better as we are writing the query ourselves (in the frontend), so we could try avoiding to rewrite queries, as it is far from perfect.

Having to treat the two cases separately may be a mess, so maybe forcing the `query` to be set when sharing isn't a bad idea to avoid having to add the query generation from table_name in yet another place.

Maybe we can go one step further, and start to always write the query on creation, so it is always set. And we could write it with the username for users in organizations, so it is always there (avoid rewrites for new datasets).

Not sure about any of that, but we are starting to add query rewriting where we need it on a case-by-case basis and it feels hacky to me.

**Comment by gfiorav** [comment]
> The dataset already has a custom query, rewriting it might be the better (only?) solution. However I'm not too fond of rewriting it on a privacy change, as the process is not perfect and may break the query. Still, I haven't got any better ideas, so we may have to do this.

Yes, it doesn't look like there's that much of an alternative TBH.

> Not sure about any of that, but we are starting to add query rewriting where we need it on a case-by-case basis and it feels hacky to me.

It is hacky: for me the problem is that we have no strong link between a layer/dataset and a table. I think we have to cope with this. There is a limited number of actions that result in the rewrite of a query, so if we "master" them then we have the problem under control. It's bug prone, but scoped at least.
