### ISSUE TITLE
Add option to control overwriting in LDS analysis

### ISSUE THREAD

**Issue by ernesmb** [CartoDB/cartodb#9818]
When adding a Georeference analysis, there is no way we can control whether rows that already have a geometry will be overwritten or not. 

![screen shot 2016-09-20 at 12 43 39](https://cloud.githubusercontent.com/assets/10940006/18667209/e64d6f84-7f2f-11e6-92ed-2d8420457676.png)

I would be very useful to have a clear way to control it, similar to the 'Override all values...' checkbox functionality we used to have in the Editor. 

![screen shot 2016-09-20 at 12 46 15](https://cloud.githubusercontent.com/assets/10940006/18667295/43f563ee-7f30-11e6-9069-fbab9b1214cb.png)

**UPDATE**
The same will happen when a new row is added to a table that has an AOI's analysis applied:
The analysis will run again over the whole table, potentially causing a lot of credit's spending, instead of reusing the rows that already exist

**Comment by xavijam** [comment]
I feel it would be pretty useful, what do you think @dgaubert and @javierarce?

**Comment by javierarce** [comment]
I'd say let's do it :)

**Comment by saleiva** [comment]
Please :) Think that if not, the workaround is a pain...

**Comment by saleiva** [comment]
Hi Guys, remember this was designed at the UI level when attacking this

**Comment by dgaubert** [comment]
> UPDATE
The same will happen when a new row is added to a table that has an AOI's analysis applied:
The analysis will run again over the whole table, potentially causing a lot of credit's spending, instead of reusing the rows that already exist

Hey @rochoa I think we can use [Conditional Expressions](https://www.postgresql.org/docs/9.5/static/functions-conditional.html) to determine whether a row has been geocoded already to avoid spending credits.
