### ISSUE TITLE
Could we get a Widget that allows a user to enter html so we can embed img's as legends temporarily

### ISSUE THREAD

**Issue by nygeog** [CartoDB/cartodb#9823]
![screen shot 2016-09-20 at 11 12 57 am](https://cloud.githubusercontent.com/assets/2790599/18676317/35f625c4-7f23-11e6-9c60-c73d1ff4c911.png)
A lot of Proof of Concept maps we are doing and want to showcase need some legend, even if its just a static image like a (.png, .jpg) that can be in `<img>` tags. It would be very useful. Could a widget be made (if its easy/quick) that is essentially a container for html?

**Comment by andrewbt** [comment]
What this request really is is a "Custom HTML/CSS widget" I believe I had heard talk of this moons ago, but can't find a related issue. It makes plenty of sense for all kinds of uses more than just a "temporary legends fix" 

CC @xavijam

**Comment by andrewbt** [comment]
This brings me back to deep-insights.js days. We had tons of hacks for custom widgets just like https://cartodb.github.io/labs-trade-areas-subway/

@nygeog ^^ at least you can do something with JS like that slider bar if you need?

**Comment by xavijam** [comment]
Hey mates, people around are working super hard to have legends as soon as possible. IMHO it is not a good idea to spend time in a temporal hacky solution when we are working on the real solution (right now) ->
https://github.com/CartoDB/cartodb/pull/9809
https://github.com/CartoDB/cartodb.js/pull/1401
…

Please, be patient just a few days more 💋  ❤️ .

**Comment by andrewbt** [comment]
Again, though, @xavijam , @CartoDB/solutions has had NUMEROUS cases where we have needed to develop a custom widget. https://cartodb.github.io/labs-trade-areas-subway/ is but one example that we feature _prominently_ on our website.

This ticket is poorly worded in what it is asking for. The value is not in the temporal solution, but the **great feature** of being able to code custom widgets easily when needed. If it's not in the roadmap already (I think it might be but I can't find a github issue) it should be. I'll file a CartoInsight too.

**Comment by jsanz** [comment]
Well a custom widget with logic tied to layer model would be really hard to place on the builder, it's a rabbit hole (lot of UI, security concerns and so on) and when we have CARTO.js 4 released it wouldn't be needed that much.

A simpler "you can put here any HTML piece" with the proper JS sanitization is not a bad idea. Still this should also be less important when we have overlays back to our map so I'm also not that sure of this feature, but still a good one to explore because I'm sure I'm missing many points :smile:

**Comment by xavijam** [comment]
Hey guys, if you consider we need a custom widget, that is totally possible in deep-insights, I encourage you to check the code there a create a new one, please.
Also, allow to add custom HTML (anywhere) is not a good idea, we have checked that after some years allowing it in the editor, and now suffering the problems we have (for example) for the migration to the new Builder due to those "custom" (htmlfied) components.
