### ISSUE TITLE
About the behaviour of "Clear view" when you apply a query that gives an error

### ISSUE THREAD

**Issue by iriberri** [CartoDB/cartodb#9869]
I have noticed a behaviour that could be confusing about how we show the "clear view" button:
#### Scenario 1: A query fails after another query has been applied
1. Go to a dataset. It has the typical `SELECT *...` query applied
   - There's no clear view button because it's using the default query, so there's no query applied
     - It will appear if the query is not 100% that specific `SELECT * FROM table`. For example, if you add a space/line feed at the end. I don't think this is important though. This is detected as a query applied, so you would not have access to edit the data either.
2. Apply a valid query, such as `SELECT * FROM table LIMIT 10`
   - The "clear view" button appears
3. Apply a query that returns an error. Silly example: `SELECT '{"type":"Point","coordinates":[0.15,40.1]}'::geometry`
   - As the "clear view" button was already there, it remains. You can comfortably click on "clear view" to  get back to your normal table. 
#### Scenario 2: A query fails without a query being applied previously
1. Go to a dataset with no query applied.
2. Apply a query that returns an error. Silly example: `SELECT '{"type":"Point","coordinates":[0.15,40.1]}'::geometry`
   - As the "clear view" button was not there because of the lack of a query applied beforehand, you can't clear your error with a button. To get back to your table, you must write the `SELECT * FROM table` query by yourself. If you're a not advanced user which doesn't know SQL, you might probably have some trouble here. The rows in the data view are removed:
   
   ![image](https://cloud.githubusercontent.com/assets/1730320/18793034/47f7c47e-81b9-11e6-897b-c4c9bc4c960d.png)
   
   Also, I'm seeing that with the SQL pane open you can't really see the SQL error message below.

At first sight I'd say that this perhaps is difficult to manage because in Scenario 2 there's clearly not a query applied, but we still hide the rows and show the "error" message so I assume we might be able to control it. I recognize it's a picky thing, but I thought it was worth sharing. :-)

**Comment by javitonino** [comment]
Some notes as I have been recently working on this. Since this ticket was reported I have done some work (see #10510) to refactor a bit the default query generation, so the behaviour may not be the same one.

Also, the code to compare whether two queries are the same is used for two purposes: display a `[SQL]` tag near the dataset name, and show/hide the clear SQL button. The code is not exactly the same in some places, so we must be careful to keep it in sync. It would be good to extract the code to a common location (SQLUtils seems like a good place).

Moreover, there is a small issue with the current code, in that it ignores quotes (`"`) which are used to escape table/user names with hyphens in the name (and other special characters). So `SELECT * FROM table-15` is taken to be the same as `SELECT * FROM "table-15", and the clear SQL option is not offered. However, the first query doesn't work, but the second one does. Maybe this is a chance to review that behaviour as well.
