### ISSUE TITLE
Analysis deletion it too destructive

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9932]
If you delete an analysis node that doesnt change the data structure, we should delete all related layers.

**Comment by inigomedina** [comment]
I'm closing this issue because it has been inactive for a long time. This probably means that it is not reproducible or it has been fixed in a newer version. If it's an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this.

Please reopen if you still encounter this issue.

Thank you!
