### ISSUE TITLE
Widgets not working on maps today that worked yesterday

### ISSUE THREAD

**Issue by makella** [CartoDB/cartodb#9949]
hello both @ramiroaznar and I have maps with widgets that stopped working today.

The two maps are:
https://alteryx.carto.com/u/alteryx-admin/builder/22be9480-7057-11e6-8adb-0e05a8b3e3d7/embed

and:
https://team.carto.com/u/solutions/builder/fe0c3650-83e9-11e6-b56f-0ee66e2c9693/embed

My map is in a blog that was published today and Ramiro's map is for a workshop he is doing right now... 

Any help is appreciated!

**Comment by AbelVM** [comment]
Same error, torque, no basemaps:

https://team.carto.com/u/solutions/builder/a108ee2b-6699-43bc-aa71-3b0bc962acf9/embed

**Comment by ramiroaznar** [comment]
I was working with [a new mapa](https://team.carto.com/u/ramirocartodb/builder/49f69c3c-8641-11e6-b7e5-0e3ff518bd15), following [these steps](https://github.com/CartoDB/solutions/issues/502#issuecomment-250187604). And when I remove a filter made by a category widget and because it was not working, I refreshed the page. Then it broke with this same error. But also the left sidebar disappeared (I was not able to find the issue related to this last bug).

**Comment by xavijam** [comment]
Related with https://github.com/CartoDB/cartodb/pull/9950#event-807013202.
Let me close it and if something appears, let's get back.
