### ISSUE TITLE
No quota indicator doesnt appearing when doing an Enrich Analysis and not having quota assigned

### ISSUE THREAD

**Issue by saleiva** [CartoDB/cartodb#9975]

**Comment by xavijam** [comment]
Sorry for asking, but do we have that kind of quota information under the user info? @rafatower 
If so, it would be easy to add the quota info/progress.

**Comment by rafatower** [comment]
We do in the user model through the metrics helper:
https://github.com/CartoDB/cartodb/blob/233e04cd1e4a2966a9dda0d9229be4fd6f801d0f/app/models/user.rb#L1016

https://github.com/CartoDB/cartodb/blob/233e04cd1e4a2966a9dda0d9229be4fd6f801d0f/app/helpers/data_services_metrics_helper.rb

I don't know if that fits the bill, otherwise let me know what specifics are required.
